src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/backend/regfile/Regfile.scala

A sync regfile,  it will save read address at the first cycle and read the data next cycle.

Regfile: finish regfile

---

src/main/scala/xiangshan/frontend/Ibuffer.scala

06/23 zoujr
src/main/scala/xiangshang/frontend/Ibuffer.scala
Implement Ibuffer module

Ibuf pull request

---

src/main/scala/xiangshan/backend/dispatch/Dispatch1.scala
src/main/scala/xiangshan/backend/dispatch/Dispatch2.scala
src/main/scala/xiangshan/backend/dispatch/DispatchQueue.scala

将printf替换为了XSInfo和XSDebug
同时修复了dispatch2里面寄存器状态的传递逻辑，应该是dispatch2传递，而不是在issue

dispatch: convert printf into XSInfo and XSDebug

---

src/main/scala/xiangshan/backend/issue/IssueQueue.scala

Add Debug log infomation: pc and instruction content for each.

Issuequeue: add debug log information: pc and instruction content for each

---

src/main/scala/xiangshan/frontend/Ibuffer.scala

Ibuffer.scala
replace printf to XSDebug

Ibuffer: Add XSLog and delete debug variable

---

src/main/scala/xiangshan/backend/issue/IssueQueue.scala

Now if instruction do not use fmac as FU, src3 will simply be set to ready.

Issuequeue : add src3 need judgement & add src3 debug info

---

src/main/scala/xiangshan/backend/decode/DecodeBuffer.scala
src/main/scala/xiangshan/backend/decode/DecodeStage.scala
src/main/scala/xiangshan/backend/dispatch/Dispatch1.scala
src/main/scala/xiangshan/backend/dispatch/Dispatch2.scala
src/main/scala/xiangshan/backend/exu/Exu.scala
src/main/scala/xiangshan/backend/issue/IssueQueue.scala
src/main/scala/xiangshan/backend/rename/BusyTable.scala
src/main/scala/xiangshan/frontend/Ibuffer.scala

improve log utils in dispatch,busytable,ibuffer

dispatch,busytable: add log content

---

src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/frontend/FakeIFU.scala
src/main/scala/xiangshan/frontend/Ibuffer.scala

Reverts RISCVERS/XiangShan#52
1.该版本Ibuf输出的pc比正确值向少了3位(0x80000000 -> 0x10000000)
2.log信息中的pc使用了10进制打印
2.log信息中存在一些无效信息

Revert "Ibuf"

---

src/main/scala/xiangshan/utils/LogUtils.scala
src/test/scala/top/XSSim.scala

Log: fix typo

---

src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/frontend/Ibuffer.scala

修复了PC地址的错误
去除了无用的调试信息
将ibuf和ibuf_pc由RegInit修改为Reg

Ibuffer:Fixed PC Address error

---

src/main/scala/xiangshan/backend/issue/IssueQueue.scala

Issuequeue：change CCU into function so that reduce modules when generating firrtl.

Issuequeue：change CCU into function

---

src/main/scala/xiangshan/backend/roq/Roq.scala
src/main/scala/xiangshan/utils/LogUtils.scala

logutils: remove XSDebug() {}

---

.github/workflows/core_ci.yml

1. Use pcl's server instead Github's server
2. Any pull request must pass cputest and riscv-tests

CI: any pull request to master must pass cputest and riscv-tests

---

Makefile
src/test/csrc/difftest.cpp

Change 'nemu-so' to 'nemu-interpreter-so'

Difftest: update nemu version

---

src/main/scala/system/SoC.scala
src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/backend/exu/LsExeUnit.scala
src/test/scala/top/SimMMIO.scala

Adapt device address

---

src/main/scala/utils/ExcitingUtils.scala
src/main/scala/utils/LogUtils.scala
src/test/scala/top/XSSim.scala

ExcitingUtils provides some API to display and check connections between source and sinks

ExcitingUtils: a wrapper of chisel's BoringUtils

---

src/main/scala/xiangshan/backend/decode/DecodeStage.scala
src/main/scala/xiangshan/frontend/Ibuffer.scala

fix bug that DecodeStage could handle the sync between Brq and
DecodeBuffer

DecodeStage: fix bug of DecodeStage and Ibuffer

---

src/main/scala/device/AXI4UART.scala
src/main/scala/xiangshan/backend/fu/Divider.scala
src/test/csrc/emu.h

spilit output of uart(stdout) and log(stderr)

Uart: print to stdout

---

Makefile

* add EMU_FLAGS including -s, -b, -e, --load-snapshot
* support snapshot on the remote machine with the same usage as if on local machine

Makefile: support snapshot on the remote machine

---

src/test/csrc/difftest.cpp
src/test/csrc/difftest.h
src/test/csrc/emu.h
src/test/csrc/ram.cpp
src/test/csrc/snapshot.cpp

Note: should update NEMU to the version which contains the commit 6214884

Snapshot difftest

---

src/main/scala/system/SoC.scala
src/main/scala/top/Parameters.scala
src/main/scala/top/TopMain.scala
src/main/scala/utils/LogUtils.scala
src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/backend/Backend.scala
src/main/scala/xiangshan/backend/brq/Brq.scala
src/main/scala/xiangshan/backend/exu/JmpExeUnit.scala
src/main/scala/xiangshan/backend/fu/CSR.scala
src/main/scala/xiangshan/backend/roq/Roq.scala
src/test/scala/top/XSSim.scala
src/test/scala/xiangshan/backend/brq/BrqTest.scala
src/test/scala/xiangshan/backend/exu/LsuTest.scala
src/test/scala/xiangshan/backend/exu/MduTest.scala
src/test/scala/xiangshan/backend/issue/IssueQueueTest.scala

The goal of this commit is to remove 'implict val p: XSConfig' in our code becasue it's inconvenient

Refactor XiangShan parameter system

---

src/main/scala/xiangshan/backend/rename/BusyTable.scala
src/main/scala/xiangshan/backend/rename/Rename.scala

reduce verilog code from 5w+ lines to 1700 lines

Optimize busytable

---

src/main/scala/xiangshan/mem/Lsroq.scala

optimize lsroqViolation detection logic: use masks to reach the first replayed instruction

lsroq: optimize lsroqViolation logic

---

src/main/scala/top/TopMain.scala
src/main/scala/top/XiangShanStage.scala
src/main/scala/xstransforms/ShowPrintTransform.scala
src/test/scala/top/XSSim.scala

xstransform: support disable printf in a specified module and it's submodules

---

debug/Makefile
src/main/scala/xiangshan/backend/fu/CSR.scala
src/main/scala/xiangshan/backend/roq/Roq.scala
src/main/scala/xiangshan/cache/atomics.scala
src/test/csrc/difftest.cpp
src/test/csrc/difftest.h
src/test/csrc/emu.cpp
src/test/scala/top/XSSim.scala

* NEMU need to be updated to 990929d or above

Update difftest to support Linux snapshot

---

Makefile
src/main/scala/top/XiangShanStage.scala
src/main/scala/utils/LogUtils.scala
src/main/scala/xstransforms/PrintModuleName.scala
src/main/scala/xstransforms/ShowPrintTransform.scala
src/test/csrc/emu.cpp

1. use "%m" to dedup modules
2. turn off multithread and waveform by default

Speed up compille

---

src/main/scala/top/XiangShanStage.scala
src/main/scala/xiangshan/backend/brq/Brq.scala
src/main/scala/xstransforms/ShowPrintTransform.scala

1. Support only enable print in specified modules
Use '-em moduleName' to specify your module.  [more details](https://www.yuque.com/euzvvh/nt7mou/ovqkoz)
2. Fix brq's bug, send replayed branch instructions to frontend in-order

Support only enable print in specified modules

---

.github/workflows/emu.yml
src/main/scala/xiangshan/mem/lsqueue/separated/LoadQueue.scala
src/main/scala/xiangshan/mem/lsqueue/separated/StoreQueue.scala

This reverts commit a0ffea309c0f3a55e476042370b39169c4716ae6.

Revert "mem,lsq: improve tailPtr update logic"

---

src/main/scala/xiangshan/frontend/PreDecode.scala
src/main/scala/xiangshan/frontend/RAS.scala

coremark return address mispredict rate 30%+ -> 1%-

fix RAS performance

---

.github/workflows/emu.yml
src/main/scala/utils/ParallelMux.scala
src/main/scala/utils/Replacement.scala
src/main/scala/xiangshan/mem/sbuffer/NewSbuffer.scala
src/test/scala/xiangshan/memend/SbufferTest.scala

add sbuffer test and change LRU

Sbuffer test

---

src/main/scala/xiangshan/backend/fu/FunctionUnit.scala
src/main/scala/xiangshan/backend/fu/Multiplier.scala

- Reduce latency of mul to 3 cycles

Multiplier: add a array multiplier

---

.gitignore
.gitmodules
Makefile
build.sc
src/test/scala/cache/L1plusCacheTest.scala
src/test/scala/cache/L2CacheNonInclusiveGetTest.scala
src/test/scala/cache/L2CacheTest.scala
src/test/scala/device/AXI4RamTest.scala
src/test/scala/device/AXI4TimerTest.scala
src/test/scala/device/SimMMIOTest.scala
src/test/scala/device/TLTimerTest.scala
src/test/scala/xiangshan/backend/brq/BrqTest.scala
src/test/scala/xiangshan/backend/exu/AluTest.scala
src/test/scala/xiangshan/backend/exu/MduTest.scala
src/test/scala/xiangshan/frontend/IFUTest.scala
src/test/scala/xiangshan/frontend/PDtest.scala
src/test/scala/xiangshan/frontend/RASTest.scala
src/test/scala/xiangshan/frontend/uBTBTest.scala
src/test/scala/xiangshan/memend/SbufferTest.scala

This patch rewrite `build.sc` to depend chisel environment by source and bump to scalatest 3.2.0

Update mill build script and bump scalatest

---

src/main/scala/device/AXI4SlaveModule.scala

AXI4SlaveModule can only hanle one transaction at a time.

AXI4SlaveModule: do not let aw and ar fire at the same time.

---

src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/cache/dcacheWrapper.scala
src/test/scala/top/XSSim.scala

This pull request
* disable optimizing SoC IOs
* fix AddressSpace for MMIO

avoid optimizing SoC io

---

src/main/scala/xiangshan/cache/L1plusCache.scala

Change icachemisQueueEntryIdWidth to icacheMissQueueEntryIdWidth.

L1plusCache: fixed typo.

---

src/main/scala/device/AXI4RAM.scala
src/main/scala/device/AXI4SlaveModule.scala
src/test/csrc/ram.cpp
src/test/scala/top/XSSim.scala

This pull request fixes a bug that >2GiB RAM cannot work correctly.

support larger simulated RAM (>2GiB)

---

src/main/scala/utils/BitUtils.scala
src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/backend/CtrlBlock.scala
src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/backend/dispatch/Dispatch.scala
src/main/scala/xiangshan/backend/dispatch/DispatchQueue.scala
src/main/scala/xiangshan/backend/fu/CSR.scala
src/main/scala/xiangshan/backend/issue/ReservationStationNew.scala
src/main/scala/xiangshan/backend/rename/BusyTable.scala
src/main/scala/xiangshan/backend/roq/Roq.scala
src/main/scala/xiangshan/mem/lsqueue/LSQWrapper.scala
src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala

This pull request removes deprecated replay logic in BusyTable, Dispatch, Roq, Lsq.

dispatch: remove replay logic

---

src/main/scala/xiangshan/backend/brq/Brq.scala
src/main/scala/xiangshan/frontend/PreDecode.scala

BRQ：change priority of writeback and replay
PreDecode:  fix predecode out mask

bug fixes in Brq and IFU

---

src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/cache/icache.scala
src/main/scala/xiangshan/frontend/IFU.scala
src/test/csrc/ram.cpp

物理地址小于0x8000_0000的ICache访问会在前端标记上access fault信号

Icache access fault

---

src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/backend/rename/FreeList.scala
src/main/scala/xiangshan/backend/rename/Rename.scala

This pull request changes Freelist's IOs and decouples valid and ready.

optimize Freelist timing

---

src/test/csrc/compress.cpp
src/test/csrc/compress.h
src/test/csrc/emu.cpp
src/test/csrc/ram.cpp
src/test/csrc/snapshot.cpp
src/test/csrc/snapshot.h

当snapshot总大小大于500MB时会压缩后存储，载入时会解压

Snapshot compress

---

scripts/coverage/coverage.py
scripts/coverage/statistics.py

1. filter out unnecessary coverage statistics
python3 scripts/coverage/coverage.py input.v output.v
2. re calculate the coverage statistics
python3 scripts/coverage/statistics.py output.v

Added scripts to remove coverage statistics of print and assert.

---

src/main/scala/utils/ParallelMux.scala
src/main/scala/utils/PriorityMuxGen.scala
src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/frontend/IFU.scala

with parallel helper functions

Ifu timing

---

src/main/scala/xiangshan/backend/dispatch/DispatchQueue.scala
src/main/scala/xiangshan/backend/roq/Roq.scala
src/main/scala/xiangshan/cache/icache.scala
src/main/scala/xiangshan/cache/ptw.scala
src/main/scala/xiangshan/frontend/Frontend.scala
src/main/scala/xiangshan/frontend/IFU.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueue.scala
src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
src/test/scala/xiangshan/frontend/IFUTest.scala

This pull request wraps icache and itlb in IFU and includes some bug fixes in IFU and Roq.

IFU: wrap icache and itlb in ifu and fix some bugs

---

src/main/scala/xiangshan/backend/rename/FreeList.scala
src/main/scala/xiangshan/backend/rename/Rename.scala
src/main/scala/xiangshan/backend/rename/RenameTable.scala
src/main/scala/xiangshan/backend/roq/Roq.scala
src/test/csrc/difftest.cpp
src/test/csrc/difftest.h
src/test/csrc/emu.cpp
src/test/csrc/emu.h

This pull request changes valid, writebacked states in Roq to Mem. This helps physical design.

roq: use mem for valid and writebacked

---

src/main/scala/xiangshan/cache/dcacheWrapper.scala
src/main/scala/xiangshan/cache/missQueue.scala
src/main/scala/xiangshan/cache/probe.scala
src/main/scala/xiangshan/cache/storeMissQueue.scala
src/main/scala/xiangshan/cache/wbu.scala

Dump refill info.
Removed unnecessary debug logs.

L1DCache: modified debug logs.

---

src/main/scala/xiangshan/backend/issue/ReservationStationNew.scala

rs: remove buggy `if FPGAPlatform else ...` code

---

src/main/scala/xiangshan/mem/sbuffer/NewSbuffer.scala
src/test/scala/xiangshan/memend/SbufferTest.scala

sbuffer: add coherence counter

Trace debug

---

src/main/scala/xiangshan/cache/dtlb.scala
src/main/scala/xiangshan/cache/icache.scala
src/main/scala/xiangshan/cache/ptw.scala
src/main/scala/xiangshan/mem/sbuffer/NewSbuffer.scala

fix tlb & ptw
increase sbuffer evict cycle
delete some useless assert

bug fixes in TLB, PTW and sbuffer

---

src/main/scala/xiangshan/cache/L1plusCache.scala

Store whole cache line in one SRAM.
Let backend engineers manually split it into smaller banks.

L1plusCache: change SRAM spec.

---

src/main/scala/utils/ExcitingUtils.scala

... Instead of requiring this condition coldbloodedly

excitingutils: warn wires that have multiple sink|source

---

src/main/scala/xiangshan/backend/decode/DecodeUnit.scala

lsr1 should not depend on decode result "src1Type === SrcType.pc"

Opt decode

---

src/main/scala/xiangshan/cache/prefetch/BestOffsetPrefetch.scala
src/main/scala/xiangshan/cache/prefetch/StreamPrefetch.scala

1. optimize performance of BOP
2. optimize timing from stream miss to allocating a new one
3. add cross-page checking in each prefetcher

dev-prefetcher: optimize timing and add cross-page checking

---

src/main/scala/utils/Replacement.scala
src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/cache/icache.scala

use ReplacementPolicy.fromString() to build a replacement policy, use replacer.access to update the state when hit and use replacer.way to get victimWayMask.

Replace policy

---

src/main/scala/xiangshan/backend/CtrlBlock.scala
src/main/scala/xiangshan/backend/dispatch/Dispatch1.scala
src/main/scala/xiangshan/backend/dispatch/DispatchQueue.scala
src/main/scala/xiangshan/backend/fu/CSR.scala
src/main/scala/xiangshan/backend/roq/Roq.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueue.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala

CtrlBlock: fix many 'flush' related bugs

---

src/main/scala/xiangshan/backend/FloatBlock.scala
src/main/scala/xiangshan/backend/IntegerBlock.scala
src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/backend/issue/ReservationStation.scala

But this would not work(for syntax bug) until other modules change

RS: add param srcLen which decides the src data len stored in rs

---

src/main/scala/xiangshan/mem/lsqueue/LoadQueue.scala
src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala

* Alternative plan: use async vaddr module

LSQ: fix vaddrModule raddr

---

src/main/scala/xiangshan/frontend/IFU.scala

likely to be a huge performance bug fixed

ifu: fix predTakenRedirect logic for if3 and if4

---

src/main/scala/xiangshan/backend/ftq/Ftq.scala

…c be updated
could have considerable performance improvements

ftq: update cfiIndex_vec only when corresponding write back port is valid

---

src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala

This pull request should fix the bug causing povray failed.

StoreQueue: issuePtr should not exceed enqPtr

---

src/main/scala/xiangshan/mem/sbuffer/NewSbuffer.scala
src/test/scala/xiangshan/memend/SbufferTest.scala

Don't merge this, it's only a test to see if it can pass ci check, the performance of sbuffer needs more test

NewSbuffer: allow multi-inflight dcache request to improve performance

---

src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/cache/DCache.scala
src/main/scala/xiangshan/cache/DCacheWrapper.scala
src/main/scala/xiangshan/cache/LoadPipe.scala
src/main/scala/xiangshan/cache/MainPipe.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

Reverts RISCVERS/XiangShan#648
#648 has conflicts with #645

Revert "DCache: rewrite pipeline and dcache array arrangement"

---

src/main/scala/utils/ParallelMux.scala
src/main/scala/xiangshan/frontend/SC.scala
src/main/scala/xiangshan/frontend/Tage.scala

previously the biggest problem was using '+' instead of '+&' to
do sums

sc: now it works

---

src/main/scala/top/Top.scala

Verilog generation time should be largely reduced.

Top: remove extra axi ID bits

---

.github/workflows/emu.yml

This pull request allows CI to use 16, 32 cores for 8-, 16-thread emu to slightly speedup emu and keeps the stability when other processes are using the same cpu cores. Also changes how perf.log is generated.

Update github ci scripts

---

src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/backend/CtrlBlock.scala
src/main/scala/xiangshan/backend/IntegerBlock.scala
src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/backend/dispatch/Dispatch.scala
src/main/scala/xiangshan/backend/dispatch/DispatchQueue.scala
src/main/scala/xiangshan/backend/ftq/Ftq.scala
src/main/scala/xiangshan/backend/fu/CSR.scala
src/main/scala/xiangshan/backend/roq/Roq.scala
src/main/scala/xiangshan/cache/DCacheWrapper.scala
src/main/scala/xiangshan/cache/MissQueue.scala
src/main/scala/xiangshan/frontend/Frontend.scala
src/main/scala/xiangshan/frontend/Ibuffer.scala
src/main/scala/xiangshan/mem/lsqueue/LSQWrapper.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueue.scala
src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala

Dirty code, but failed to come up with decent writing styles.
Cache related counters can be added once newer version is merged into mainstream

Add some in-core hardware performance counters

---

src/main/scala/xiangshan/cache/ICache.scala

useRefillReg is not be used when holdRead

ICache: fix holdRead performance bug.

---

src/main/scala/xiangshan/frontend/BPU.scala
src/main/scala/xiangshan/frontend/RAS.scala

May have performance improvements on programs with deep call stack

ras: partly handle stack overflow problems

---

src/main/scala/utils/SRAMTemplate.scala

For dual-port SRAMs, when reading and writing to the same index at the same clock cycle,
the output read data is uncertain at the next clock cycle. To avoid any errors, we randomize
the read data when reading and writing to the same entry of dual-port SRAMs. Besides, we
add a bypassWrite option to support bypassing write data when it has read/write conflicts.

SRAMTemplate: bypass either wdata or random number for dual-port sram

---

Makefile
Makefile.emu

* the time log can be found at build/time.log

Makefile: refine time logging

---

src/main/scala/xiangshan/backend/fu/CSR.scala

* Only ssip in sip is writeable in smode
* Add sip write permission check
* Fix mipReg write logic

CSR: fix mip/sip implementation

---

README-ZH-HANS.md
README.md

I'd like to contribute to your projects, as a shown of respect to your genius work. but so sad I know little about `Chisel` and computer architectures. 😥
So I randomly picked up issue #835 (issues come with needs) and merely made some typo works lol.
<small>Further review is necessary because I'm not really good at writing both in English and Chinese.</small>
(逃

Update README.md and add a simplified Chinese version

---

README.md

For https://github.com/OpenXiangShan/XiangShan/pull/859

readme: update outdated Chinese readme link

---

Makefile
src/test/csrc/common/common.h
src/test/csrc/difftest/difftest.cpp
src/test/csrc/difftest/difftest.h
src/test/csrc/difftest/nemuproxy.cpp
src/test/csrc/verilator/emu.cpp
src/test/csrc/verilator/emu.h
verilator.mk

* support NUM_CORES in Makefile to indicate the number of XiangShan cores
* fix simulation run-time errors
* code cleanup

misc: fix compile-time and run-time issues for SMP simulation

---

src/main/scala/xiangshan/backend/fu/SRT4Divider.scala

Thanks to @hyf6661669's advice, we can select the quotient selection table we need based on the value of the divisor before the start of the iteration.

Optimize timing for SRT4 Divider

---

src/main/scala/xiangshan/backend/issue/ReservationStation.scala
src/main/scala/xiangshan/backend/issue/StatusArray.scala

Fix isFirstIssue required in #887

backend,rs: add isFirstIssue flags in status entries

---

src/main/scala/xiangshan/backend/issue/ReservationStation.scala
src/main/scala/xiangshan/backend/issue/StatusArray.scala

Compare SqPtr when an instruction with wait bit enqueuing. This should have minor
performance improvements. Also add some performance counters.

backend,rs: compare sqPtr when enqueue

---

src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala

For simplicity, we increase cmtPtr and set commited flags when
store instructions commit from ROB. However, this causes problems
when there's an MMIO at the head and new instructions enqueue after
the MMIO finishes but before the MMIO commits.
For example, at cycle T0 mmio store instruction with sqPtr p0
finishes and deqPtr is increased. At cycle T1, a new store
instruction enqueues and the p0 is allocated for this new instruction.
At cycle T2, the mmio instruction commits from ROB. With cmtPtr,
p0 is set to commited. However, since p0 is allocated to the new
store instruction, the commited flag should be false.
The example causes at least two issues. (1) when redirect happens, p0
will not be flushed. (2) p0 will be commit to sbuffer before p0
writes back to store queue.
In this commit, …

mem,sq: don't set commited flag when mmio commits

---

src/main/scala/xiangshan/mem/lsqueue/LoadQueue.scala

* Fix allocated flag update logic

mem: enable non pow of 2 load queue size

---

scripts/xiangshan.py

This PR adds a random seed to emu.

scripts: add random seed to emu runs

---

src/main/scala/xiangshan/backend/Scheduler.scala
src/main/scala/xiangshan/backend/issue/ReservationStation.scala

This PR limits dequeue width of every RS to 2 for better timing.

backend, rs: add a maximum dequeue width (default 2)

---

src/main/scala/xiangshan/backend/issue/SelectPolicy.scala

This commit changes how io.out is computed for age detector. We use a
register to keep track of the position of the oldest instruction. Since
the updating information has better timing than issue, this could
optimize the timing of issue logic.

rs,age: optimize timing for output

---

.github/workflows/emu.yml
src/main/scala/xiangshan/frontend/FTB.scala

- Fix bug that of incorrect calculation of target stat when updating ftb entry
- False hit will no longer appear in some programs

BPU: Fix bug and significantly reduce false_hit 

---

src/main/scala/xiangshan/backend/issue/StatusArray.scala

This commit adds critical_wakeup_*_* counters to indicate which function
units wake up the instructions in RS. Previously we have wait_for_src_*
counters but they cannot represent where the critical operand (the last
waiting operand) comes from.
We need these counters to optimize fast wakeup logic. If some
instructions critically depend on some other instructions, we can think
of how we can optimize the wakeup process.

backend,rs: add counters for critical wakeup sources

---

src/main/scala/xiangshan/cache/L1Cache.scala
src/main/scala/xiangshan/frontend/Frontend.scala
src/main/scala/xiangshan/frontend/ICache.scala
src/main/scala/xiangshan/frontend/IFU.scala

* connect fencei signal to ICache metaArray to flush valid bits
* use full ppn as physical tag in ICache

Fix fencei and physical tag bugs in ICache

---

src/main/scala/xiangshan/frontend/NewFtq.scala

- Fix bug that of incorrect calculation of carry when generating ftb entry
- False hit will no longer appear in mcf

FTQ: Fix the false hit bug when run mcf

---

src/main/scala/xiangshan/backend/FUBlock.scala
src/main/scala/xiangshan/backend/exu/ExeUnit.scala
src/main/scala/xiangshan/backend/exu/Exu.scala

This commit applys Definition and Instance for some modules. Refer to
https://github.com/chipsalliance/chisel3/pull/2045.

misc: use Definition and Instance for modules

---

src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/backend/ExuBlock.scala
src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/backend/Scheduler.scala
src/main/scala/xiangshan/backend/dispatch/Dispatch2Fp.scala
src/main/scala/xiangshan/backend/dispatch/Dispatch2Int.scala
src/main/scala/xiangshan/backend/exu/ExeUnit.scala
src/main/scala/xiangshan/backend/regfile/Regfile.scala
src/main/scala/xiangshan/backend/rob/Rob.scala

* change ROB to 256 entries
* change physical register file to 192 entries
* re-organize reservation stations, function units and regfile

configs, core: update some parameters

---

.github/workflows/emu.yml
scripts/xiangshan.py
src/main/scala/xiangshan/backend/fu/Alu.scala
src/main/scala/xiangshan/package.scala

This commit fixes maxu/minu/rol/ror results in ALU. Regression tests are added to CI.

alu: fix maxu/minu/rol/ror results

---

src/main/scala/xiangshan/backend/fu/PMA.scala

add two more areas for pll and core_reset

pma: update pma init config

---

src/main/scala/xiangshan/frontend/Frontend.scala
src/main/scala/xiangshan/frontend/IFU.scala
src/main/scala/xiangshan/frontend/NewFtq.scala

* f3 send uncache fetch to InstrUncache
* send to ibuffer if fetch responsed
* stop the pipeline until this instruction commit
* flush the frontend from the next pc (+ 2 for RVC , +4 for RVI)

IFU: mmio instruction fetch waits for commit and flush frontend

---

src/main/scala/utils/ResetGen.scala
src/main/scala/xiangshan/XSCore.scala

This fixes differences between the pingpong bits in ctrlblock and dispatch2.

reset: delay two cycles for the next level

---

src/main/scala/system/SoC.scala
src/main/scala/xiangshan/backend/fu/PMA.scala

udate pma default value.
update plic ext interrupts to64.
sync external interrupts before plic

Update pma default value

---

.github/workflows/emu.yml
Makefile
README.md
readme.zh-cn.md
scripts/xiangshan.py
src/main/scala/top/ArgParser.scala
src/main/scala/utils/LogUtils.scala
src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/backend/Scheduler.scala
src/main/scala/xiangshan/backend/dispatch/Dispatch.scala
src/main/scala/xiangshan/backend/fu/CSR.scala
src/main/scala/xiangshan/backend/rob/Rob.scala
src/main/scala/xiangshan/cache/dcache/mainpipe/MissQueue.scala
src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
src/main/scala/xiangshan/mem/pipeline/AtomicsUnit.scala
src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala
src/test/scala/top/SimTop.scala

* disable log as default
* code clean up

top: enable fpga option for simulation emu

---

src/main/scala/top/Top.scala
src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/backend/fu/CSR.scala

top: add seip and meip bits from plic

---

Makefile
src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/backend/Scheduler.scala
src/main/scala/xiangshan/backend/exu/WbArbiter.scala
src/main/scala/xiangshan/backend/fu/CSR.scala
src/main/scala/xiangshan/backend/rename/Rename.scala
src/main/scala/xiangshan/backend/rob/Rob.scala

This commit adds basic difftest features for every release, no matter
it's for simulation or physical design. The macro SYNTHESIS is used to
skip these logics when synthesizing the design. This commit aims at
allowing designs for physical design to be verified.

difftest: add basic difftest features for releases

---

src/main/scala/xiangshan/frontend/PreDecode.scala

* assuming that beyond fetch => oversize

PreDecode: rule out taken when beyond fetch

---

src/main/scala/xiangshan/backend/fu/fpu/FDivSqrt.scala

Fix div-sqrt bug when switching S/D

Fix div-sqrt bug when switching S/D

---

src/main/scala/xiangshan/backend/decode/FusionDecoder.scala

This commit optimizes instruction fusion detection logic for fused
addw{byte, bit, zexth, sexth}, mulw7, and logic{lsb, zexth}
instructions.
Previously we use fuType and fuOpType from the normal decoder, and this
incurs a bad timing. Now we change the detection logic to use only the
raw instructions. Though the fused instruction still uses the
fuOpType from the normal decoder, there should be only serveral MUXes
left.

decode,fusion: optimize detection logic for addw and logic ops

---

.gitmodules
Makefile
README.md
build.sc

- Clean up project dependencies
- Support compiling XiangShan by using Chisel source code (use ivy by default)

Clean up project dependencies

---

src/main/scala/xiangshan/frontend/icache/ICacheMainPipe.scala
src/main/scala/xiangshan/frontend/icache/ReplacePipe.scala

* use toMeta.fire() will cause data miss match when toMeta.valid :=
req.valid

fix ResultHoldBypass valid condition

---

src/main/scala/xiangshan/backend/fu/CSR.scala

This commit fixes the write mask for mstatus, mepc and sepc.
According to the RISC-V instruction manual, for RV64 systems,
the SXL and UXL fields are WARL fields that control the value of
XLEN for S-mode and U-mode, respectively. For RV64 systems, if
S-mode is not supported, then SXL is hardwired to zero. For RV64
systems, if U-mode is not supported, then UXL is hardwired to zero.
Besides, mepc[0] and sepc[0] should be hardwired to zero.

csr: fix write mask for mstatus, mepc and sepc

---

src/main/scala/xiangshan/backend/issue/ReservationStation.scala
src/main/scala/xiangshan/backend/issue/StatusArray.scala

This commit optimizes the issue grant timing when age is enabled.
Select from age and SelectPolicy are processed parallely.

rs: optimize issue grant timing with age

---

src/main/scala/xiangshan/frontend/IFU.scala

update f2_mmio logic.
it can alse be added to f3_mmio too.

update f2_mmio update logic

---

src/main/scala/xiangshan/backend/fu/CSR.scala

All bits for stvec and mtvec are writable in XiangShan.
According to the RISC-V spec, {m,s}tvec[1:0] are MODE bits. When
MODE=Vectored, all synchronous exceptions into M/S mode cause the pc
to be set to the address in the BASE field, whereas interrupts cause
the pc to be set to the address in the BASE field plus four times
the interrupt cause number.
If XiangShan decides to not support vectored mode, {m,s}tvec[1:0]
should be hardwired to zero.

csr: add vectored trap mode

---

src/main/scala/xiangshan/frontend/icache/ICacheMainPipe.scala

When two consecutive packets request the same block and a page fault occurs in the second block of the latter packet, ICache will send 2 Acquire of same address to L2.

ICacheMainPipe: fix miss_0_except_1 resend problem

---

src/main/scala/xiangshan/backend/exu/WbArbiter.scala

There is a missing option check in  #1219

difftest: fix missing AlwaysBasicDiff option in WbArbiter

---

src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/cache/dcache/mainpipe/Probe.scala
src/main/scala/xiangshan/mem/lsqueue/LSQWrapper.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueue.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

* mem: optimize missq reject to lq timing 
* dcache: compare probe block addr instead of full addr
* mem: do not replay from RS when ldld vio or fwd failed

Optimize dcache timing

---

src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/backend/fu/CSR.scala
src/main/scala/xiangshan/backend/rob/Rob.scala
src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueue.scala
src/main/scala/xiangshan/mem/pipeline/AtomicsUnit.scala

* Fix stepie bit in dcsr
* Fix ROB enq and writeback logic not considering trigger hits
* Add trigger to atomic instructions
* dcache: fix ecc tag error trigger condition

Debug mode debug

---

src/main/scala/xiangshan/frontend/Frontend.scala
src/main/scala/xiangshan/frontend/icache/ICache.scala
src/main/scala/xiangshan/frontend/icache/ICacheMainPipe.scala

* add 2 ILTB requestor and delete tlb_arb

ITLB <timing>: delay miss and flush req for ITLB

---

.github/workflows/emu.yml

- difftest:
1. support using '-F' option to specify flash bin file;
2. add load_flash_bin function to synchronize the bin file with NEMU;
- ready-to-run:
1. add a ready-to-run test where a 1-iteration coremark test is copied from flash space to ram space and jump to execute.

Rebuild flash simulation

---

src/main/scala/device/AXI4IntrGenerator.scala
src/main/scala/top/Top.scala
src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/XSTile.scala
src/main/scala/xiangshan/backend/CtrlBlock.scala
src/main/scala/xiangshan/backend/decode/DecodeUnit.scala
src/main/scala/xiangshan/backend/dispatch/Dispatch.scala
src/main/scala/xiangshan/backend/fu/CSR.scala
src/main/scala/xiangshan/backend/rob/Rob.scala
src/main/scala/xiangshan/package.scala

This PR adds support for the wait-for-interrupt (WFI) instruction. Instead of the NOP implementation before, we implement the real WFI in ROB.

Add support for the WFI instruction

---

.gitignore
src/main/scala/utils/BitUtils.scala
src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/backend/Scheduler.scala
src/main/scala/xiangshan/backend/dispatch/Dispatch2Rs.scala
src/main/scala/xiangshan/backend/issue/ReservationStation.scala
src/main/scala/xiangshan/backend/rob/Rob.scala
src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala
src/main/scala/xiangshan/cache/dcache/data/BankedDataArray.scala
src/main/scala/xiangshan/mem/MemCommon.scala
src/main/scala/xiangshan/mem/lsqueue/LSQWrapper.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueue.scala
src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
src/main/scala/xiangshan/mem/sbuffer/DatamoduleResultBuffer.scala
src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala

Parameterize load store

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

misc: update issue templates

---

src/main/scala/xiangshan/backend/fu/CSR.scala
src/main/scala/xiangshan/backend/fu/PMA.scala

Debug Module: fix PMA Debug Module execute privilege

---

src/test/scala/top/SimTop.scala

Uage: https://xiangshan-doc.readthedocs.io/zh_CN/latest/tools/chiseldb/#_3

Added chisel-db to dump hw data into a database automatically

---

src/main/scala/utils/PerfCounterUtils.scala

This commit adds a pipeline for performance counters. No functional changes.

utils,perf: optimize timing

---

src/main/scala/utils/DataModuleTemplate.scala
src/main/scala/xiangshan/frontend/NewFtq.scala

and remove all bypass for ftq_pc_mem

datamodule: add per-read-port bypass enable bit

---

src/main/scala/xiangshan/backend/rename/RenameTable.scala
src/main/scala/xiangshan/backend/rename/freelist/MEFreeList.scala
src/main/scala/xiangshan/backend/rename/freelist/RefCounter.scala
src/main/scala/xiangshan/backend/rename/freelist/StdFreeList.scala

ctrl: optimize freelist timing

---

src/main/scala/utils/BitUtils.scala

Should improve the code quality of OnesMoreThan.

utils: optimize OnesMoreThan and XORFold

---

src/main/scala/utils/CircularQueuePtr.scala
src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/backend/decode/DecodeUnit.scala
src/main/scala/xiangshan/frontend/Ibuffer.scala

This commit optimizes the read timing of ibuffer.

ibuffer: optimize read timing

---

src/main/scala/xiangshan/backend/issue/ReservationStation.scala

Balance between the first numDeq ports. Possible IPC increase?

rs: fix enqBypass when numEnq > 2

---

src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala

It should remove dtlb to rs critical path

sta: delay sta to rs feedback for 1 cycle

---

src/main/scala/xiangshan/backend/rob/Rob.scala

This commit fixes the allowEnqueue condition of ROB. When the ROB is
not walking, we should always consider the enqueue instructions.
Previously the condition is isCommit, which may be deasserted even
if new instructions are allowed to enqueue.

rob: fix the allowEnqueue condition

---

src/main/scala/xiangshan/mem/lsqueue/LoadQueue.scala

Note that it is intend to prevent X prop in simulation, may cause
timing problem. These check can be removed safely for better
timing

lq,xprop: check store tlb hit in violation check

---

src/main/scala/xiangshan/frontend/RAS.scala

ras: delay write for 1 cycle and bypass write to read

---

src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala
src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala

Now we use tag_write_intend to generate ready signal for load issue
It should remove the critical path from dcacheReq.ready to rs

dcache,ldu: simplify load issue ready logic

---

src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/mem/lsqueue/LSQWrapper.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueue.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala

It should fix the timing problem caused by ldld violation check and
forward error check

ldu: report ldld vio and fwd error in s3

---

src/main/scala/xiangshan/frontend/IFU.scala
src/main/scala/xiangshan/frontend/icache/ICacheMainPipe.scala

* fix lastHalf register bug when last instruction in a block is miss-predicted (caused by timing rebuild)
* latch ITLB response when pipeline stop

Nanhu frontend debug

---

src/main/scala/xiangshan/backend/issue/DataArray.scala

This commit optimizes the fanout of fmul results.

rs: add registers for fma mid-results

---

src/main/scala/xiangshan/frontend/SC.scala
src/main/scala/xiangshan/frontend/Tage.scala

tage-sc: add hold read logic and write bypass for base table and sc table

---

src/main/scala/xiangshan/cache/dcache/meta/AsynchronousMetaArray.scala

It should reduce dcache meta write fanout

dcache: divide meta array into nWays banks

---

src/main/scala/xiangshan/cache/mmu/L2TLB.scala
src/main/scala/xiangshan/cache/mmu/MMUConst.scala
src/main/scala/xiangshan/cache/mmu/PageTableCache.scala

page cache has large fanout:
1. addr_low -> sel data
2. level
3. sfence
4. ecc error flush
solution, add duplicate reg:
1. sfence/csr reg
2. ecc error reg
3. memSelData
4. one hot level code

l2tlb: add duplicate reg for better fanout

---

src/main/scala/xiangshan/cache/CacheInstruction.scala
src/main/scala/xiangshan/frontend/icache/ICache.scala
src/main/scala/xiangshan/frontend/icache/ICacheBundle.scala
src/main/scala/xiangshan/frontend/icache/ICacheMainPipe.scala
src/main/scala/xiangshan/frontend/icache/ICacheMissUnit.scala
src/main/scala/xiangshan/frontend/icache/ReleaseUnit.scala
src/main/scala/xiangshan/frontend/icache/ReplacePipe.scala

* <timing> fix icache cacheOP fanout
* <timing> fix miss_*_s2_* fanout
* <timing> fix MissUnit fanout
* <timing> fix ReplacePipe fanout

fix icache fanout

---

src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala

Report error if sc fails too many times on an addr while
lrsc_addr === get_block_addr(s3_req.addr).

dcache: update sc fail assert

---

src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/backend/Scheduler.scala
src/main/scala/xiangshan/backend/issue/ReservationStation.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

ld,rs: optimize load-load forward timing

---

src/main/scala/utils/BitUtils.scala
src/main/scala/xiangshan/backend/exu/Exu.scala
src/main/scala/xiangshan/backend/exu/MulDivExeUnit.scala
src/main/scala/xiangshan/backend/fu/FunctionUnit.scala
src/main/scala/xiangshan/backend/fu/InputBuffer.scala
src/main/scala/xiangshan/backend/fu/SRT16Divider.scala
src/main/scala/xiangshan/backend/issue/BypassNetwork.scala
src/main/scala/xiangshan/backend/issue/ReservationStation.scala
src/main/scala/xiangshan/backend/issue/SelectPolicy.scala
src/main/scala/xiangshan/package.scala

This commit moves JumpCSRUnit to the last writeback port, where
there should be less mul and div instructions.

Timing optimizations for Ctrl and EXU

---

src/main/scala/xiangshan/backend/fu/CSR.scala

* Replace wire DontCare with initialization
* Separate assign of wires/regs into different when-elsewhen-otherwise expressions

CSR: Fix illegal xret

---

src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala
src/main/scala/xiangshan/cache/dcache/FakeDCache.scala
src/main/scala/xiangshan/cache/dcache/mainpipe/AtomicsReplayUnit.scala
src/main/scala/xiangshan/mem/pipeline/AtomicsUnit.scala

move functions and replay feature in `Atomicsreplayunit` to `Atomicsunit`

dcache, atomicUnit: remove Atomicsreplayunit

---

src/main/scala/top/Configs.scala
src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala
src/main/scala/xiangshan/cache/dcache/FakeDCache.scala
src/main/scala/xiangshan/cache/dcache/loadpipe/LoadPipe.scala
src/main/scala/xiangshan/cache/mmu/MMUBundle.scala
src/main/scala/xiangshan/cache/mmu/TLB.scala
src/main/scala/xiangshan/cache/mmu/TLBStorage.scala
src/main/scala/xiangshan/frontend/Frontend.scala
src/main/scala/xiangshan/frontend/IFU.scala
src/main/scala/xiangshan/frontend/icache/ICacheMainPipe.scala
src/main/scala/xiangshan/frontend/icache/IPrefetch.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueue.scala
src/main/scala/xiangshan/mem/pipeline/AtomicsUnit.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala

Sync timing modification of #1681 and #1793

---

src/main/scala/xiangshan/mem/mdp/StoreSet.scala

Reverts OpenXiangShan/XiangShan#1819

Fix "mdp: Fix the mdp predicts that the load may depend on itself"

---

src/main/scala/xiangshan/frontend/IFU.scala
src/main/scala/xiangshan/frontend/NewFtq.scala

IFU: Add toIBuffer and toFtq record
Ftq: Add branch trace datebase framework

frontend: Add ChiselDB records

---

src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/backend/Scheduler.scala
src/main/scala/xiangshan/backend/issue/ReservationStation.scala
src/main/scala/xiangshan/mem/MemCommon.scala
src/main/scala/xiangshan/mem/lsqueue/LSQWrapper.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueue.scala
src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala

* replay load/store from load/store queue instead of RS

Replay all load instructions from LQ

---

src/main/scala/xiangshan/backend/rob/Rob.scala

* bump difftest and wire extra signals (robidx, lqidx, sqidx etc) from ROB to difftest

ROB, difftest: add robidx support

---

src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala

将ptw改为sw寄存器模式，时序得到优化的同时，性能也不受影响

modified ptw and keep performance from dropping

---

src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala

This commit solves bugs of [Nightly Regression-225](https://github.com/OpenXiangShan/XiangShan/actions/runs/3714441234), [Nightly Regression-232](https://github.com/OpenXiangShan/XiangShan/actions/runs/3766701870), [EMU Test-5125](https://github.com/OpenXiangShan/XiangShan/actions/runs/3806779529), [Nightly Regression-240](https://github.com/OpenXiangShan/XiangShan/actions/runs/3812738111), [Nightly Regression-242](https://github.com/OpenXiangShan/XiangShan/actions/runs/3823621322), [EMU Test-5139](https://github.com/OpenXiangShan/XiangShan/actions/runs/3826447614), [EMU Test-5140](https://github.com/OpenXiangShan/XiangShan/actions/runs/3826455422)

PTW: Fix bug when resp valid but not fire

---

src/main/scala/xiangshan/cache/mmu/L2TLB.scala

Add PageCache_refill_check which is similar to icache_refill_check and dcache_refill_check. I have checked that both icache_refill_check and dcache_refill_check can still work after this commit.
Please also merge https://github.com/OpenXiangShan/difftest/pull/97 to master.

PTW: Add PTW refill check in difftest

---

src/main/scala/xiangshan/frontend/NewFtq.scala

Remove unclear fixup by fixing the actual ftq redirect handling issue

refactor cfiVec fix

---

src/main/scala/xiangshan/backend/Scheduler.scala

fix(Scheduler):fix "store commit different" bug in povray-tests
TODO: fix wfi bug in misc-tests

fix rf-after-issue bug

---

src/main/scala/xiangshan/frontend/NewFtq.scala

CommPtr will not depend on IfuWbPtr

break ifuwbptr dependency

---

src/main/scala/xiangshan/frontend/NewFtq.scala
src/main/scala/xiangshan/frontend/icache/ICache.scala
src/main/scala/xiangshan/frontend/icache/ICacheBundle.scala
src/main/scala/xiangshan/frontend/icache/ICacheMainPipe.scala
src/main/scala/xiangshan/frontend/icache/ICacheMissUnit.scala
src/main/scala/xiangshan/frontend/icache/IPrefetch.scala

* ipfBuffer: Add 3 stage pipeline to filter before refill
* mainPipe & ipfBuffer:refactor read ipfBuffer logic

icache:fix multi-hit problem

---

src/main/scala/xiangshan/backend/fu/Alu.scala
src/main/scala/xiangshan/backend/rename/Rename.scala

1. pass lsrc0NotZero by imm(15)
2. modify the logic for generating vl in Alu

vset: pass lsrc0NotZero by imm(15) & modify vl calculation logic in alu

---

src/main/scala/xiangshan/frontend/icache/ICache.scala
src/main/scala/xiangshan/frontend/icache/ICacheBundle.scala
src/main/scala/xiangshan/frontend/icache/ICacheMainPipe.scala
src/main/scala/xiangshan/frontend/icache/ICacheMissUnit.scala
src/main/scala/xiangshan/frontend/icache/IPrefetch.scala

finish use multi-bank to slove anti-alias problem

solve anti-alias problem

---

scripts/constantHelper.py

util: Add constant-solver

---

src/main/scala/xiangshan/backend/decode/DecodeUnit.scala
src/main/scala/xiangshan/backend/decode/VecDecoder.scala
src/main/scala/xiangshan/backend/exu/ExeUnit.scala
src/main/scala/xiangshan/backend/exu/Exu.scala
src/main/scala/xiangshan/backend/fu/FunctionUnit.scala
src/main/scala/xiangshan/backend/fu/fpu/FPUSubModule.scala
src/main/scala/xiangshan/backend/fu/vector/VFPU.scala
src/main/scala/xiangshan/backend/fu/vector/VPPU.scala
src/main/scala/xiangshan/backend/rob/Rob.scala
src/main/scala/xiangshan/package.scala

* fix(vipu): fix bug that readFpFu should consider condition numVecSrc > 0
* func(f2s vslide1up): support VppuType.f2s & VppuType.vslide1up
* func(vfadd vfsub): support vfadd.vv vfsub.vv vfadd.vf vfsub.vf
* refactor(VFPU): replace PipelineVFPU with BlockingVFPU

func(f2s vslide1up vfadd vfsub): support VppuType.f2s & VppuType.vslide1up vfadd.vv vfsub.vv vfadd.vf vfsub.vf

---

src/main/scala/xiangshan/backend/decode/VecDecoder.scala
src/main/scala/xiangshan/backend/fu/vector/VFPU.scala

* refactor(VFPU): Wrapper VectorFloatAdder to VfaluWrapper
* func(vfmacc):support vfmacc.vf vfmacc.vv

func(vfmacc):support vfmacc.vf vfmacc.vv

---

src/main/scala/xiangshan/backend/decode/VecDecoder.scala
src/main/scala/xiangshan/backend/fu/vector/VIPU.scala

* func(vrsub):support vrsub.vv
* func(adc): support vmadc.vv vmadc.vi vmadc.vx

func(VIPU): support vrsub & vmadc

---

src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/backend/decode/DecodeUnit.scala
src/main/scala/xiangshan/backend/fu/FunctionUnit.scala
src/main/scala/xiangshan/backend/fu/fpu/FPUSubModule.scala
src/main/scala/xiangshan/backend/fu/vector/VFPU.scala
src/main/scala/xiangshan/backend/fu/vector/VIPU.scala
src/main/scala/xiangshan/backend/issue/ReservationStationBase.scala
src/main/scala/xiangshan/package.scala

* fix(VFPU):fix bug that there is a conflict when VIPU and VFPU write back at the same time
* func(vmask): add vmask to the pipeline & support vmadc.vim

fix write conflit bug between VFPU and VIPU & add vmask to the pipeline

---

src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/backend/CtrlBlock.scala
src/main/scala/xiangshan/backend/decode/DecodeUnit.scala
src/main/scala/xiangshan/backend/decode/DecodeUnitComp.scala
src/main/scala/xiangshan/backend/exu/ExeUnit.scala
src/main/scala/xiangshan/backend/exu/Exu.scala
src/main/scala/xiangshan/backend/exu/WbArbiter.scala
src/main/scala/xiangshan/backend/fu/CSR.scala
src/main/scala/xiangshan/backend/fu/FunctionUnit.scala
src/main/scala/xiangshan/backend/fu/vector/VFPU.scala
src/main/scala/xiangshan/backend/fu/vector/VIPU.scala
src/main/scala/xiangshan/backend/rob/Rob.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueue.scala
src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala
src/main/scala/xiangshan/package.scala

1. add end flag for uopIdx
2. fix(VFPU): io.in.ready should be ture.B
3. func(VIAlu):add VIAlu code v2
4. add vxsat form VIPU to CSR

func(vxsat): add end flag for uopIdx  & vxsat form VIPU to CSR

---

src/main/scala/top/Configs.scala
src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/cache/mmu/L2TLB.scala
src/main/scala/xiangshan/cache/mmu/MMUBundle.scala
src/main/scala/xiangshan/cache/mmu/MMUConst.scala
src/main/scala/xiangshan/cache/mmu/PageTableCache.scala
src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala
src/main/scala/xiangshan/cache/mmu/Repeater.scala
src/main/scala/xiangshan/cache/mmu/TLB.scala
src/main/scala/xiangshan/cache/mmu/TLBStorage.scala

Please also merge https://github.com/OpenXiangShan/difftest/pull/112 to master.

MMU: Add sector tlb for larger capacity

---

src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/backend/FUBlock.scala
src/main/scala/xiangshan/backend/decode/VecDecoder.scala
src/main/scala/xiangshan/backend/exu/ExeUnit.scala
src/main/scala/xiangshan/backend/exu/Exu.scala
src/main/scala/xiangshan/backend/fu/vector/VFPU.scala
src/main/scala/xiangshan/backend/fu/vector/VIPU.scala
src/main/scala/xiangshan/backend/fu/vector/VPUSubModule.scala

* func(vstart): add vstart from CSR to VIPU
* func(VipuType): add VipuType of vwsubu.vv vwsubu.wv vwsub.vx vwsub.wx
* pom(yunsuan): support vfmin vfmax
* func(vfmin vfmax): pass vfmin & vfmax in VectorFloatAdder

func(vfmin vfmax): pass vfmin & vfmax in VectorFloatAdder

---

src/main/scala/top/Top.scala
src/test/scala/top/SimTop.scala
src/test/scala/xiangshan/DecodeTest.scala

use `filename` instead of `extension` to record file

util: change ElaborationArtefacts to FileRegisters 

---

src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/backend/CtrlBlock.scala
src/main/scala/xiangshan/backend/decode/DecodeStage.scala
src/main/scala/xiangshan/backend/decode/DecodeUnitComp.scala
src/main/scala/xiangshan/backend/rob/Rab.scala
src/main/scala/xiangshan/backend/rob/Rob.scala

* fix(vset): fix vset bug that writing vconfig need the condition of rfWen==true

fix(vset): fix vset bug that writing vconfig need the condition of rfWen==true

---

src/main/scala/xiangshan/cache/CacheInstruction.scala
src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala
src/main/scala/xiangshan/cache/dcache/data/BankedDataArray.scala
src/main/scala/xiangshan/cache/dcache/loadpipe/LoadPipe.scala
src/main/scala/xiangshan/cache/dcache/meta/TagArray.scala

Optimize the `cacheOp_dup` code written by @happy-lx

code opt: optimize duplicate codes

---

src/main/scala/xiangshan/backend/decode/VecDecoder.scala

* fix(selImm): fix selImm bug of OPIVI inst

fix(selImm): fix selImm bug of OPIVI inst

---

src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/backend/decode/DecodeStage.scala
src/main/scala/xiangshan/backend/decode/DecodeUnitComp.scala
src/main/scala/xiangshan/backend/decode/VecDecoder.scala
src/main/scala/xiangshan/backend/fu/vector/VFPU.scala
src/main/scala/xiangshan/backend/fu/vector/VPerm.scala
src/main/scala/xiangshan/backend/rob/Rob.scala
src/main/scala/xiangshan/package.scala

* pom(yunsuan):add vfslide1up & vfslide1down
* func(DecodeUnitComp):support vslide1down & vfslide1down
* func(DecodeUnitComp): support vfslide1up.vf

func(DecodeUnitComp) : support vfslide1up & vslide1down & vfslide1down

---

src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/backend/decode/DecodeUnitComp.scala
src/main/scala/xiangshan/backend/decode/VecDecoder.scala
src/main/scala/xiangshan/backend/fu/vector/VPerm.scala
src/main/scala/xiangshan/package.scala

* func(UopDivType): support VEC_SLIDEUP/VEC_ISLIDEUP/VEC_SLIDEDOWN/VEC_ISLIDEDOWN
* pom(yunsuan): add isVsilde in VpermType & fix bugs of Permutation

func(UopDivType): support VEC_SLIDEUP/VEC_ISLIDEUP/VEC_SLIDEDOWN/VEC_ISLIDEDOWN

---

src/main/scala/xiangshan/v2backend/issue/IssueQueue.scala

* fix(IssueQueue): fix bugs of dequeue selection strategy in IssueQueue

fix(IssueQueue): fix bugs of dequeue selection strategy in IssueQueue

---

src/main/scala/xiangshan/frontend/ITTAGE.scala

fix ITTAGE update condition

---

src/main/scala/xiangshan/frontend/NewFtq.scala

Allow BpuPtr and CommPtr to proceed at the same time when FTQ is full.

Ftq: fix efficiency on full

---

src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/backend/datapath/DataPath.scala
src/main/scala/xiangshan/backend/exu/ExeUnit.scala
src/main/scala/xiangshan/backend/exu/ExeUnitParams.scala
src/main/scala/xiangshan/backend/fu/Bku.scala
src/main/scala/xiangshan/backend/fu/FuncUnit.scala
src/main/scala/xiangshan/backend/fu/fpu/FPToFP.scala
src/main/scala/xiangshan/backend/fu/fpu/FPToInt.scala
src/main/scala/xiangshan/backend/fu/fpu/IntToFP.scala
src/main/scala/xiangshan/backend/fu/wrapper/MulUnit.scala
src/main/scala/xiangshan/backend/issue/IssueQueue.scala
src/main/scala/xiangshan/backend/issue/Scheduler.scala
src/main/scala/xiangshan/backend/issue/StatusArray.scala

func(IQ): add fuBusyTable
func(IssueQueue): suppport fuBusyTable write with og0Resp & og1Resp
func(RSFeedbackType): delete issueFail/rfArbitFail in RSFeedbackType
func(Fu):make some FuncUnits piped
fix(fuBusyTable): fix write of fuBusyTable
type(fuBusyTable): rename & delete some comments

func(fuBusyTable): add fuBusyTable with resp

---

src/main/scala/xiangshan/backend/decode/DecodeUnitComplex.scala
src/main/scala/xiangshan/backend/decode/VecDecoder.scala
src/main/scala/xiangshan/backend/fu/vector/VIMacU.scala
src/main/scala/xiangshan/backend/fu/vector/VPerm.scala
src/main/scala/xiangshan/package.scala

* func(UopDivType): support UopDivType.VEC_COMPRESS & vcompress test pass
* func(VIMac): add VIMac
* pom(yunsuan): add VimacType

func(UopDivType): support vcompress & some insts of VIMac

---

src/main/scala/xiangshan/backend/decode/DecodeUnitComplex.scala
src/main/scala/xiangshan/backend/decode/VecDecoder.scala
src/main/scala/xiangshan/backend/fu/vector/VIAluFix.scala
src/main/scala/xiangshan/package.scala

fix(vsmul_vx): fix a bug of vsmul_vx's decode
func(VecDecoder):support vmv_s_x in vialuF
pom(yunsuan): support vmv_s_x in VialuFixType

func(Decoder):fix a bug of vsmul_vx's decode & support vmv_s_x in vialuF

---

src/main/scala/xiangshan/cache/mmu/MMUBundle.scala

update hit func for global entry

---

src/main/scala/xiangshan/backend/decode/DecodeUnitComplex.scala
src/main/scala/xiangshan/backend/decode/VecDecoder.scala
src/main/scala/xiangshan/backend/fu/vector/VPerm.scala
src/main/scala/xiangshan/package.scala

* func(Decode): support vmvnr
* type(comment):add some comments for DecodeUnitComplex.scala

func(Decode): support vmvnr

---

src/main/scala/xiangshan/mem/lsqueue/UncacheBuffer.scala

- load uncache buffer may hold on 1 cycle

lsu, uncache buffer: fix uncache buffer writeback loadOut is incorrectly held

---

src/main/scala/xiangshan/XSTile.scala

- remove l1i_to_l2_buffer
- remove ptw_to_l2_buffer
- remove intBuffer
- remove bosc_TLBuffer

XSTile: remove some buffers

---

src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/backend/Bundles.scala
src/main/scala/xiangshan/backend/decode/VecDecoder.scala
src/main/scala/xiangshan/backend/fu/FuConfig.scala
src/main/scala/xiangshan/backend/fu/vector/ByteMaskTailGen.scala
src/main/scala/xiangshan/backend/fu/vector/Mgu.scala
src/main/scala/xiangshan/backend/fu/vector/Utils.scala
src/main/scala/xiangshan/backend/fu/vector/VecPipedFuncUnit.scala
src/main/scala/xiangshan/backend/fu/vector/VecSrcTypeModule.scala
src/main/scala/xiangshan/backend/fu/vector/utils/MaskExtrator.scala
src/main/scala/xiangshan/backend/fu/vector/utils/UIntToCont0s.scala
src/main/scala/xiangshan/backend/fu/vector/utils/UIntToCont1s.scala
src/main/scala/xiangshan/backend/fu/vector/utils/VecDataSplitModule.scala
src/main/scala/xiangshan/backend/fu/wrapper/VIAluFix.scala
src/main/scala/xiangshan/backend/fu/wrapper/VIMacU.scala
src/test/scala/xiangshan/backend/fu/vector/ByteMaskTailGenTest.scala

* Add some utilities for vector piped function units

Add vimac support

---

src/main/scala/system/SoC.scala
src/main/scala/top/Top.scala
src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/XSTile.scala
src/test/scala/top/SimTop.scala

Note that tllog is still enabled when alwaysBasicDB is set

Disable chiselDB by default to minimize the size of DB

---

src/main/scala/xiangshan/mem/lsqueue/LoadQueueRAR.scala

- In latest design, delay release check will not happen.

LQ: fix rar release check, remove delay cycle

---

src/main/scala/xiangshan/mem/lsqueue/LSQWrapper.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueueReplay.scala

- Replay cycles increased from 2 to 3 cycles
- Simplified replay selection logic

LQ: Optimizing LoadQueueReplay replay timing

---

src/main/scala/xiangshan/cache/dcache/mainpipe/MissQueue.scala

* all miss entries will have chance to wakeup load replay queue

Dcache: remove should_refill_data_reg

---

src/main/scala/xiangshan/cache/dcache/data/BankedDataArray.scala

loadpipe & write conflict fine grained with bank mask, and update on master.

dcache: loadpipe & write conflict fine grained

---

src/main/scala/xiangshan/backend/fu/wrapper/VIPU.scala
src/main/scala/xiangshan/backend/fu/wrapper/VPPU.scala

vector: fix vred instruction when mask is set

---

src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/XSTile.scala
src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/frontend/Frontend.scala

Move itlbrepeater to Frontend and MemBlock, dtlbrepeater to MemBlock, L2 TLB (PTW) and ptw_to_l2_buffer to Memblock for better partition.

PTW: Move PTW to MemBlock

---

src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala
src/main/scala/xiangshan/cache/dcache/mainpipe/MissQueue.scala
src/main/scala/xiangshan/cache/dcache/mainpipe/WritebackQueue.scala
src/main/scala/xiangshan/mem/lsqueue/FreeList.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueueRAR.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueueRAW.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueueReplay.scala
src/main/scala/xiangshan/mem/lsqueue/VirtualLoadQueue.scala
src/main/scala/xiangshan/mem/prefetch/SMSPrefetcher.scala

- MissQueue timing
- MainPipe timing
- Prefetcher timing
- LSQ timing

MemBlock: fix timing

---

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

* dcache hit rate = s2_dcache_real_miss_first_issue / s2_in_fire_first_issue

perf: add counter

---

src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala
src/main/scala/xiangshan/cache/dcache/loadpipe/LoadPipe.scala
src/main/scala/xiangshan/cache/dcache/mainpipe/MissQueue.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueueReplay.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

- forward data from TL D channel at s2
- fix _wpu_fail_ wakeup logic

Ldu, LQ: fix tl d fwd at s2

---

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

forward accuracy: (s2_successfully_forward_channel_D + s2_successfully_forward_mshr + s3_fwd_frm_d_chan) / s2_forward_req

ldu: add perf counter

---

src/main/scala/xiangshan/frontend/Frontend.scala

This PR adds basic frontend instruction stream check that may check errors before a wrong stream triggers difftest

Frontend: add basic instruction stream check

---

src/main/scala/xiangshan/frontend/Frontend.scala
src/main/scala/xiangshan/frontend/IFU.scala
src/main/scala/xiangshan/frontend/icache/ICache.scala
src/main/scala/xiangshan/frontend/icache/ICacheBundle.scala
src/main/scala/xiangshan/frontend/icache/ICacheMainPipe.scala
src/main/scala/xiangshan/frontend/icache/ICacheMissUnit.scala
src/main/scala/xiangshan/frontend/icache/IPrefetch.scala

ICache: change itlb port to no-blocked
FDIP: optimize timing and functionality (disable temporarily, needs to be optimized)
IFU: fix assert bug

icache: change itlb port to no-blocked and new fdip

---

src/main/scala/xiangshan/backend/CtrlBlock.scala
src/main/scala/xiangshan/backend/rename/Rename.scala
src/main/scala/xiangshan/backend/rename/RenameTable.scala

* add old_pdest connection from vecRat to rename

vector: fix rename for vector instructions

---

src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/mem/prefetch/SMSPrefetcher.scala

* pass evict from agt to pht only when access_cnt is greater than 1

sms: fix evict condition

---

src/main/scala/xiangshan/frontend/Frontend.scala
src/main/scala/xiangshan/frontend/IFU.scala
src/main/scala/xiangshan/frontend/PreDecode.scala

Predecode delayed to f3 and use partial paralle valid generation logic in f2
Remove CacheOp support in ICache

Frontend: timing optimization

---

src/main/scala/xiangshan/mem/lsqueue/UncacheBuffer.scala

Using AddPipelineReg to refactor handshake logic. There may be bugs in the old logic.

UncacheBuffer: refactoring uncache buffer hand shake logic

---

src/main/scala/xiangshan/backend/Scheduler.scala
src/main/scala/xiangshan/backend/exu/WbArbiter.scala
src/main/scala/xiangshan/backend/fu/CSR.scala
src/main/scala/xiangshan/backend/rob/Rob.scala
src/main/scala/xiangshan/cache/dcache/mainpipe/MissQueue.scala
src/main/scala/xiangshan/cache/mmu/L2TLB.scala
src/main/scala/xiangshan/cache/mmu/TLB.scala
src/main/scala/xiangshan/frontend/icache/ICacheMainPipe.scala
src/main/scala/xiangshan/frontend/icache/ICacheMissUnit.scala
src/main/scala/xiangshan/frontend/icache/IPrefetch.scala
src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
src/main/scala/xiangshan/mem/pipeline/AtomicsUnit.scala
src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala

* add `VERILATOR_5` macro to indicate v5.0
* update the clock gating primitive for Verilator v5.0
* remove the clock IOs for DifftestModules

Bump difftst, huancun, and utility

---

src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/backend/decode/DecodeUnit.scala
src/main/scala/xiangshan/backend/decode/VecDecoder.scala
src/main/scala/xiangshan/backend/fu/FuConfig.scala
src/main/scala/xiangshan/backend/fu/FuType.scala
src/main/scala/xiangshan/backend/fu/vector/VecPipedFuncUnit.scala
src/main/scala/xiangshan/backend/fu/wrapper/VCVT.scala

1. add vfcvt fu.
2. suppport vfrsqrt7, vfrec7 and all vector float convert inst in RVV1.0.

rtl: add vfcvt fu

---

src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/backend/Backend.scala
src/main/scala/xiangshan/backend/Bundles.scala
src/main/scala/xiangshan/backend/datapath/DataPath.scala
src/main/scala/xiangshan/backend/fu/CSR.scala
src/main/scala/xiangshan/backend/issue/EnqEntry.scala
src/main/scala/xiangshan/backend/issue/IssueQueue.scala
src/main/scala/xiangshan/backend/issue/OthersEntry.scala
src/main/scala/xiangshan/backend/issue/Scheduler.scala
src/main/scala/xiangshan/backend/regfile/Regfile.scala
src/main/scala/xiangshan/mem/MemCommon.scala

These may not cause any performance change.

DontCare or remove unconnected/unused and connect missing signals

---

src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala

check probe_ttob when coh is Trunk or Dirty

mainpipe: fix probe tob

---

src/main/scala/top/Configs.scala
src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/frontend/NewFtq.scala
src/main/scala/xiangshan/frontend/icache/ICache.scala
src/main/scala/xiangshan/frontend/icache/ICacheBundle.scala
src/main/scala/xiangshan/frontend/icache/ICacheMainPipe.scala
src/main/scala/xiangshan/frontend/icache/ICacheMissUnit.scala
src/main/scala/xiangshan/frontend/icache/IPrefetch.scala

The prefetch location is optional, prefetch to L2 was selected temporarily due to timing

fdip: change instruction prefetch position to L2

---

src/main/scala/xiangshan/frontend/BPU.scala
src/main/scala/xiangshan/frontend/FrontendBundle.scala

This PR fixes the wrong comments.
No code actually changed.

docs: change comments

---

src/main/scala/xiangshan/mem/lsqueue/LoadQueueReplay.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

Bugs descriptions:
when WPU enable (default disable), load may not be wakeup cause WPU predict fail.
Bugs fix:
add wakeup logic.

LDU, LQ:fix wpu wakeup

---

src/main/scala/device/AXI4Memory.scala
src/main/scala/device/AXI4RAM.scala
src/main/scala/xiangshan/cache/dcache/FakeDCache.scala
src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
src/test/scala/top/SimTop.scala

* use the abstract DifftestMem class
* move DifftestModule.finish to hardware

Bump difftest

---

src/main/scala/top/Configs.scala

- from 128KB to 64KB
- from 8 ways to 4 ways

DCache: reduce dcache from 128KB to 64KB for better area

---

scripts/sram_size_collect.py

This should help SRAM size confirmation

util: add sram size collect script

---

.github/CODEOWNERS

Code owner's review will be enforced in frontend

github: add frontend code owner info

---

src/main/scala/xiangshan/backend/Backend.scala
src/main/scala/xiangshan/backend/exu/ExeUnit.scala
src/main/scala/xiangshan/backend/fu/wrapper/VCVT.scala
src/main/scala/xiangshan/backend/issue/CancelNetwork.scala
src/main/scala/xiangshan/backend/issue/Dispatch2Iq.scala
src/main/scala/xiangshan/backend/issue/Entries.scala
src/main/scala/xiangshan/backend/issue/FuBusyTableWrite.scala
src/main/scala/xiangshan/backend/issue/IssueQueue.scala
src/main/scala/xiangshan/backend/rename/RenameTable.scala
src/main/scala/xiangshan/backend/rob/Rob.scala

Ensure that redundant debug logic is cleared in the release version.

backend: control dontTouch opcode by debugEn

---

Makefile
src-chisel/main/scala/top/XiangShanStage.scala
src-chisel/main/scala/xiangshan/types.scala
src-chisel/main/scala/xstransforms/Helpers.scala
src-chisel/main/scala/xstransforms/PrintControl.scala
src-chisel/main/scala/xstransforms/PrintModuleName.scala
src-chisel3/main/scala/xiangshan/types.scala
src/main/scala/top/Generator.scala
src/main/scala/xstransforms/PrintControl.scala
src/test/scala/fu/IntDiv.scala
src/test/scala/xiangshan/DecodeTest.scala

PrintControl and PrintModuleName should be fully supported in chisel 6. Usage is the same as that in chisel 3.

xstransform: support PrintControl and PrintModuleName for chisel6

---

src/main/scala/xiangshan/backend/decode/DecodeUnitComp.scala
src/main/scala/xiangshan/backend/fu/FuConfig.scala
src/main/scala/xiangshan/backend/issue/IssueQueue.scala
src/main/scala/xiangshan/package.scala

* update fuOpType for vload and vstore
* add vpu connection for vload and vstore issue queue

rv64v: fix vload/vstore issuse queue connection

---

src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/frontend/NewFtq.scala

TODO: backend remove jmp/ldReplay/exception

ftq: remove jmp/ldReplay/exception(redirectAhead)

---

src/main/scala/xiangshan/frontend/IFU.scala

1.  PC adder‘s logical depth cut in half 
2.  merge some adders

IFU adder optimize

---

src/main/scala/xiangshan/frontend/BPU.scala
src/main/scala/xiangshan/frontend/Composer.scala

ftq: reduce meta length

---

src/main/scala/utils/Trigger.scala
src/main/scala/xiangshan/frontend/PreDecode.scala

Frontend debug module used more than expected comparing logic.
Still waiting for possible removal of instruction comparison

predecode: optimize frontend debug module size

---

src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/backend/CtrlBlock.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueueRAW.scala
src/main/scala/xiangshan/mem/lsqueue/UncacheBuffer.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

LQ: remove rawNuke

---

src/main/scala/xiangshan/frontend/icache/ICache.scala

ICache Data SRAM: 4 blocks of 128x1024 -> 16 blocks of 128x256

ICache: split dataArray for physical synthesis

---

src/main/scala/xiangshan/cache/dcache/Uncache.scala

Bugs description:
when uncache outstanding disable,  _uncache.io.flush.empty_ is incorrect.
Bugs fix:
use invalid count to fix _uncache.io.flush.empty_

Uncache: fix flush.empty logic

---

src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/backend/Bundles.scala
src/main/scala/xiangshan/backend/decode/DecodeUnitComp.scala
src/main/scala/xiangshan/backend/decode/VecDecoder.scala
src/main/scala/xiangshan/backend/fu/FuConfig.scala
src/main/scala/xiangshan/backend/fu/fpu/IntToVec.scala
src/main/scala/xiangshan/backend/fu/wrapper/VIAluFix.scala
src/main/scala/xiangshan/package.scala

* also fix some bugs for vwadd.w and vrgather.vi

rv64v: support copy data directly use i2v

---

README.md

Remove acknowledgement from readme, will review and add license in the following commits.

Remove acknowledgement

---

src/main/scala/xiangshan/frontend/ITTAGE.scala

Modify the writing method of ITTAGE validArray

Modify the writing method of ITTAGE validArray

---

scripts/vlsi_mem_gen

This fixes the bug introduced in #2591

scripts: fix 1bitmask memory gen

---

src/main/scala/xiangshan/backend/decode/DecodeStage.scala
src/main/scala/xiangshan/backend/decode/DecodeUnitComp.scala
src/main/scala/xiangshan/backend/decode/UopInfoGen.scala
src/main/scala/xiangshan/backend/fu/FuType.scala
src/main/scala/xiangshan/backend/fu/wrapper/VPPU.scala
src/main/scala/xiangshan/mem/vector/VSUopQueue.scala

vcompress:
1. uop split
2. refactor vcompress
VSUopQueue:
1. fix recover entry when redirect

Refactor vcompress and fix VSUopQueue bug

---

src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/backend/decode/DecodeUnit.scala
src/main/scala/xiangshan/backend/decode/VecDecoder.scala
src/main/scala/xiangshan/backend/fu/FuConfig.scala
src/main/scala/xiangshan/backend/fu/FuType.scala
src/main/scala/xiangshan/backend/fu/wrapper/VIDiv.scala

* support vdiv, vdivu, vrem and vremu

rv64v: add vidiv module

---

src/main/scala/xiangshan/backend/fu/CSR.scala
src/main/scala/xiangshan/backend/fu/wrapper/VFALU.scala
src/main/scala/xiangshan/mem/lsqueue/FreeList.scala

CSR and LSQueue: add enable to RegNext
vfalu: fix bug for fp widen add/sub instructions

low power and rv64v : add enable to RegNext and fix bug for fp widen add/sub instructions

---

src/main/scala/xiangshan/frontend/icache/ICache.scala
src/main/scala/xiangshan/frontend/icache/ICacheMainPipe.scala

Flush ICacheMainPipe pipeline and invalidate reserved data when receive fencei.

ICache: fix ICacheMainPipe bug about fencei

---

src/main/scala/xiangshan/backend/Backend.scala

This reverts commit db91dcf13d2e3e40bec0f41a2d61346bb2b3baa4.

Revert "backend: vfExuBlock out assigin 0"

---

src/main/scala/xiangshan/backend/issue/Dispatch2Iq.scala
src/main/scala/xiangshan/mem/vector/VLUopQueue.scala

1. VLUopQueue: fix recover entry when redirect
2. Dispatch2Iq: fix load deq ports selection

VLUopQueue & Dispatch2Iq: fix recover entry when redirect & fix load deq ports selection

---

.github/workflows/emu.yml
Makefile
build.sc
scripts/xiangshan.py
src/main/scala/utils/Trigger.scala
src/main/scala/xiangshan/backend/fu/CSR.scala
src/main/scala/xiangshan/backend/fu/Multiplier.scala
src/main/scala/xiangshan/backend/fu/SRT16Divider.scala
src/main/scala/xiangshan/backend/fu/SRT4Divider.scala
src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala
src/main/scala/xiangshan/cache/dcache/mainpipe/MissQueue.scala
src/main/scala/xiangshan/cache/mmu/L2TLB.scala
src/main/scala/xiangshan/cache/mmu/MMUBundle.scala
src/main/scala/xiangshan/cache/mmu/TLBStorage.scala
src/main/scala/xiangshan/mem/prefetch/L1PrefetchComponent.scala
src/main/scala/xiangshan/mem/sbuffer/DatamoduleResultBuffer.scala

Some deprecated APIs in chisel 3.6.0 have been deleted in chisel 6.0.0. This PR replaces them.

chore: bump chisel 6.0.0

---

src/main/scala/xiangshan/frontend/Frontend.scala
src/main/scala/xiangshan/frontend/icache/ICache.scala
src/main/scala/xiangshan/frontend/icache/ICacheMainPipe.scala

Flush ICacheMainPipe pipeline when receive backend redirect.

ICache: fix ICacheMainPipe bug about sfence

---

Makefile

Command should be as follows:
Build:
make sim-verilog PLDM=1 WITH_CHISELDB=0 WITH_CONSTANTIN=0 MFC=1
make pldm-build SYNTHESIS=1 (no-diff) || make pldm-build (with-diff)
To add extra Macros, we can pass PLDM_EXTRA_MACRO="+define+xxx +define+yyy"
Run:
make pldm-run/pldm-debug SYNTHESIS=1 (no-diff) || make pldm-run/pldm-debug (with-diff)
To add extra running args, we can pass PLDM_EXTRA_ARGS="+workload=../../ready-to-run/microbench.bin +diff=../../ready-to-run/riscv64-nemu-interpreter-so". Note that relative paths should be based on build/pldm-compile

Bump difftest for palladium simulation

---

scripts/generate_all.sh
scripts/parser.py

scripts to parse verilog for physical design group
these scripts are originally in southlake branch

Script: add verilog parser script

---

src/main/scala/xiangshan/mem/prefetch/L1PrefetchComponent.scala
src/main/scala/xiangshan/mem/prefetch/L1StreamPrefetcher.scala
src/main/scala/xiangshan/mem/prefetch/SMSPrefetcher.scala

prefetch: clock gated

---

src/main/scala/xiangshan/cache/mmu/L2TLB.scala
src/main/scala/xiangshan/cache/mmu/PageTableCache.scala
src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala
src/main/scala/xiangshan/cache/mmu/TLB.scala
src/main/scala/xiangshan/cache/mmu/TLBStorage.scala

MMU clockgeted (24-02-22)
* Finshed:
RegNext -> RegEnable(Except valid)
* TODO:
1. RegNext -> RegEnable(valid)
2. reg file(add Ren)
3. delete note

Kmh v2 mmu reg ctrl

---

src/main/scala/xiangshan/frontend/NewFtq.scala
src/main/scala/xiangshan/frontend/icache/ICache.scala

ftq_redirect_sram: 64*247 -> 64*248
ftq_meta_1r_sram: 64*219 -> 64*220
ICache: fix ready of SRAMTemplateWithFixedWidth

Ftq: change SRAM size

---

src/main/scala/xiangshan/backend/fu/fpu/FMA.scala

This backports #2779 and #2586 from master. Should be rebased and merged.

Fix fma rm

---

Makefile
src/main/scala/system/SoC.scala
src/main/scala/top/ArgParser.scala
src/main/scala/top/Top.scala
src/main/scala/xiangshan/transforms/NestedPrefixModulesAnnotation.scala

This does not work for chisel 3

Makefile: `XSTOP_PREFIX` for nested prefix of `XSTop`

---

src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/frontend/BPU.scala
src/main/scala/xiangshan/frontend/FTB.scala
src/main/scala/xiangshan/frontend/FauFTB.scala
src/main/scala/xiangshan/frontend/FrontendBundle.scala
src/main/scala/xiangshan/frontend/ITTAGE.scala
src/main/scala/xiangshan/frontend/NewFtq.scala
src/main/scala/xiangshan/frontend/SC.scala
src/main/scala/xiangshan/frontend/Tage.scala
src/main/scala/xiangshan/frontend/newRAS.scala

ftb_entry_mem:
full ftb_entry: reg->sram;
origin reg: dlt valid/lower/tarStat/pftAddr/carry/last_may_be_rvi_call/always_taken
ftq_meta_1r_sram:
dlt Tage_SC: scMeta-tageTakens/scUsed/providerResps-unconf/altDiffers/takens;
dlt ITTage: altDiffers/taken
dlt uFTB: pred_way
dlt RAS: sctr/TOSR/NOS
ftq_redirect_sram->ftq_redirect_mem

ftq: cut ftq area

---

src/main/scala/xiangshan/backend/exu/ExuBlock.scala
src/main/scala/xiangshan/backend/issue/Entries.scala
src/main/scala/xiangshan/backend/issue/EntryBundles.scala
src/main/scala/xiangshan/backend/rob/Rob.scala

add xsperf:
caculate all exu fire cnt
caculate load wakeup/cancel
calculate wait falu,fmac,fdiv and falu(all fuoptype)

add some xsperf

---

src/main/scala/xiangshan/backend/Bundles.scala
src/main/scala/xiangshan/backend/issue/Dispatch2Iq.scala
src/main/scala/xiangshan/backend/issue/Scheduler.scala
src/main/scala/xiangshan/backend/rename/Rename.scala
src/main/scala/xiangshan/mem/lsqueue/LSQWrapper.scala
src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
src/main/scala/xiangshan/mem/lsqueue/VirtualLoadQueue.scala

add LSQ backpressure logic and 'uop' continuous application LSQ entries logic

rv64v:add support for continuous 'uop'

---

src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/backend/dispatch/Dispatch.scala
src/main/scala/xiangshan/backend/fu/util/Trigger.scala
src/main/scala/xiangshan/frontend/PreDecode.scala
src/main/scala/xiangshan/mem/pipeline/AtomicsUnit.scala

* delete data trigger in frontend
* optimiza trigger comparison logic
co-author-by: Guokai Chen <chenguokai17@mails.ucas.ac.cn>
* delete frontendTiming & frontendChain in TriggerCf

Trigger: optimize trigger

---

src/main/scala/xiangshan/backend/fu/vector/VecPipedFuncUnit.scala
src/main/scala/xiangshan/backend/fu/wrapper/VFALU.scala

1. fix vs2 and vs1 swapping positions when widen occurs on vs1
2. fix vfalu timing

rv64v: fix vfalu timing

---

src/main/scala/xiangshan/backend/dispatch/Dispatch.scala

TopDown: fix load store not issue condition

---

src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/frontend/BPU.scala
src/main/scala/xiangshan/frontend/FrontendBundle.scala
src/main/scala/xiangshan/frontend/ITTAGE.scala
src/main/scala/xiangshan/frontend/NewFtq.scala
src/main/scala/xiangshan/frontend/SC.scala
src/main/scala/xiangshan/frontend/Tage.scala

dlt folded_hist/afhob/lastBrNumOH
ftq_redirect_mem: 247*64->73*64

ftq: cut area of ftq_redirect_mem

---

src/main/scala/xiangshan/backend/fu/wrapper/VFALU.scala

fix vfalu timing :
advance eew vdidx vlfix to previous cycle

fix vfalu timing

---

src/main/scala/xiangshan/cache/mmu/MMUBundle.scala
src/main/scala/xiangshan/cache/mmu/MMUConst.scala
src/main/scala/xiangshan/cache/mmu/PageTableCache.scala

It should be noted that this commit will change SRAM width between ecc enable and unable.

PTW, PageCache: set ECC disable by default

---

src/main/scala/xiangshan/backend/fu/vector/ByteMaskTailGen.scala
src/main/scala/xiangshan/backend/fu/vector/Mgu.scala
src/main/scala/xiangshan/backend/fu/wrapper/VIAluFix.scala
src/main/scala/xiangshan/backend/fu/wrapper/VIMacU.scala
src/test/scala/xiangshan/backend/fu/vector/ByteMaskTailGenTest.scala

* Modify the signal names about divided vector elements to be consistent with RVV Spec.

FU: fix mgu for body elements's agnostic

---

src/main/scala/xiangshan/backend/exu/ExeUnit.scala
src/main/scala/xiangshan/backend/fu/FuConfig.scala
src/main/scala/xiangshan/backend/fu/FuncUnit.scala
src/main/scala/xiangshan/backend/fu/FunctionUnit.scala
src/main/scala/xiangshan/backend/fu/fpu/FPUSubModule.scala

move extra delay to latency field renamed as extralatency 
use it as latency = Certaindelay(original delay, extra delay)

Functionunit: move extra delay to latency field and rename

---

Makefile
src/main/scala/top/ArgParser.scala

use DISABLE_ALWAYSDB=1   disab AlwaysBasicDB

args: add support for disabling AlwaysBasicDB

---

src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/cache/mmu/MMUConst.scala

This will make FIR elaboration much faster as discussed in #2951

Parameters: replace val with def in trait HasXSParametes

---

Makefile
src/main/scala/xiangshan/backend/Backend.scala
src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/backend/fu/CSR.scala
src/main/scala/xiangshan/backend/issue/Dispatch2Iq.scala
src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala
src/main/scala/xiangshan/cache/dcache/data/BankedDataArray.scala
src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala
src/main/scala/xiangshan/cache/dcache/mainpipe/MissQueue.scala
src/main/scala/xiangshan/cache/mmu/L2TLB.scala
src/main/scala/xiangshan/frontend/IFU.scala
src/main/scala/xiangshan/frontend/NewFtq.scala
src/main/scala/xiangshan/frontend/icache/ICacheMainPipe.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueueReplay.scala
src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
src/main/scala/xiangshan/mem/prefetch/L1StreamPrefetcher.scala
src/main/scala/xiangshan/mem/prefetch/L1StridePrefetcher.scala
src/main/scala/xiangshan/mem/prefetch/PrefetcherMonitor.scala
src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala

* use BigInt for initValue of Constantin.createRecord
* use WITH_CONSTANTIN=1 to enable the ConstantIn plugin

Bump utility and disable ConstantIn by default

---

src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/frontend/FrontendBundle.scala

Remove these prints during compilation.

bpu: clean up param and remove annoying print

---

src/main/scala/top/Top.scala
src/main/scala/xiangshan/L2Top.scala

Since coupledL2 and HuanCun are using p(MaxHartIdBits), we should pass them in the configs.

Configs: Pass MaxHartIdBits to Caches

---

src/main/scala/xiangshan/cache/CacheInstruction.scala
src/main/scala/xiangshan/frontend/IFU.scala
src/main/scala/xiangshan/frontend/PreDecode.scala
src/main/scala/xiangshan/frontend/icache/ICache.scala
src/main/scala/xiangshan/frontend/icache/ICacheMainPipe.scala

This PR is dup with #2734, just resolve conflict after new-backend merged.

ifu: clock gating optimization

---

src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/backend/decode/DecodeStage.scala
src/main/scala/xiangshan/backend/decode/DecodeUnitComp.scala
src/main/scala/xiangshan/backend/fu/CSR.scala
src/main/scala/xiangshan/backend/fu/FuConfig.scala
src/main/scala/xiangshan/backend/fu/FuType.scala

Fix some vector bugs due to floating point splitting. See commit message for details.

Fix some vector bugs due to floating point splitting

---

src/main/scala/xiangshan/backend/fu/wrapper/VIAluFix.scala

1. vmask: use old vd when vl = 0 for vmsbf, vmsif and vmsof
2. Zvbb: 
1.  fix wrong result location for vclz and vctz
2.  fix input and output for vwsll
3. Util: Concatenate the input and 1 as the new input in priorityEncode to solve the input is all 0

fix Zvbb and vmask bug

---

src/main/scala/xiangshan/backend/datapath/DataPath.scala
src/main/scala/xiangshan/backend/issue/IssueQueue.scala

See commit message for details.

Fix some vector bugs after merging out-of-order vlsu

---

src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/backend/MemBlock.scala

This commit remove one vector load/store RS, which is for timing.

remove one vector load/store RS

---

src/main/scala/xiangshan/mem/lsqueue/FreeList.scala
src/main/scala/xiangshan/mem/lsqueue/LSQWrapper.scala
src/main/scala/xiangshan/mem/lsqueue/LoadExceptionBuffer.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueueRAR.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueueRAW.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueueReplay.scala
src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
src/main/scala/xiangshan/mem/lsqueue/StoreQueueData.scala
src/main/scala/xiangshan/mem/lsqueue/UncacheBuffer.scala
src/main/scala/xiangshan/mem/lsqueue/VirtualLoadQueue.scala

LSQ: optimize static clock gating coverage

---

src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala

onlyStage1 reqs may be sent into LLPTW. Their state transition is similar to noS2xlate reqs'. Their state need to be addr_check rather than hptw_req

LLPTW: fix error state transition when the new llptw req is onlyStage1

---

src/main/scala/xiangshan/backend/rob/Rob.scala

Previous we submit loadEvent for all committed instructions. According to cpp code, we only check load when isAmo and isLoad. And MMIO will be skipped, no need to check REF and GoldenMem.
When some loadEvent are dropped to speed up difftest, this change fix legacy impact of loadEvent unprocessed before.

difftest: check load only when isAmo or isLoad and skip MMIO

---

src/main/scala/xiangshan/backend/Backend.scala
src/main/scala/xiangshan/backend/Bundles.scala
src/main/scala/xiangshan/backend/CtrlBlock.scala
src/main/scala/xiangshan/backend/datapath/BypassNetwork.scala
src/main/scala/xiangshan/backend/datapath/VldMergeUnit.scala
src/main/scala/xiangshan/backend/datapath/WbArbiter.scala
src/main/scala/xiangshan/backend/exu/ExeUnit.scala
src/main/scala/xiangshan/backend/exu/ExeUnitParams.scala
src/main/scala/xiangshan/backend/rob/Rab.scala
src/main/scala/xiangshan/backend/rob/Rob.scala

rab:
fix commit/walk/special walk Count from popcount to priority mux
exuwb:
fix exuwb Nto1 logic: add int/fp/vec 3 wbpath to wbarbiter
wbtorob:
fix writebacknum count: delete extra count for exu which cannot be compressed

Backend fixtiming: fix rab/exuwb/wbtorob timing

---

src/main/scala/xiangshan/mem/lsqueue/FreeList.scala
src/main/scala/xiangshan/mem/lsqueue/LSQWrapper.scala
src/main/scala/xiangshan/mem/lsqueue/LoadExceptionBuffer.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueueRAR.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueueRAW.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueueReplay.scala
src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
src/main/scala/xiangshan/mem/lsqueue/StoreQueueData.scala
src/main/scala/xiangshan/mem/lsqueue/UncacheBuffer.scala
src/main/scala/xiangshan/mem/lsqueue/VirtualLoadQueue.scala

This reverts commit 082b30d1b017bd096bce2e5fc66bac2ab749293a.

Revert "LSQ: optimize static clock gating coverage (#3023)"

---

.github/CODEOWNERS

remove @ssszwic(SongZhengwei) and add @ngc7331(XuZhihao) according to #3050.

MISC: Update CODEOWNERS about ICache

---

src/main/scala/xiangshan/frontend/icache/ICache.scala
src/main/scala/xiangshan/frontend/icache/ICacheMainPipe.scala

The new ICache will soon be merged into master (https://github.com/OpenXiangShan/XiangShan/pull/3051) and it doesn't have this problem. On the other hand, the verification team still needs a functionally correct version of the old icache.
Therefore, I'm creating a new branch [frontend-240614-verification](https://github.com/OpenXiangShan/XiangShan/tree/frontend-240614-verification?rgh-link-date=2024-06-14T10%3A39%3A10Z) for verification team, and moving this PR to the new branch.

ICache: Init registers to prevent x-state

---

src/main/scala/xiangshan/backend/Bundles.scala
src/main/scala/xiangshan/backend/datapath/BypassNetwork.scala
src/main/scala/xiangshan/backend/issue/EnqEntry.scala
src/main/scala/xiangshan/backend/issue/Entries.scala
src/main/scala/xiangshan/backend/issue/IssueQueue.scala

BypassNetwork: ExuOH->ExuVec, add mask for forwardOrBypassValidVec3

---

src/main/scala/xiangshan/frontend/NewFtq.scala

Previously, FTQ did not handle flush-itself redirect level, which is used by load replays. This leads to running out of FTQ entries because commPtr remains the same while ifuPtr keeps increasing when a new replay redirect request arrives. Now, commPtr will also increase in this scenario.

fix: multiple load replays lead to running out of FTQ entries

---

src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/backend/issue/Dispatch2Iq.scala
src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
src/main/scala/xiangshan/mem/lsqueue/VirtualLoadQueue.scala
src/main/scala/xiangshan/mem/vector/VSegmentUnit.scala
src/main/scala/xiangshan/mem/vector/VecCommon.scala
src/main/scala/xiangshan/package.scala

Support for vector exceptions has been added to StoreQueue, as described in (887019e53d5b5984d81306d4bf9de1af0abf9278).
Modified the dispatch logic of vector access instruction in dispatch2iq, and modified the queue logic in LSQ, as described in (8d5a89235ddd9eb16bf33169bdc1ba030b295a53).
Fixed some bugs in vector SegmentIndex instruction, as described in (4752638fa49a8f7bae14615e5902cfc14ac05e0c).

VLSU: Fix vector exception handling and fix bug for SegmentUnit.

---

src/main/scala/xiangshan/mem/vector/VSegmentUnit.scala

This commit fix bug of VsegmentUnit sent `v0Wen` false.

VSegmentUnit: refactor control signal assignment

---

src/main/scala/xiangshan/backend/Backend.scala
src/main/scala/xiangshan/backend/CtrlBlock.scala
src/main/scala/xiangshan/backend/decode/DecodeStage.scala
src/main/scala/xiangshan/backend/decode/DecodeUnit.scala
src/main/scala/xiangshan/backend/decode/DecodeUnitComp.scala
src/main/scala/xiangshan/backend/decode/VecDecoder.scala
src/main/scala/xiangshan/backend/decode/VecExceptionGen.scala
src/main/scala/xiangshan/backend/fu/CSR.scala
src/main/scala/xiangshan/backend/rob/Rob.scala

* after execute vset and vload/vstore(no exception) instructions, set vstart to zero
* when execute vector instructions except above instructions, raise illegal instruction exception
* when modify vstart, blockback and flushpipe

vstart: support vstart value update and handle vstart exception

---

src/main/scala/xiangshan/cache/dcache/loadpipe/LoadPipe.scala

Remove redundant s2_nack_data from s2_mq_nack

DCache: Remove redundant nack_data from mq_nack

---

src/main/scala/xiangshan/backend/fu/wrapper/VFALU.scala

when fold , only some bits of fflags from vfalu0 are valid
fflags vfredmin/max has to be masked

Vfalu: fix ffagsEn logic for vfredunction

---

.github/workflows/emu.yml
.gitmodules
build.sc
src/main/scala/system/SoC.scala
src/main/scala/top/BusPerfMonitor.scala
src/main/scala/top/Configs.scala
src/main/scala/top/Top.scala
src/main/scala/xiangshan/L2Top.scala
src/main/scala/xiangshan/XSTile.scala
src/test/scala/top/SimTop.scala

This pull request implements [DummyLLC](https://github.com/OpenXiangShan/OpenLLC) as a home node in CHI version of XiangShan. Please note that DummyLLC has no local cache or snoop filter and merely functions as interconnect, so it cannot be used to analyze performance.

Add DummyLLC and SimTop for CHI version

---

src/main/scala/xiangshan/backend/fu/wrapper/VFALU.scala

fix vfredmin/max
when only one active src and the src is sNAN, the result should be sNAN not cNAN
set default result of fflags mask ,when not fold
set fflagsen of last uop to 0x00000001

Vfalu: add fflagsEn default value; fix vfredmin/max

---

src/main/scala/xiangshan/backend/decode/DecodeUnit.scala

* Auto-vectorized generates a large number of csrr vlenb instructions. Csr instructions require waitForward and blockBackward, which reduce program performance. Therefore, we can convert it to a simple addi instruction to reduce the stalls in pipeline.

csr: convert csrr vlenb instruction to a addi instruction

---

src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala

Add satp and vsatp check to flush condition in HPTW

HPTW, RVH: Fix flush condition

---

src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala

When hptw resps gaf or gpf, llptw should change status to mem_out. This state transition is wrong.

LLPTW, RVH: fix the bug that llptw doesn't resp L1TLB when hptw gaf or gpf happens

---

src/main/scala/xiangshan/backend/CtrlBlock.scala
src/main/scala/xiangshan/backend/rename/Rename.scala
src/main/scala/xiangshan/backend/rob/Rob.scala
src/main/scala/xiangshan/backend/rob/RobBundles.scala
src/main/scala/xiangshan/backend/rob/RobDeqPtrWrapper.scala

1.when writeback exception, rob may commit next cycle. 2.when fulshOut, rob commit info to ftq may 4 cycle after redirect but redirect info to ftq need 5 cycle.

Rob: fix bug of exception

---

src/main/scala/xiangshan/backend/fu/wrapper/VFALU.scala

each uop need fflags according to fold situation

Vfalu: fix vfredusum fflags

---

src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/frontend/newRAS.scala

Fix NOS update error when redirecting ret instruction, and correct the bit width of sctr.

RAS: modify the NOS pointer write value during redirection

---

src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala

*add tselect, tdada1 selected, tinfo, tcontrol

NewCSR: support trigger csr in difftest

---

src/main/scala/xiangshan/backend/fu/NewCSR/CSRPermitModule.scala

* Wen data legal when !(EX_II | EX_VI)

NewCSR: Modify the condition of legal wen

---

src/main/scala/xiangshan/backend/dispatch/Dispatch.scala

*hart should have entered debugMode after singleStep generate exception

debugModule: fix bug，singleStep don't generate exception correctly.

---

.github/workflows/emu.yml
scripts/xiangshan.py

This commit add simple ci test for V extension.

ci: add ci for V extension

---

src/main/scala/xiangshan/frontend/icache/ICacheMainPipe.scala

In original code, when `fromMSHR.bits.corrupt && fromMSHR.valid === true.B`:
`s2_MSHR_match` will be `false.B`
-> `s2_MSHR_hits` will be `false.B`
-> `s2_hits` and `s2_corrupt` is never updated
Therefore, MainPipe will be still waiting for MissUnit response, however, MissUnit assumes MainPipe has received data, so it will not send again. MainPipe hangs forever, and no access fault is sent to IFU.
Fix:
`s2_MSHR_match` no longer requires `!fromMSHR.bits.corrupt`, thus `s2_hits` and `s2_corrupt` will be updated. However, we still not update `s2_datas` to save power.

ICacheMainPipe: fix s2_hit/corrupt not updating when fromMSHR.corrupt

---

src/main/scala/xiangshan/backend/decode/DecodeUnit.scala
src/main/scala/xiangshan/backend/fu/NewCSR/MachineLevel.scala
src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala

* Support difftest for fcsr.
* Set misa.B to 1.
* bump nemu ref and spike ref.

difftest: support difftest for fcsr.

---

src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala
src/main/scala/xiangshan/cache/dcache/data/BankedDataArray.scala
src/main/scala/xiangshan/cache/wpu/VictimList.scala
src/main/scala/xiangshan/cache/wpu/WPUWrapper.scala

fix points:
1. parameter bug in DCacheWrapper
2. add clock gate to avoid frequent flip in BankedDataArray
3. remove redundant designs in WPU
power comparison：

wpu: fix the issue of abnormal power 

---

src/main/scala/xiangshan/backend/fu/NewCSR/InterruptBundle.scala
src/main/scala/xiangshan/backend/fu/NewCSR/InterruptFilter.scala
src/main/scala/xiangshan/backend/fu/NewCSR/TrapHandleModule.scala

* All major interrupts have been splited into 7 groups
* Custom highest group
* Local high group
* Custom middle-high group
* Priviledge architecture group
* Custom middle-low group
* Local low group
* Custom lowest group

CSR: add custom IRQ injection mechanism

---

src/main/scala/xiangshan/frontend/IFU.scala

Fixes state transfer condition of `m_sendTLB` and `m_tlbResp` in IFU mmio fsm.
https://github.com/OpenXiangShan/XiangShan/blob/091c28ff02749943c410f414784d991bc205e8cb/src/main/scala/xiangshan/frontend/IFU.scala#L659-L663
2 years ago, TLB can be configured as `sameCycle` and therefore `io.iTLBInter.resp.bits.miss` is in the same cycle with `io.iTLBInter.req.fire`, see: https://github.com/OpenXiangShan/XiangShan/blob/c3b2d83a43a64198f94aced1db4b998ebf29a3bb/src/main/scala/xiangshan/cache/mmu/TLBStorage.scala#L59-L62
In that case, the current fsm will wait in state `m_sendTLB` until `io.iTLBInter.resp.bits.miss === false.B` (TLB hit or PTW work done), and enters state `m_tlbResp` in next cycle, getting the correct response (`paddr`, etc.).
However, currently `io.iTLBInter.resp.bits.miss` is …

IFU: fix mmio fsm for itlb handshake

---

src/main/scala/xiangshan/backend/datapath/DataConfig.scala

Bump Difftest, and fix a bug that the pc vaddr only support 39 bits in branch unit.

Bump difftest.

---

src/main/scala/xiangshan/frontend/newRAS.scala

When the speculation queue is about to overflow, the bpu is blocked. When the call instruction retires, the bottom data of the speculation queue is automatically dequeued.

RAS: Block BPU prediction when the speculative queue is about to overflow

---

scripts/xiangshan.py

previous line
```scala
self.with_chiseldb = 0 if args.no_db else None
```
will cause with_chiseldb permanently disabled

script: fix xiangshan.py `with_chiseldb` permanently disabled

---

src/main/scala/xiangshan/frontend/icache/ICacheMissUnit.scala

See Tilelink spec section 4.4:
> The ones that are not marked corrupt still contain valid data. Every TileLink request message requires a mandatory response message of a mandatory size, and all beats of the message must be sent, even if every beat is marked as corrupt.
We can't simply reset counter and send response to MainPipe when corruption happens, but we have to wait until all beats of the message are sent back from L2 cache even if there's a corrupt.

ICacheMissUnit: wait for all beats even corrupt has already occurred

---

src/main/scala/xiangshan/cache/mmu/MMUBundle.scala
src/main/scala/xiangshan/cache/mmu/PageTableCache.scala
src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala

1. gpf pte shouldn't be refilled in page cache
2. In stage2, U bit should be valid when pte is leaf
3. rewrite the check of pf and gpf in PTW and HPTW

MMU, RVH: fix the refill of pte that has gpf and change the check of pf/gpf in PTW and HPTW

---

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

LoadUnit: optimize ifetchPrefetch timing, use RegNext, pass vaddr to Frontend in s1.

LoadUnit: optimize ifetchPrefetch timing

---

src/main/scala/xiangshan/backend/decode/DecodeUnit.scala
src/main/scala/xiangshan/backend/decode/FPDecoder.scala
src/main/scala/xiangshan/backend/decode/VecDecoder.scala
src/main/scala/xiangshan/backend/fu/fpu/FPU.scala
src/main/scala/xiangshan/backend/fu/fpu/IntToFP.scala
src/main/scala/xiangshan/backend/fu/wrapper/FCVT.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueue.scala
src/main/scala/xiangshan/package.scala

* Decode unit adds decoding of zfhmin extension related instructions
* Re exemplified the functional units for scalar fpcvt
* Bump yunsuan :add conversion for FP16 and modified CVT64 module to parameterize it

zfhmin: add zfhmin extensions

---

src/main/scala/xiangshan/mem/lsqueue/LoadQueueReplay.scala

LoadQueueReplay can always enter, as long as it is the same size as VirtualLoadQueue.

LoadQueueReplay: fix LoadQueueReplay enqueue logic

---

src/main/scala/top/Configs.scala
src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala
src/main/scala/xiangshan/mem/lsqueue/LSQWrapper.scala
src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala

+ Remove `RVA23` prefix to clean up code
+ set `hasCMO` to true by default

Remove `RVA23` prefix and enable CMO by default

---

src/main/scala/xiangshan/frontend/icache/IPrefetch.scala

Do not bypass `m_enqWay` state to make sure that s1_waymasks (and maybe other registers) is updated, whether is softPrefetch or not.

IPrefetch: fix s1 fsm for softPrefetch

---

src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala

In previous design, mem_addr is generated with `level`, which is updated two cycles after mem resp. However, pmp check need addr one cycle before mem req, so we should generate mem_addr with `af_level`, which is updated one cycle after mem resp. Previous control logic(s_pmp_check, io.mem.req.valid) will not change.

fix(HPTW): addr & s_pmp_check should be valid on same cycle

---

src/main/scala/xiangshan/backend/decode/DecodeUnit.scala
src/main/scala/xiangshan/backend/decode/FPDecoder.scala
src/main/scala/xiangshan/backend/fu/FuConfig.scala
src/main/scala/xiangshan/backend/fu/fpu/FliTable.scala
src/main/scala/xiangshan/backend/fu/fpu/IntFPToVec.scala
src/main/scala/xiangshan/backend/fu/wrapper/FCVT.scala
src/main/scala/xiangshan/backend/fu/wrapper/VCVT.scala

* Support fli.{h.s.d}, fminm.{h.s.d}, fmaxm.{h.s.d}
* Support fround.{h.s.d}, froundnx.{h.s.d}, fcvtmod.w.d
* Support fleq.{h.s.d}, fltq.{h.s.d}

feat(riscv64): Support RISC-V Zfa extension

---

src/main/scala/xiangshan/cache/mmu/MMUConst.scala
src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala

checking the high bits of gpaddr need according to the mode of hgatp rather than the mode of vsatp

fix(PTW): fix the bug that gpf does't happen when gpaddr high bits check fails in onlyStage2

---

src/main/scala/xiangshan/cache/mmu/TLB.scala

First, if `hgatp.MODE` is not equal to zero, non-zero G-stage PTE PBMT bits override the attributes in the PMA to produce an intermediate set of attributes. Otherwise, the PMAs serve as the intermediate attributes. 
Second, if `vsatp.MODE` is not equal to zero, non-zero VSstage PTE PBMT bits override the intermediate attributes to produce the final set of attributes used by accesses to the page in question. Otherwise, the intermediate attributes are used as the final set of attributes.
[1]《Volume II: Privileged Architecture》

fix(TLB): pbmt requires non-0 to be overridden

---

src/main/scala/xiangshan/cache/dcache/data/BankedDataArray.scala

If the addresses(for example:0x88000000, 0x90000000) of two read requests fall in the same dcache set(0), the same bank(0), and different ways, bank conflict will occur in the previous design.
In fact, in the design of BankedDataArray, each read request will read all the way of an entire bank. So this situation should not necessarily produce a bank conflict.

fix(dcache): fix perf bug of BankedDataArray

---

err.txt
out.txt

fix(TP): fix hardcoding issues in TP to support sv48
replace magic numbers(hardcoding issues) with variable; support sv48(avoid assertion failure)

submodule(CoupledL2, HuanCun): bump

---

err.txt
out.txt

chore: delete useless files (wrongly uploaded)

---

src/main/scala/top/Configs.scala
src/main/scala/xiangshan/cache/mmu/MMUBundle.scala
src/main/scala/xiangshan/cache/mmu/MMUConst.scala
src/main/scala/xiangshan/cache/mmu/PageTableCache.scala

l0: 32 * 3624 -> 32 * (16 * 228), fill 24 reserved bits
waySplit = 4, dataSplit = 4
l1: 8 * 1560 -> 8 * (8 * 200), fill 40 reserved bits
waySplit = 2, dataSplit = 4
also, minimalconfig need different reservedBits (for l0 and l1, 0 & 1), just for requirement in SplittedSRAM.

feat(PTWCache): split Page Cache SRAM

---

.github/filters.yaml
.github/workflows/perf.yml

1. add performance regression workflow every Friday
2. ignore modification of non-EMU workflows

ci: add performance regression workflow

---

src/main/scala/device/RocketDebugWrapper.scala
src/main/scala/device/standalone/StandAloneDebugModule.scala
src/main/scala/device/standalone/StandAloneDevice.scala

This PR should be __*rebase and merged*__.

Fix standalone device

---

src/main/scala/xiangshan/backend/fu/NewCSR/CSRAIA.scala
src/main/scala/xiangshan/backend/fu/NewCSR/CSRPermitModule.scala
src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala

This pr fix aia permit check, and prevents writting sireg/mireg when read from sireg/mireg.

fix(aia): fix permit check for aia and fix wen for aia csr.

---

src/main/scala/xiangshan/mem/vector/VSegmentUnit.scala

Need to wait for the data in the pipeline stage sbufferOut to be sent to the sbuffer before you can write back.

fix(VSegmentUnit): wait for data from the sbufferOut to sbuffer

---

src/main/scala/device/imsic_axi_top.scala

feat(IMSIC): change tl source width to 4

---

src/main/scala/xiangshan/backend/fu/PMA.scala

Also increase RAM size to 8TB in difftest

feat(PMA): increase memory size to 8TB

---

src/main/scala/xiangshan/frontend/ITTAGE.scala

when provider differs from alt provider, update provider useful according to real target match

fix(ittage): fix useful bit update condition

---

src/main/scala/xiangshan/backend/decode/DecodeUnit.scala

* Since software cannot promiss all sinval.vma between sfence.w.inval and sfence.inval.ir, we make sinval.vma always wait forward.

fix(Svinval): make all insts in Sinval behavior like fence to avoid software wrong usage

---

scripts/xiangshan.py

To reduce the possibility of conflicts.

ci: randomly delay a few seconds between two `get_free_cores`

---

src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala

This buffer is for difftest only, and when dataBuffer enqueue, difftestbuffer should enqueue as well.

fix(StoreQueue): fix difftestBuffer enqueue condition

---

src/main/scala/system/SoC.scala
src/main/scala/xiangshan/PMParameters.scala
src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/backend/fu/PMA.scala
src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala
src/main/scala/xiangshan/mem/prefetch/L1PrefetchComponent.scala
src/main/scala/xiangshan/mem/prefetch/L1PrefetchInterface.scala
src/main/scala/xiangshan/mem/prefetch/SMSPrefetcher.scala

TODO: Prefetcher should check pmp & pma in order to decide whether to send requests

fix(prefetch): MMIO address should not send prefetch requests

---

src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala

This Pr fix the condition to read imsic, and exception generate when access imsic.

Bump aia and fix exception generate when access imsic.

---

src/main/scala/xiangshan/cache/mmu/TLB.scala

A TLB query requires two cycles, the first (s0) to receive the req and the second (s1) to return the result. pre exception checking will be done on the first cycle, so should use `vmenable` and `s2xlateEnable` of the first cycle.

fix(TLB): fix exception judgement condition

---

src/main/scala/xiangshan/frontend/BPU.scala
src/main/scala/xiangshan/frontend/FTB.scala
src/main/scala/xiangshan/frontend/FauFTB.scala
src/main/scala/xiangshan/frontend/FrontendBundle.scala
src/main/scala/xiangshan/frontend/newRAS.scala

1.adjust S3 target address selection.

fix(BPU): adjust s3 target when fallThroughErr signal is high

---

src/main/scala/xiangshan/frontend/FTB.scala

this avoids btb conflict in some special pattern

feat(btb): add index hash

---

src/main/scala/xiangshan/backend/decode/DecodeUnit.scala
src/main/scala/xiangshan/backend/decode/isa/bitfield/RiscvInst.scala

* When FS is Off, executing vfslide1up/down should raise illegal instruction exception

fix(vector,decode): use OPFV[VF] encoded in inst to check if need FS not Off

---

.github/workflows/emu.yml
scripts/xiangshan.py
src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/backend/fu/NewCSR/CSREvents/CSREvent.scala
src/main/scala/xiangshan/backend/fu/NewCSR/CSREvents/MretEvent.scala
src/main/scala/xiangshan/backend/fu/NewCSR/CSREvents/TrapEntryMEvent.scala
src/main/scala/xiangshan/backend/fu/NewCSR/Debug.scala
src/main/scala/xiangshan/backend/fu/NewCSR/DebugLevel.scala
src/main/scala/xiangshan/backend/fu/NewCSR/MachineLevel.scala
src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala

This PR should be rebase and merged.

feat(Trigger): Trigger Module support mcontrol6.

---

src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala

* Although EX_II will be raised when access these CSRs in some illegal ways(e.g. writing pmpcfg in S mode), the regs in these CSRs will always be changed by wdata. The reason for the mistake is that the wen of these CSRs is assigned directly to wen of NewCSR instead of wenLegal which only assert when writing CSR in some legal ways.
* Fixed CSRs are pmpcfgs, pmpaddrs, miregs, siregs and vsiregs.
* Todo: all wen and wdata of CSRModule assigned in the same for loop

fix(CSR): fix shadow write for many CSRs

---

src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala

When an exception is thrown by vector store:
* If not the last flow triggers an exception, then pull up the vecExceptionFlag and do not allow subsequent flows to actually 
* write to the sbuffer, but can exit the queue from the sq normally.
* If it is the last flow that triggered the exception, then there is no need to pull up vecExceptionFlag.
The vecExceptionFlag affects the vecvalid signal passed into the sbuffer, and only when vecvalid is high can data actually be written to the sbuffer.
Based on the current ports of the sbuffer, we list the cases as shown in the implementation:
* When only the first port is valid, we only need to see if the first port is lastflow.
* When both ports are valid, we need to judge based on whether robidx is equal or not:
* When equal, the first port is …

fix(StoreQueue): commitLastFlow should be true when the port 1 has no exception

---

src/main/scala/xiangshan/backend/rob/Rob.scala

fix(rob): update robentry.interrupt_safe when uop enter rob.

---

src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala

merge after https://github.com/OpenXiangShan/NEMU/pull/572

fix(csr): fix local counter overflow interrupt req to diff mip.lcofip

---

src/main/scala/xiangshan/backend/fu/NewCSR/CSRPermitModule.scala

* Access stimecmp/vstimecmp raise EX_II when mcounteren.TM = 0 or menvcfg.STCE = 0 in less M mode

fix(csr): fix read/write stimecmp raise EX_II

---

src/main/scala/xiangshan/backend/rob/ExceptionGen.scala

* Trigger action also update with the smaller vstart uop.

fix(ExceptionGen): assign vector exception info when robidxes equal

---

src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala

* Add asynchronous write IMSIC
* Modify the condition for `io.out.valid` to be pulled high when accessing IMSIC asynchronously

fix(csr): fix asynchronous access IMSIC

---

src/main/scala/xiangshan/mem/lsqueue/LoadMisalignBuffer.scala

Since misaligned memory access will be separated into aligned memory access, the actual address of the memory access might be different from the original address. 
If a gpa exception occurs, the exception address should be recovered from the original address using original page offset.

fix(misalign): fix wrong gpa in misalignBuffer

---

src/main/scala/xiangshan/backend/rob/Rob.scala

* vstart need update when hart enter debugMode because of trigger.

 fix(rob): VstartEn should be asserted when triggerAction is debug

---

src/main/scala/xiangshan/backend/dispatch/Dispatch.scala

* Singlestep should commit all uop of one `vector` machine instruction after dret.

fix(Step): It shouldn't be a uop stepped but a machine instruction

---

src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala

The misalign store should not be marked as committed.

fix(misalign): Dont mark misalign store as commit

---

src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala

Use one reg to store EX_II/EX_VI when output not fired.

fix(csr): fix intermediate storage reg for EX_II and EX_VI

---

src/main/scala/xiangshan/backend/VecExcpDataMergeModule.scala
src/main/scala/xiangshan/mem/vector/VSegmentUnit.scala

This pr should be rebase and merged.

fix(VSegmentUnit): fix VSegment trigger logic

---

src/main/scala/utils/AXI4Lite.scala

Reported-by: hong Zhao <zhaohong@bosc.ac.cn>
Fixed-by: jiuyue Ma <majiuyue@bosc.ac.cn>
Signed-off-by: yuxin Zhang <zhangyuxin@bosc.ac.cn>

fix(utils): Fix AXI4LiteBundle signal connection

---

src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/mem/pipeline/AtomicsUnit.scala

This pr should be cherry-picked to branch `v2r2-930`.

fix(trigger): move trigger checking to `s_tlb_and_flush_sbuffer_req` in AtomicsUnit

---

src/main/scala/xiangshan/frontend/icache/ICacheMissUnit.scala

Cut critical path `io.flush -> mainPipe/prefetchPipe s2_miss -> s2_ready -> ftq ready` for timing.
Now missUnit will still send response to mainPipe/prefetchPipe/wayLookup when `io.flush` or `io.fencei` is `true.B`, but unnecessary response will be dropped by mainPipe/prefetchPipe/wayLookup since their `sx_valid` is set to false at the moment, so no functional/performance change is expected.

timing(ICache): allow send MSHR response to (pre)fetch even when io.flush

---

src/main/scala/xiangshan/mem/lsqueue/LoadMisalignBuffer.scala
src/main/scala/xiangshan/mem/lsqueue/StoreMisalignBuffer.scala

We should not use GatedRegNext here as `overwrite*` may be X-state when `shouldOverwrite` is false.

fix(MisalignBuffer): Use RegEnable in datapath to avoid xprop

---

src/main/scala/xiangshan/frontend/FTB.scala

The FTBEntry given by s3 level in the design expectation should not have a fallThroughErr of true.

feat(ftb): add fallThroughErr check function to check FTBEntry given by S3 level

---

src/main/scala/top/Top.scala
src/main/scala/top/XSNoCTop.scala
src/main/scala/xiangshan/L2Top.scala
src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/XSTile.scala
src/main/scala/xiangshan/XSTileWrap.scala
src/main/scala/xiangshan/backend/Backend.scala
src/main/scala/xiangshan/backend/CtrlBlock.scala
src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/backend/exu/ExeUnit.scala
src/main/scala/xiangshan/backend/exu/ExeUnitParams.scala
src/main/scala/xiangshan/backend/exu/ExuBlock.scala
src/main/scala/xiangshan/backend/fu/FuConfig.scala
src/main/scala/xiangshan/backend/fu/FuncUnit.scala
src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala
src/main/scala/xiangshan/backend/fu/wrapper/CSR.scala
src/main/scala/xiangshan/backend/rob/Rob.scala

this pr :
* add critical error generate and collect
* report critical-error signal to XSTop
* stop commit when critical error raise

feat(dbltrp) : add support for critical error 

---

src/main/scala/xiangshan/mem/prefetch/SMSPrefetcher.scala

when the bits update in act,it will be update in pht at the same time.

sms: update pht when act update

---

src/main/scala/xiangshan/backend/dispatch/Dispatch.scala

* Next instruction which enter same robentry shouldn't be committed after one instruction flush itself.

fix(step): fix step for exception.

---

src/main/scala/xiangshan/backend/fu/NewCSR/InterruptFilter.scala

When there are multiple interrupts in different modes, Debug interrupt > NMI interrupt > M mode interrupt > HS mode interrupt > VS mode interrupt.

fix(intr): set the sequence of interrupt in different mode

---

src/main/scala/xiangshan/backend/fu/NewCSR/MachineLevel.scala

This PR should be Rebase and Merge.

fix(mip): add otherwise when wen mip and mip.seip is alias of mvip.seip when mvien.seie = 0

---

README.md

Thanks for the project, hope the newer version gets taped out soon!
This PR adds minor grammar fixes to README.md
Best wishes,
Rishikeshan

Minor fixes to README.md 😊

---

src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/cache/dcache/data/BankedDataArray.scala
src/main/scala/xiangshan/cache/dcache/loadpipe/LoadPipe.scala
src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala
src/main/scala/xiangshan/mem/lsqueue/LoadMisalignBuffer.scala
src/main/scala/xiangshan/mem/lsqueue/StoreMisalignBuffer.scala
src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
src/main/scala/xiangshan/mem/lsqueue/UncacheBuffer.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

- Fixed the relevant path **s2_tag** -> **s2_can_send_miss_req **-> **dcache/dataArray**
- Fixed load unit writeback port select logic and misalignBuffer exceptions
- Fixed **cmoReq.opcode** from **MemBlock** to **L2Top**

timing(MemBlock): fix MemBlock inner timing

---

src/main/scala/xiangshan/backend/Backend.scala
src/main/scala/xiangshan/backend/CtrlBlock.scala
src/main/scala/xiangshan/backend/fu/CSR.scala
src/main/scala/xiangshan/backend/fu/NewCSR/CSREvents/TrapEntryDEvent.scala
src/main/scala/xiangshan/backend/fu/NewCSR/Debug.scala
src/main/scala/xiangshan/backend/fu/NewCSR/DebugLevel.scala
src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala
src/main/scala/xiangshan/backend/fu/NewCSR/Unprivileged.scala
src/main/scala/xiangshan/backend/fu/wrapper/CSR.scala
src/main/scala/xiangshan/backend/rob/Rob.scala
src/main/scala/xiangshan/backend/rob/RobBundles.scala

this pr should be rebase and merged

fix(CSR): fix dcsr to support `stopcount`, `stoptime`, `nmip` and `cetrig`

---

src/main/scala/xiangshan/frontend/IFU.scala

Should raise access fault when:
1. Inconsistent mmio states for two cachelines of a double-line request.
2. Inconsistent mmio states with ICache check result when IFU mmio fsm rechecks itlb/pmp.
"mmio state" here refers to `pmp.io.resp.mmio` and/or `itlb.io.resp.pbmt`.
In current design:
1. When the mmio states of the two cachelines do not match, we fetch the instructions according to the state of the first cacheline. This can result in instructions in mmio space being cached by ICache (functionality error), or doing uncache fetch in non-mmio space (performance loss).
2. IFU mmio fsm only re-checks the response of PMP, which is incorrect after the introduction of the Svpbmt extension (should allow for the case where `pmp.io.resp.mmio === false.B` and `Pbmt.isUncache(itlb.io.resp.pbmt)`, …

fix(IFU): check consistency of mmio states

---

src/main/scala/xiangshan/backend/fu/NewCSR/CSREvents/TrapEntryHSEvent.scala
src/main/scala/xiangshan/backend/fu/NewCSR/CSREvents/TrapEntryMEvent.scala
src/main/scala/xiangshan/backend/fu/NewCSR/CSREvents/TrapEntryVSEvent.scala

this pr should be rebase and mergerd

fix(xtval): fix selection of tval for trap

---

src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala
src/main/scala/xiangshan/backend/rob/Rob.scala

* critical-error diff REF as xiangshan pass criticial-error too early
* bump difftest to make critical_error more prominent

fix(critical-error): critical-error pass early then trap

---

src/main/scala/top/Configs.scala

Add a configuration to enable basic diff when fpga difftest is used

CONFIG: add fgpa_difftest config

---

src/main/scala/xiangshan/backend/decode/VecDecoder.scala

fix(vnclip): use uimm instead of imm for vnclip_wi instructions

---

src/main/scala/xiangshan/cache/mmu/TLBStorage.scala

* tlb hitVec related timing paths -34ps

area(TLB): remove duplicate copy for each read port

---

build.sc
src/main/scala/top/XiangShanStage.scala
src/main/scala/utils/SeqUtils.scala
src/main/scala/xiangshan/backend/issue/IssueBlockParams.scala
src/main/scala/xiangshan/backend/issue/SchdBlockParams.scala

This PR should be rebased and merged.

Bump scala and chisel

---

src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/XSDts.scala

feat(isa): add isa-base and isa-extensions to param and dts

---

src/main/scala/xiangshan/backend/fu/NewCSR/InterruptFilter.scala
src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala
src/main/scala/xiangshan/backend/fu/NewCSR/PMPEntryModule.scala
src/main/scala/xiangshan/backend/fu/wrapper/CSR.scala

This PR adds 1 cycle for csr read/write and selects highest interrupt priority to fix timing.

timing(csr): add 1 cycle to csr read/write and select highest interrupt priority

---

src/main/scala/xiangshan/frontend/IFU.scala

When mmio mismatch happens, we can still fetch inst from the first page. So we can just mark the exception on the second cacheline.
Also fixes a bug: when itlb page fault occurs only on the second page, PMP check may return incorrect results (as the input paddr may be incorrect), on which request the mmio mismatch check should not be performed. (Here we still perform the check, but the result will be ignored, since itlb exception has higher priority in `ExceptionType.merge`)

fix(IFU): mark mmio mismatch exception only on the second line

---

src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueueRAR.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueueRAW.scala
src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala

* LoadQueueRAR PAddr hash function, total 16bits:
* LoadQueueRAW use PAddr[29:6], total 24bits

area(Lsq): compress rar/raw paddr and remove sq useless regs

---

src/main/scala/device/AXI4IntrGenerator.scala

Previously, we simply use the lower 32 bits of wdata regardless of the waddr, which happens to be correct in TileLink version of XiangShan because in such version, the wdata is repeated if the valid data bits are less than the bus width. 
However, this is not true for CHI version of XiangShan. This commit fix this by extracting correct bits of wdata according to lower bits of waddr.

fix(AXI4IntrGenerator): extract wdata according to waddr

---

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

Should use `s2_real_exception` for `s_safe_writeback` and `s2_wakeup` judgement.
When misaligned encounters mmio, we should actually generate the misaligned exception and write it back directly.
Here's something I forgot to add to LoadUnit's writeback condition earlier.

fix(LoadUnit): fix trigger exception when writeback and wakeup logic

---

src/main/scala/xiangshan/backend/fu/NewCSR/TrapHandleModule.scala

* calculate VSSIP, VSTIP, VSEIP trap entry in VSmode should use vscause after mapping

fix(NewCSR): fix the error of trap entry PC in vs mode interrupts

---

src/main/scala/xiangshan/mem/lsqueue/StoreMisalignBuffer.scala

Entries in `storeMisalignBuffer` can only be replaced when `s_idle`, and should not be replaced by a new `req` if the state has been switched and a store is in progress.

fix(StoreMisalignBuffer): crosspage can only be replaced when `s_idle`

---

src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala
src/main/scala/xiangshan/cache/dcache/Uncache.scala
src/main/scala/xiangshan/mem/MemCommon.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueueUncache.scala
src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala

* L1: deliver the NC and PMA signals of uncacheReq to L2
* L2: [support Svpbmt on CHI MemAttr](https://github.com/OpenXiangShan/CoupledL2/pull/273)
* LLC: [Non-cache requests are forwarded directly downstream without entering the slice](https://github.com/OpenXiangShan/OpenLLC/pull/28)

submodule(CoupledL2, OpenLLC): support pbmt in CHI scene

---

src/main/scala/xiangshan/frontend/ITTAGE.scala

also
- update copyright
- rename some function
- add type annotation to make IDE happy

refactor(ittage): remove unused code

---

src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala
src/main/scala/xiangshan/backend/fu/wrapper/CSR.scala

* CSR read is Out-of-Order operation.
* If a inst executed before a CSR read inst is redirected, we need to refresh CSR.

fix(CSR): flush CSR when inst redirect

---

.github/workflows/emu.yml
src/main/scala/top/XSNoCTop.scala

Check the connection compatibility of the generated NOCdifftest top module with the difftest svh.

CI: Check the connection  of the  NOCTOP and difftest

---

src/main/scala/xiangshan/frontend/icache/ICacheMissUnit.scala

>   }.elsewhen(last_fire_r) {
// Clear corrupt_r when response it sent to mainPipe
// This used to be io.fetch_resp.valid (last_fire_r && mshr_resp.valid) but when mshr is flushed by io.flush/fencei,
// mshr_resp.valid is false.B and corrupt_r will never be cleared, that's not correct
// so we remove mshr_resp.valid here, and the condition leftover is last_fire_r
// or, actually, io.fetch_resp.valid || (last_fire_r && !mshr_resp.valid)

fix(ICacheMissUnit): clear corrupt_r when response is sent to MainPipe

---

src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala

* remove mainpipe duplicate signals, wait for timing evaluation.
* The critical path slack is -37ps

area(MainPipe): remove duplicate signals

---

src/main/scala/xiangshan/backend/fu/wrapper/CSR.scala

Register 1 cycle addr and wdata, then write to frontend and memory.

timing(CSR): using addr/wdata after 1 cycle for writing frontend and memory

---

build.sc

build: add `difftest.test` to build target

---

src/main/scala/xiangshan/L2Top.scala

1. https://github.com/OpenXiangShan/CoupledL2/pull/309
2. https://github.com/OpenXiangShan/CoupledL2/pull/312

submodule(CoupledL2): bump CoupledL2

---

src/main/scala/device/RocketDebugWrapper.scala
src/main/scala/device/standalone/StandAloneDebugModule.scala
src/main/scala/top/Top.scala
src/test/scala/top/SimTop.scala

* gsim can not handle such clocks

device,DebugMoudle: do not use clock with Bool type

---

src/main/scala/xiangshan/mem/lsqueue/LoadQueue.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

optimization load unit writeback data generate logic
* merge multi source data at `s2`, select and expand data at `s3`
* select data use one-hot instead of shifter

timing(LoadUnit): optimization load unit writeback data generate logic

---

src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/mem/prefetch/BasePrefecher.scala
src/main/scala/xiangshan/mem/prefetch/L1PrefetchComponent.scala
src/main/scala/xiangshan/mem/prefetch/SMSPrefetcher.scala

**Checklist:**
1. no page/access fault
2. not uncache
3. no pmp access fault
**Changes:**
1. Add pmp response from PMPChecker
2. Wait until s3 phase to process the response of TLB (got in s2) and PMP(got in s3)

fix(L1PF, SMS): add pmp check

---

README.md
readme.zh-cn.md

This patch includes:
* docs(README): update documentation infomation
* docs(README): update copyright and license

docs(README): update document and license

---

src/main/scala/xiangshan/cache/mmu/L2TLB.scala

In the previous design, we will ensure that L2 TLB will be able to receive the request by repeater between L1 TLB and L2 TLB. Specifically, the number of entries in L2 TLB MissQueue will be greater than or equal to the sum of itlbRepeater entries + dtlbRepeater entries, so as long as the repeater is able to accept, the L2 TLB will be able to handle.
However, there is always a problem with this approach: the repeater does not know whether multiple reqs of the TLB will be on the same huge page (e.g. a 2MB page), so it is possible that there may be multiple items on the same huge page in a repeater at the same time. In this case, L2 TLB will release more than one repeater entry at a time (these pages are in a same huge page). However, the req and resp of L2 TLB are one-to-one correspondence, …

fix(L2TLB): Fix stuck caused by MissQueue full

---

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala

* remove useless cancel logic for writeback valid

timing(LoadUnit, StoreUnit): remove redirect for out

---

src/main/scala/xiangshan/mem/pipeline/AtomicsUnit.scala

Atomic access on uncache or MMIO region is not supported for now. The previous design did not consider exception handling for atomic instructions with PBMT=NC.

fix(AtomicsUnit): atomic access on uncache should raise af

---

Makefile
src/main/scala/top/Configs.scala
src/main/scala/top/Top.scala
src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/L2Top.scala
src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/XSTile.scala
src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/backend/fu/NewCSR/CSRBundles.scala
src/main/scala/xiangshan/backend/fu/NewCSR/CSRCustom.scala
src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala
src/main/scala/xiangshan/backend/fu/wrapper/CSR.scala
src/main/scala/xiangshan/frontend/Frontend.scala
src/main/scala/xiangshan/mem/prefetch/BasePrefecher.scala

This pull request includes:
- add compilation support for CHI Issue C (but not yet verified)
- enable DataCheck and Poison
- add requirement for CHI port width check
- add prefetch control by custom csr
- optimize timing in CoupledL2, mainly paths from SRAM to ICG
- add clock gate to each of the splitted SRAMs in CoupledL2
- fix several bugs concerning WriteEvictOrEvict, SnpQuery, SnpCleanShared, SnpStash*, etc

submodule(CoupledL2, OpenLLC): bump L2 and LLC

---

src/main/scala/xiangshan/backend/fu/NewCSR/CSRAIA.scala
src/main/scala/xiangshan/backend/fu/NewCSR/InterruptFilter.scala
src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala

* The current external interrupts come from two sources, `PLIC` and `IMSIC`.
* The external interrupt priority number of PLIC is `0`, and the external interrupt priority number of IMSIC is `1~2047`.
* The case where the priority number is greater than `255` is added to the interrupt priority comparison method.
* The priority number of each interrupt in the `iprios array` occupies `8` bits, and its read data is masked by the corresponding bit of the `xie` register, so when writing the `xie` register, the `read data` of the `iprios array` needs to be updated.
* Note: The external interrupt source comes from PLIC or IMSIC, the commit messages in NEMU and ready-to-run repositories are wrong.

fix(aia): external interrupt priority from PLIC or IMSIC

---

src/main/scala/xiangshan/backend/fu/NewCSR/DebugLevel.scala
src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala

* Hardware should ignore writes to mcontrol6 that set dmode to 1 if the previous trigger has both dmode of 0 and chain of 1.

fix(Mcontrol6): fix writing mcontrol6.dmode for trigger chain

---

src/main/scala/xiangshan/frontend/PreDecode.scala

This PR is a supplement to https://github.com/OpenXiangShan/XiangShan/pull/4234, correctly setting the ftqOffset when cfi is jalr.

fix(PreDecode): fix fixedTaken for jalr

---

src/main/scala/xiangshan/mem/Bundles.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueue.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

Fixed the situation where the nc_with_data was not replayed correctly.

fix(uncache): uncache load fails to replay

---

src/main/scala/xiangshan/cache/dcache/Uncache.scala

When `lsq.req` enters `uncachebuffer` and the entry that meets the merge conditions of `lsq.req` is in the following cases, the entry can not be merge.
1. receiving uncache response
2. waiting return `lsq.resp`
Why? the status of the former entry changes to `waitReturn`. There is no signal to wake up the latter entries whoes state are `waitSame`, because the trigger former entry will not be sent to bus, get response and wake up the latter entry.

fix(uncache): avoid merging the corner cases

---

src/main/scala/xiangshan/mem/lsqueue/LoadQueueUncache.scala

**Bug trigger point:**
The flush occurs during the `s_wait` phase. The entry has already passed the flush trigger condition of `io.uncache.resp.fire`, leading to no flush. As a result, `needFlushReg` remains in the register until the next new entry's `io.uncache.resp.fire`, at which point the normal entry is flushed, causing the program to stuck.
**Bug analysis:** The granularity of flush handling is too coarse.
In the original calculation:
```
val flush = (needFlush && uncacheState === s_idle) || (io.uncache.resp.fire && needFlushReg)
```
Flush is only handled in two states: `s_idle` and non-`s_idle`. This distinction makes the handling of the other three non-`s_idle` states very coarse. In fact, for the remaining three states, there needs to be corresponding feedback based on when …

fix(LoadQueueUncache): exhaust the various cases of flush

---

src/main/scala/xiangshan/cache/dcache/Uncache.scala

1. Wrong forward index
2. Duplicate judgment `waitSame` index

fix(uncache): correct the indexes

---

src/main/scala/xiangshan/frontend/newRAS.scala

1. Predictor pipeline stalls exhibit poor fault tolerance.
2. Speculative queue overflow (requiring 32 uncommitted call/return instructions) is an extreme scenario where disabling return stack prediction incurs negligible performance impact.
3. Queue overflow often indicates recursion. In such cases, using top-of-stack data (static return addresses) may outperform IT-TAGE predictions despite disabled return stack.

feat(RAS): change the stall mechanism upon return stack overflow to dynamically disable the return stack.

---

src/main/scala/xiangshan/L2Top.scala
src/main/scala/xiangshan/XSTile.scala
src/main/scala/xiangshan/mem/MemBlock.scala

feat(BEU): beu will trigger `NMI_31` non-maskable interrupt

---

src/main/scala/xiangshan/mem/MemBlock.scala

The preivous GenExceptionVa function makes some mistakes in selecting the exception vaddr when exception. The check for S-stage, VS-stage and G-stage are mixed together, which causes the one-hot signal to be wrong.
This patch rewrites the relative logic and fixes the bug.

fix(MMU): incorrect generation of Exception vaddr

---

src/main/scala/xiangshan/backend/datapath/WbArbiter.scala
src/main/scala/xiangshan/backend/rob/Rob.scala
src/main/scala/xiangshan/backend/rob/RobBundles.scala

Currently, we implement the multi core vector load check in difftest.
We modified difftest and NEMU and added related content in XiangShan.

feat(Difftest): add multi-core vector load check

---

.github/workflows/emu.yml
.gitmodules
Makefile
build.sc
src/main/scala/device/IMSIC.scala
src/main/scala/device/IMSICAsync.scala
src/main/scala/device/imsic_axi_top.scala
src/main/scala/system/SoC.scala
src/main/scala/top/ArgParser.scala
src/main/scala/top/Top.scala
src/main/scala/top/XSNoCTop.scala
src/main/scala/xiangshan/L2Top.scala
src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/XSTile.scala
src/main/scala/xiangshan/XSTileWrap.scala
src/main/scala/xiangshan/backend/Backend.scala
src/main/scala/xiangshan/backend/fu/CSR.scala
src/main/scala/xiangshan/backend/fu/NewCSR/CSRAIA.scala
src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala
src/main/scala/xiangshan/backend/fu/wrapper/CSR.scala
src/main/scala/xiangshan/mem/MemBlock.scala

This reverts commit 7fbc1cb42a2c96ef89a1dfd0f5f885ccada40c26.

Revert "feat(AIA): integrate ChiselAIA (#4378)"

---

src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala

**Read this PR(https://github.com/OpenXiangShan/XiangShan/pull/4442) from LoadUnit first.**
---
In addition to the above, `nc` has been added to the misalign checks as well.
(https://github.com/OpenXiangShan/XiangShan/pull/4441/files#diff-cd162a95fcb65b10cf6ac087d3aac686ccb932ab4f5e270c0cfdb38437462b37L464-R471)
---
Currently, it is not to fully replace `s2_mmio` with `s2_actually_uncache` due to inconsistencies in the way `nc` and `mmio` are handled in the `StoreQueue`, so the original `s2_mmio` is still retained.
Other than that, there is no longer a need for an additional `s2_uncache`, as StoreUnit does not need to handle prefetching.

fix(StoreUnit): no uncache store misalign of mmio

---

src/main/scala/xiangshan/L2Top.scala

* add wfi state (cpu_halt) port to CoupledL2
* bump CoupledL2 with fix of wfi state checking before exit coherency

fix(L2Top): connect cpu_halt port to l2

---

src/main/scala/xiangshan/frontend/icache/IPrefetch.scala

`s1_exception_out` is for prefetch s2 only, but we want backend exception to be considered as part of itlb exception and sent to waylookup, so we merge it to `s1_itlb_exception`

fix(IPrefetchPipe): consider backend exception as part of itlb exception

---

.github/workflows/perf.yml

1. set a more reasonable start time and time period
2. change uploading artifact to setting step summary

ci(perf): more execution time and use summary instead of artifact

---

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

for best timing, add processing at s3.

fix(LoadUnit): not enter misalignbuffer on exception

---

src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala

* Atomics and Sbuffer write request should not report error

fix(MainPipe): fix error valid generate logic

---

src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala

In the previous design, we used `gvpn_gpf` to detect whether the G-Stage meets the gvpn high level of 0 after the VS-Stage translation is completed in allStage case, or else a guest page fault is reported.
However, due to some historical reasons, `gvpn_gpf` can only be used to detect guest faults during the translation process; for the first time when entering the PTW after the request to query the Page Table Cache has finished, similar error checking will be done in `check_gpa_high_fail`, but when the PTW resp valid is 1, the error checking will be done in `check_gpa_high_fail`, `full_gvpn` has been cleared to 0 (line 374), so `gvpn_gpf` will not be 1 (should be 1), resulting in an error in the returned message.
I do not know why it was designed this way at the time, so I had to add …

fix(PTW): fix gvpn check when req first enter PTW

---

Makefile
src/main/scala/top/ArgParser.scala
src/main/scala/top/Configs.scala
src/main/scala/top/Top.scala
src/main/scala/top/XSNoCTop.scala
src/main/scala/xiangshan/L2Top.scala
src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/XSTile.scala
src/main/scala/xiangshan/XSTileWrap.scala
src/main/scala/xiangshan/backend/Backend.scala
src/main/scala/xiangshan/cache/dcache/data/BankedDataArray.scala
src/main/scala/xiangshan/cache/dcache/meta/TagArray.scala
src/main/scala/xiangshan/cache/mmu/PageTableCache.scala
src/main/scala/xiangshan/frontend/Frontend.scala
src/main/scala/xiangshan/mem/MemBlock.scala

* add `SRAM_CTL` interface for SRAMTemplate
* use `SRAM_WITH_CTL` to enable, 
e.g.  `make sim-verilog CONFIG=KunminghuV2Config RELEASE=1 SRAM_WITH_CTL=1`

feat(Sram): add `SRAM_CTL` interface

---

src/main/scala/xiangshan/cache/dcache/Uncache.scala

which case is PBMT>0 but PMA=MainMemory

fix(Uncache): uncache mm store needs difftest to update goldenmem

---

src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala

In https://github.com/OpenXiangShan/XiangShan/pull/4422, For the virtualized allStage scenario, we attempt to suppress PMP checks until the G-stage translation result is returned. However, the approach used in https://github.com/OpenXiangShan/XiangShan/pull/4422 is to try ignoring the `accessFault` result when `io.hptw.req.valid` is asserted.
In reality, the `accessFault` signal remains valid because it is implemented as a `RegEnable`. Therefore, we need to prevent `sent_to_pmp` from being asserted when sending the G-stage translation request to HPTW. To address this, we introduce the `vs_finish` signal. When `vs_finish` is `true.B`, `sent_to_pmp` will be false, thus avoiding false `accessFault` reports.

fix(PTW): should not do pmp check before G-stage finish

---

src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala

When vs-stage pagefault occurs, check high bits of gvpn for g-stage is meaningless, and should not report guest page fault.

fix(LLPTW): should not check g-stage pf when vs-stage pf occured

---

src/main/scala/xiangshan/backend/rob/Rob.scala
src/main/scala/xiangshan/mem/Bundles.scala
src/main/scala/xiangshan/mem/MemBlock.scala
src/main/scala/xiangshan/mem/lsqueue/LoadMisalignBuffer.scala
src/main/scala/xiangshan/mem/lsqueue/StoreMisalignBuffer.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala

* a misalign store will enqueue misalign buffer at s1, and revoke if it needs at s2

timing(StoreMisalignBuffer): fix misalign buffer enq timing

---

src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala

In the previous design, the input s2xlate signal was directly used to determine whether to virtualize, but the input signal changed to the default value 0 due to timing problems, resulting in the use of the wrong PBMTE.
In fact, LLPTW can handle both virtualized and non-virtualized requests simultaneously. This information is stored in entries(i).req_info.s2xlate. By using this signal, we can distinguish between PBMTEs under different virtualization modes. This commit fixes the bug.

fix(LLPTW): each LLPTW entry should use its own s2xlate

---

src/main/scala/top/XSNoCTop.scala
src/main/scala/utils/LowPowerState.scala
src/main/scala/utils/PowerSwitchBuffer.scala
src/main/scala/xiangshan/XSTileWrap.scala

*set do not touch low power port of XSTileWrapper
*add async bridge Q-channel logic

fix: add low power related logic

---

src/main/scala/xiangshan/frontend/NewFtq.scala

split Ftq meta SRAM into smaller size: (64 × 160) × 2 -> (64 × 80) × 4

feat(Ftq): split Ftq meta SRAM into smaller size

---

src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala

In certain cases where a `pageFault` or `guestFault` occurs, `accessFault` signal might still be true; however, it is actually invalid and should not be reported. We fixed this bug in commit https://github.com/OpenXiangShan/XiangShan/pull/4540.
However, in the previous design, the level field of the PTW response was defined as: `Mux(accessFault, af_level, Mux(guestFault, gpf_level, level))`. As a result, although we fixed the false accessFault reporting in https://github.com/OpenXiangShan/XiangShan/pull/4540, the level in the PTW response was still incorrectly set to `af_level`. This commit fixes that issue.
Additionally, this commit extracts the arguments in `ptw_resp.apply` into separate variables to improve code readability. Previously, it was incorrectly assumed that `pte_valid` was a …

fix(PTW): false positive accessFault should not use af_level when resp

---

src/main/scala/xiangshan/cache/mmu/TLB.scala

Similar to https://github.com/OpenXiangShan/XiangShan/pull/4471

fix(TLB): explicitly specify the signal width again when truncated

---

src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala

* `s1_way_en`  should use `io.pseudo_error.valid` on the same stage, not `RegNext(io.pseudo_error.valid)`. Otherwise, `MainPipe` may use wrong way enable to write DCache, it will result in two identical tags.

fix(MainPipe): fix `s1_way_en` logic when pseudo tag error inject

---

src/main/scala/xiangshan/mem/lsqueue/LoadQueue.scala

* move `need_rep`, `mmio` and `nc` check from `s1` to `s2` for better timing

timing(LoadQueueUncache): adjust s1 enq and s2 enq valid generate logic

---

src/main/scala/top/XSNoCTop.scala

sync the signal :srcint,  reset and other signals for lowpower

fix : sync the signal before use for lowpower

---

src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala

The Svpbmt CI of master at https://github.com/OpenXiangShan/XiangShan/actions/runs/14639358525/job/41077890352 reported the following implicit output error:
```
check_misa_h                                                          PASSED
test_pbmt_perf                                                        
TEST: read 4 Bytes 1000 times
Svpbmt IO test...
addr:0x10006d000
start: 8589, end: 59845, ticks: 51256
Svpbmt NC test...
addr:0x10006c000
start: 67656, end: 106762, ticks: 39106
Svpbmt NC OUTSTANDING test...
smblockctl = 0x3f7
addr:0x10006c000
start: 118198, end: 134513, ticks: 16315
Svpbmt PMA test...
addr:0x100000000
start: 142696, end: 144084, ticks: 1388
PASSED
test_pbmt_ldld_violate                                                ERROR: untested exception! cause NO: 5
(mhandler, …
```

fix(StoreQueue): add nc_req_ack state to avoid duplicated request

---

src/main/scala/top/XSNoCTop.scala

sync low power state to new define

fix(XSNocTop): sync low power state

---

src/main/scala/top/Configs.scala

Use the latest KunminghuV2Config for fuzzing.

feat(config): update FuzzConfig with KunminghuV2

---

src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala

A represents a normal store, and B represents an NC (Non-Cacheable) store. In the SQ (Store Queue), there exists a sequence like A1 B1 B2 B3 B4 .... A1 enters the `dataBuffer`, and `rdataPtr` moves to B1. Due to a blockage in the `Sbuffer`, A1 is unable to be issued, and `deqPtr` remains at A1.  
At `rdataPtr`, B1 is found and successfully sent to the `UncacheBuffer`, causing `rdataPtr` to move forward. Since the NC handshake succeeds, `deqPtr` also moves forward (from A1 to B1), even though A1 itself has not completed.  
Subsequently, as NC(Bx) handshakes continue to succeed, `deqPtr` keeps advancing. Meanwhile, `enqPtr` continues to insert new entries, eventually overwriting the original A1 entry.  
When the `Sbuffer` finally becomes available, the design attempts to clear (set …

fix(StoreQueue): strictly ensure deq moves in order

---

src/main/scala/xiangshan/cache/mmu/MMUBundle.scala

1. Level: Previously, the code always used the smaller value between s1.stage and s2.stage, regardless of the virtualization stage. In fact, only the allStage case should compare both stages; other cases should determine the level independently based on their respective stage.
2. VPN: Previously, only the allStage case checked the level to decide whether to concatenate the lower bits of the VPN. However, in reality, other cases also need to perform VPN concatenation based on the level.

fix(TLB): fix two issues in genVpn

---

src/main/scala/xiangshan/backend/fu/NewCSR/CSRPermitModule.scala

* xstateen.IMSIC should control to access sireg/vsireg when  siselect/vsiselect is between 0x70 and 0xff.
* xstateen.AIA should control to access sireg when siselect is between 0x30 and 0x3f.
This pr should be rebase and merged

fix(Smstateen): fix access to sireg/vsireg

---

src/main/scala/xiangshan/cache/mmu/MMUBundle.scala

When the L2 TLB returns a PTW result to L1 TLB, if virtualization is enabled (including onlyS1, onlyS2, and allStage modes), then even when a huge page is accessed, only one entry in valididx(i) is marked as true.
During the refill of the L1 TLB into TLBStorage, in the case of large pages, all valididx(i) entries should be manually set to true to ensure proper hit matching during subsequent lookups.
However, in the previous design, this handling was only applied to address translations in onlyS2 mode. In fact, regardless of which virtualization translation mode is active, if a large page is accessed, all valididx(i) entries should be set to true. This commit fixes the bug.

fix(TLB): valididx(i) should all be true when isSuperPage

---

src/main/scala/xiangshan/backend/fu/NewCSR/CSRPermitModule.scala
src/main/scala/xiangshan/backend/fu/NewCSR/HypervisorLevel.scala
src/main/scala/xiangshan/backend/fu/NewCSR/MachineLevel.scala
src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala
src/main/scala/xiangshan/backend/fu/NewCSR/StateEnBundle.scala
src/main/scala/xiangshan/backend/fu/NewCSR/SupervisorLevel.scala

This pr shoule rebase and merged. Include two commits:
* fix(csr): add [m|h|s]context for sdtrig extension
* submodule(ready-to-run): bump ready-to-run to add context CSRs

fix(csr): add [m|h|s]context for sdtrig extension

---

README.md
readme.zh-cn.md

Since we use the `--split-verilog` option and MFC, the elaborator will generate multiple System Verilog files.

docs(README): update output files explanation in generate verilog section

---

src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala

According to the manual description, cbo instr (inval clean flush) requires read permission but throws store exception.
Considering that NEMU has multiple commits for other content modifications, I'll mention a separate bump NEMU pr

fix(StoreUnit): cbo requires read permission

---

src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/backend/fu/NewCSR/CSRBundles.scala
src/main/scala/xiangshan/frontend/Frontend.scala
src/main/scala/xiangshan/frontend/FrontendBundle.scala
src/main/scala/xiangshan/frontend/bpu/BPU.scala
src/main/scala/xiangshan/frontend/bpu/Composer.scala
src/main/scala/xiangshan/frontend/bpu/FTB.scala
src/main/scala/xiangshan/frontend/bpu/FauFTB.scala
src/main/scala/xiangshan/frontend/bpu/ITTAGE.scala
src/main/scala/xiangshan/frontend/bpu/Ras.scala
src/main/scala/xiangshan/frontend/bpu/SC.scala
src/main/scala/xiangshan/frontend/bpu/Tage.scala
src/main/scala/xiangshan/frontend/ftq/BundleCollection.scala
src/main/scala/xiangshan/frontend/ftq/FtbEntryGen.scala
src/main/scala/xiangshan/frontend/ftq/Ftq.scala

Move bpu related files into a seperate package.

refactor(bpu): move bpu modules into bpu package

---

src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala

Bug desciptions:
* when the request from `MissQueue` occur `BtoT` fail (in fact, the request sent from `MissQueue` does not need to be check), `MainPipe` will response a replay to sbuffer, at the same time, hit response will sent to sbuffer too.
How to fix:
* In the case of `BtoT` fail, only requests from sbuffer are allowed to return replay response.

fix(MainPipe): only requests from sbuffer are allowed to return replay response

---

src/main/scala/xiangshan/mem/lsqueue/StoreMisalignBuffer.scala

Previously, we overlooked one scenario:
This would result in a situation where, when there is a cross-page request in the misalignbuffer, the `enq` request that needs to be revoked would not be revoked, leading to a deadlock.

fix(StoreMisalignBuffer): fix crosspage enq request and revoke logic

---

src/main/scala/xiangshan/frontend/bpu/Bpu.scala
src/main/scala/xiangshan/frontend/bpu/Ftb.scala
src/main/scala/xiangshan/frontend/bpu/Ittage.scala
src/main/scala/xiangshan/frontend/bpu/MicroFtb.scala
src/main/scala/xiangshan/frontend/bpu/Ras.scala
src/main/scala/xiangshan/frontend/bpu/SC.scala
src/main/scala/xiangshan/frontend/bpu/Tage.scala

refactor(bpu): refactor style

---

src/main/scala/xiangshan/frontend/bpu/Bpu.scala
src/main/scala/xiangshan/frontend/bpu/Ftb.scala
src/main/scala/xiangshan/frontend/bpu/SC.scala
src/main/scala/xiangshan/frontend/bpu/Tage.scala
src/main/scala/xiangshan/frontend/ftq/BundleCollection.scala
src/main/scala/xiangshan/frontend/ftq/Ftq.scala

We will rewrite a new SC later, so the old SC is temporarily disabled for now.

feat(Bpu): temporarily disable SC

---

src/main/scala/xiangshan/backend/Bundles.scala
src/main/scala/xiangshan/backend/decode/DecodeUnit.scala
src/main/scala/xiangshan/backend/rename/Rename.scala
src/main/scala/xiangshan/backend/rob/Rob.scala

feat: use custom HINT for simulation debug trigger

---

src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala

* probe/atomics should report tag error as long as there is an error in one tag

fix(MainPipe): fix report error for probe/atomic request

---

src/main/scala/xiangshan/mem/Bundles.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala

The cbo needs to perform st ld checks in the pipe at cache line granularity.
I also adjusted the code style to prepare for more granular checks that may be required in the future.

fix(LSU): cbozero also needs to perform raw checks on the pipe

---

src/main/scala/utils/AXI4Lite.scala

Bugfix: Configure AXI Lite interface with correct mapping.

---

src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala

* clear nmip when trap.valid from rob

fix(CSR, NMI): fix the logic for clearing `nmip`

---

src/main/scala/xiangshan/frontend/BPU.scala

Manipulating reset signal to initialize a register will fail if reset is asynchronous.

fix(reset): reset pc with asynchronous signal

---

src/main/scala/xiangshan/mem/vector/VSegmentUnit.scala

`dcache.error_delayed` will be one beat later than `dcache.resp`, and if it is a fof instruction, no exception should be generated.

fix(VSegmentUnit): `dcache.error_delayed` will be one beat latet than `dcache.resp`

---

src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala

* `extra_meta_resp` will be overrided when requset is blocked at `s1` in `MainPipe`.
How to fix:
* add a skid buffer

fix(MainPipe): fix `extra_meta_resp` overrided

---

src/main/scala/xiangshan/mem/vector/VMergeBuffer.scala

When vlmax = 1 and split the misaligned unit-stride into two memory accesses.
Then after `elemidx = elemidx & vlmax - 1.U`, the elemidx of both memory accesses will become 0, making it impossible to select the exception that was triggered first by comparing elemidx.

fix(VMergeBuffer): adjust elemidx generation logic when exception

---

src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala
src/main/scala/xiangshan/cache/dcache/meta/AsynchronousMetaArray.scala

* `errorArray` enable by default
* `accessArray` disable by default

fix(DCache): add bypass switch for `L1FlagMetaArray`

---

README.md
readme.zh-cn.md

* New version of Design Doc
* New link for User Guide
* Translation platform Weblate

docs: add latest document infomation

---

src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala

example： 
rdataPtr(0) is last element of vector store, rdataPtr(0) need to occupy two write port, which lead to vecExceptionFlag not cancel. (Because of `firstSplit`)

fix(StoreQueue): fix not set vecExceptionFlagCancel

---

src/main/scala/xiangshan/frontend/bpu/Bpu.scala
src/main/scala/xiangshan/frontend/bpu/phr/Bundles.scala
src/main/scala/xiangshan/frontend/bpu/phr/Phr.scala

- add folded history output based on meta phrPtr for BPU training
- modify code structure and comments

feat(phr): add folded history output based on meta phrPtr

---

src/main/scala/xiangshan/frontend/bpu/Abstracts.scala
src/main/scala/xiangshan/frontend/bpu/Bpu.scala
src/main/scala/xiangshan/frontend/bpu/Bundles.scala
src/main/scala/xiangshan/frontend/bpu/CompareMatrix.scala
src/main/scala/xiangshan/frontend/bpu/ubtb/MicroBtb.scala

Also:
- fix that `io.enable` should control `t0_valid`

feat(ubtb): train first mispredict branch

---

src/main/scala/xiangshan/frontend/bpu/WriteBuffer.scala
src/main/scala/xiangshan/frontend/bpu/tage/Bundles.scala
src/main/scala/xiangshan/frontend/bpu/tage/Tage.scala
src/main/scala/xiangshan/frontend/bpu/tage/TageBaseTable.scala
src/main/scala/xiangshan/frontend/bpu/tage/TageTable.scala

WriteBuffer is connected to Tage
By the way, remove the useless parameter hasTag from WriteBuffer

fix(tage): connect WriteBuffer to Tage

---

src/main/scala/xiangshan/frontend/ftq/Bundles.scala
src/main/scala/xiangshan/frontend/ftq/Ftq.scala
src/main/scala/xiangshan/frontend/icache/ICacheMainPipe.scala
src/main/scala/xiangshan/frontend/icache/ICachePrefetchPipe.scala
src/main/scala/xiangshan/frontend/icache/ICacheWayLookup.scala
src/main/scala/xiangshan/frontend/ifu/Ifu.scala

Also: remove flushByStage2 as it doen't exists on V3 Bpu

fix(ICache,Ifu): do not bpuFlush if not valid

---

src/main/scala/xiangshan/cache/mmu/MMUBundle.scala

In previous design, the smaller value between the stage1 and stage2 levels was always written back into the TLB entry. However, this approach caused issues when exceptions occurred: a larger page could mistakenly be treated as a smaller one. During TLB lookups this would only result in performance bugs, for example:
(1) The first lookup of vpn 0x0 should return a 1 GB page, but instead a 2 MB page is written back. (2) The second lookup of vpn 0x0 + 4 MB should hit, but because the level written back last time was incorrect, it actually misses, triggering another PTW. (3) After the PTW completes, a new 2 MB page starting at vpn 0x0 + 4 MB is written back.
However, this handling leads to a functional bug in the sfence scenario. For a 1 GB page, an sfence with any address within the 1 GB …

fix(TLB): fix incorrect TLB level refill when has exception
