OpenXiangShan/XiangShan

src/main/scala/xiangshan/mem/lsqueue/VirtualLoadQueue.scala
A software prefetch instruction is similar to a normal load instruction in that it allocates loadqueue entries, and we need to write them back to the backend through loadunit. Unlike normal load instructions, software prefetch instructions will not be replayed, and will be written directly back to the backend. At the same time in loadqueue, as long as this instruction is at the head of the queue, it can deq.
In the past design, although the software prefetch instruction will not enter load replay queue, it still needs to wait for both addrvalid and datavalid to be ready before it can deq from loadqueue, which in fact will cause the entry to never deq from loadqueue, resulting in a deadlock. This commit fixes this bug: addrvalid and datavalid will always be considered true for software …
=> fix(LoadQueue): software prefetch should always be ready to deq

src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala
In previous design, when a miss_req is waiting for a probe and replay in mshr continually, refill_req will block store_req ans probe_req which will cause dead lock. 
Remove useless block now to fix this problem.
=> fix(DCache): remove block_decoupled by refill_req

src/main/scala/xiangshan/backend/decode/VecExceptionGen.scala
feat(VceExceptionGen): Cancel the exception of the Zvfhmin extension instruction and support Zvfhmin extension.
* The Zvfhmin extension refers to the case where sew==1, where the exceptions for VFWCVT_F_F_V and VFNCVT_F_F_W instructions are removed.
=> feat(VceExceptionGen): Cancel the exception of the Zvfhmin extension instruction and support Zvfhmin extension.

src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
Fixed the bugs introduced by this commit (https://github.com/OpenXiangShan/XiangShan/pull/3464)
Deq exception checking need comparing robidx. 
We need to find other ways to mitigate the timing here.
=> fix(StoreQueue): deq exception checking need comparing robidx

src/main/scala/xiangshan/mem/MemCommon.scala, src/main/scala/xiangshan/mem/prefetch/BasePrefecher.scala, src/main/scala/xiangshan/mem/prefetch/L1StreamPrefetcher.scala
Perf Bug Description:
Stream Prefetcher is **trained and triggered in all memory access traces**. If the program(As shown above) repeatedly accesses an 8K space in a loop, the first loop can be prefetched normally, but in the subsequent loop the data has been fetched back to Dcache already. In theory, there is no need to prefetch again, since the Stream Prefetcher is triggered in all memory access traces, which will cause subsequent prefetching requests to be triggered and preempt the pipeline which may cause performance loss.
FIX:
Let the Stream prefetcher only trigger prefetching when **miss and Prefetch hit** (training still uses all memory access traces).
=> perf(L1PF): Stream only pf at miss/pfHit

src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala
In riscv-privileged, it is load or store in G-stage which support VS-stage, such as to get the non-leaf pte of VS-stage
> For G-stage address translation, all memory accesses (including those made to access data structures for VS-stage address
translation) are considered to be user-level accesses, as though executed in U-mode. Access type permissions—readable, writable, or executable—are checked during G-stage translation the same as for VS-stage translation. For a memory access made to support VS-stage address translation (such as to read/write a VS-level page table), permissions and the need to set A and/or D bits at the G-stage level are checked as though for an implicit load or store, not for the original access type. However, any exception is always reported for the original access …
=> fix(PTW, RVH): the pte of G-stage which support VS-stage is load rather than original access type

src/main/scala/xiangshan/backend/decode/DecodeUnit.scala, src/main/scala/xiangshan/backend/fu/util/CSRConst.scala, src/main/scala/xiangshan/backend/rename/Rename.scala
Add a table of "read only" CSRs, which can only be modified by CSR instructions (or almost). Modify this table to simplify circuits.
=> Backend: accelerate csrr for read only CSRs by pipelining

src/main/scala/xiangshan/frontend/NewFtq.scala, src/main/scala/xiangshan/frontend/newRAS.scala
1. RAS: relax the conditions for unblocking the speculative queue after it has been blocked
2. FTQ: correct the pre-decode information sent to the RAS
=> fix(RAS): correct the Call and Ret signals during redirection, and modify the blocking mechanism of RAS.

src/main/scala/xiangshan/cache/mmu/L2TLB.scala
When two req having same vpn are sent to L2TLB, the first req has af because of the first pte in VS check high bits fail. This result doesn't refill to page cache. And the next req has the same situation. Then the assert will arise
=> fix(L2TLB, RVH): fix the assert bug when two same vpn reqs are sent to L2TLB and have af

scripts/xiangshan.py
The previous riscv64-xs config for nexus-am includes VGA and AUDIO devices, which do not exist in XiangShan simulation environment. This patch modifies the workloads used by xiangshan.py to solve the above problem.
=> ci: update nexus-am base ci workload bins

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
In previous design, prefetch.i would use HWPrefetch's paddr in load_s0 and send it to pmp in load_s1. However, when prefetch.i is valid, HWPrefetch's valid is 0 and paddr is X-stated, resulting in X-state propagation.
In fact, prefetch.i just sends vaddr to Frontend and does not use the result of the pmp check. In this commit, paddr that prefetch.i sends to pmp is written directly to 0, thus avoiding X-state propagation.
=> fix(LoadUnit): prefetch.i should not use HWPrefetch paddr

src/main/scala/xiangshan/backend/MemBlock.scala, src/main/scala/xiangshan/mem/lsqueue/LoadExceptionBuffer.scala, src/main/scala/xiangshan/mem/lsqueue/LoadMisalignBuffer.scala, src/main/scala/xiangshan/mem/lsqueue/LoadQueue.scala, src/main/scala/xiangshan/mem/lsqueue/StoreMisalignBuffer.scala, src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala, src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala, src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala, src/main/scala/xiangshan/mem/vector/VMergeBuffer.scala, src/main/scala/xiangshan/mem/vector/VSegmentUnit.scala, src/main/scala/xiangshan/mem/vector/VecBundle.scala, src/main/scala/xiangshan/mem/vector/VecCommon.scala
In our previous design, we did not consider the handling of gpf of unaligned & vector load and stores. This commit adds a fix to correctly return the guest paddr when gpf happens in the above instructions.
=> fix(exception): Add guest page fault logic of misalign and vlsu

src/main/scala/xiangshan/cache/mmu/MMUConst.scala
With CHI enabled and CMN connected, a transaction may easily last over 10,000 cycles. This commit raises the time out threshold of PTW to 100,000 cycles.
=> chore(MMUConst): raise time out threshold

src/main/scala/xiangshan/Parameters.scala
In fact, our compilation speed has dropped by 75% since Sv48 was merged into the master. The reason is that this require **(`require(PAddrBits == 48 || !EnableSv48)`)**  takes over 70% of the entire compile time. 
This commit fixes it.
=> fix(Parameters): remove require of PaddrBits to speed up compile

src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala
PR #3527 adds guest page fault logic of misalign buffer. However, that commit didn't pass store gpaddr to misalign buffer. This commit fixes it.
=> fix(StoreUnit): pass gpaddr from StoreUnit to MisalignBuffer

src/main/scala/xiangshan/cache/mmu/L2TLB.scala, src/main/scala/xiangshan/cache/mmu/MMUBundle.scala, src/main/scala/xiangshan/cache/mmu/PageTableCache.scala, src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala
* fix(L2TLB): Fix exception generation logic
We may currently generate three types of exceptions, pf, gpf, and af. There must be only one type of exception that should occur in each resp returned by L2 TLB, which is the type of exception that occurs for the first time during the PTW process. Among them
pf & gpf: the two cases correspond to stage1 and stage2 respectively. **In our previous design, the error is that onlyStage1 is also considered to need gpf checking, but in fact, onlyStage1 shouldn't report gpf.**
af: there are two kinds of access faults, the first one is the access fault obtained by querying pmp before PTW accesses the memory, and the second one is the access fault obtained by the PPN high level of page table is not 0 after PTW accesses the memory. we call these two kinds …
=> fix(L2TLB): Fix exception generation logic 

src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala, src/test/scala/top/SimMMIO.scala
When a SoC level non-data error such as an attempt to access a location that does not exist is generated, SimMMIO should be capable of returning `DECERR` on the r/b channel of AXI4. The TLToAXI4 Bridge will transfer the `DECERR` and drive `denied` field in TileLink high. Receiving the `denied` signal, StoreQueue will raise store access fault and update mtval CSR with the exception virtual address.
=> fix(SQ, SimMMIO, L2): fix bugs in mtval when non-data error is raised

src/main/scala/xiangshan/backend/decode/DecodeUnit.scala, src/main/scala/xiangshan/backend/fu/NewCSR/CSRBundles.scala, src/main/scala/xiangshan/backend/fu/NewCSR/CSRDefines.scala, src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala, src/main/scala/xiangshan/backend/fu/wrapper/CSR.scala
* CSR
* When reset, xenvcfg.CBZE = 1, xenvcfg.CBCFE = 1, xenvcfg.CBIE = 0b11, while x in {m, s, h}.
* Support xenvcfg.CBIE = Flush(0b01)
* Decode
* Use the illegalInst and virtualInst conditions from CSR to assert EX_II or EX_VI.
* Convert CBO.INVAL to CBO.FLUSH when envcfg.CBIE === EnvCBIE.Flush.
=> feat(Zicbom,Zicboz): add permission check and convert CBO.INVAL to CBO.FLUSH when CBIE=0b01

Makefile, src/main/scala/xiangshan/backend/Backend.scala, src/main/scala/xiangshan/backend/BackendParams.scala, src/main/scala/xiangshan/backend/CtrlBlock.scala, src/main/scala/xiangshan/backend/datapath/DataPath.scala, src/main/scala/xiangshan/backend/rename/Rename.scala, src/main/scala/xiangshan/backend/rename/RenameTable.scala, src/main/scala/xiangshan/backend/rob/Rab.scala, src/main/scala/xiangshan/backend/rob/Rob.scala, src/main/scala/xiangshan/backend/rob/RobBundles.scala
This commit turns on basic difftest features again, no matter it's for simulation or physical design. This commit aims at allowing designs for physical design to be verified.
=> build: enable always-basic-diff for make verilog

.github/workflows/perf.yml
1. Change the default path of `GITHUB_WORKSPACE` to an NFS path for cross-server operation
=> ci: fix the default path of `GITHUB_WORKSPACE`

src/main/scala/xiangshan/mem/lsqueue/LoadQueueReplay.scala
Because the vector unit-stride instruction may not set all addr and data entries in storequeue to valid, it may cause retransmissions to fail from the replayqueue, resulting in a stuck.
=> fix(LoadQueueReplay): fix blocking logic

src/main/scala/xiangshan/cache/mmu/MMUBundle.scala, src/main/scala/xiangshan/cache/mmu/PageTableCache.scala
Since L2 Cache access width is 512 bits, 8 PTE items are refilled into page cache together. In previous design, when an exception occurs in one of the 8 refilled PTE entries, none of the 8 entries will be refilled. In this case, if there is a normal entry in one of the 8 neighbouring page tables, it will not be refillled because of the exception in the other entries, which will lead to blocking.
This commit fixes this problem. `vs` means that if one of the 8 consecutive page tables has an exception, the corresponding `vs` will be forced to be false when judging hit. `onlypf` means that if x2slate is not enabled, and only pf occurs, then the pf information will be returned. Except for the onlypf case, the rest of the exceptions will not be refilled in page cache (none of them will hit).
=> fix(PageTableCache): fix ptwcache refill logic when exception

src/main/scala/xiangshan/cache/mmu/L2TLB.scala, src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala, src/main/scala/xiangshan/cache/mmu/Repeater.scala, src/main/scala/xiangshan/cache/mmu/TLB.scala
With CHI enabled and CMN connected, a transaction may last over timeoutThreshold. So this commit removes it (also since L2 Cache will detect timeout)
=> chore(MMU): Remove timeout assertion

src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala, src/main/scala/xiangshan/backend/fu/SRT16Divider.scala, src/main/scala/xiangshan/backend/fu/wrapper/CSR.scala
CSR instructions used to be executed without pipelining, so a state machine is not needed inside the CSR module. After adding an optimization that allows certain CSRR instructions to be pipelined, a state machine is required, since the arbiter to integer register files must allow a write request before a CSRR instructions is successfully executed.
=> fix(CSR): add a finite state machine in NewCSR

src/main/scala/xiangshan/backend/Backend.scala, src/main/scala/xiangshan/backend/Bundles.scala, src/main/scala/xiangshan/backend/MemBlock.scala, src/main/scala/xiangshan/backend/fu/CSR.scala, src/main/scala/xiangshan/backend/fu/NewCSR/CSREvents/CSREvent.scala, src/main/scala/xiangshan/backend/fu/NewCSR/CSREvents/TrapEntryHSEvent.scala, src/main/scala/xiangshan/backend/fu/NewCSR/CSREvents/TrapEntryMEvent.scala, src/main/scala/xiangshan/backend/fu/NewCSR/CSREvents/TrapEntryVSEvent.scala, src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala, src/main/scala/xiangshan/cache/mmu/MMUBundle.scala, src/main/scala/xiangshan/cache/mmu/TLB.scala, src/main/scala/xiangshan/frontend/IFU.scala, src/main/scala/xiangshan/mem/MemCommon.scala, src/main/scala/xiangshan/mem/lsqueue/LSQWrapper.scala, src/main/scala/xiangshan/mem/lsqueue/LoadExceptionBuffer.scala, src/main/scala/xiangshan/mem/lsqueue/LoadMisalignBuffer.scala, src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala, src/main/scala/xiangshan/mem/pipeline/AtomicsUnit.scala, src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala, src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala, src/main/scala/xiangshan/mem/prefetch/L1PrefetchComponent.scala, src/main/scala/xiangshan/mem/prefetch/SMSPrefetcher.scala, src/main/scala/xiangshan/mem/vector/VecBundle.scala, src/main/scala/xiangshan/mem/vector/VecCommon.scala
In previous implementation, we simply truncated the higher bits of jump target or load & store address, which made it impossible to raise exceptions in such cases.
Commit https://github.com/OpenXiangShan/XiangShan/commit/c1b28b66879239a5b3a44741376f3b002e8ac834 has already fixed high address bits checking of jump target. This commit fixes lsu part, checking full address in tlb and passing full address directly to csr.
=> fix(exception): check high address bits of lsu

src/main/scala/xiangshan/backend/rob/Rob.scala
The "head" of commit_vDeqGroup and commit_wDeqGroup might be invalid after the instruction at index[0] committed.
So the "head" is not real rob head, which skews the meaning of headNotReady and skews topdown counters.
=> fix(topdownCounter): obtain ROB head from deqPtr instead of from "head"

src/main/scala/xiangshan/frontend/FTB.scala, src/main/scala/xiangshan/frontend/FrontendBundle.scala
When fallThroughErr is generated, even if FTB hits, it is treated as a miss. The destination address is not the destination jump address in FTB.
=> fix(BPU): modify the usage of the fallThroughErr signal

src/main/scala/system/SoC.scala, src/main/scala/xiangshan/PMParameters.scala, src/main/scala/xiangshan/Parameters.scala, src/main/scala/xiangshan/backend/fu/PMA.scala, src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala, src/main/scala/xiangshan/mem/prefetch/L1PrefetchComponent.scala, src/main/scala/xiangshan/mem/prefetch/L1PrefetchInterface.scala, src/main/scala/xiangshan/mem/prefetch/SMSPrefetcher.scala
This is beneficial if we have several sparse memory ranges.
=> refactor(Pmem): use `Seq` for physical memory ranges

src/main/scala/xiangshan/backend/fu/NewCSR/HypervisorLevel.scala, src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala, src/main/scala/xiangshan/backend/fu/NewCSR/TrapInstMod.scala
This PR fix trap inst update.
Because of CSRR inst is out of order insts, trap inst should select the oldest trap inst when CSRR inst raise trap.
=> fix(csr): fix trap inst update when CSRR insts raise trap and remove useless io

src/main/scala/xiangshan/cache/mmu/MMUBundle.scala, src/main/scala/xiangshan/cache/mmu/PageTableCache.scala
The meaning of `onlyPf` signal is that only pagefault occurs and no other exceptions occurs. In our design intent, this case for entry l0 (4KB page) would be considered hit (by setting `vs` = 1) and the pf signal would be returned to the L1 TLB; however, the previous condition of `vs` being 1 requires that `pte.isLeaf()` must be satisfied, which requires that the `pte.v` bit is 1. In fact, for the `onlyPf` condition to be satisfied, `vs` can be set to 1 without judging `pte.isLeaf()`.
For the 8 consecutive page tables refilled into PageCache, when `pte.canRefill` and `onlyPf` are both not satisfied, `vs` is set to 0, and thus judged as hit=0. However, when the 8 entries with valid `vs` hits, the other `vs` 0's may be refilled (`refill.valid` is 1), in which case the `bypass` and `hit` …
=> fix(PageTableCache): fix hit & bypass logic when onlypf

src/main/scala/xiangshan/frontend/BPU.scala, src/main/scala/xiangshan/frontend/FTB.scala, src/main/scala/xiangshan/frontend/FrontendBundle.scala, src/main/scala/xiangshan/frontend/newRAS.scala
1.restore the generation mechanism of BPU hit and fallThruError signals.
2.the hit signal and fallThroughError signal are associated with other modules.
=> fix(BPU): adjust fallThroughErr signal usage strategy

src/main/scala/xiangshan/frontend/FrontendBundle.scala
shouldShiftVec should be all zero when not hit
Related issue:
=> fix(ghist): fix ghist maintaining

src/main/scala/xiangshan/mem/lsqueue/LoadQueue.scala, src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala, src/main/scala/xiangshan/mem/vector/VMergeBuffer.scala
The vector exception address comes from the VMergebuffer, which needs to store all 64 bits addresses and connect to the LSQ exception processing.
=> fix(exception): connect new address port for vector access exceptions

src/main/scala/xiangshan/backend/MemBlock.scala, src/main/scala/xiangshan/mem/vector/VSplit.scala
In the previous design, the judgment of `flush` of pipeline connect and skid buffer is `io.in.bits.uop.robidx.needFlush(redirect)`, which will causes the request stored in the buffer that should not be flushed to be flushed. 
The function of `flush`: 
1. When `in.fire`, `flush` means to cancel request that will be buffer stored.
2. When `!in.fire`, `flush` means to cancel the request which stored in the buffer can't be send to the next stage, new request can't enter the buffer. 
This patch fixs the meaning of `flush` above.
=> fix(VLSU): fix bug in flush of pipeline connect & skid buffer

src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala, src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala
* Make rdataFields as Output for InterruptFilter usage.
* This commit fix the problem that SEIP cannot be raised.
=> fix(CSR,interrupt): use rdata instead of regOut to produce interrupt

src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala, src/main/scala/xiangshan/backend/fu/wrapper/CSR.scala
* Normal csr instrctions could fire by one cycle, while support IMSIC now.
* IMSIC and CSR have different clocks.
* Therefore, CSR interacts with IMSIC through asynchronous reading.
* Implementd by fsm, and its state includes idle, waitIMSIC, finish.
* Output can fire when NewCSR requests an IMSIC response, and the intermediate data should be stored.
=> fix(csr): intermediate data should be stored when output not fire

src/main/scala/xiangshan/backend/fu/NewCSR/MachineLevel.scala
* mhartid should be assigned directly to multicycle hartid from top.
=> fix(CSR): remove reg in mhartid

src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala
If hptw resp gpf or gaf, the gvpn_gpf should not be valid. The pr fixes the bug that gvpn_gpf is valid after hptw resp gpf or gaf.
=> fix(PTW, RVH): fix the priority of gpf, gaf and gvpn_gpf in PTW

Makefile
Previously, if we call `Mem` in XS, it will generate combmem RTL with x assignment if ren is low:
``` verilog
module data_mem_0_4x2(
input  [1:0] R0_addr,
input        R0_en,
input        R0_clk,
output [1:0] R0_data,
input  [1:0] W0_addr,
input        W0_en,
input        W0_clk,
input  [1:0] W0_data
);
reg [1:0] Memory[0:3];
always @(posedge W0_clk) begin
if (W0_en & 1'h1)
Memory[W0_addr] <= W0_data;
end // always @(posedge)
assign R0_data = R0_en ? Memory[R0_addr] : 2'bx;
endmodule
```
This is not expected because const-x should be avoided in synthesis. In this commit, we add `--ignore-read-enable-mem` option to disable x assignment if we generate release code.
=> fix(combmem): remove x assignment if ren is low

src/main/scala/device/imsic_axi_top.scala
It is better for Top IO to be register out. Add TLBuffer for TileLink version of IMSIC.
=> fix(IMSIC): add TLBuffer for tilelink IO

src/main/scala/xiangshan/frontend/BPU.scala, src/main/scala/xiangshan/frontend/Frontend.scala
Currently, `DelayNWithValid` generates code like:
``` verilog
module DelayNWithValid(
input         clock,
input  [47:0] io_in_bits,
input         io_in_valid,
output [47:0] io_out_bits
);
reg        valid_REG, valid_REG_1, valid_REG_2, valid_REG_3;
reg [47:0] data, data_1, data_2, data_3, res_bits;
always @(posedge clock) begin
valid_REG <= io_in_valid;
if (io_in_valid)
data <= io_in_bits;
valid_REG_1 <= valid_REG;
if (valid_REG)
data_1 <= data;
valid_REG_2 <= valid_REG_1;
if (valid_REG_1)
data_2 <= data_1;
valid_REG_3 <= valid_REG_2;
if (valid_REG_2)
data_3 <= data_2;
if (valid_REG_3)
res_bits <= data_3;
end // always @(posedge)
assign io_out_bits = res_bits;
endmodule
```
If we pass `reset` as `io_in_valid`, it is actually:
``` verilog
// ...
always @(posedge clock)
if (reset)
data <= …
```
=> fix(BPU): remove reg of reset_vector

src/main/scala/xiangshan/backend/fu/NewCSR/ExceptionBundle.scala, src/main/scala/xiangshan/backend/fu/NewCSR/HypervisorLevel.scala, src/main/scala/xiangshan/backend/fu/NewCSR/MachineLevel.scala
* No.16 exception is named double trap which is not delegatable. The bit in medeleg and hedeleg should be RO 0.
* No.18 exception is named Software check.
* No.19 exception is named Hardware error.
=> feat(CSR): add No.16,18 and 19 exceptions

src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala
Previously, menvcfg and henvcfg were added to "PerfCnt" to skip read/write them, because its implementation is different between XiangShan and NEMU. This patch removes this workaround as both XiangShan and NEMU support menvcfg and henvcfg. This could solve the pbmte diff problem.
=> fix(csr): not skip read/write menvcfg/henvcfg

src/main/scala/xiangshan/backend/rob/Rob.scala
When an instruction raises an exception and needs flush pipe, rob needs several cycles to handle flushing. If an interrupt raised during these cycles, another unexpected flushing will be triggered, which causes complaint from frontend.
This commit avoids this by blocking interrupt marking process when rob is handling flushing.
=> fix(Rob): block interrupt during flush handling

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
1. When cleaning up the exception vector at s2 in loadunit, loadunit should check misalign exception when tlb miss, otherwise misaligned load will send to LoadQueueRepaly instead of loadMisalignedBuffer.
2. When cleaning up the exception vector at s2 in loadunit, loadunit should check breakpoint exception when tlb miss.
=> fix(LoadUnit): add misalign and breakpoint exception check when cleaning up exception vector

src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala
This PR add support Non-register interrupt pending which come from platform.
Interrupts that cannot be generated by NEMU can be obtained through XiangShan ->Difftest ->NEMU.
Remove skip xip, xenvcfg to diff xip, xenvcfg.
Bump difftest and ready-to-run.
=> fix(csr): add support Non-registers interrupt pending to diff xip

src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala, src/main/scala/xiangshan/package.scala
When the DUT executes a cbo.inval, a set in Difftest is used to record its cacheline address.
Later, if there is a data mismatch between DUT and GoldenMem in the address space operated by the cbo.inval instruction, the Pmem of REF and GoldenMem will be directly updated using the data of DUT.
=> fix(cmo): Support Difftest with cbo.inval instruction

src/main/scala/top/Configs.scala, src/main/scala/xiangshan/cache/mmu/MMUBundle.scala, src/main/scala/xiangshan/cache/mmu/TLB.scala, src/main/scala/xiangshan/frontend/IFU.scala, src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala, src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala, src/main/scala/xiangshan/mem/prefetch/L1PrefetchComponent.scala, src/main/scala/xiangshan/mem/prefetch/SMSPrefetcher.scala
In our previous design, it was assumed that a request for gpaddr would always be replayed until it was responsed. However, this condition is not satisfied for prefetch and redirected requests, resulting in stuck. This commit fixes this bug.
=> fix(TLB): Should not send gpa when prefetch or redirect

src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala
* Use CSR.w.wen insread of addr comparation to avoid this mistake.
=> fix(CSR): assert vsatpASIDChanged when actually write vsatp by satp

src/main/scala/xiangshan/Bundle.scala, src/main/scala/xiangshan/backend/Bundles.scala, src/main/scala/xiangshan/backend/decode/DecodeUnit.scala, src/main/scala/xiangshan/backend/rob/Rob.scala, src/main/scala/xiangshan/frontend/FrontendBundle.scala, src/main/scala/xiangshan/frontend/IBuffer.scala, src/main/scala/xiangshan/frontend/IFU.scala
Multiple Ftq entries in one Rob entry have caused numerous issues related to MMIO instruction fetching. This PR tries to disallow RobCompress when crossing a Ftq entry boundary. Also, fix buggy code related.
=> Fix multiple ftq entries in single rob entry

src/main/scala/xiangshan/frontend/icache/WayLookup.scala
In the existing design, ICache assumes that once a gpf occurs, it works on the wrong path until a flush (redirect) arrives, so it can discard redundant gpf/gpaddr data to reduce power/area.
As shown below, the 2nd(orange) and 3rd(blue) gpaddr write to wayLookup is discarded.
This assumption is mostly true, except:
1. Consider a 34B fetch block in which the first 32B have no exceptions and consist entirely of RVC instructions, and the last 2B cross a page boundary and a gpf occurs.
2. The IFU sends at most 16 instructions to the ibuffer, and therefore discards the last 2B. This way, none of the instructions received by the backend have exceptions and no flush (redirect) is generated.
3. The next fetch block again has a gpf, which ICache (wayLookup) considers redundant and discards the …
=> fix(ICache): block waylookup if there is a pending gpf

src/main/scala/xiangshan/mem/lsqueue/LSQWrapper.scala
**Bug Description:**
When an uncache store (st) is immediately followed by an uncache load (ld), due to the `AddPipelineReg` in MemBlock when the LSQ transfers data with the Uncache, even though Uncache is handling the store request, `MemBlock.uncacheReq.ready` is still true. Under the original assignment conditions, the ld request(ld req) from LQ will be received by `MemBlock.uncacheReq` in the `s_store` state. So when `MemBlock.uncacheReq` is received by Uncache, the LSQ state has already transitioned from `s_store` to `s_idle`, without switching to `s_load`. As a result, the load response (ld resp) from Uncache can never be received by the LSQ. The process is briefly described as follows: 
1. SQ: st req
2. Uncache: st req received
3. LQ: ld req in `s_store` state
4. Uncache: st resp
5. …
=> fix(lsq): uncache req can be assigned only in idle state

src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
`scommit` from RoB represents the number of store instructions committed in this cycle, excluding the stores that raise exceptions. However the FSM for uncache store transitions from `s_wait` to `s_idle` only when `scommit > 0.U`. Therefore when a non-data error is raised from error device and an access fault is reported, the FSM gets blocked on `s_wait` state. Supposing that the next store in SQ raises another exception, the uncache FSM will get into deadlock.
This pr fixes the bug by a little modification on the uncache FSM, that is, when a mmio store that is detected for a non-data error writes back to backend, the FSM will transition into `s_idle` directly, skipping the state of `s_wait`.
=> fix(StoreQueue): fix bug in `uncacheState` FSM

src/main/scala/system/SoC.scala, src/main/scala/xiangshan/L2Top.scala, src/test/scala/top/SimMMIO.scala, src/test/scala/top/SimTop.scala
Previously, on-chip devices use a continuous memory range, which contains many memory holes not actually used. If we access these holes, the core will hang. This commit use fine-grained on-chip MMIO ranges so that memory accessing of these holes will be routed out of core and handled by other mechanisms.
=> fix(MMIO): use fine-grained on-chip MMIO ranges

src/main/scala/xiangshan/backend/rob/Rob.scala
The `RegNext` has been removed, so the comments are outdated.
=> docs(rob): remove outdated comments

src/main/scala/xiangshan/backend/Backend.scala, src/main/scala/xiangshan/backend/Bundles.scala, src/main/scala/xiangshan/backend/MemBlock.scala, src/main/scala/xiangshan/mem/lsqueue/LoadMisalignBuffer.scala, src/main/scala/xiangshan/mem/lsqueue/StoreMisalignBuffer.scala, src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala, src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala, src/main/scala/xiangshan/mem/vector/VMergeBuffer.scala, src/main/scala/xiangshan/mem/vector/VSplit.scala
fix(Backend, MemBlock): add `isFromLoadUnit` to indicate whether it is written back by LoadUnit, avoid other units polluting RegCache
=> fix the write-back of loadMisalignBuffer polluting RegCache

src/main/scala/xiangshan/backend/rob/RobBundles.scala
Due to the rob compression mechanism, the number of instructions committed per cycle may be greater than 7.
And the source signal `retiredInstr` sent by rob to the csr module has a bit width of 3, while the sink signal `instNum` has a bit width of 7, causing the low bits to be truncated when any cycle the number of commit instructions is greater than 7, making the minstret update inaccurate.
=> fix(csr): fix width of instruction commit

src/main/scala/xiangshan/mem/vector/VMergeBuffer.scala
The current condition, when there are no exceptions in the entry and the frompipe carries an exception, will go directly to the next level of determining whether it is a fof instruction. If it is a fof instruction and a non-zero element triggers an exception, the value of vl is modified directly.
> 
when((((entryElemIdx >= selElemIdx) && entryExcp && portHasExcp(i)) || (!entryExcp && portHasExcp(i))) && pipewb.valid && !mergedByPrevPortVec(i)) { // When there are no exceptions in the entry and the frompipe carries exceptions.
entry.uop.trigger     := selPort(0).trigger
entry.elemIdx         := selElemIdx
when(!entry.fof || vstart === 0.U){
// For fof loads, if element 0 raises an exception, vl is not modified, and the trap is taken.
entry.vstart       := vstart
entry.exceptionVec := …
=> fix(VMergeBuffer): vl of fof only allows setting smaller values

src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala
In order to prevent some strange cases from occurring in store and reduce complexity, let store enter storeMisalignBuffer only when tlb hits.
=> fix(misalign): enter storeMisalignBuffer when tlb hit

src/main/scala/xiangshan/backend/rob/ExceptionGen.scala, src/main/scala/xiangshan/backend/rob/Rob.scala, src/main/scala/xiangshan/backend/rob/RobBundles.scala
=> fix(VecExcp): use `isEnqExcp` to distinguish pc and mem trigger

src/main/scala/xiangshan/XSCore.scala, src/main/scala/xiangshan/backend/MemBlock.scala
Physical design: L2 and the backend are not allowed to be directly connected in partition. Pass Coupled L2 HPM signal through MemBlock.
=> timing(HPM): pass Coupled L2 HPM signal through memblock

src/main/scala/xiangshan/backend/MemBlock.scala, src/main/scala/xiangshan/mem/vector/VMergeBuffer.scala
[6e4a3d5](https://github.com/OpenXiangShan/XiangShan/pull/3741/commits/6e4a3d51e29a114d2d2697cd44efd733252740fc) Now we use the more fine-grained canAccept with ready feedback.
Separating the vector load from the vector store to determine the canAccept reduces the number of cases that can't be queued, and this also fixes the problem of deadlocks caused by a full RAWQueue.
* Ignore [fix(VMergeBuffer): vl of fof only allows setting smaller values](https://github.com/OpenXiangShan/XiangShan/pull/3741/commits/ e7e1bcabb679b8b77fdcc52bcdc1b2447a40c0f9). This commit is already in the master cbbad3d9821348664612590be62c941195db2035.
* Waiting for regression testing before merging.
=> fix(MemBlock): more accurate vector ready signal

src/main/scala/xiangshan/backend/Bundles.scala, src/main/scala/xiangshan/backend/fu/NewCSR/CSREvents/CSREvent.scala, src/main/scala/xiangshan/backend/fu/NewCSR/CSREvents/TrapEntryHSEvent.scala, src/main/scala/xiangshan/backend/fu/NewCSR/CSREvents/TrapEntryMEvent.scala, src/main/scala/xiangshan/backend/fu/NewCSR/CSREvents/TrapEntryVSEvent.scala, src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala, src/main/scala/xiangshan/backend/fu/wrapper/CSR.scala, src/main/scala/xiangshan/backend/rob/Rob.scala
* This commit fix the value of {m|s|vs}tval when load/store/atomic trigger fire. The faulting address should be written to tval.
=> fix(Breakpoint): memory trigger set {m|s|vs}tval with faulting address

src/main/scala/xiangshan/backend/rob/Rab.scala
* Since the commit info passed from ROB is absolutely right arch state, there is no need to limit diff commit valid only assert in RAB is in commit state(s_idle, s_special_walk).
=> fix(Rab): no need to limit diff commit valid only assert in commit state

src/main/scala/xiangshan/mem/lsqueue/LoadMisalignBuffer.scala, src/main/scala/xiangshan/mem/lsqueue/StoreMisalignBuffer.scala
In the previous design, the H extension information was lost in the `fuOpType` of the misalignBuffer split instruction, causing the split instruction to not perform two-stage address translation and cause errors.
This PR fixes the information about H extension in `fuOpType` in misalignBuffer.
=> fix(misalign): fix misaligned HLV and HLVX

scripts/xiangshan.py
This change can help us to capture the waveform of problem caused by hardware stuck. Besides, since we enlarged mmap memory, it may take much more time on `fork()` syscall. Enlarging the fork interval here also results better simulation speed in some circumstances.
=> ci(enable-fork): set fork interval to 10 seconds

src/main/scala/xiangshan/backend/Bundles.scala, src/main/scala/xiangshan/backend/fu/wrapper/CSR.scala, src/main/scala/xiangshan/backend/rob/Rob.scala
* This signal is only used to distinguish EX_BP store pc or load/store address in {m|s|vs}tval.
=> fix(Ebreak): use isPcBkpt to hold exception raised by ebreak

src/main/scala/xiangshan/cache/mmu/TLB.scala
PBMTE is already judged at L2, so there is no need to repeat the judgment and the assignment should not be affected in L1TLB.
=> fix(pbmt): fix assignment bug in tlb

src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
In the current design, vectors do not support hardware misalignment, so `unaligend` should not be set.
Support for vector misalignment will be added later.
=> fix(StoreQueue): vector instr are not set `unaligned`

src/main/scala/xiangshan/Parameters.scala
FpDqDeqWidth in fpSchdParams is incorrectly written as VecDqDeqWidth
=> fix(Parameters): change incorrect VecDqDeqWidth to FpDqDeqWidth

Makefile, build.sc, src/main/scala/system/SoC.scala, src/main/scala/top/Configs.scala, src/main/scala/top/Top.scala
* Bump OpenLLC to introduce the CHI-to-AXI bridge `OpenNCB`
* Build the SoC under KunminghuV2Config using OpenNCB and OpenLLC
* Update build dependencies and submodule initialization rules
=> feat(SoC): Replace DummyLLC with OpenLLC+OpenNCB in KunminghuV2Config

src/main/scala/xiangshan/frontend/icache/IPrefetch.scala
Cut critical path prefetchPipe s2 -> toMSHRArbiter.valid(i) -> toMSHR.paddr -> missUnit hit -> missUnit.req.ready -> prefetchPipe toMSHRArbiter.ready ***-> s2_finish ->*** s2_ready -> s1_ready -> toFtq.ready
for timing.
This can be thought of as adding 1 cycle to the prefetchPipe s2_finish, but only a minor performance change is expected, since the timing of issuing the first miss request is unchanged, and the additional waiting delay for subsequent miss requests can be hidden by the l2 cache access delay.
=> timing(IPrefetch): add 1 cycle to s2_finish

src/main/scala/xiangshan/backend/rename/Rename.scala
因为香山的decoder会在rd就是rs时增加一个numRegSrc，并令该reg为rs_n+1，所以并不需要这一段逻辑就可以处理类似于fmacc的指令。
=> fix(Rename): remove the handling of dest being src in bypassCond

src/main/scala/xiangshan/frontend/icache/ICache.scala
mainPipe.io.errors is not ensured to be at-most-one-hot, ECC errors may occur on both cachelines at the same time.
Note: DCache may have similar problems, as this code is actually copy-and-pasted from DCache 3 years ago.
https://github.com/OpenXiangShan/XiangShan/blob/0303f76a84fd705d32f6f0434c63c55e2ff02186/src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala#L991-L997
=> fix(ICache): use PriorityMux instead of Mux1H for io.error

src/main/scala/xiangshan/frontend/BPU.scala, src/main/scala/xiangshan/frontend/Composer.scala, src/main/scala/xiangshan/frontend/FTB.scala, src/main/scala/xiangshan/frontend/FauFTB.scala, src/main/scala/xiangshan/frontend/Frontend.scala, src/main/scala/xiangshan/frontend/FrontendBundle.scala, src/main/scala/xiangshan/frontend/IFU.scala, src/main/scala/xiangshan/frontend/ITTAGE.scala, src/main/scala/xiangshan/frontend/PreDecode.scala, src/main/scala/xiangshan/frontend/SC.scala, src/main/scala/xiangshan/frontend/Tage.scala, src/main/scala/xiangshan/frontend/WrBypass.scala, src/main/scala/xiangshan/frontend/newRAS.scala
scalafmt is ugly in some cases
also remove unused import
=> style(frontend): manually wrap some line

.github/workflows/perf.yml
1. Use a conditional step after the schedule to ensure strict biweekly execution.
2. Allow specifying a commit SHA for manual runs.
3. Retain each test's emu; if an emu exists, skip the build. This approach both preserves the emu for reproducibility and saves build time.
=> ci(perf): optimize the schedule

src/main/scala/xiangshan/XSDts.scala
This line makes the following print, which is not human-readable.
=> chore(dts): remove very vague print

src/main/scala/xiangshan/backend/MemBlock.scala, src/main/scala/xiangshan/mem/lsqueue/LSQWrapper.scala, src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala, src/main/scala/xiangshan/mem/pipeline/HybridUnit.scala, src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala, src/main/scala/xiangshan/mem/vector/VMergeBuffer.scala, src/main/scala/xiangshan/mem/vector/VSegmentUnit.scala, src/main/scala/xiangshan/mem/vector/VecCommon.scala
This will result in the delivery of clean generated code and may remove some of the pseudo-paths.
=> refactor(MemBlock):  turn on `dontTouch` only when debugging

src/main/scala/xiangshan/backend/fu/FuConfig.scala, src/main/scala/xiangshan/backend/fu/NewCSR/CSRBundles.scala, src/main/scala/xiangshan/backend/fu/NewCSR/CSREvents/CSREvent.scala, src/main/scala/xiangshan/backend/fu/NewCSR/CSREvents/MNretEvent.scala, src/main/scala/xiangshan/backend/fu/NewCSR/CSREvents/MretEvent.scala, src/main/scala/xiangshan/backend/fu/NewCSR/CSREvents/SretEvent.scala, src/main/scala/xiangshan/backend/fu/NewCSR/CSREvents/TrapEntryHSEvent.scala, src/main/scala/xiangshan/backend/fu/NewCSR/CSREvents/TrapEntryMEvent.scala, src/main/scala/xiangshan/backend/fu/NewCSR/CSREvents/TrapEntryVSEvent.scala, src/main/scala/xiangshan/backend/fu/NewCSR/HypervisorLevel.scala, src/main/scala/xiangshan/backend/fu/NewCSR/InterruptFilter.scala, src/main/scala/xiangshan/backend/fu/NewCSR/MachineLevel.scala, src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala, src/main/scala/xiangshan/backend/fu/NewCSR/SupervisorLevel.scala, src/main/scala/xiangshan/backend/fu/NewCSR/TrapHandleModule.scala, src/main/scala/xiangshan/backend/fu/NewCSR/VirtualSupervisorLevel.scala, src/main/scala/xiangshan/package.scala
* NEMU commit: 066cb1f1c61feb21153399c26ca393dfb3a560d7
* NEMU configs:
* riscv64-xs-ref_defconfig
* riscv64-dual-xs-ref_defconfig
Including:
* fix(format): adjust code format and add one config (OpenXiangShan/NEMU#603)
* fix(vfredusum): set xstatus.fs and xstatus.vs dirty (OpenXiangShan/NEMU#605)
* fix(vf): do not set dirtyFs for some instructions (OpenXiangShan/NEMU#606)
* feat(trigger): add trigger support for rva.
* configs(xs): open Sm/sdbltrp extension and add MDT_INIT config (OpenXiangShan/NEMU#604)
---
* spike commit: c0b18d3913d8ceac83743a053a7dbd2fb8716c83
* spike config: CPU=XIANGSHAN
Including:
* fix(rva, trigger): For rva instr, raise BP from trigger prior to misaligned.
* fix(Makefile): Increase maxdepth for finding .h files.
* fix(tdata1): CPU_XIANGSHAN do not implement hit …
=> feat(Ss/Smdbltrp) : Support RISC-V Ss/Smdbltrp Extension

.github/workflows/format.yml
previously `on push` condition causes problem for outside collabrators
=> chore(ci): allow pr run format flow

src/main/scala/xiangshan/cache/mmu/TLB.scala, src/main/scala/xiangshan/mem/lsqueue/LoadMisalignBuffer.scala, src/main/scala/xiangshan/mem/lsqueue/StoreMisalignBuffer.scala
We should not use GatedRegNext here as `overwrite*` may be X-state when `shouldOverwrite` is false.
Also fix a bug about generate gpaddr when a cross-page misalign load request.
Should not squash these two commits.
=> fix(MisalignBuffer): Use RegEnable in datapath to avoid xprop

src/main/scala/xiangshan/frontend/FTB.scala
During the shutdown period of FTB, there is no need to make FTB update requests, which has performance benefits for FTQ blocking caused by FTB updates after FTB shutdown
=> fix(FTB): Turn off FTB updates when FTB is closed.

src/main/scala/xiangshan/frontend/BPU.scala, src/main/scala/xiangshan/frontend/FTB.scala, src/main/scala/xiangshan/frontend/FauFTB.scala, src/main/scala/xiangshan/frontend/ITTAGE.scala, src/main/scala/xiangshan/frontend/NewFtq.scala, src/main/scala/xiangshan/frontend/Tage.scala
Reuse always_taken to mark the first occurrence of the jalr instruction and rename always_taken to strong_bias.
=> feat(ittage): Reuse always_taken to mark the first occurrence of the jalr inst

src/main/scala/xiangshan/backend/decode/DecodeUnit.scala
This pr add zihintpause extension:
* decode pause to FENCE with pred=W, succ=0, fm=0, rd=x0, rs1=x0
* Currently, FENCE has no side effects.
=> feat(zihintpause): support zihintpause

src/main/scala/xiangshan/cache/mmu/TLB.scala, src/main/scala/xiangshan/mem/lsqueue/LoadMisalignBuffer.scala
For onlyStage2 situations, gpaddr is equal to vaddr. Therefore, for cross-page requests, we need to pass gpaddr out correctly (see comments) Also, in previous design, we would set gpaddr offset to all zero when cross-page in loadmisalign buffer. This has been removed and all gpaddrs are generated in tlb.
=> fix(misalign): fix gpaddr of misalign loads when onlyStage2

src/main/scala/xiangshan/backend/Bundles.scala, src/main/scala/xiangshan/mem/pipeline/AtomicsUnit.scala
Atomics memory operations only work on word, double word and quad word in the future. Therefore any code concerning byte and half word is redundant and only contributes to worse timing and area.
=> style(AtomicsUnit): remove unnecessary logics

src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala, src/main/scala/xiangshan/cache/dcache/data/BankedDataArray.scala, src/main/scala/xiangshan/cache/dcache/meta/TagArray.scala, src/main/scala/xiangshan/cache/mmu/PageTableCache.scala, src/main/scala/xiangshan/mem/prefetch/SMSPrefetcher.scala
By using ClockGate for DCache SRAM, memory Power has 64% reduction, MemBlock total power has 23.38% reduction.
=> power(MemBlock): add  ClockGate for DCache SRAM

src/main/scala/top/Configs.scala, src/main/scala/xiangshan/frontend/icache/ICache.scala
| gcc12, 0.8 coverage              | master-8way |        | master-4way |        | speedup  |
|----------------------------------|-------------|--------|-------------|--------|----------|
| ********* SPECINT 2006 ********* | 3GHz        | /GHz   | 3GHz        | /GHz   |          |
| 400.perlbench                    | 37.155      | 12.385 | 37.053      | 12.351 | -0.27%   |
| 401.bzip2                        | 26.535      | 8.845  | 26.503      | 8.834  | -0.12%   |
| 403.gcc                          | 47.012      | 15.671 | 46.925      | 15.642 | -0.19%   |
| 429.mcf                          | 59.51       | 19.837 | 59.43       | 19.81  | -0.13%   |
| 445.gobmk                        | 30.241      | 10.08  | 30.208      | 10.069 | -0.11%   |
| 456.hmmer                        | 40.753 …
=> area(DCache): reduce 8 way to 4 way

src/main/scala/xiangshan/mem/lsqueue/LoadMisalignBuffer.scala, src/main/scala/xiangshan/mem/lsqueue/LoadQueueReplay.scala, src/main/scala/xiangshan/mem/lsqueue/StoreMisalignBuffer.scala, src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala, src/main/scala/xiangshan/mem/pipeline/AtomicsUnit.scala, src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala, src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala, src/main/scala/xiangshan/mem/vector/VSegmentUnit.scala, src/main/scala/xiangshan/mem/vector/VSplit.scala
optimise redundant signals to reduce MemBlock area.
1. optimise 'exceptionVec', selected by LduCfg or StaCfg;
2. optimise 'fuType',  reassign the value when writeback Rob in pipeline, so no longer saved in LSQ.
3. optimise 'uop.imm',  vaddr is computed in StoreMisalignBuffer and there is no need to store the uop.imm.
=> area(MemBlock): remove redundant signals to optimise area

src/main/scala/xiangshan/cache/mmu/TLB.scala
In PR #3822, the gpaddr generating logic is modified for cross-page handleing. But that modification doesn't consider that the fullva of iTLB is always zero and should not be used, which causes the wrong htval/mtval2 when instruction guest page fault occurs. This patch fixes this.
=> fix(TLB): incorrect tval2 info when IGPF occurs

src/main/scala/xiangshan/Bundle.scala, src/main/scala/xiangshan/backend/fu/wrapper/CSR.scala, src/main/scala/xiangshan/frontend/Frontend.scala, src/main/scala/xiangshan/frontend/IFU.scala, src/main/scala/xiangshan/frontend/PreDecode.scala
* fix RVC floating-point inst raise EX_II in predecode when xstatus.fs is off
Fix #3864
Update: https://github.com/OpenXiangShan/rocket-chip/pull/20 is merged and this PR is rebased, ready to review.
=> fix(CSR,RVC): c.fp instrs should be illegal when fs is off

src/main/scala/xiangshan/frontend/BPU.scala
Detailed Issue please refer to issue: https://github.com/OpenXiangShan/XiangShan/issues/3837
Close #3837
=> fix(BPU): fix potential bug on s2_fire_dup

src/main/scala/system/SoC.scala
To support maximum number of L-Credits defined in CHI.IssueE.b.14.2.1
=> fix: change CHIAsyncQueueBridge depth to 16

src/main/scala/xiangshan/mem/lsqueue/LoadQueueReplay.scala
* Bug descriptions:
When an instruction first enq LoadQueueReplay and needs to be redirected, the EnqMask generation does not take this situation into account, then incorrectly updating the age matrix.
* Bug fix
use newEnqueue to generate EnqMask
=> fix(LoadQueueReplay): fix enq mask generate when redirect

src/main/scala/xiangshan/frontend/FTB.scala, src/main/scala/xiangshan/frontend/ITTAGE.scala, src/main/scala/xiangshan/frontend/NewFtq.scala, src/main/scala/xiangshan/frontend/SC.scala, src/main/scala/xiangshan/frontend/Tage.scala, src/main/scala/xiangshan/frontend/icache/ICache.scala
* Add param `withClockGate` at SRAMTemplate
* when SRAM is single-port, use maskedClock for both array\.read\(\) and array\.write\(\) to ensure single-port SRAM access.
* when SRAM is multi-port, the read and write ports of the multi-port SRAM are gated using different clocks.
=> feat(frontend): add ClockGate at frontend SRAMTemplate

src/main/scala/xiangshan/backend/fu/NewCSR/CSREvents/DretEvent.scala
* ref: When an MRET instruction is executed, the virtualization mode V is set to MPV, unless MPP=3, in which case V remains 0
=> fix(dret): fix update of privstate in dretevent

src/main/scala/xiangshan/Parameters.scala, src/main/scala/xiangshan/backend/GPAMem.scala, src/main/scala/xiangshan/backend/fu/NewCSR/CSREvents/CSREvent.scala, src/main/scala/xiangshan/backend/fu/NewCSR/CSREvents/TrapEntryHSEvent.scala, src/main/scala/xiangshan/backend/fu/NewCSR/CSREvents/TrapEntryMEvent.scala, src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala, src/main/scala/xiangshan/frontend/IFU.scala, src/main/scala/xiangshan/frontend/icache/ICacheMainPipe.scala, src/main/scala/xiangshan/frontend/icache/IPrefetch.scala, src/main/scala/xiangshan/frontend/icache/WayLookup.scala
We found that the CSR mtval2 truncates the high bits of gpaddr when GPF occurs in instruction fetching. Actually, there is an GPAMem which storages the whole 64-bit gpaddr, but it does not pass to CSR correctly, due to incorrect width of trapPCGPA in module NewCSR and bundle TrapEntryEventInput. This patch fixes this.
=> fix(CSR): correct the width of PC pgaddr for inst fetch exception

src/main/scala/xiangshan/backend/decode/VecDecoder.scala
Although the vs2 used by the vnclip instruction is signed, the immediate number is unsigned
=> fix(vnclip): use uimm instead of imm for vnclip_wi instructions

src/main/scala/xiangshan/backend/fu/NewCSR/CSRAIA.scala, src/main/scala/xiangshan/backend/fu/NewCSR/HypervisorLevel.scala, src/main/scala/xiangshan/backend/fu/NewCSR/InterruptBundle.scala, src/main/scala/xiangshan/backend/fu/NewCSR/InterruptFilter.scala, src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala, src/main/scala/xiangshan/backend/fu/NewCSR/TrapHandleModule.scala
* This PR fixes interrupt filtering and deleging with AIA.
* The generation of the `xcause` interrupt number depends on the `default` interrupt priority, and the generation of the `xtopi` interrupt number depends on the `default` priority and the `custom` priority.
* We use `xtopi.IID` as interrupt code to pass diff.
* Add AIA xtopei event diff and remove AIA csr skip.
=> fix(csr, aia): fix interrupt filter and deleg with AIA

src/main/scala/xiangshan/cache/dcache/loadpipe/LoadPipe.scala, src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
* break hitVec -> ldu tag_error -> loadunit path
=> timing(DCache): delay tag error to s3 instead of s2

.github/filters.yaml, .gitignore
In our development pratices, it's common to name stdout and stderr output log as *.log and *.err, respectively, based on informal observation within our team. 
This patch adds *.log and *.err to the .gitignore file to ensure they are ignored by Git. Notably, *.log is already ignored due to existing rules, and there is no source files in the projects with a *.err extension. As such, this patch is safe.
This patch also adds .gitignore into .github/filters.yaml to sikp ci. It seems no need to run CI again when .gitignore is modified.
=> chore(gitignore): ignore log file like *.err and *.log

src/main/scala/xiangshan/frontend/icache/ICache.scala, src/main/scala/xiangshan/frontend/icache/ICacheBundle.scala, src/main/scala/xiangshan/frontend/icache/ICacheMainPipe.scala
This PR is part of *RAS(Reliability, Accessibility, Serviceability)* error recovery features.
Unlike DCache, data in ICache is always not dirty, so when it is corrupted, we can always re-fetch from L2 cache.
Port & behavior changes:
- Add a `flush` port to metaArray, letting mainPipe be able to clear valid_array before doing re-fetch, thereby preventing multi-hit in ICache.
- if metaArray ECC error is detected, flush vSets in each way, since `waymask` is unreliable.
- if dataArray ECC error is detected, flush the vSet in way specified by `waymask`.
- metaArray / dataArray ECC errors will no longer raise access fault, as they can be resolved by re-fetching. Raise af only when response from L2 is marked as corrupted.
- When ECC error is detected, mainPipe will send miss requests to L2 …
=> feat(ICache): re-fetch data from L2 if ECC error is detected

src/main/scala/xiangshan/frontend/FrontendBundle.scala, src/main/scala/xiangshan/frontend/IFU.scala, src/main/scala/xiangshan/frontend/icache/ICacheMainPipe.scala
Move Vec(2) inside `ICacheMainPipeResp` to eliminate unused ports. No functional changes.
=> refactor(IFU,ICache): refactor interface

src/main/scala/xiangshan/backend/MemBlock.scala, src/main/scala/xiangshan/backend/decode/DecodeStage.scala, src/main/scala/xiangshan/backend/dispatch/Dispatch.scala, src/main/scala/xiangshan/backend/rename/BusyTable.scala, src/main/scala/xiangshan/backend/rename/Rename.scala, src/main/scala/xiangshan/backend/rename/freelist/StdFreeList.scala, src/main/scala/xiangshan/cache/mmu/PageTableCache.scala, src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala
`getperfevent` retrieves both the `name` and `value` fields, whereas `getperf` only retrieves the `value` port. The original implementation caused all perf event information for PTW to be printed as `perfEventsPTW`, making them indistinguishable.
=> fix(HPM): Fix PTW perfevent print error, organize the code format of some perfevents .

src/main/scala/xiangshan/cache/dcache/loadpipe/LoadPipe.scala
Remove the redundant logic of the miss queue nack based on the issues raised in the issues(https://github.com/OpenXiangShan/XiangShan/issues/3916).
When a tlb miss and a dcache miss occur at the same time and the miss queue nack, it will cause the `LoadUnit` to generate both replay signals `C_TM` and `C_DR`. We will give priority to `C_TM`, which is why we need to send a kill signal to dcache when a tlb miss occurs.
Although there was no problem before, as the issue(https://github.com/OpenXiangShan/XiangShan/issues/3916) says, this will cause ambiguity, and the miss queue nack message is already included in `s2_nack_no_mshr`, so the choice is to remove the `s2_miss_req_fire` signal from the generation logic of the `s2_mq_nack` signal.
=> refactor(LoadPipe): remove the redundant logic of the `mq_nack`

src/main/scala/xiangshan/backend/decode/DecodeUnit.scala, src/main/scala/xiangshan/backend/issue/Dispatch2Iq.scala, src/main/scala/xiangshan/backend/issue/EntryBundles.scala
* when vstart is not zero, it need to combine the old data in the range of 0 to vstart, so we need old vd in this case
* different instructions may have same fuoptype, so we need to check both futype and fuoptype to distinguish the instructions
=> fix(decode): not eliminate old vd when vstart is not zero

src/main/scala/xiangshan/backend/fu/NewCSR/MachineLevel.scala
* menvcfg.DTE only control Smode dbltrp. Thus mstatus.sdt will not
control by DTE.
* as sstatus is alias of mstatus, when menvcfg.DTE close write
sstatus.sdt cannot lead to shadow write of mstatus.sdt. As a result,
we add wmask of sdt, when write source is from alias write.
While vsstatus is not alias of any other CSR fields, so origin logic
is correct.
* align spike/nemu logic to xiangshan. see spike pr[60](https://github.com/OpenXiangShan/riscv-isa-sim/pull/60), NEMU pr[688](https://github.com/OpenXiangShan/NEMU/pull/688) for detail.
=> fix(dbltrp): fix sdt/dte interaction logic 

src/main/scala/xiangshan/frontend/icache/FIFO.scala, src/main/scala/xiangshan/frontend/icache/ICache.scala, src/main/scala/xiangshan/frontend/icache/ICacheBundle.scala, src/main/scala/xiangshan/frontend/icache/ICacheMainPipe.scala, src/main/scala/xiangshan/frontend/icache/ICacheMissUnit.scala, src/main/scala/xiangshan/frontend/icache/IPrefetch.scala, src/main/scala/xiangshan/frontend/icache/InstrUncache.scala, src/main/scala/xiangshan/frontend/icache/WayLookup.scala
- add type annotation to public members
- add private qualifier to other members
- add `asUInt` to shift results (Bits)
- fix typo
- remove unused imports
- rename `ICacheMSHR.waymask` to `way` since it is not a mask
- use `idxBits` for `log2Up(nSets)`
- use `wayBits` for `log2Up(nWays)`
- use `foreach` instead of `map` when return value is not needed
- use `{}` instead of `()` for multi-line `foreach` and `map`
The generated verilog is checked and is identical with the original (except `waymask` -> `way` & order changes).
=> refactor(ICache): refactor code style & eliminate IDE warnings

src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala
* This commit fix the shadow write to custom PMA CSRs which are writable before but not writable now.
=> fix(CSR): fix shadow writing for custom PMA CSRs not in `csrRwMap`

scripts/xiangshan.py
`/nfs-nvme` does not exist in `nodexxx` machines, which leads to ci failure. Change it to `/nfs` instead.
=> ci(nightly): change checkpoint directory

src/main/scala/xiangshan/cache/mmu/TLB.scala
L1TLB does not store gpaddr, but gpaddr is needed when a guest page fault occurs. In that situation, L1TLB needs to send a PTW request to get the gpaddr, which we called it getGpa. The getGpa mechanism could only handle one GPF TLB request (the first one) and expects the corresponding TLB entry is still in L1TLB.
L1TLB replacement uses PLRU (Pseudo-LRU) algorithm, which may replace intems that are not necessarily the least recently used. We found an case that L1TLB replace that GPF TLB entry, although that GPF TLB entry is accessed recently. This results in a deadlock in getGpa mechanism, which eventually causes the entire core to freeze. To solve this problem, we decides to prevent any unrelated ptw refills when getGpa mechanism is working (need_gpa).
After solve such problem, we …
=> fix(TLB): avoid freeze when GPF occurs

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
According to the backend instructions, currently, we have a total of three signals that can notify the backend to generate a flush pipe:
`flushPipe`, `replayInst`, and `rollback`
Among these, `flushPipe` and `replayInst` will be combined into the same flush signal in the backend, and the flush will be generated only when the command reaches the Rob dequeue pointer.
The `rollback` signal will flush as soon as it is sent, so flushing the pipe via the `rollback` signal is faster.
Currently in MemBlock, store/load MisalignBuffer will flush via `flushPipe`, RAR violations and mismatch of virtual and physics addresses in the forward will flush via both `flushPipe` and `rollback`, and RAW and uncached nack will flush via `rollback`.
When `flushPipe` and `rollback` are triggered at the same time, …
=> fix(loadUnit): rollback should be used for flush

src/main/scala/xiangshan/backend/CtrlBlock.scala, src/main/scala/xiangshan/backend/decode/DecodeStage.scala
* For inst fusion, we keep the seqNum of the inst before and after the fusion consistent, both of which are the SeqNum of the latter inst.
* For uop split, we keep the seqNum of the last uop and set the seqNum of the remaining uops to all 1s.
=> fix(PerfCCT): fix inst seqNum when inst fusion and uop split

scripts/xiangshan.py, src/main/scala/xiangshan/Bundle.scala, src/main/scala/xiangshan/backend/fu/NewCSR/CSRBundles.scala, src/main/scala/xiangshan/backend/fu/NewCSR/CSRDefines.scala, src/main/scala/xiangshan/backend/fu/NewCSR/HypervisorLevel.scala, src/main/scala/xiangshan/backend/fu/NewCSR/MachineLevel.scala, src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala, src/main/scala/xiangshan/backend/fu/wrapper/CSR.scala, src/main/scala/xiangshan/cache/mmu/MMUBundle.scala, src/main/scala/xiangshan/cache/mmu/MMUConst.scala, src/main/scala/xiangshan/cache/mmu/TLB.scala, src/main/scala/xiangshan/mem/pipeline/AtomicsUnit.scala, src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala, src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala, src/main/scala/xiangshan/mem/vector/VSegmentUnit.scala
feat(pointer masking): support Ssnpm & Smnpm & Smmpm
=> feat(pointer masking): support Ssnpm & Smnpm & Smmpm

src/main/scala/top/Configs.scala, src/main/scala/xiangshan/L2Top.scala
* add optional ECC for L2 Cache tag & data
* add Poison & (optional) DataCheck for CHI
=> feat(ECC): add ECC for coupledL2 and bump coupledL2 & openLLC

src/main/scala/xiangshan/cache/mmu/TLB.scala
In previous design, refill.valid will be false when `need_gpa` is true. However, need_gpa is a reg so we add signal `need_gpa_wire` which will be true one cycle before need_gpa. refill.valid will be false either need_gpa or need_gpa_wire is true.
=> fix(TLB): avoid refill when one cycle before need_gpa

src/main/scala/xiangshan/backend/rob/Rob.scala
The frontend needs to send redirect before sending commit.
When flushPipe occurs continuously, it may not meet the above condition in some cases, so this logic is added.
=> fix(redirect): fix the `blockCommit` condition

src/main/scala/xiangshan/frontend/Frontend.scala, src/main/scala/xiangshan/frontend/icache/ICache.scala, src/main/scala/xiangshan/frontend/icache/IPrefetch.scala
ITLB does not store `gpaddr` to save resources, instead it takes `gpaddr` from L2TLB when gpf occurs, which poses a two-option requirement for the requestor (i.e. IPrefetchPipe):
1. resend the same `itlb.io.req.vaddr` until `itlb.io.resp.miss` is pulled down
2. flush gpf entry in ITLB by pulling up `itlb.io.flushPipe`
Otherwise, ITLB is unable to handle the next gpf and the core hangs.
However, the first point cannot be guaranteed during the speculative execution, as IPrefetchPipe sends request to ITLB at s0 stage and may receive a flush request from BPU s3 stage, IFU or Backend at s1 stage, then the same vaddr is never resend to ITLB.
Therefore, we must ensure that ITLB is flushed synchronously when IPrefetchPipe s1 stage is flushed, thus satisfying the second point. This PR implements …
=> fix(ICache,ITLB): also flush itlb pipe when prefetchPipe s1_flush

scripts/xiangshan.py, src/main/scala/xiangshan/backend/fu/NewCSR/CSRPermitModule.scala
* fix the access check for custom CSR and remove the illegal instruction check when accessing S-mode custom CSR from VS mode. This is because we can now use the Smstateen extension to control access to custom content at different privilege levels.
* fix the misjudgment of the U-mode custom CSR.
* fix the missing access check for the stopi CSR in AIA.
=> fix(Smstateen): fix access check when Smstateen extension enable.

scripts/xiangshan.py, src/main/scala/xiangshan/Parameters.scala, src/main/scala/xiangshan/backend/Bundles.scala, src/main/scala/xiangshan/backend/MemBlock.scala, src/main/scala/xiangshan/backend/decode/DecodeUnit.scala, src/main/scala/xiangshan/backend/decode/DecodeUnitComp.scala, src/main/scala/xiangshan/backend/decode/UopInfoGen.scala, src/main/scala/xiangshan/backend/issue/Scheduler.scala, src/main/scala/xiangshan/backend/rename/Rename.scala, src/main/scala/xiangshan/backend/rob/Rob.scala, src/main/scala/xiangshan/cache/CacheConstants.scala, src/main/scala/xiangshan/cache/L1Cache.scala, src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala, src/main/scala/xiangshan/cache/dcache/mainpipe/AMOALU.scala, src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala, src/main/scala/xiangshan/cache/dcache/mainpipe/MissQueue.scala, src/main/scala/xiangshan/mem/MemCommon.scala, src/main/scala/xiangshan/mem/pipeline/AtomicsUnit.scala, src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala, src/main/scala/xiangshan/package.scala
This pull request implements **Zacas** extension for atomic Compare-and-Swap (CAS) instructions. For RV64, AMOCAS.W / AMOCAS.D / AMOCAS.Q atomically loads 32 / 64 / 128-bits of  a data value from **rs1**, compares the loaded value to register **rd** (for AMOCAS.Q, a register pair consisting of **rd** and **rd+1**), and if the comparison is bitwise equal, then stores the value held in **rs2** (for AMOCAS.Q, a register pair consisting of **rs2** and **rs2+1**) to the original address in **rs1**.
This pull request re-uses the existing AtomicsUnit design. However, an AMOCAS instruction may consume more than 1 std and even more than 1 sta in the new design. As far as stds,
* for AMOs (except AMOCAS) and LR/SC, 1 std uop is wanted: X(rs2) with uopIdx = 0
* for AMOCAS.W / AMOCAS.D, 2 std uops …
=> feat(Backend, MemBlock): add support for Zacas extension

src/main/scala/top/Top.scala
The previous design set OpenNCB concurrency to the default value of 15. This commit adjusts the configuration to align with the parallelism of L2 MSHR requests and MMIO requests, enhancing overall performance.
=> perf(XSTop): improve concurrency of CHI-AXI bridge

src/main/scala/xiangshan/backend/MemBlock.scala, src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala, src/main/scala/xiangshan/cache/dcache/loadpipe/LoadPipe.scala, src/main/scala/xiangshan/cache/mmu/Repeater.scala, src/main/scala/xiangshan/mem/MemCommon.scala, src/main/scala/xiangshan/mem/lsqueue/LSQWrapper.scala, src/main/scala/xiangshan/mem/lsqueue/LoadExceptionBuffer.scala, src/main/scala/xiangshan/mem/lsqueue/LoadMisalignBuffer.scala, src/main/scala/xiangshan/mem/lsqueue/LoadQueue.scala, src/main/scala/xiangshan/mem/lsqueue/LoadQueueReplay.scala, src/main/scala/xiangshan/mem/lsqueue/StoreMisalignBuffer.scala, src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala, src/main/scala/xiangshan/mem/lsqueue/VirtualLoadQueue.scala, src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala, src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala, src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala, src/main/scala/xiangshan/mem/vector/VMergeBuffer.scala, src/main/scala/xiangshan/mem/vector/VSegmentUnit.scala, src/main/scala/xiangshan/mem/vector/VSplit.scala, src/main/scala/xiangshan/mem/vector/VecBundle.scala
1. Changed Dcache's 128bitReq to access addresses with 128bit alignment.
2. Minorly refactored the misaligned hardware implementation, but due to other constraints, there was no significant performance gain. Currently, the detection of the Linux kernel startup shows a performance improvement of about ~4 times (misaligned). It is foreseeable that with the refactoring of other components, there is still room for further improvement in misaligned performance.
3. **Supports vector misaligned access.**
4. Unreasonable assertions in the `Sbuffer` have been removed.
5. To support the new misaligned implementation, the blocking condition of the `forwarding fault` of `LoadQueueReplay` has been changed to not detect the item where `sqIdx` is located. In theory, this will bring a very small …
=> feat(Zicclsm): minor refactoring misalign and support for vector misalign

src/main/scala/xiangshan/cache/mmu/MMUConst.scala, src/main/scala/xiangshan/cache/mmu/PageTableCache.scala
Previous design: l0 32 sets * 8 ways * 8 entries = 2048; l1 8 sets * 4 ways * 8 entries = 512 
Modified: l0 32 sets * 4 ways * 8 entries = 1024; l1 8 sets * 2 ways * 8 entries = 256
Performance drops by 0.09% in spec06 with 0.3 coverage.
=> area(PTWCache): reduce l2tlb entries from 2k to 1k

src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
The acquisition of information related to the difftest when a non-aligned Store is split into a Sbuffer was not considered before. Use a more robust way to get the information needed for the difftest.
=> fix(StoreQueue): fix `difftestinfo` for store event

src/main/scala/xiangshan/cache/dcache/data/BankedDataArray.scala
Bug description:
use **s2** index to select **s3** readline **error_delayed**
Fix:
use **s3** index to select **s3** readline **error_delayed**
=> fix(BankedDataArray): fix readline error_delayed selection

src/main/scala/xiangshan/backend/decode/VecDecoder.scala, src/main/scala/xiangshan/package.scala
* when use simple split type, instruction cannot send to complex decoder and not do the exception check
* vs dirty is setted when split type is not simple
=> fix(uopsplit): set vector instructions never use simple split type

src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
Only if `dataBuffer.io.enq.fire` is considered to have `deq`
=> fix(StoreQueue): fix the `vecExceptionFlag` setting condition

src/main/scala/xiangshan/cache/dcache/data/BankedDataArray.scala, src/main/scala/xiangshan/cache/dcache/loadpipe/LoadPipe.scala
This modification changes `load bank conflict` from [default priority 0 1 2] to [so that the oldest Load does not have a `bank conflict`].
In the following, `Load 0` refers to `LoadUnit 0`.
For example, before:
Load 0 lqidx 5 
Load 1 lqidx 3
Load 2 lqidx 8
Assuming that three Loads have `bank conflict`, then we will default to making Load1 and Load2 have `bank conflict` so that they can be replayed.
---
However, this may lead to deadlocks in some cases.
For example:
Load  0 robidx 7
Store 0 robidx 6
Load  1 robidx 5
`Store 0` is dependent on `Load 1` for data, while `Load 0` is dependent on `Store 0` for data, and `Load 0` and `Load 1` will have a `bank conflict`.
In this case then, `Load 1` will `Replay` because of `bank conflict` and `Load 0` will `Replay` because of `forward …
=> fix(bank_conflict): Selecting the oldest Load causes a conflict

src/main/scala/xiangshan/frontend/IFU.scala
Skip `m_waitLastCmt` & `m_waitCommit` state if `f3_itlb_pbmt === Pbmt.nc`, as these memory spaces are idempotent and in which we can do speculative inst fetch.
=> feat(IFU,Svpbmt): allow speculative fetch in pbmt.NC (idempotent) spaces

src/main/scala/xiangshan/mem/lsqueue/LoadQueueReplay.scala, src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
Previously, I used an inappropriate way for another misalign to trigger a `forward fault`:
https://github.com/OpenXiangShan/XiangShan/blob/38d0d7c5a34a23dfdb58a3cb2737c3cfddb3ec9d/src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala#L684-L711
This would cause the `BlockSqIdx` passed to `LoadQueueReplay` to use the `sqIdx` from `uop` instead of the `sqIdx` with the unalign flag bit:
https://github.com/OpenXiangShan/XiangShan/blob/38d0d7c5a34a23dfdb58a3cb2737c3cfddb3ec9d/src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala#L776-L782
**This leads to a possible stuck in `LoadQueueReplay`.**
And to resolve the stuck, we incorrectly introduced this Commit(af757d1b973e03dae3ce0078a4a8249b593188ec).
This Commit(af757d1b973e03dae3ce0078a4a8249b593188ec) causes `BlockSqIdx` to unblock without …
=> fix(LSQ): modify misaligned `forward fault` detection

src/main/scala/xiangshan/cache/dcache/data/BankedDataArray.scala
Changes in this Commit(8ffb12e45361b854daf46d200530e9b2b01e4a9c) will make: 
In this case, there will be multiple replay: ldu0,1,2's lqptr= [5,7,6], bank_conflict only in ldu1 and ldu2. Ideally only replay ldu1, but here both ldu1 and ldu2 will replay.
This mod fixes the issue and theoretically performance will improve again.
=> fix(BankedDataArray): fix `oldest` selection logic

.github/workflows/format.yml, src/main/scala/xiangshan/mem/MemCommon.scala, src/main/scala/xiangshan/mem/lsqueue/StoreMisalignBuffer.scala, src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala, src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala, src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala
1. Fixed some exception handling logic for misalign access.
2. removed redundant registers in StoreQueue, roughly ‘9*64’ bits.
---
Forgive me for combining these two parts, as the changes to `1` are related to the changes to `2`.
=> fix(MemBlock): fix misaligned exception and remove redundant reg from `SQ`

.github/filters.yaml, .github/workflows/format.yml
Github automatically updates ubuntu-latest from 22.04 to 24.04, which does not contain .local at the home directory anymore.
=> ci(check-format): make sure ~/.local/bin exists

src/main/scala/xiangshan/backend/fu/PMA.scala
Currently, we require that a `PMA` can generate an mmio response only if the address has the appropriate `PMA` permissions.
---
As per `Fei Ge` wishes, a refactoring of PMA/PMP may follow to make the checking and maintenance of permissions more concise and complete.
=> fix(PMA): report `MMIO` only when you have permission

src/main/scala/xiangshan/frontend/newRAS.scala
During reset, the update registers related to the return stack are not reset. At the same time, the update of the update register value is subject to some signal restrictions, resulting in the BOS pointer being updated incorrectly with the old value.
=> fix(RAS): bos pointer needs to be updated when the instruction is committed

src/main/scala/xiangshan/Parameters.scala, src/main/scala/xiangshan/cache/dcache/data/BankedDataArray.scala, src/main/scala/xiangshan/cache/dcache/meta/TagArray.scala, src/main/scala/xiangshan/mem/prefetch/SMSPrefetcher.scala
power optimization：
(1) use “withClockGate” instead of  ClockGate in DCache
(2) reduce LSQ entries
=> power(MemBlock): power optimization in MemBlock 

src/main/scala/xiangshan/backend/fu/NewCSR/Debug.scala, src/main/scala/xiangshan/backend/fu/NewCSR/InterruptFilter.scala, src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala, src/main/scala/xiangshan/backend/fu/NewCSR/PMPEntryModule.scala, src/main/scala/xiangshan/backend/fu/NewCSR/TrapHandleModule.scala, src/main/scala/xiangshan/backend/fu/wrapper/CSR.scala
* Currently we support 61 major interrupts, and 8 bits are sufficient. 
* There is no need to use 64 bits to store the intermediate data of the `interrupt NO`.
* In order to save area, we only need to add 1 cycle to `wen`, not `waddr` and `wdata`.
=> area(csr): fix intr NO bits and remove reg for waddr/wdata

src/main/scala/xiangshan/mem/lsqueue/LoadQueueUncache.scala
bug scene:
When the valid vector of ldu0-2 is [0, 0, 1], and the freelist can only allocate one entry (when the `canAllocate` vector is [1, 0, 0]), the ldu2's request can not be allocated and then be rollbacked. This is because the allocation did not take into account the valid offset.
=> fix(LQUncache): consider offset when allocating

src/main/scala/xiangshan/cache/dcache/mainpipe/MissQueue.scala
- Latency of < 100 is not enough for performance analysis
- To reduce outputs, use larger bucket (30 per bucket)
=> feat(XSPerf): count histogram of larger Ld-to-use latency

src/main/scala/xiangshan/cache/dcache/loadpipe/LoadPipe.scala
* disable s1 permission check at s1 in LoadPipe for timing before.
=> fix(LoadPipe): enable s1 permission check for prefetch_w

src/main/scala/xiangshan/backend/MemBlock.scala, src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala, src/main/scala/xiangshan/cache/dcache/data/BankedDataArray.scala, src/main/scala/xiangshan/cache/dcache/meta/TagArray.scala
* CacheOpDecoder  is no longer used
=> area(CacheOpDecoder): remove CacheOpDecoder

src/main/scala/xiangshan/mem/lsqueue/LoadQueue.scala, src/main/scala/xiangshan/mem/lsqueue/LoadQueueRAR.scala, src/main/scala/xiangshan/mem/lsqueue/LoadQueueRAW.scala
Vector Load's additional release logic in the `RAR/RAW Queue` looks unneeded, which would result in the `RAR/RAW Queue` storing redundant `regs` for `uopidx`.
=> area(LoadQueue): remove useless regs

src/main/scala/xiangshan/Parameters.scala
For vectors, if the size of the `RAR` is not equal to the `VLQ`, it can lead to a jam. This is because:
A `uop` of a vector splits into multiple Load operations and occupies multiple `VLQ`. The release condition of the `RAR` is that the `VLQ` are dequeue, whereas the vector requires that all Load operations of the `uop` are written back to the `MergeBuffer` before the `VLQ` can be let out of the queue. 
Therefore, it may happen that when the deqptr of `VLQ` waits for vector `uop` to write back all, but the `RAR` is already full, the Load operation split by vector `uop` can not enter the `RAR`, so it will wait in the `ReplayQueue` for the `RAR` to be non-full, and the `RAR` can not be released because `VLQ` can not get dequeue, which leads to deadlock.
=> fix(LoadQueueRAR): aligning the size of `RARSize` to `VLQSize`

src/main/scala/xiangshan/mem/lsqueue/LSQWrapper.scala, src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala, src/main/scala/xiangshan/mem/lsqueue/VirtualLoadQueue.scala
The addition used previously to calculate the `lsq` pointer results in overflow, this is because, the bit width of `numLsElem` is 5 and multiple uop accumulations result in data overflow.
---
Theoretically this would have been a problem in previous versions as well, but for some reason the bug didn't occur in previous versions until `newDispatch`.
=> fix(MemBlock): fix overflow during lsqptr calculation

src/main/scala/xiangshan/frontend/NewFtq.scala
The start of the first instruction can be the second 2-byte of the entry.
=> fix(FTQ): start of the first instruction in an entry

src/main/scala/xiangshan/mem/lsqueue/VirtualLoadQueue.scala
* remove datavalid, addrvalid, veccommitted
* add committed
=> area(VirtualLoadQueue): remove useless regs

src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala
In PTW/LLPTW/HPTW, mem.resp.fire is set in first cycle, but mem.resp.data comes in second cycle. The signal full_gvpn depends on mem data, but it is incorrectly updated in first cycle, retrieving the old value. This leads to an in correct GPF.
This patch tries to fix this problem. It splits full_gvpn into wire and reg, and introduces a new signal to control the update of reg and the selection between wire and reg.
=> fix(PTW): incorrect GPF due to timing mismatch

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
1. Only if no `pf/af` occurs can it be considered a `mmio`. Thus allowing a non-aligned Load to generate a misalign exception.
The store also suffers from this problem, but I will modify `StoreUnit` later in some other way
2. Prefetching shouldn't produce non-alignment, and I previously placed the logic for prefetching processing in the wrong place.
=> fix(LoadUnit): fix Load misalign related bugs

src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala, src/main/scala/xiangshan/cache/dcache/mainpipe/MissQueue.scala, src/main/scala/xiangshan/mem/pipeline/HybridUnit.scala, src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
When DCache refill reponses with `denied` or `corrupt` asserted, the loads belonging to the cache line should report load access fault. This is accomplished by including a `corrupt` bit in the DCache MSHR forwarding and TileLink channel D forwarding logic and triggering excepion when `corrupt` is detected.
Store non-data error that comes from DCache store miss is unable to trigger a precise access fault trap but an imprecise bus-error interrupt. And it will be included in another commit.
=> fix(MemBlock): support non-data error handling for cacheable region

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
Currently, when `RAW` is full, a `RAW nack` is generated, which leads to `LoadQueueReplay`.
And when `RAW` is non-empty, commands are reissued from `Replay`.
Currently, a load instruction goes into `LoadUnit` at `S2`, and then if an exception occurs, a `revoke` is generated at `S3`.
Therefore, this will happen:
`RAW` has only one item remaining.
The instructions in `LoadQueueReplay` are sent to `LoadUnit1`.
The Load instruction also exists in `LoadUnit0`, so `LoadUnit0` has access to `RAW`, while a Load in `LoadUnit1` produces a `RAW nack`.
And `LoadUnit0` and `LoadUnit1` would generate `bank conflict`, thus causing `LoadUnit0` to get to `S3` to generate a `fast replay` and `revoke`, which would result in `RAW` being non-full, which would result in `RAW in `LoadQueueReplay` nack` command …
=> fix(LoadUnit): `fastReplay` can only happen once

src/main/scala/xiangshan/mem/vector/VMergeBuffer.scala, src/main/scala/xiangshan/mem/vector/VSplit.scala
Now, we no longer have `inActive` is `unit-stride` sent to the pipeline.
This will fix some bugs caused by `inActive` not being handled properly in `LSU`.
And will theoretically result in some performance gains.
=> fix(VSplit): inactive elements of `UnitStride` are no longer executed

src/main/scala/xiangshan/backend/MemBlock.scala, src/main/scala/xiangshan/mem/vector/VMergeBuffer.scala, src/main/scala/xiangshan/mem/vector/VSplit.scala, src/main/scala/xiangshan/mem/vector/VecBundle.scala
To solve the stuckness caused by insufficient RAW, we use `threshold` to control the execution of vector instructions.
When the mergebuffer has few free entries than it can hold in the flow, we backpressure to make `IssueQueue` send the oldest `Uop` for us.
=> fix(VLSU): `mergebuffer` threshold was added

src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala
In previous PR #3968 added a new TL port for CMOUnit in MissQueue, but did not update the config for dcache client, which make CMOUnit and the first releaseEntry share the same sourceId. Now fix it.
=> fix(DCache): fix dcache TL client parameters

src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala, src/main/scala/xiangshan/backend/fu/NewCSR/Unprivileged.scala
* Since we only implement one time register to hold the value of `time`(used in non-virtual mode) and `time + htimedelta`(used in virtual mode), the value should be updated when virtual mode changes.
* Otherwise, when virtual mode changes and rtc clock tick does not assert, the value in `time` register does not match the current virtual mode.
=> fix(csr): update time reg when virtual mode changes

src/main/scala/xiangshan/mem/lsqueue/LoadQueueUncache.scala
**Old design**:
When enqueuing, it is in the order of ldu0-1, i.e. ldu0 is allocated first.
**Bug scene:**
LQUncacheBuffer is small. The enqueue `robIdx` of ldu0-1 is [57, 56, 55], the [57, 56] can enqueue, and [55] can not because buffer is full. 57/56 send the `NC` request after enqueuing. 55 is rollbacked. In principle, 57 and 56 need be flushed. But to ensure the correspondence between requests and responses of uncache, 57 is flushed when getting the uncache response. So when the same sequence [57, 56, 55] is coming, there is still no space to allocate 55, which causes that it is rollbacked again. Then a deadblock emerged.
This bug is triggered after cutting `LoadUncacheBufferSize` from 20 to 4.
**One way to fix**:
When enqueuing, it is in the order of `robIdx`, i.e. the oldest is …
=> fix(LQUncache): fix a potential deadblock when enqueue

src/main/scala/xiangshan/backend/fu/NewCSR/Unprivileged.scala
When virt mode changed, `time` should be updated because we may need a offset version with `htimedelta`. This commit delays a cycle to update `time` register because `v` is actually changed a cycle after `nextV =/= v`.
=> fix(Unprivileged): wait a cycle to update `time` when `nextV =/= v`

src/main/scala/xiangshan/backend/fu/NewCSR/HypervisorLevel.scala
For bits of mideleg that are zero, the corresponding bits in hideleg, hip, and hie are read-only zeros.
The VSSIP, VSTIP, VSEIP in mideleg are read-only ones when the H extension is implemented.
When the hypervisor extension is implemented, if a bit is zero in the same position in both mideleg
and mvien, then that bit is read-only zero in hideleg (in addition to being read-only zero in sip, sie,
hip, and hie). But if a bit for one of interrupts 13-63 is a one in either mideleg or mvien, then the same
bit in hideleg may be writable or may be read-only zero, depending on the implementation. No bits in
hideleg are ever read-only ones. The RISC-V Privileged Architecture further constrains bits 12:0 of
hideleg.
=> fix(hideleg): fix the read value of the LCOFI bit of hideleg.

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
1. `lqIdx` has less bit width.
2. for vectors, the `robIdx` is the same for multiple `flow`s. Previously, for vectors, we would additionally use `uopIdx` for judgement. But actually, in theory, we only need to use `lqIdx/sqIdx`.
Here we change the age judgement for vectors to `lqIdx` to ensure accurate age judgement. And change the age judgement of scalar to `lqIdx` as well to reduce the cost.
=> fix(LoadUnit): use `lqIdx` to determine age

src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
The line of code that was removed was written by me, but I can't now think of any reason at all why I would have added this incorrect line of code at the time. 
**The line of code doesn't seem to make any sense and only generates errors.** :sob:
=> fix(StoreQueue): remove the incorrect redirect logic

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
In the code that follows, overriding assignments exist below：
https://github.com/OpenXiangShan/XiangShan/blob/23767fc38e3f03726f910926add24b7f85db5eab/src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala#L1771-L1775
=> style(LoadUnit): removes redundant 'fast_rep_out' assignments

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
For `fast replay`, there is no need to request access to the `RAW/RAW Queue`.
This prevents the `RAW Queue` from constantly ping-ponging between `not full/full` due to `revoke`.
These two lines were removed because it would lead to combinatorial logic loops and it was an unwanted condition:
https://github.com/OpenXiangShan/XiangShan/blob/dfc474ebe17bbfb1bf2ec4cc122301a9c7998e09/src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala#L1269-L1270
---
Probably questions like this: https://github.com/OpenXiangShan/XiangShan/pull/4102
With the previous changes plus this one, i don't think a similar stuck will happen again. :raised_hands:
**This may result in some performance gains.**
=> fix(LoadUnit): `fast replay` no longer requests to `RAR/RAW Queue`

src/main/scala/xiangshan/cache/dcache/Uncache.scala
From TileLink SPEC 1.9.3 Chapter7 "TileLink Uncached Lightweight (TL-UL)":
* AccessAck: `d_corrupt` is reserved and must be 0.
* AccessAckData, `d_corrupt` being HIGH indicates that masked data in this beat is corrupt.
So it need consider both `d_denied` and `d_corrupt` when geting the data.
For uncache now, it complete in one beat, so there can execute `d_denied || d_corrupt` directly.
=> fix(uncache): consider both corrupt and denied when granting

src/main/scala/top/Top.scala
Without this commit, CHI messages cannot be correctly routed in multi-core scenarios, leading to simulation errors.
=> fix(XSTop): assign unique nodeID to each core

src/main/scala/xiangshan/backend/rob/Rob.scala
* This PR fix the boundary case where rob has redirect.
* The `needflush` signal should be `true` when rob flushes all entries.
* Co-authored-by: xiaofeibao-xjtu <59299641+xiaofeibao-xjtu@users.noreply.github.com>
=> fix(rob): fix needflush when rob has redirect

src/main/scala/device/RocketDebugWrapper.scala, src/main/scala/device/standalone/StandAloneDebugModule.scala, src/main/scala/top/Configs.scala
It is more straight-forward to use `DebugModuleParams` in `Config.scala`.
=> style(DebugModule): remove unnecessary `XSDebugModuleParams`

src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala, src/main/scala/xiangshan/backend/fu/NewCSR/SstcInterruptGen.scala
* The STIP signal is updated when:
* time.valid of clint
*   stimecmp CSR is written
*   menvcfg CSR is written
* The VSTIP signal is updated when:
*   time.valid of clint
*   vstimecmp CSR is written
*   htimedelta CSR is written
*   menvcfg CSR is written
*   henvcfg CSR is written
Co-authored-by: Xuan Hu <39661208+huxuan0307@users.noreply.github.com>
=> fix(CSR): fix xTIP update in sstcIRGen

src/main/scala/xiangshan/backend/fu/NewCSR/CSRPermitModule.scala, src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala
Before this, we assumed that all possible exceptions during CSR read and write operations should be handled according to their priority.
Therefore, we ensured that all illegal instruction exceptions take precedence over virtual instruction exceptions.
However, with the implementation of certain extensions like Smcsrind and Smstateen, we encounter scenarios where virtual instruction exceptions must take precedence over illegal instruction exceptions triggered.
For instance, when mstateen0.csrind is set to 1 and hstateen0.csrind is 0, a virtual instruction exception should be raised if VS mode attempts to access sireg. However, if the vsiselect value is reserved in this situation, an illegal instruction exception will be raised instead. If these checks are treated as being at the same …
=> feat(exception): divide the exceptions raised from CSR access into different sources.

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
when loadunit writeback
* **fpWen** uses register directly out
* **pdest** uses register directly out
=> timing(LoadUnit): fpWen and pdest reg out

build.sc
See https://mill-build.org/mill/fundamentals/tasks.html#_inputs.
=> fix(build): `gitStatus` should use `Task.Input`

.github/workflows/emu.yml, Makefile, build.sc, scripts/xiangshan.py, src/main/resources/config/Default.yml, src/main/scala/system/SoC.scala, src/main/scala/top/ArgParser.scala, src/main/scala/top/Configs.scala, src/main/scala/top/YamlParser.scala, src/main/scala/xiangshan/PMParameters.scala, src/main/scala/xiangshan/Parameters.scala, src/main/scala/xiangshan/XSCore.scala, src/main/scala/xiangshan/backend/fu/PMA.scala, src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala, src/main/scala/xiangshan/mem/prefetch/L1PrefetchComponent.scala, src/main/scala/xiangshan/mem/prefetch/L1PrefetchInterface.scala, src/main/scala/xiangshan/mem/prefetch/SMSPrefetcher.scala
This commit enables complicated parameterization by yaml parsing. We use circe to do this.
In this commit, we implement 6 configurations:
- PmemRanges: physical memory ranges
- PMAConfigs
- CHIAsyncBridge: set depth to 0 to disable it
- L2CacheConfig
- L3CacheConfig
- DebugModuleBaseAddr
For better human-readability, this commit changes `WithNKBL2/3` to `L2/3CacheConfig`, changing to case classes, and making the first parameter only accept human-readable size configuration like `0.5 MB` or `256KB`.
This commit also changes PMAConfigs and PmemRanges into List of case classes.
=> feat(Config): add yaml parser for complicated parametrization

.github/workflows/artifacts.yml, .github/workflows/emu.yml
Self-hosted runners sometimes fail to upload artifacts due to special network environment. To make use of free machines, we allocate a 10 GB swapfile to avoid oom failure.
=> ci(artifacts): use GitHub-hosted runner to generate and upload artifacts

src/main/scala/xiangshan/cache/mmu/Repeater.scala
ptwResp_OldMatchVec is not a one-hot vector, so we should use PriorityMux rather than OHToUInt.
=> fix(PTWRepeater): use PriorityMux for not one-hot vector

src/main/scala/top/Top.scala, src/main/scala/top/XSNoCTop.scala, src/main/scala/xiangshan/Bundle.scala, src/main/scala/xiangshan/L2Top.scala, src/main/scala/xiangshan/XSCore.scala, src/main/scala/xiangshan/XSTile.scala, src/main/scala/xiangshan/XSTileWrap.scala, src/main/scala/xiangshan/backend/Backend.scala, src/main/scala/xiangshan/backend/MemBlock.scala, src/main/scala/xiangshan/backend/datapath/DataPath.scala, src/main/scala/xiangshan/backend/decode/DecodeStage.scala, src/main/scala/xiangshan/backend/rob/Rob.scala, src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala, src/main/scala/xiangshan/cache/dcache/mainpipe/MissQueue.scala, src/main/scala/xiangshan/frontend/Frontend.scala, src/main/scala/xiangshan/frontend/IBuffer.scala, src/main/scala/xiangshan/mem/lsqueue/LSQWrapper.scala, src/main/scala/xiangshan/mem/lsqueue/LoadQueue.scala, src/main/scala/xiangshan/mem/lsqueue/VirtualLoadQueue.scala
This PR adds hardware synthesizable three-level categorized TopDown performance counters.
Level-1: Retiring, Frontend Bound, Bad Speculation, Backend Bound.
Level-2: Fetch Latency Bound, Fetch Bandwidth Bound, Branch Missprediction, machine clears, Core Bound, Memory Bound.
Leval-3: L1 Bound, L2 Bound, L3 Bound, Mem Bound, Store Bound.
=> feat(TopDown): add TopDown PMU Events

src/main/scala/xiangshan/backend/fu/NewCSR/CSRAIA.scala, src/main/scala/xiangshan/backend/fu/NewCSR/CSRPermitModule.scala, src/main/scala/xiangshan/backend/fu/NewCSR/HypervisorLevel.scala, src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala
Along the same lines, when hstatus.VGEIN is not the number of an implemented guest external interrupt, attempts from M-mode or HS-mode to access CSR vstopei raise an illegal instruction exception, and attempts from VS-mode to access stopei raise a virtual instruction exception.
=> fix(aia): add the missing AIA-related permission checks

.github/workflows/emu.yml, Makefile, src/main/scala/system/SoC.scala, src/main/scala/top/Configs.scala, src/main/scala/top/Top.scala, src/main/scala/top/XSNoCTop.scala
build(Makefile): support PLDM_ARGS for make verilog
For PLDM_ARGS, we make it consistent with DEBUG_ARGS by default. User can set PLDM_ARGS in command line to extend it.
Examples as follows:
1. By set PLDM_ARGS="--fpga-platform" and PLDM=1, we will disable
XSLog(including PerfCounters) for both verilog and sim-verilog.
2. By set PLDM_ARGS="--diffest-config ESBINP" and PLDM=1, we can
accelerate Difftest in Palladium through some optimization feature.
-------------------
feat(XSNoCDiffTop): wrap XSNoCTop with Difftest Interface
To apply Difftest framework for CHI NoC, we wrapper lazy XSNoCTop inside XSNoCDiffTop when difftest enabled, and expose necessary soc/core/difftest IOs.
Currently we use two-step flow for CHI-NoC-XS as follow:
Step1. Generate single-core XSNoCDiffTop with …
=> feat(XSNoCDiffTop): wrap XSNoCTop with Difftest Interface

src/main/scala/xiangshan/cache/mmu/PageTableCache.scala
In the previous design, the `spRefill` signal will be true when the `refill.levelOH.sp` or `memPte(0).isNapot(refill.level_dup(0))` conditions is met, and acted as a control signal to control the refill of the sp entries. However, `memPte(0).isNapot(refill.level_dup(0))` does not determine whether `refill.level_dup(0)` is valid. When `refill.level_dup(0)` is X, it causes `spRefill` to also be X, which in turn causes X-prop.
This commit adds `refill.levelOH.l0` to `isNapot`. On the one hand, only `levelOH.l0` (4KB page) can be a Svnapot page; on the other hand, the assignment of `refill.levelOH.l0` takes `refill.valid` into account, thus avoiding X-prop.
=> fix(PTWCache): avoid X-prop of spRefill

src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala
Data selection logic should use signals in `s3` instead of `s1`, which is introduced in a former pr #4117.
=> fix(MainPipe): fix bug in data select of AMOCAS.Q

src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala, src/main/scala/xiangshan/cache/dcache/data/BankedDataArray.scala, src/main/scala/xiangshan/cache/dcache/loadpipe/LoadPipe.scala, src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala, src/main/scala/xiangshan/mem/vector/VSegmentUnit.scala
* `latchVAddr` needs to index all dcache data sram from top to bottom, which causes a large fanout, so duplicate `latchVaddr`
=> timing(VSegmentUnit): duplicate latchVAddr

src/main/scala/xiangshan/mem/vector/VMergeBuffer.scala, src/main/scala/xiangshan/mem/vector/VSegmentUnit.scala, src/main/scala/xiangshan/mem/vector/VSplit.scala, src/main/scala/xiangshan/mem/vector/VecBundle.scala
**Timing issue caused by too long address calculations for vector modules:**
- Solved by moving some of the logic to the previous cycle.
---
**Timing issue caused by long exception logic of load writeback to `VLMergeBuffer`:**
- Add one cycle to the load writeback exception, now the same number of cycles as the load write back data.
=> timing(VLSU): fix timing issues in `VLSU`

src/main/scala/xiangshan/frontend/icache/ICacheMissUnit.scala
> we can latch mshr.io.resp.bits since they are set on req.fire or acquire.fire, and keeps unchanged during response
> however, we should not latch mshr.io.resp.valid, since io.flush/fencei may clear it at any time
Old:
```
tilelink.resp.id -> | Reg | 
|
v
| MSHR0 |     ->    | --- |
| MSHR1 |     ->    | Mux | -> io.resp
|  ...  |     ->    |     |
| MSHRn |     ->    | --- |
```
New:
```
tilelink.resp.id 
|
v
| MSHR0 | -> | --- |
| MSHR1 | -> | Mux | -> | Reg | -> io.resp
|  ...  | -> |     |
| MSHRn | -> | --- |
```
Timing results are good, related path: slack -44ps -> positive.
=> timing(ICache): move mshr_resp selector 1 cycle ahead

src/main/scala/xiangshan/frontend/IFU.scala
When an override occurs in BPU S3 stage, the corresponding req can at most reach the IFU F0 stage.
=> fix(IFU): remove useless bpu override flush logic

src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala
The existence of `s2/s3_req.miss` in `atomic_resp_valid` will cause an error resp to AtomicsUnit by a normal refill_req from MissQueue. Remove it now to fix the problem.
=> fix(DCache): remove error wakeup signal for atomic resp

src/main/scala/xiangshan/frontend/ITTAGE.scala, src/main/scala/xiangshan/frontend/Tage.scala, src/main/scala/xiangshan/frontend/icache/ICache.scala
- Remove `mispred_mask` from ITTAGE update logic due to timing issues
- Remove `mispred_mask` from TAGE update logic due to timing issues
- Disable clock gating in ICacheDataArray to improve timing
=> timing(frontend): remove bad timing clock gating

src/main/resources/config/Default.yml, src/main/scala/system/SoC.scala
The previous PMA configuration was as follows, we should only remove useless GPU address space.
>     addPMA(0x0L, range = 0x1000000000000L, a = 3)
>     addPMA(PMPPmemHighBounds(0), c = true, atomic = true, a = 1, x = true, w = true, r = true) 
>     addPMA(PMPPmemLowBounds(0), a = 1, w = true, r = true) 
>     addPMA(0x3A000000L, a = 1)
>     addPMA(0x39002000L, a = 1, w = true, r = true)
>     addPMA(0x39000000L, a = 1, w = true, r = true)
>     addPMA(0x38022000L, a = 1, w = true, r = true)
>     addPMA(0x38021000L, a = 1, x = true, w = true, r = true)
>     addPMA(0x38020000L, a = 1, w = true, r = true)
>     addPMA(0x30050000L, a = 1, w = true, r = true) // FIXME: GPU space is cacheable?
>     addPMA(0x30010000L, a = 1, w = true, r = true)
>     addPMA(0x20000000L, a = 1, x = true, …
=> fix(Config): add the 'L3CacheCtrl' address space permission back

src/main/scala/top/Configs.scala
Previous this config set WithNKBL1D ways to 8, resulting in compile error. This change make it same as FPGADefaultConfig.
=> fix(FPGADiffDefaultConfig): set WithNKBL1D ways as default

src/main/scala/xiangshan/frontend/IFU.scala, src/main/scala/xiangshan/frontend/PreDecode.scala
When there is a jalr instruction in the middle of an instruction block but
the BPU fails to predict it, the IFU should adjust the length of the
instruction block to terminate at the jalr instruction. 
However, the IFU currently does not check for this scenario, which may 
result in the unintended execution of instructions following the jalr that 
should not have been executed. This PR fixed this issue.
=> fix(IFU): add range checking for instruction blocks containing jalr

src/main/scala/top/ArgParser.scala, src/main/scala/xiangshan/Parameters.scala
This change introduce XSPerfLevel, including `VERBOSE`/`NORMAL`/`CRITICAL`. Only counters with level greater or equal than threhold will be instantiated, which will reduce utilization and compile time on Pallaium.
PerfLevel therhold can be set in command line, `VERBOSE` by default to apply all counters.
An example usage as follows:
SIM_ARGS="--perf-level CRITICAL" or
PLDM_ARGS="--perf-level CRITICAL" PLDM=1
PerfLevel param is also `VERBOSE` by default, which means all counters will be ignored now if threhold greater than that. User can explicitly set params to keep some important counters instantiated, as follows: XSPerfAccumulate(xx, yy, perfLevel = XSPerfLevel.CRITICAL)
=> submodule(utility): introduce XSPerfLevel for performance counter

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
`prefetch.w` sends a write request to `TLB/PMA/PMP`.
As a result, `PMA/PMP` returns a permission check (`io.pmp.st`) for the write request.
---
Previously, we only handled the case where `prefetch.r` did not have read permissions, not handled  the case where  `prefetch.w` did not have write permissions.
**So, when `prefetch.w` has an address without write permissions, the request will still be sent to `Dcache`, which generates an error.**
**This pr fixes that, when `PMA/PMP` returns `io.pmp.st`, we generate `dcache.s2_kill`.**
=> fix(LoadUnit): `dcache_kill` if `prf_wr` has no permissions

src/main/scala/xiangshan/mem/lsqueue/StoreMisalignBuffer.scala
Assignment overwritten by forgetting to add `Otherwis`.
=> fix(StoreMisalignBuffer): fix state transition when writeback

src/main/scala/xiangshan/cache/CacheConstants.scala
Though CAS related operations are added in `MemoryOpConstants` in the previous pr #3958, the code concerning cache coherence is located in rocket-chip, which can only import `MemoryOpConstants` from rocket-chip. Therefore, CAS related code is moved to rocket-chip in this commit.
=> submodule(rocket-chip): bump rocket-chip

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
when `io.dcache.req.ready` is false, misalign load will be stall, but `wakeup`  still work normally and is not canceled in `s3`, which will cause the backend to get wrong data.
=> fix(LoadUnit): fix  misalign load wrong wakeup

src/main/scala/xiangshan/frontend/icache/ICache.scala
=> timing(icache): restore the relaxation of ICG for icache data

src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala
* When inject tag ecc error `io.pseudo_error.valid  == 1` and mainpipe request valid (for example `io.miss_req.valid == 1`
```
val s1_need_replacement = s1_req.miss && !s1_tag_match
val s1_need_eviction = s1_req.miss && !s1_tag_match && s1_repl_coh.state =/= ClientStates.Nothing
val s1_way_en = Mux(s1_need_replacement, s1_repl_way_en, s1_tag_match_way)
```
when generate `s1_way_en`,  `s1_tag_match == 0` cause inject tag ecc error, so `s1_need_replacement == 1`, but may be target cacheline already in dcache (for example `prefetch.w` miss), finally there is 2 same paddr cacheline in dcache, obviously this is illegal.
* Determine whether it is a pseudo error. If it's pseudo error, use no-toggled-tag (which no toggled by cacheCtrl) for generate `s1_way_en`, otherwise use toggled-tag
=> fix(MainPipe): fix `s1_way_en` generate logic when ecc inject occur

src/main/scala/xiangshan/mem/lsqueue/StoreMisalignBuffer.scala, src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala
There is no exception misaligned store instruction  enters the misalignbuffer. Due to the exception timing difference generated by the `PMA`, the timing of the misalignbuffer rejection condition is bad timing, which in turn leads to the bad timing of `feedback_slow.hit`.
=> timing(STU, StoreMisalignBuffer): adjust misalign buffer enq logic

src/main/scala/device/MemEncrypt.scala, src/main/scala/device/MemEncryptUtil.scala, src/main/scala/system/SoC.scala, src/main/scala/top/Configs.scala, src/main/scala/xiangshan/Bundle.scala, src/main/scala/xiangshan/PMParameters.scala, src/main/scala/xiangshan/Parameters.scala, src/main/scala/xiangshan/backend/fu/NewCSR/CSRDefines.scala, src/main/scala/xiangshan/backend/fu/NewCSR/CSREvents/CSREvent.scala, src/main/scala/xiangshan/backend/fu/NewCSR/MachineLevel.scala, src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala, src/main/scala/xiangshan/backend/fu/PMP.scala, src/main/scala/xiangshan/backend/fu/util/CSRConst.scala, src/main/scala/xiangshan/backend/fu/wrapper/CSR.scala, src/main/scala/xiangshan/cache/mmu/BitmapCheck.scala, src/main/scala/xiangshan/cache/mmu/L2TLB.scala, src/main/scala/xiangshan/cache/mmu/MMUBundle.scala, src/main/scala/xiangshan/cache/mmu/MMUConst.scala, src/main/scala/xiangshan/cache/mmu/PageTableCache.scala, src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala, src/main/scala/xiangshan/frontend/Frontend.scala, src/main/scala/xiangshan/mem/MemBlock.scala
- Add bitmap module in MMU for memory isolation
- Add memory encryption module based on AXI protoco
- Can don't using these modules by setting the option `HasMEMencryption` & `HasBitmapCheck` to false
=> feat(bitmap/memenc): support memory isolation by bitmap checking and memory encrpty used SM4-XTS

src/main/scala/xiangshan/Parameters.scala, src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
Previously, `ForceWrite` was conditioned to write dead (60, 55), which no longer applies after we adjusted `StoreQueueSize`.
---
Now a more reasonable parameterized setting is used. 
However, the conditions for optimal performance still need to be tested.
=> fix(StoreQueue): fix threshold condition for fore write sbuffer

src/main/scala/xiangshan/backend/dispatch/NewDispatch.scala, src/main/scala/xiangshan/cache/dcache/Uncache.scala, src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala, src/main/scala/xiangshan/mem/lsqueue/VirtualLoadQueue.scala, src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala
Previous in PR#3982, we support collecting XSLogs to LogPerfEndpoint. However with --enable-log, we should also collect some missing XSDebug.
This change move these missing XSDebug outside WhenContext, and add WireInit to LogUtils' apply, to enable probing some subaccessed data, like a vec elem with dynamic index.
=> submodule(utility), XSDebug: support collecting missing XSDebug

src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala
* reduce meta/tag read enable generate logic
* when `set_conflict == 1`, request can not go to `s1`, and `write` has higher priority to `read`
=> timing(MainPipe): remove `set_conflict` for tag/meta read

Makefile, src/main/scala/system/SoC.scala, src/main/scala/top/ArgParser.scala, src/main/scala/top/Top.scala, src/main/scala/top/XSNoCTop.scala, src/main/scala/xiangshan/L2Top.scala, src/main/scala/xiangshan/XSTile.scala, src/main/scala/xiangshan/XSTileWrap.scala
This commit supports a configurable extra TileLink bus for DebugModule besides the peripheral device bus. This involves all 3 environments including TileLink-XSTop, CHI-XSTop, CHI-XSNoCTop. The feature is disabled by default. To enable it, you can add `SEPERATE_DM_BUS=1` in the make command line.
=> feat: support seperate DebugModule TileLink bus

src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
For misalign store that crosses 16-byte boundary, a store would write sbuffer twice in one cycle but only takes up one SQ entry. If there is only one misalign store in SQ, `isCboZeroToSbVec`, which is used to check if there is any cbo.zero written to sbuffer based on `fuOpType` in `uop`, may apply wrong `fuOpType` in an empty SQ entry, or lead to X-state propogation in VCS simulaition.
=> fix(StoreQueue): cbo.zero is written to sbuffer only if allocated

src/main/scala/xiangshan/mem/lsqueue/LoadQueueRAR.scala, src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
* Because of `LoadQueueRARSize == VirtualLoadQueueSize`, so no need to add additional logic for rar enq
* When no need fast replay, loadunit allocate raw entry
=> timing(LoadQueueRAR, LoadUnit): adjust rar/raw query logic

src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala
Following lr should be blocked when previous lr's resv_set is still valid, which means `lrsc_count > 0`.
In previous PR #3017 and #4117, `lrsc_count > 8` is used as block condition, and stop update `lrsc_count` when it reaches 8, fix it now.
=> fix(DCache): fix wrong condition for blocking lr

src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala
* When there are multiple errors，`Mux1H` is equivalent to using `|`,  for example 
* error 0, valid = 1, addr0 = 0x1000
* error 1, valid = 1, addr1 = 0x0ffff
* the result is `io.error.valid == 1`, but `io.error.bits.addr == (addr0 | addr1)`,  cause `Mux1H` will generate circuit like this:
```
addr = (valid0 ? addr0 : 'h0) |
(valid1 ? addr1 : 'h0)
```
* This problem can be avoided by using `ParallelMux`
=> fix(DCache): use `ParallelMux` instead of `Mux1H`

build.sc
Since #4312 merged, we need sourcecode library as an ivy dependency.
This library will no longer be included in chisel, see: https://github.com/chipsalliance/chisel/pull/3855
=> deps: add ivy dependency for sourcecode library

.github/workflows/perf.yml
The workflow uses `date +'%V'` to get the week number, but the ISO week number has a leading zero, which is interpreted as an octal number by bash. This caused errors in weeks 08 and 09, which went unnoticed previously.
This patch fixes the issue by using `10#$(date +'%V')` to force the number to be interpreted as decimal.
=> ci: fix date error in performance regression

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
`s0_src_valid_vec` is not `s0_src_select_vec`, and bit corresponding to `s0_src_valid_vec` is valid when any of the inputs `valid`. Therefore, `misalign wakeup` needs to globally control `s0_valid`.
=> fix(LoadUnit): misalign wakeup should not set s0 valid

src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala
* `s2_fire` and `s2_can_to_s3` are different 
* `io.error.valid` uses `s2_fire`, but `s3_l2_error` uses `s2_can_to_s3`, causing `io.error.valid` to be updated, but `s3_l2_error` not to be updated.
=> fix(MainPipe): fix `s3_l2_error` and `s3_error` enable signal

src/main/scala/xiangshan/mem/lsqueue/LoadQueueRAR.scala, src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
* In order to ensure timing, the RAR enqueue conditions need to be compromised, worst source of timing from `pmp` and `missQueue`.
* if `LoadQueueRARSize` == `VirtualLoadQueueSize`,  just need to exclude prefetching.
* if `LoadQueueRARSize` < `VirtualLoadQueueSize`, need to consider the situation of `s2_can_query`
=> fix(LoadUnit): exclude prefetch requests

src/main/scala/xiangshan/mem/MemBlock.scala, src/main/scala/xiangshan/mem/lsqueue/LSQWrapper.scala, src/main/scala/xiangshan/mem/lsqueue/LoadQueue.scala, src/main/scala/xiangshan/mem/lsqueue/LoadQueueRAR.scala, src/main/scala/xiangshan/mem/lsqueue/LoadQueueReplay.scala, src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
Since a load instruction that cross 16Byte needs to be split and accessed twice, it needs to enter the `RAR Queue` twice, but occupies only one `virtual load queue`, so in the extreme case it may happen that 36 load instructions that span 16Byte fill all 72 `RAR queues`.
---
There is some problem with our previous handling; if the oldest load instruction spanning 16Byte enters the `replayqueue` and at the same time there exists an instruction in the `loadmisalignbuffer` that can't finish executing because the `RAR Queue` is full, then the oldest load instruction is never cannot be issued because the `loadmisalignbuffer` has instructions in it all the time.
---
Therefore, we use a more violent scheme to do this.
When the RAR is full, we let the misaligned load generate a rollback, and the …
=> fix(LSU): misaligned violation detection stuck

src/main/scala/xiangshan/backend/fu/NewCSR/CSROoORead.scala
Since CSR VTYPE is not renamed (VL is renamed), the instruction CSRR with VTYPE cannot be executed out-of-order.
=> fix(CSR): add VTYPE to in-order read CSRs

src/main/scala/system/SoC.scala, src/main/scala/top/Configs.scala, src/main/scala/top/Top.scala
In order to be compatible with st's environment, the fpga difftest project in tilelink is generated in the same way as noc top, which leads tilelink top and difftest signals to difftop together
=> config: add fpga diff top on tilelink for diff_top

scalastyle-config.xml, scalastyle-test-config.xml
This follows code spec on yuque on best effort and hopefully make use of IDE warning
Checks:
- License: always starts with XiangShan license, I'm using `//` instead of `/**/` since most repositories I've seen does this
- File size: avoid large files, classes, lines, methods
- Tabs, new lines, and spaces: use correctly at EOF/EOL/around operators
- Imports: avoid block/wildcard imports (except `chisel3._` and `chisel3.util._`)
- Names:
- UpperCamelCase for classes, objects, constants, methods (when use as constants)
- lowerCamelCase for variables, parameters, methods\
- pure lower case for packages
=> chore(scalastyle): complete rewrite configuration

src/main/scala/xiangshan/cache/mmu/L2TLB.scala
The Reg `hptw_bypassed` is used to indicate a hptw's mem response no need to refill PTWCache.
So add condition `from_hptw(mem.d.bits.source)` for `hptw_bypassed` used in `refill_valid`,
to fix bug of Reg `hptw_bypassed` wrongly killing refill request from another ptw.
=> fix(L2TLB): fix `hptw_bypassed` wrong used in `refill_valid`

src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala
- When `HasBitmapCheck` is enabled in `CVMConfig`.
- PTW module checks whether a bitmap check(`whether_need_bitmap_check`) is needed after receiving a `mem.resp` .  then set `s_llptw_req` to be valid and send a request to LLPTW. 
- However, the `s_llptw_req` signal becomes valid one cycle too early.
=> fix(Bitmap): Fix early `s_llptw_req` trigger in PTW

src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala
`sc` miss are treated as failures directly and are no longer sent to the `missqueue`.
The meta is no longer updated when `sc` fail.
=> fix(MainPipe): `DCache` meta is not changed by the `sc/cas` that fails

src/main/scala/xiangshan/cache/mmu/TLB.scala
In the previous design, since we don't flush pipeline after modifying `satp`, we need to set whether or not increase the delay for different signals in the csr bundle, such as priv and satp, respectively.
Currently, CSR will add send redirect signal to refresh the pipeline after modifying `satp`, so we can unify latency in different CSR bundles to fenceDelay.
=> fix(MMU): Unify latency in different CSR bundles

src/main/scala/xiangshan/cache/mmu/MMUConst.scala, src/main/scala/xiangshan/cache/mmu/PageTableCache.scala
In the previous design, since we stored asid/vmid and vaddr information in SRAM, it was not possible to simply read out all the information in a single cycle for comparison with the parameters of sfence/hfence. As a result, for L2 TLB entries, we ignored the rs1/rs2 parameters passed by sfence/hfence and instead flushed all valid entries, regardless of asid/vmid or vaddr.
However, this caused unnecessary flushing of a large number of entries during process switching in virtualized environments, leading to L2 TLB misses after a process switch. This forced the processor to perform a page table walk in memory again, negatively impacting performance.
In this commit, asid/vmid and vaddr are hashed and stored in the register file. When an sfence/hfence signal is received, these stored values …
=> feat(PTWCache): Support a more precise flush for L2 TLB entries

src/main/scala/xiangshan/backend/CtrlBlock.scala
* When the high address bits check of jump target causes an exception, the valid signal of redirectGen is valid.
=> fix(reidrectGen): fix redirectGen valid signal

src/main/scala/xiangshan/backend/fu/NewCSR/CSROoORead.scala, src/main/scala/xiangshan/backend/rename/Rename.scala
* AIA registers are designed to be access asynchronously, so newCSR will wait for response. Therefore, CSRR instruction read mireg/sireg/vsireg inOrder.
=> fix(csr): CSRR instruction read xireg inOrder

src/main/scala/xiangshan/cache/mmu/L2TLB.scala, src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala
In the previous exception handling in LLPTW, both isAf and isGpf were checked for all cases, including allStage, onlyStage1, and noS2xlate.
In fact, for allStage, only isPf & isGpf needs to be checked, while for onlyStage1 and noS2xlate, only isPf & isAf should be checked.
This commit fixes this issue.
=> fix(LLPTW): Fix exception judgement for different virtualisation stages

src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala
* There were errors in the previous design
* `writeback` generate wrong addr
* `writeback`'s addr use `s3_tag` to generate , no need to use `s3_tag_error` to select. 
* `error` generate wrong addr
* `error` must use `s3_tag` to generate, not use `s3_req.addr`,
*  because the enable condition of `s3_req.addr` is different from that of `s3_error`,
* should use access cacheline corresponding address
=> fix(MainPipe):  `error` and `writeback` addr generate logic

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
I didn't REVIEW this pr(https://github.com/OpenXiangShan/XiangShan/pull/4326) carefully. :skull:
It resulted in a change in the semantics of the modification.
---
The loadAddrMisaligned exception is generated when misaligned accesses uncache space.
---
A misaligned load sets a loadAddrMisaligned exception at the s0 flag to ensure that it only enters the loadmisalignbuffer and has no other side effects.
So it will prevent s2_uncache from spawning properly.
Previously we used an additional `s2_un_misalign_exception` to flag this.
Now, after examining the semantics of s2_uncache, the semantics of s2_uncache can be appropriately represented by directly removing the excepiont related signals
=> fix(LoadUnit): fix misalign exception and clearer uncache semantics

scripts/top-down/configs.py, scripts/top-down/draw.py
The flushed Inst is counted in two ways, including a hardware accumulation counter and a software script counting uOPs that exceed the length of the checkpoint. Due to indentation issues, the latter one is not correctly calculated.
This pull request accomplishes the following:
* fix bad speculation instructions calculation.
* add vector freelist stalls, which are already supported by hardware perf counters but are not analyzed by software scripts.
=> fix(scripts): fix calculation of `BadSpecInst` in topdown scripts.

src/main/scala/xiangshan/backend/decode/DecodeUnitComp.scala, src/main/scala/xiangshan/backend/dispatch/NewDispatch.scala
Re-split uops to avoid stalls caused by renaming when rd and rs2 are the same.
When rd and rs2 are the same, uop1'src will wait uop0'dest after rename, which cause stalls.
In this commit, we set src2 in uop0 and dest in uop1, avoiding stalls by renaming.
=> fix(amocas): re-split uops for amocas to avoid stalls

src/main/scala/xiangshan/backend/decode/DecodeUnitComp.scala
when rd is equal to rs1, uop1 will write rd, while uop2 and uop3 of amocas.q need rs1 as src, which cause a RAW stalls.
However, rs1, the address of load and store, is used in uop1, we donot need rs1 in other uops.
=> fix(amocas): fix amocas.q to avoid stalls

scalastyle-config.xml
e.g.
```scala
some_wire :=
super && loooooooooooooooooong && logic ||
other && logic
```
=> chore(scalastyle): allow newline after operators

src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala
In the previous design, every time a page table entry was fetched from memory, a PMP check was performed on the physical address of the next-level page table. However, for cases requiring Stage-2 address translation or when a page fault occurs during the page table fetch, a PMP check is unnecessary. Performing a PMP check in these cases could lead to false access fault reports. This commit fixes the issue.
Future work: The current exception handling logic is messy and unsustainable. A complete refactor of this code is needed in the future, rather than continuing to add patches.
=> fix(PTW): Fix exception handle logic when both pf and af occur

src/main/scala/xiangshan/cache/mmu/PageTableCache.scala
ppnLen: PaddrBits - Offset = 48 - 12 = 36
gvpnLen: GVaddrBits - Offset = 50 (Sv48x4) - 12 = 38
When hypervisor extension implemented, PPN length should be gvpnLen rather than ppnLen
=> fix(PTWCache): length of PPN should be gvpnLen when hypervisor

src/main/scala/xiangshan/cache/mmu/MMUBundle.scala
Actually, the bit-width of s1ppn is sectorppnLen, which is defined as PaddrBits(48) - Offset(12) - TLB compression(3). In contrast, the L2 TLB returns item.s1.entry.ppn with a bit-width of sectorptePPNLen, which equals ptePaddrLen(56) - Offset(12) - TLB compression(3).
The part of the PPN beyond PaddrBits is only used to generate gpaddr when a guest page fault occurs, so it isn’t stored in the L1 TLB entry. Here, we simply assign the lower (sectorppnLen - 1, 0) bits. In fact, the original implementation would also work correctly, as it automatically truncates the lower bits of item.s1.entry.ppn and assigns them to s1ppn.
TODO: Not storing gpaddr (the upper PPN bits) in the L1 TLB currently provides minimal benefits and significantly increases the complexity, scalability, and …
=> fix(TLB): L1 TLB will not save the high bit of PPN

src/main/scala/xiangshan/cache/mmu/TLB.scala
Pre af/pf/gpf means the exceptions before real translating, such as high bits exception. There is some mistakes in choosing the translation mode, which may causes problems in which different mode are used for Non-virt S-stage and Virt VS-Stage.
This patch fixes the problems by smallest changes. There is too many debts in L1TLB.
=> fix(MMU): incorrect check for pre af/pf/gpf

src/main/scala/xiangshan/backend/dispatch/NewDispatch.scala
When instruction is fused, the fromRename.valid is false. It is taken as an invalid uop which not fire in Dispatch's TopDown logic.
However, the fused instruction is attached to the previous instruction. So the fused instrduction's topdown should be same with the previous one.
Statistic example:
XS' master branch runs SPEC CPU2017's cactuBSSN_128179 checkpoint, 20M for warmup and 20M for sampiling. 
The sampling phase's TopDown's "NoStall":
1. before-fix: 17892923, less than commitInstr
2. after-fix: 20020602, more than commitInstr
=> fix(topdown): when instr fused, take it as NoStall

src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala
when pageFault or ppn_af valid, it means that an exception occurs when Stage1 translation. So should not check high bits of gvpn(Stage2 check)
=> fix(PTW): Should not do gvpn check when pageFault or ppn_af

src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala
In previous design, we always use `ptes(index).getPPN()` to generate PPN for last G-stage translate. However, when VS-Stage is napot, we should use the low 4 bits of vpn for generating ppn.
=> fix(LLPTW): Should consider napot scenario when allStage

src/main/scala/xiangshan/Bundle.scala, src/main/scala/xiangshan/XSCore.scala, src/main/scala/xiangshan/backend/CtrlBlock.scala, src/main/scala/xiangshan/cache/L1Cache.scala, src/main/scala/xiangshan/frontend/BPU.scala, src/main/scala/xiangshan/frontend/FTB.scala, src/main/scala/xiangshan/frontend/FauFTB.scala, src/main/scala/xiangshan/frontend/Frontend.scala, src/main/scala/xiangshan/frontend/FrontendBundle.scala, src/main/scala/xiangshan/frontend/IBuffer.scala, src/main/scala/xiangshan/frontend/IFU.scala, src/main/scala/xiangshan/frontend/ITTAGE.scala, src/main/scala/xiangshan/frontend/NewFtq.scala, src/main/scala/xiangshan/frontend/PreDecode.scala, src/main/scala/xiangshan/frontend/PrunedAddr.scala, src/main/scala/xiangshan/frontend/RAS.scala, src/main/scala/xiangshan/frontend/SC.scala, src/main/scala/xiangshan/frontend/Tage.scala, src/main/scala/xiangshan/frontend/icache/ICache.scala, src/main/scala/xiangshan/frontend/icache/ICacheMainPipe.scala, src/main/scala/xiangshan/frontend/icache/IPrefetch.scala, src/main/scala/xiangshan/frontend/icache/InstrUncache.scala, src/main/scala/xiangshan/frontend/icache/WayLookup.scala, src/main/scala/xiangshan/frontend/newRAS.scala, src/test/scala/xiangshan/frontend/FrontendTrigger.scala
According to RISC-V specification, the least significant 1 or 2 bits (depending on whether the C extension is enabled or not) are hardwired to zero. Therefore, these bits can be pruned to save area.
This PR prunes almost all the addresses in the frontend, except those related to the backend. The backend should also use `PrunedAddr` instead of plain `UInt`. Some of these places have been labeled with FIXME or TODO in the code.
Apart from this, there are several other things that need attention:
* Line 351 of SC.scala appears to have a historical that needs to be fixed.
* `>>` of `PrunedAddr` should be removed to avoid confusion. This is mostly used to calculate tags, which can be rewritten as selecting corresponding bits.
* Implicit conversion of Scala has been attempted. However, the …
=> refactor(frontend): prune the least significant bit of PC

src/main/scala/xiangshan/Parameters.scala, src/main/scala/xiangshan/backend/Bundles.scala, src/main/scala/xiangshan/backend/CtrlBlock.scala, src/main/scala/xiangshan/backend/decode/DecodeUnit.scala, src/main/scala/xiangshan/backend/dispatch/NewDispatch.scala, src/main/scala/xiangshan/backend/fu/FuType.scala, src/main/scala/xiangshan/backend/rename/CompressUnit.scala, src/main/scala/xiangshan/backend/rename/Rename.scala, src/main/scala/xiangshan/backend/rob/Rob.scala, src/main/scala/xiangshan/backend/rob/RobBundles.scala, src/main/scala/xiangshan/backend/trace/Trace.scala, src/main/scala/xiangshan/frontend/NewFtq.scala, src/main/scala/xiangshan/package.scala
This PR completely refactors the commit mechanism from frontend to backend, addressing the commit problem once and for all. Additionally, these changes are expected to save noticeable area for frontend.
The backend now guarantees that every FTQ entry is committed on time, rather than committing only a subset of instructions. To accomplish this, each ROB entry can now compress a maximum of two FTQ entries. As a result, the `commitStateQueue` is no longer needed in the FTQ.
During the refactoring process, some historical bugs were identified and fixed.
**Attention**: Modifications in the FTQ may lead to a noticeable drop in BP accuracy. Performance data should be checked before merging into master.
=> feat(commit): complete rewrite of commit mechanism

src/main/scala/xiangshan/frontend/icache/ICache.scala
As per the requirements of the physical backend, split the ICache's Tag SRAM into smaller blocks.
=> area(ICache): split ICache meta SRAM

src/main/scala/xiangshan/mem/pipeline/AtomicsUnit.scala
In the previous design, AtomicsUnit sends out sbuffer flush request only under `s_tlb_and_flush_sbuffer_req` state. The request sets sbuffer under `x_drain_all` state. Sbuffer returns to `x_idle` state when it is empty. However StoreQueue may not be fully cleared at this point because there could be committed stores that haven't yet entered sbuffer. After these stores eventually enter sbuffer, sbuffer remains in `x_idle` state and will not flush them into DCache. This results in sbuffer being unable to drain completely, therefore the atomic instruction gets into deadlock.
This commit fixes this bug by continuously request sbuffer flush until sbuffer is fully drained.
=> fix(AtomicsUnit): flush sbuffer until sbuffer is empty

src/main/scala/xiangshan/cache/mmu/MMUBundle.scala
In scenarios where virtualisation is turned on, either onlyS1, onlyS2, or allStage, vmid matching is required. Specifically:
onlyS2: s2.vmid
onlyS1 or allStage: s1.vmid
=> fix(MMU): unify vmid matching logic

src/main/scala/device/AXI4Memory.scala
According to AXI4 spec, the total number of transfers in a transaction is encoded as Length = AxLEN + 1. Therefore the XSError assertion is incorrect and is removed in this pr.
=> fix(AXI4Memory): remove `AWLEN == 0` Check

src/main/scala/xiangshan/backend/dispatch/NewDispatch.scala
kunminghu v3 does not have `isFused` field after commit mechanism is refactored; use `fusionNum` instead
=> fix(topdown): calculate instruction fusion with fusionNum

src/main/scala/xiangshan/frontend/FTB.scala, src/main/scala/xiangshan/frontend/NewFtq.scala
If the frontend directly uses the SplittedSRAM of coupledL2, the frontend's SRAM will be marked as a multi-cycle path, the same as coupledL2's SRAM.
=> fix(FTB, FTQ): dont use CPL2 SplittedSRAM

Makefile, src/main/resources/config/Default.yml, src/main/scala/system/SoC.scala, src/main/scala/top/ArgParser.scala, src/main/scala/top/Top.scala, src/main/scala/top/XSNoCTop.scala, src/main/scala/top/YamlParser.scala, src/main/scala/xiangshan/L2Top.scala, src/main/scala/xiangshan/XSTile.scala, src/main/scala/xiangshan/XSTileWrap.scala
- `SeperateTLBus` and `SeperateTLBusRanges`: Generate a separate TileLink bus with corresponding address ranges
- with `XSNoCTopConfig`: Multiple ranges can be specified, and `SeperateDM` is ignored
- without `XSNoCTopConfig`: exactly one address range can be specified, and can only be used to connected with DM by `SeperateDM`
=> feat(Top): make address spaces of seperate TL port configurable

.github/workflows/emu.yml, .github/workflows/nightly.yml, .github/workflows/perf.yml, scripts/xiangshan.py
To avoid waveform corrupt in verilator.
=> ci: use fst instead of vcd

Makefile, src/main/scala/top/ArgParser.scala
This pull request parameterizes the NS (Non-Secure) field in the CHI bus, making it configurable. By default, the NS field is set to 0 (Secure), allowing XiangShan core to function as a secure boot processor in NoC. For systems that already utilize an MCU for secure boot, access of XiangShan core should theoretically be non-secure. In the latter cases, `ENABLE_NS=1` option should be added to the `make` compilation command.
=> submodule(CoupledL2): parameterize NS assignment

scripts/perfcct.py, src/main/scala/xiangshan/Bundle.scala, src/main/scala/xiangshan/backend/Backend.scala, src/main/scala/xiangshan/backend/Bundles.scala, src/main/scala/xiangshan/backend/datapath/DataPath.scala, src/main/scala/xiangshan/backend/decode/DecodeStage.scala, src/main/scala/xiangshan/backend/exu/ExeUnit.scala, src/main/scala/xiangshan/backend/fu/Fence.scala, src/main/scala/xiangshan/backend/fu/FuncUnit.scala, src/main/scala/xiangshan/backend/issue/IssueQueue.scala, src/main/scala/xiangshan/backend/rename/Rename.scala, src/main/scala/xiangshan/backend/rob/Rob.scala, src/main/scala/xiangshan/frontend/FrontendBundle.scala, src/main/scala/xiangshan/frontend/IBuffer.scala, src/main/scala/xiangshan/frontend/IFU.scala, src/main/scala/xiangshan/mem/MemBlock.scala, src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala, src/main/scala/xiangshan/mem/pipeline/AtomicsUnit.scala, src/main/scala/xiangshan/mem/pipeline/HybridUnit.scala, src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala, src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala, src/main/scala/xiangshan/package.scala
PerfCCT(performance counter commit trace) is a Instruction-level granularity perfCounter like GEM5
How to use this:
1. Make with "WITH_CHISELDB=1" argument
2. Run with "--dump-db --dump-select-db lifetime", then get the database
3. Instruction lifetime visualize run "python3 scripts/perfcct.py "the-db-file-path" -p 1 -v  | less"
4. Analysis script now is in XS-GEM5 repo, see https://github.com/OpenXiangShan/GEM5/blob/xs-dev/util/ClockAnalysis.py
How it works:
1. Allocate one unique tag "seqNum" like GEM5 for each instruction at fetch stage
2. Passing the "seqNum" in each pipeline
3. Recording perf data through the DPIC interface
=> feat: support inst lifetime trace

.github/CODEOWNERS, src/main/scala/xiangshan/frontend/Frontend.scala, src/main/scala/xiangshan/frontend/FrontendBundle.scala, src/main/scala/xiangshan/frontend/icache/Parameters.scala, src/main/scala/xiangshan/frontend/ifu/Ifu.scala, src/main/scala/xiangshan/frontend/instruncache/Abstracts.scala, src/main/scala/xiangshan/frontend/instruncache/Bundles.scala, src/main/scala/xiangshan/frontend/instruncache/InstrUncache.scala, src/main/scala/xiangshan/frontend/instruncache/InstrUncacheEntry.scala, src/main/scala/xiangshan/frontend/instruncache/InstrUncacheImp.scala, src/main/scala/xiangshan/frontend/instruncache/Parameters.scala, src/main/scala/xiangshan/mem/MemBlock.scala
- each class in a separate file (except Bundles / Utils)
- module IO inside module class
- renames:
- camel cases
- unify bundle naming convention
- re-organize IO
- rewrite `InstrUncacheEntry`
- use `switch-is` for fsm
- avoid `DontCare`: we can assign values directly
- replace `Mux(pc(...), data(...), Mux(pc(...), ..., ...))` tree with `Mux1H(UIntToOH(pc), Seq(data(...), ...))` for better readability (and maybe timing?)
- remove InstrUncache's dependency on `ICacheParameters`
=> refactor(InstrUncache): follow new style guide

src/main/scala/xiangshan/backend/rob/Rob.scala
The RISC-V manual says that:
> In typical usage, software will invalidate a range of virtual addresses in the addresstranslation caches by executing an SFENCE.W.INVAL instruction, executing a series of SINVAL.VMA, HINVAL.VVMA, or HINVAL.GVMA instructions to the addresses (and optionally ASIDs or VMIDs) in question, and then executing an SFENCE.INVAL.IR instruction.
Some additional information was obtained through https://github.com/riscv/riscv-isa-manual/issues/1936
However, other instructions may still appear between SFENCE.W.INVAL and SFENCE.INVAL.IR.
> Translation of any memory accesses during that sequence are subject to the usual uncertainty as to which translation (among old and new ones) is used.
Moreover, these memory accesses are not entirely unpredictable either.
> Each …
=> fix(Svinval): remove assert related to Svinval extension in ROB

src/main/scala/xiangshan/cache/mmu/TLB.scala
`req_need_gpa` indicates that the request needs to access the guest physical address (GPA) where a GPF occurred by querying the L2 TLB. When `req_need_gpa` is valid, it is sufficient to send an onlyStage1 request to obtain the guest physical address.
In the original design, multiple cases in the `MuxCase` could be valid at the same time. For example, when both `csr.vsatp.mode =/= 0.U` and `csr.hgatp.mode =/= 0.U` are valid, an allStage request would be sent directly, without considering the `req_need_gpa` condition. This commit fixes that bug.
=> fix(TLB): should always send onlyS1 req when req_need_gpa

src/main/scala/xiangshan/mem/lsqueue/LoadMisalignBuffer.scala, src/main/scala/xiangshan/mem/lsqueue/StoreMisalignBuffer.scala, src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala, src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala
For misaligned accesses, say if the access after the split goes to `nc` space, then a misaligned exception should also be generated.
=> fix(LSU): fix exception for misalign access to `nc` space

src/main/scala/xiangshan/cache/mmu/PageTableCache.scala
In "RISC-V Instruction Set Manual: Volume II: Privileged Architecture": The G bit in all G-stage PTEs is reserved for future standard use. Until its use is defined by a standard extension, it should be cleared by software for forward compatibility, and must be ignored by hardware.
=> fix(PTWCache): hfence_gvma should ignore g bit

src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala
When `pte_valid` is true and a page fault or guest page fault occurs, the original design only treated `ppn_af` as invalid (without checking whether the higher bits of ppn are zero). However, in this case, the PMP check would still be performed, potentially raising the `accessFault` signal.
This commit fixes the bug by ensuring that if a PMP check fails, only `accessFault` is raised, and pf or gpf will not be incorrectly asserted. Therefore, when either pf or gpf is valid, any `accessFault` resulting from PMP should be ignored.
=> fix(PTW): fix exception gen when both af and (pf | gpf) occur

src/main/scala/xiangshan/cache/mmu/L2TlbPrefetch.scala
All components within the L2 TLB should use the same flush condition to avoid potential issues.
=> fix(L2TlbPrefetch): fix flush condition of L2 TLB Prefetch

src/main/scala/xiangshan/backend/fu/NewCSR/InterruptFilter.scala
* if hvictl.VTI = 0:
* the highest-priority pending-and-enabled major interrupt indicated
* by vsip and vsie other than a supervisor external interrupt(code 9),
* using the priority numbers assigned by hviprio1 and hviprio2. 
* 
* A hypervisor can choose to employ registers hviprio1 and hviprio2
* when emulating the (virtual) supervisor-level iprio array accessed
* indirectly through siselect and sireg (really vsiselect and vsireg)
* for a virtual hart. For interrupts not in the subset supported by
* hviprio1 and hviprio2, the priority number bytes in the emulated
* iprio array can be read-only zeros.
=> fix(vstopi): remove SEI from Candidate 4

.gitmodules
The repo url in Gitee is case sensitive. It's necessary to correct the urls.
=> misc(submodule): correct case seneitivity in url

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
The prior design reassigns `io.lsq.ldin.bits.rep_info.need_rep` to 0 when source comes from MisalignBuffer, preventing cancellation of rar/raw enqueue requests during misaligned instruction reissuance. 
Thus, we must use `io.misalign_ldout.bits.rep_info.need_rep` to determine whether to revoke rar/raw enqueue requests when source is from MisalignBuffer.
=> fix(LoadUnit): fix ldld && stld query revoke logic

src/main/scala/xiangshan/cache/mmu/TLB.scala
In the previous design, `s2_paddr` was used whenever virtualization was enabled (`s2xlate =/= noS2xlate`). This was incorrect — we should use `s2_paddr` only when `onlyStage2` or `allStage` is active, and use `s1_paddr` when in `onlyStage1` or `noS2xlate` mode. This commit fixes that bug.
=> fix(TLB): onlyStage1 req should use s1_paddr rather than s2_paddr

src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala
In the original design, the condition for `to_last_hptw_req` was: `dup_wait_resp && entries(io.mem.resp.bits.id).req_info.s2xlate === allStage`. As a result, when a newly entered LLPTW request dups with an entry currently returning from memory, and the new request is marked as allStage, the `to_last_hptw_req` signal would be true. This causes the state machine to transition to the `state_last_hptw_req` state and send a request to HPTW.
However, if the page table returned from memory contains a `vsStagePf` or `gStagePf`, it should directly go to `mem_out` or `bitmap_check` without performing a final HPTW translation. Therefore, this commit fixes the bug by adding a restriction to the original `to_last_hptw_req` condition to ensure that no exceptions are present; otherwise, the state …
=> fix(LLPTW): dup_wait_resp should not send last_hptw_req when excp

src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala
* Sbuffer write and Atomics should not report errors, but refill from L2 should report ecc error, but requests in MissQueue carry `isAmo` or `isStore` and `req.miss` in a request, hence `(s2_req.isAMO || s2_req.isStore)` includes the refill, so the missing request of  `isAmo` or `isStore` will not report an error
=> fix(MainPipe): fix error valid when Atomics and SBuffer request miss

src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala
The cbo instruction should check for violations at the granularity of cacheline.
Theoretically modifying the condition of this variable would allow checking at cacheline granularity in RAW and should not introduce any other side effects.
See:
https://github.com/OpenXiangShan/XiangShan/blob/57a8ca5e38b9245f78623b83e7b009df606585fb/src/main/scala/xiangshan/mem/lsqueue/LoadQueueRAW.scala#L293
=> fix(StoreUnit): cbo violation check should check cacheline

scalastyle-config.xml, scalastyle-test-config.xml
... also sync configuration to `scalastyle-test-config.xml`
In recent development I've noticed that `scalastyle`'s analysis is rather simple (it only does lexical analysis), which leads to it not being able to distinguish between different semantics of a token, which in turn generates a lot of false-positive warnings:
```scala
val a = b + c // we want spaces around "add"
def +(that: UInt) = ... // we don't want space after "overload definition"
val d = e * f // we want spaces around "multiply"
def example(args: Int*) // we don't want spaces around "varargs"
if (cond) { // we want space or newline after left braces
...
} // and space or newline before right braces
println(s"${something}") // but not in this case
```
On the other hand, `scalafmt` can handle those cases very well and …
=> chore(scalastyle): disable space-around-operator checks

src/main/scala/xiangshan/backend/fu/NewCSR/CSRAIA.scala
The miselect register implements at least enough bits to support all implemented miselect values.
The siselect register will support the value range 0..0xFFF at a minimum.
The vsiselect register will support the value range 0..0xFFF at a minimum.
=> fix(xiselect): set the minimum range for xiselect

src/main/scala/xiangshan/Parameters.scala
This is a misrepresentation; currently, there is only one item in the fofbuffer.
=> chore(Parameters): remove the incorrect parameter description

src/main/scala/xiangshan/mem/vector/VecCommon.scala
For "unit-stride access with element granularity misaligned and emul<0", it could be the case that: 
has only once valid elements, but splits into two flows(misaligned), which would result in the `elemidx` being the same, making it impossible for the exception handling logic in the `mergebuffer` to recognise the correct order.
Instead of adding a new variable, we have chosen to reuse `elemidx` as a marker.
But this does pollute the original semantics of `elemidx`.
=> fix(VLSU): modifying vector misalign elemidx generation

src/main/scala/device/AXI4Memory.scala
* At `t0`, `w0 with lenght = 1` arrive,
* At `t1`, `w` buffer's `valid=1`, then `aw0 with id = 0` arrive
* At `t2`, `aw` buffer's `valid = 1, id = 0`, then write to WriteRequestQueue with `id = 0`
* At `t3`, `aw1 with id = 1` and `w1 with length=1` arrive at same time, then write to WriteRequestQueue with `id = 0`. In other words, the ID is used incorrectly.
How to fix:
* When writing, determine whether it can be written immediately. If it is written immediately, use the ID of the current, otherwise use the pending ID.
=> fix(AXI4Memory): fix write request enqueue DRAMSim logic for AXI4Memory

src/main/scala/xiangshan/backend/fu/NewCSR/InterruptFilter.scala
* For `mtopi` / `stopi` :
> AIA Spec:
> If all bytes of the supervisor-level iprio array are read-only zeros, a simplified implementation of field `IPRIO` is allowed in which its value is always `1` whenever `stopi` is not zero.
* We are configurable and `do not need` to simplify the implementation.
* For `vstopi`: 
> AIA Spec:
> Ties in nominal priority are broken as usual by the default priority order from `Table 8`, unless `hvictl` fields `VTI = 1` and `IID ≠ 9` (last item in the candidate list above), in which case default priority order is determined solely by `hvictl.DPR`.
> If bit `IPRIOM` (IPRIO Mode) of `hvictl` is zero, `IPRIO` in `vstopi` is 1; else, if the priority number for the highest-priority candidate is within the range `1` to `255`, `IPRIO` is that value; else, `IPRIO` …
=> fix(xtopi): fix xtopi generation conditions

src/main/scala/xiangshan/Bundle.scala, src/main/scala/xiangshan/Parameters.scala, src/main/scala/xiangshan/frontend/FrontendBundle.scala, src/main/scala/xiangshan/frontend/Ras.scala
Remove the S3-level correction code from the return stack branch predictor and adjust the formatting of the return stack code.
=> feat(ras): remove the S3 correction code from the return stack and adjust the code formatting

Makefile, src/main/scala/top/ArgParser.scala, src/main/scala/xiangshan/L2Top.scala
By default, XiangShan uses a fixed 48-bit physical address width, which is not configurable. However, some SoCs require support for different address widths (e.g., CHI buses support 44-52-bit addressing). To accommodate these SoC needs, this pr introduces a parameterized physical address width configured via `CHI_ADDR_WIDTH`. Key notes:
1. `CHI_ADDR_WIDTH` only modifies the address width for interactions between CoupledL2 and the CHI bus. Addresses within CoupledL2 and XSCore remain 48-bit, incurring some area overhead but functionally correct.
2. If `CHI_ADDR_WIDTH` < 48, CoupledL2 truncates the upper bits of addresses. As for snoops, truncated bits are treated as zero. Therefore It is critical to configure PMA at compile time to prevent XiangShan from generating address beyond the …
=> feat: support parameterized addr width with `CHI_ADDR_WIDTH`

src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala, src/main/scala/xiangshan/cache/dcache/Uncache.scala, src/main/scala/xiangshan/mem/Bundles.scala, src/main/scala/xiangshan/mem/lsqueue/LoadQueueUncache.scala, src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala, src/main/scala/xiangshan/mem/pipeline/HybridUnit.scala, src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala
1. Update pbmt when tlb hit.
2. Kill dcache request when there is nc.
3. Remove the useless `atomic` signal in `LsPipelineBundle`.
=> fix(StoreUnit): optimize the code by StoreUnit Code Review

src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
**Please wait for the results of the verification feedback.**
---
Adjusted a problem caused by expanding loops within for loops.
The expected condition for `ncstall` is:
` val ncStall = if(i == 0) nc(rdataPtrExt(0).value) else (nc(rdataPtrExt(i).value) || nc(rdataPtrExt(i-1).value)) `.
Since expanding the assignment in the loop: 
```
dataBuffer.io.enq(0).valid := canDeqMisaligned && allocated(rdataPtrExt(0).value) && committed(rdataPtrExt(0).value) &&
((!isVec(rdataPtrExt(0).value) && allvalid(rdataPtrExt(0).value) || vecMbCommit(rdataPtrExt(0).value)) &&
(!isCross4KPage || isCross4KPageCanDeq) || hasException(rdataPtrExt(0).value)) && !ncStall
dataBuffer.io.enq(1).valid := canDeqMisaligned && allocated(rdataPtrExt(0).value) && committed(rdataPtrExt(0).value) && …
```
=> fix(StoreQueue): fix misalign's Databuffer enq logic

.github/workflows/check_verilog.py, src/main/scala/xiangshan/backend/fu/NewCSR/CommitIDModule.scala, src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala
This allows the Git commit SHA and dirty status to be known directly from the simulation output.
It helps in scenarios such as responding to issues in the XiangShan repository, where the version used can be identified directly from the provided log file.
=> chore: add the version info to the simulation print output

src/main/scala/xiangshan/mem/lsqueue/LoadQueueUncache.scala, src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala, src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
* mmio or nc should report `Hardware Error` when response with `nderr`
* loadunit should report `Hardware Error` when it should be `delay kill` from fast replay
=> fix(LoadUnit, LSQ): fix report exception type for hardware error

src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala, src/main/scala/xiangshan/mem/lsqueue/LSQWrapper.scala, src/main/scala/xiangshan/mem/lsqueue/LoadQueueUncache.scala, src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
The priority of entering the uncacheBuffer has been changed from load priority to robIdx old priority
=> fix: use a more sensible entry priority of uncacheBuffer

src/main/scala/xiangshan/mem/lsqueue/StoreMisalignBuffer.scala
* a younger misalign store enq at `s1`, and revoke at `s2`, but `req_valid`  not set to false. As a result, it is not freed, and the later older misalign store cannot enter the buffer and cannot be completed, resulting in a stuck state.
How to fix:
* when a misalign store enq at `s1`, but revoke at `s2`, `req_valid` will be set `false` at `s2`
* ~~when a cross page enq replacement occur, but previous request will bt revoked, then previous request will be recovered.~~
=> fix(StoreMisalignBuffer): fix misalign store enq but revoke logic

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
We no longer allow software prefetch requests to generate nc signals, thus preventing weirdness in LoadUnit.
=> fix(LoadUnit): perfetch no longer generates nc access

src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
Previously, we set addrvalid to be set only at s1.
For misaligned stores, if it will go into misalignbuffer at s1, it may generate a revoke at s2 due to an exception.
If no revoke is generated, the addrvalid should not be set because the addrvalid will be set by the subsequent split request.
And if a revoke is generated, then an exception is generated and the addrvalid should be set at s2 to make this uop available for enq.
=> fix(StoreQueue): setting addrvalid on misalign revoke

src/main/scala/xiangshan/backend/fu/NewCSR/HypervisorLevel.scala, src/main/scala/xiangshan/backend/fu/NewCSR/MachineLevel.scala
For implementations that support Smcdeleg, Sscofpmf, and Smaia, the local counter overflow interrupt (LCOFI) bit (bit 13) in each of CSRs mvip and mvien is implemented and writable.
For implementations that support Smcdeleg/Ssccfg, Sscofpmf, Smaia/Ssaia, and the H extension, the LCOFI bit (bit 13) in each of hvip and hvien is implemented and writable.
=> fix(LCOFI): fix writable of LCOFI bit(13) of mvip/mvien/hvip/hvien

src/main/scala/xiangshan/cache/mmu/TLB.scala
Consider the following two-stage address translation process:
In the vs-stage, a 2MB large page is found during the lookup, which means the lower 9 bits of the resulting ppn are zeros. When generating the gvpn for the g-stage, it is formed as `gvpn = {s1_ppn, s1_vpn(9 bits)}`.
Then, in the g-stage translation, a 1GB large page is found, so the lower 9 * 2 = 18 bits of the resulting ppn are zeros. The final physical page number is constructed as ppn = `{s2_ppn, s2_gvpn(18 bits)}` = `{s2_ppn, s1_ppn(9 bits), s1_vpn(9 bits)}`.
In other words, if the g-stage page is larger than the vs-stage page, the final ppn should be composed of three parts: s2_ppn, s1_ppn, and s1_vpn.
However, in `handle_block`, the original implementation incorrectly concatenated the lower 18 bits of the ppn solely from …
=> fix(TLB): fix a bug in handle_block where s2_ppn is generated

src/main/scala/xiangshan/cache/mmu/MMUBundle.scala, src/main/scala/xiangshan/cache/mmu/PageTableCache.scala, src/main/scala/xiangshan/cache/mmu/Repeater.scala, src/main/scala/xiangshan/cache/mmu/TLB.scala, src/main/scala/xiangshan/mem/MemBlock.scala
According to the current RISC-V specification, the Svnapot extension defines pages of size 64KB. Therefore, when performing TLB or bypass hit tag matching, the lower 4 bits of the VPN and tag do not need to be compared.
In MMU, the hit determination logic typically consists of two parts: tag matching and level matching. For pages of different levels—512GB, 1GB, 2MB, or 4KB—different bit fields of the tag need to be matched. In our implementation, the napot case is treated as a variant of the 4KB page. As such, we need to modify the 4KB tag matching logic (`tag_match(0)`) accordingly so that when napot is enabled, the lower 4 bits of the tag are ignored during comparison.
However, the MMU codebase contains numerous `def hit` definitions (which is also one of the reasons for the code …
=> fix(MMU): fix MMU hit logic for napot cases

src/main/scala/utils/Duplicate.scala
We sometimes manually duplicate some signals to control fanout, like:
```scala
val io = IO(new Bundle{
val toModuleA = UInt(width.W)
val toModuleB = Vec(2, UInt(width.W))
val toModuleC = UInt(width.W)
}
val source = Wire(UInt(width.W))
val xxxDup = Vec(4, UInt(width.W))
xxxDup.foreach(x => x := source)
io.toModuleA.xxx := xxxDup.head
io.toModuleB.xxxDup := VecInit(xxxDup.slice(1, 2))
io.toModuleC.xxx := xxxDup.last
```
This can be confusing sometimes, in BPU for example:
https://github.com/OpenXiangShan/XiangShan/blob/6bd705ec99d7e5781230da449bc54f333b6fcddc/src/main/scala/xiangshan/frontend/BPU.scala#L155-L161
https://github.com/OpenXiangShan/XiangShan/blob/6bd705ec99d7e5781230da449bc54f333b6fcddc/src/main/scala/xiangshan/frontend/ITTAGE.scala#L444-L446
Just, why there is a `(3)` after …
=> feat(utils): add Duplicate

src/main/scala/utils/EnumUInt.scala
Basically a enhanced `NamedUInt`, refer to comments in `EnumUInt.scala`:
https://github.com/OpenXiangShan/XiangShan/blob/9c0cfc26f18c8bb85af825da6d74612b7108696f/src/main/scala/utils/EnumUInt.scala#L6-L66
It uses [java reflection](https://www.runoob.com/java/java-reflection.html) mechanism to check constant definations (UpperCamelCase, return UInt, and take no parameters), and can help prevent mistakes like:
- [`7ff49a5` (#4461)](https://github.com/OpenXiangShan/XiangShan/pull/4461/commits/7ff49a504062bd585789fcf8bc1bc985ba1f289d)
- #4124 
Migration example:
- `NamedUInt(log2Up(...))` (uses width) -> `EnumUInt` (uses actual number of unique values, or width for one-hot mode)
```diff
- private object S1FsmState extends NamedUInt(log2Up(5)) {
+ private object S1FsmState extends EnumUInt(5) …
```
=> feat(utils): Add EnumUInt for defining enum values

src/main/scala/xiangshan/frontend/BPU.scala, src/main/scala/xiangshan/frontend/Composer.scala, src/main/scala/xiangshan/frontend/FTB.scala, src/main/scala/xiangshan/frontend/FauFTB.scala, src/main/scala/xiangshan/frontend/FrontendBundle.scala, src/main/scala/xiangshan/frontend/Ftq.scala, src/main/scala/xiangshan/frontend/ITTAGE.scala, src/main/scala/xiangshan/frontend/Ras.scala, src/main/scala/xiangshan/frontend/Tage.scala
To make it easier to manage the predictors' meta, we restructured it as a `Bundle` rather than a `UInt`.
=> refactor(Frontend): refactor meta io

src/main/scala/top/XSNoCTop.scala
This fix change  clock gate enable by hard reset since i_cpu_sw_rst_n is not used.
=> fix(XSNoCTop): gate clock by hard reset Not i_cpu_sw_rst_n

src/main/scala/xiangshan/backend/Bundles.scala, src/main/scala/xiangshan/backend/fu/NewCSR/CSREvents/TrapEntryMEvent.scala, src/main/scala/xiangshan/backend/fu/NewCSR/TrapInstMod.scala, src/main/scala/xiangshan/backend/fu/wrapper/CSR.scala
- fix trapInst update when flush and CSR illegal instruction happen together
- exception instruction stored in trapinst was not flushed when being interrupted at the same time
=> fix(CSR): fix trapInst update logic

src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala, src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala, src/main/scala/xiangshan/cache/dcache/mainpipe/MissQueue.scala, src/main/scala/xiangshan/cache/dcache/mainpipe/Probe.scala, src/main/scala/xiangshan/mem/pipeline/AtomicsUnit.scala, src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala
* t0: dcache has a tag (e.g. `0x90054`), but cacheline sbuffer without write permission has a write request with the tag.
* t1: sbuffer writes dcache, which will cause dcache miss because there is no write request, thus sending a miss request with the tag.
* t2: when other miss request refill to mainpipe, it needs to be replaced, and the algorithm replacement always chooses the way with tag=`0x90054`, At the same time, mainpipe will compare tag=`0x90054` with missqueue. there is a request with tag=`0x90054` in missqueue, causing missqueue refill failure and resend.
* t3: In BtoT's sbuffer write request, L2 did not send grantData, resulting in the refill not being completed, which led to tag=`0x90064` request will not refill to dcache, and probe `0x90064` will be blocked.
* L2 receives a …
=> fix(DCache): fix DCache replacement when replace a `BtoT` ways

src/main/scala/xiangshan/frontend/BPU.scala, src/main/scala/xiangshan/frontend/Composer.scala, src/main/scala/xiangshan/frontend/FTB.scala, src/main/scala/xiangshan/frontend/FauFTB.scala, src/main/scala/xiangshan/frontend/FrontendBundle.scala, src/main/scala/xiangshan/frontend/Ftq.scala, src/main/scala/xiangshan/frontend/ITTAGE.scala, src/main/scala/xiangshan/frontend/Ras.scala, src/main/scala/xiangshan/frontend/SC.scala, src/main/scala/xiangshan/frontend/Tage.scala
In the previous implementation, we duplicated certain wires to reduce fan-out, but this led to confusing variable naming and reduced code readability. This PR removes all such duplication in the frontend, and we will address fan-out issues in a more readable way in the future.
=> refactor(Frontend): remove all dups

src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
When the vector store that raised the exception is written back to the backend, the StoreQueue is too late to set the corresponding entries to `committed`, resulting in the `redirect` flush them, which results in the `vecExceptionFlag` being asserted due to the timeout not being cleared.
=> fix(StoreQueue): fix timeout of vecExceptionFlag when redirect

scripts/Makefile.docker
Many variables in XiangShan Makefile can be overridden from command line. Without forwarding these to docker, commands executed in the container may produce unexpected results due to variable mismatches.
=> fix(docker): Forward variables in the make command line to docker

src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
Only if there are no exceptions, cbozero is allowed to set the status bits inside the storequeue and write back through the storequeue.
When there is an exception, write back directly through storeunit.
=> fix(StoreQueue): cbozero flag should not be set on exception

src/main/scala/xiangshan/backend/fu/NewCSR/CSRPermitModule.scala, src/main/scala/xiangshan/backend/fu/NewCSR/HypervisorLevel.scala, src/main/scala/xiangshan/backend/fu/NewCSR/MachineLevel.scala, src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala, src/main/scala/xiangshan/backend/fu/NewCSR/StateEnBundle.scala, src/main/scala/xiangshan/backend/fu/NewCSR/SupervisorLevel.scala
* add [m|h|s]stateen[1|2|3] csr.
* Bits in any stateen CSR that are defined to control state that a hart doesn’t implement are read-only zeros
for that hart.
* only reset mstateen[0|1|2|3]
This pr should be rebase and merged. Include two commits:
* fix(smstateen): add [m|h|s]stateen[1|2|3] csr.
* submodule(ready-to-run): bump ready-to-run to fix smstateen
=> fix(smstateen): add [m|h|s]stateen[1|2|3] CSRs

.github/workflows/emu.yml
As an alternative to XiangShanRobot
This will be helpful when we want to compare any two of CI runs, instead of just latest runs on PR & master
Showcase: https://github.com/OpenXiangShan/XiangShan/actions/runs/15086713467?pr=4700
=> misc(ci): write IPC to GITHUB_STEP_SUMMARY

src/main/scala/xiangshan/mem/lsqueue/LoadQueueUncache.scala
**Bug Trigger:** When the data responsed by `Uncache` is 0x0013 xxxx xxxx xxxx, the selected data handled by `LoadQueueUncache` is `0x0000 0000 0000 0013` in which case that `raddr(2, 0)` is 0b110 and `LSUOpType` is `lhu`. And this data is what we want. However it is then processed by the LoadUnit again with the same process and a new data `0x0000 0000 0000 0013` is obtained, which is error.
So here needs to return origin data which will be selected in LoadUnit.
=> fix(LoadQueueUncache): return origin data in LoadQueueUncache.

src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala
In this pr(https://github.com/OpenXiangShan/XiangShan/pull/4673), we set `fullva` incorrectly. 
`fullva` will be overridden by `tlb.resp.bits.fullva` again in a later stage.
So we should set `fullva` in `s1_out` instead of `s0_out`.
=> fix(LSU): misaligned exception addr should use split addr

src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
The NC store does not handle exceptions properly. When an exception occurs during its execution, the store queue (SQ) continues to process it as if it were a normal nc store—this includes committing it and sending it to the uncache—resulting in an invalid memory access.
In the current SQ design, for regular stores, both `rdataPtr` and `deqPtr` advance based on handshakes with `dataBuffer` and `SBuffer`, respectively. Thus, even if an exception occurs, the store is marked as `committed = true` and passed into both buffers. If an exception is detected at the `SBuffer`, the actual write is skipped.
For NC stores, the `committed` logic is reused from regular stores. However, there is no dedicated handling for exceptional cases in the later pipeline stages—such as preventing handshake with the …
=> fix(StoreQueue): not do nc store when having exception

src/main/scala/xiangshan/Bundle.scala, src/main/scala/xiangshan/mem/MemBlock.scala, src/main/scala/xiangshan/mem/lsqueue/LSQWrapper.scala, src/main/scala/xiangshan/mem/lsqueue/LoadMisalignBuffer.scala, src/main/scala/xiangshan/mem/lsqueue/LoadQueueUncache.scala, src/main/scala/xiangshan/mem/lsqueue/StoreMisalignBuffer.scala, src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala, src/main/scala/xiangshan/mem/pipeline/HybridUnit.scala, src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala, src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala, src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala
**Bug Trigger:** In a self-modifying program, the program modifies its own instructions in a region where PBMT=NC and PMA=MM. If difftest is skipped in this case, NEMU will not execute the corresponding memory access instruction. This causes NEMU and DUT to execute different instructions later on, ultimately leading to an error.
**Solution:** For regions where PBMT=NC and PMA=MM, difftest should not be skipped, since PMA=MM indicates that NEMU can perform normal synchronization. However, for regions with PMA=IO, difftest should still be skipped because NEMU might not be able to access the corresponding devices. Instruction self-modification in PMA=IO regions is generally not a concern, as such regions are typically non-writable. Therefore, synchronization of self-modifying IO instructions …
=> fix(NCMM): nc access in main memory should not skip difftest

src/main/scala/top/Top.scala, src/main/scala/top/XSNoCTop.scala
There are two independent SoC designs in XiangShan (a.k.a. `XSTop` and `XSNoCTop`),
each containing its own DTS generation logic. This PR merges them into common
base class `BaseXSSoc` and a specialized `HasDTSImp` trait, to prevent modifications
to this part from being missed in different designs.
=> feat(top): Move DTS ResourceBinding flow to BaseXSSoC

src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
In this pr(https://github.com/OpenXiangShan/XiangShan/pull/4660), we introduce additional logic for redirect on vector exceptions.
Previously, it was because, when `vecExceptionFlag` was high, we would need to wait for `lastflow` deq, in order to clear `vecExceptionFlag`, so we might need to prevent this one instruction from being flushed.
---
However, with the previous modification, when a vector store has not yet deq, but needs to redirect itself, it will fail to cancel due to the use of `isAfter`. 
This leads to ptr exceptions in the storequeue, which can lead to stuckness.
---
The solution, which has always been simple, is to prevent canceling itself only when the exception's directive deqs, i.e., when `vecExceptionFlag` is set.
=> fix(StoreQueue): redirect logic for vector exception

src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala, src/main/scala/xiangshan/cache/dcache/mainpipe/MissQueue.scala
When `MissQueue` refills data, ECC error injection occurs. The way where the tag hits before the ECC error is injected (if any) should be selected for replacement. However, `s1_need_replacement` does not take this into account, resulting in the error tag reported to `BEU` being the one selected by the replacer, rather than the tag corresponding to the ECC error injection.
How to fix:
* In the `s1` stage of  `MainPipe`, add a check to determine whether it is in the ECC injection state. If so, it is necessary to determine whether to compare with the non-injected tag, determine whether there is a hit way, and select the hit way as the path corresponding to accessing `BankedDataArray`.
*  In the `s2` stage of `MainPipe`, by determining whether it is in the ECC injection …
=> fix(MainPipe): fix pseudo ecc inject report address

Makefile, scripts/Makefile.docker
- fix(docker): Fix docker "-e" param when `MAKEOVERRIDES` contains space
- fix(build): Always re-generated test-jar target by mill
=> Minor fix to docker build and test-jar dependency

.github/workflows/emu.yml, src/main/scala/top/Top.scala, src/main/scala/top/XSNoCTop.scala
Use inherit instead of composite to reduce redundant IO port definitions
and connections. At the same time, we are able to keep the original module
name `XSTop` unchanged.
=> refactor(XSNoCTop): Inherit XSNoCDiffTop from XSNoCTop instead composite

src/main/scala/xiangshan/mem/prefetch/L1StreamPrefetcher.scala
This PR change stream prefetcher L2 distance from 128 to 256 blocks.
Since the latency from L2 to DDR is much higher in NoC scenarios, it is necessary to increase the L2 prefetch distance of  stream prefetcher to ensure timeliness.
=> perf(L1StreamPf): double the L2 prefetch distance

src/main/scala/top/ArgParser.scala, src/main/scala/top/Configs.scala, src/main/scala/top/XSNoCTop.scala, src/main/scala/top/YamlParser.scala, src/main/scala/xiangshan/Parameters.scala
* Refactor `DFT` option passing method by `DFTOptionsKey`
* `DFX` and `DFTOptionsKey.EnableMbist` are related. e.g. `DFX=1` equal to `DFTOptionsKey.EnableMbist=true`
* `SRAM_WITH_CTL` and `DFTOptionsKey.EnableSramCtl` are related. e.g. `SRAM_WITH_CTL=1` equal to `DFTOptionsKey.EnableSramCtl=1`
* `DFTOptionsKey.EnableMbist=true` by default
**!!!Attention!!!**
* `EnableMbist=true` and `EnableSramCtl=true`: support
* `EnableMbist=true` and `EnableSramCtl=false`:  support
* `EnableMbist=false` and `EnableSramCtl=true`: it needs bump latest `Utility` for submodules, which references `Utility`
* `EnableMbist=false` and `EnableSramCtl=false`: support
=> refactor(Config): refactor `DFT` option passing method

src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala
* When there are multiple errors，`Mux1H` is equivalent to using `|`,  for example 
* error 0, valid = 1, addr0 = 0x1000
* error 1, valid = 1, addr1 = 0x0ffff
* the result is `io.error.valid == 1`, but `io.error.bits.addr == (addr0 | addr1)`,  cause `ParallelMux` will generate circuit like this:
```
addr = (valid0 ? addr0 : 'h0) |
(valid1 ? addr1 : 'h0)
```
* This problem can be avoided by using `ParallelPrioirtyMux`
* adjust `MainPipe` error priority to highest
=> fix(DCache): use `ParallelPrioirtyMux` instead of `ParallelMux`

src/main/scala/xiangshan/cache/mmu/MMUBundle.scala
The lower bits of valididx(i) indicate whether the i-th entry is valid among a contiguous range of n 4KB pages, and `addr_low_hit` is used to check this. However, for large pages and NAPOT cases, since the covered range exceeds what the TLB compression can represent, `addr_low_hit` should always be true.
=> fix(MMU): SuperPage should not consider valididx

src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala, src/main/scala/xiangshan/cache/dcache/mainpipe/MissQueue.scala
* Tag ECC injection may cause a cache miss and raise a miss req, when mshr refill this miss req will see a cache hit after recovering the tag ecc injection.
* Now fix it, add a miss_tag_error signal for miss req, ignore the cache hit in MainPipe when refill a miss req with miss_tag_error.
=> fix(DCache): ignore tag match when refill a miss req caused by tag error

src/main/scala/xiangshan/cache/dcache/loadpipe/LoadPipe.scala, src/main/scala/xiangshan/cache/dcache/mainpipe/MissQueue.scala
Related PR：#4729：fix(LoadPipe): fix `prefetch_w` btot stall
=> fix(LoadPipe): load will not enter missqueue when btot grow fail

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
Misaligned load that cause TLB miss are no longer allowed to enter the loadmisalignbuffer.
This is because it would cause subsequent exception addresses to be incorrect :
The original address of the misaligned load is 0x07, while the first request address after splitting is 0x00. 
Thus, when a page fault exception occurs, 0x00 would be considered the exception address instead of the original 0x07.
---
Store have always been handled this way and do not require modification.
=> fix(LoadUnit): no longer allow tlb missing misaligned load to enter misalignbuffer

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala, src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala
Previously, when accessing mmio space after splitting, we generated an exception in misalignbuffer, which prevented the exception address from being written to exceptionbuffer. 
Therefore, we now choose to generate an exception in pipeline so that the exception address can be written correctly.
=> fix(LSU): misalign exception are generated directly within the pipeline

src/main/scala/xiangshan/backend/Bundles.scala, src/main/scala/xiangshan/mem/Bundles.scala, src/main/scala/xiangshan/mem/MemBlock.scala, src/main/scala/xiangshan/mem/lsqueue/LSQWrapper.scala, src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala, src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala, src/main/scala/xiangshan/mem/vector/VMergeBuffer.scala, src/main/scala/xiangshan/mem/vector/VSegmentUnit.scala, src/main/scala/xiangshan/mem/vector/VSplit.scala, src/main/scala/xiangshan/mem/vector/VecBundle.scala
* Background
We use rdataPtr(0) and rdataPtr(1) to determine whether we need to set `vecExceptionFlag`. Unfortunately, when rdataPtr(0) is a request that is misaligned and cross-16Byte and has exception, the request need to split and occupy two write ports of dataBuffer, which lead to different perspectives: `rdataPtr` consider Vector Store can't `Deq`; `vecExceptionFlag` consider Vector Store can `Deq`. In conclusion, this issue will result in write data that should not be written.
---
* Example
1. vle16, Addr = 0xF, LMUL = 1/4, SEW = 16-bit, EEW = 16-bit, EMUL = 1/4, vstart = 0, vl = 2. 
First flow in Store Queue is misaligned and cross-16Byte and has exception, in order to store datas of vle16 (we will not store data to sbuffer when flow have exception, but need to `Deq`), we need to …
=> fix(StoreQueue): fix vecExceptionFlag when flow is misaligned

src/main/scala/xiangshan/backend/fu/PMP.scala
When leaveHitMux is enabled, pmp will take a beat for the vast majority of io.req.bits. 
However, io.req.bits.cmd didn't take a beat.
Previously, a pipeline would only generate one cmd request, so even if the beat count was not aligned, no bugs would occur.
However, currently, loadunit issues both write and read requests, which causes permission checks to fail.
=> fix(PMP): take a beat for `cmd`

src/main/scala/xiangshan/package.scala
Currently, the access memory generates hwe exception for bus error and the frontend generates iaf exception for bus error .
We plan to have the frontend also generate hwe exception in kmhV3.
---
HardwareError should belong to memory access exception, and use virtual addresses as the value of xtval when trapping.
Previously, no exception types were added for HardwareError to handle in trapEvent, which resulted in the inability to match and select valid xtval:
https://github.com/OpenXiangShan/XiangShan/blob/8769efd7b4782ab06aed08c14e330f602918c930/src/main/scala/xiangshan/backend/fu/NewCSR/CSREvents/TrapEntryMEvent.scala#L85-L90
---
**In addition**
Since fetch may also produce hardwareError exception in theory, and hardwareError exception produced by fetch should write pc to xtval. …
=> fix(TrapEntry): hardwareError should be a memory exception

src/main/scala/xiangshan/cache/mmu/TLB.scala
Previously, handle_block manually checked hit for stage1 and stage2, which could lead to issues when s1 and s2 are at different levels (different page sizes). This commit refactors the logic to use the existing unified function io.ptw.resp.bits.hit instead of checking io.ptw.resp.bits.s1.hit and s2.hit separately.
=> fix(TLB): use the same hit logic for block as for bypass

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
Previously the hardware error handling for writeback to the backend only considers errors generated at s3 stage such as DCache ECC error, but ignores errors originating from earlier stages (e.g., errors received from the outer bus by NC/MMIO access). This commit fixes this bug.
=> fix(LoadUnit): fix bug in hardware error written back

src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala, src/main/scala/xiangshan/cache/dcache/mainpipe/MissQueue.scala
* Tag ECC injection may cause a cache miss and raise a miss req, when mshr refill this miss req will see a cache hit after recovering the tag ecc injection.
Now fix it, fix `s2_can_go_to_s3` select priority for refill ecc inject lead to tag miss
* when req is refill and hit, it will wait for `refill_info_valid` otherwise req will replay
=> fix(MainPipe): adjust `s2_can_go_to_s3` select priority for refill ecc inject lead to tag miss

src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala, src/main/scala/xiangshan/cache/dcache/data/BankedDataArray.scala, src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala
`MainPipe`  has two requests, `req0 (probe)`, `req1 (sbuffer)`
`t0`: `req0` arrives first and to `s3`.  At this time, `WritebackQueue` cannot accept the request, thus blocking `req0`, and `s3_data_error=1`
`t1`: `req1` arrives at `s0`,
`t2`: `req1` arrives at `s1`, and `s1_fire=1`,
`t3`: `req1` arrives at `s2`, at this time `s2_may_report_data_error = 0`
`t4`: `req1` returns to sbuffer
`t5`: `WritebackQueue` can accept the request, but at this time, `GatedValidRegNextN(s1_fire, 2) = 1`, at this time `s3_data_error` will be updated to the result of `req1`, and then latched.
How to fix:
* `s3_data_error` use `s2_can_fire_to_s3` instead of `s2_fire`
=> fix(MainPipe): add reg enable for mainpipe `ecc_delayed`

src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala, src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala, src/main/scala/xiangshan/cache/dcache/mainpipe/MissQueue.scala
Bug description:
Address `0x15002cf00` has a valid cacheline at setidx`0x3c`, then there is an sbuffer write request, setidx=`0xfc`, it will miss and enters the `MissQueue`, then wait for refill. There is another refill request sent by `MissQueue` with setidx=`0xfc`, it will replace this cacheline, but the tag (`0x15002cf00`) is already in the `MissQueue`, so it will blocks
How to fix:
Add alias bit comparison to the blocking logic of replace and probe
=> fix(MainPipe): fix probe/replace stall for alias scheme

src/main/scala/xiangshan/cache/dcache/meta/AsynchronousMetaArray.scala
Enable bypass to allow reads to obtain write data when reads and writes occur simultaneously.
---
load s0 reads meta.
load s1 obtains the read meta result.
load s2 requests entry into rarqueue.
If a write meta probe is generated simultaneously with load s0, without enabling bypass, this read meta will obtain old data.
This will result in a dcache hit.
However, the rarqueue release occurs on the next cycle after the probe write meta, which is when load s1 is generated. At this point, the load has not yet entered the rarqueue, so it is not marked as released in the rarqueue.
=> fix(MetaArray): enable write bypass for read

src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala
* Related to [fix(csr, perf): skip CSR read xtopi](https://github.com/OpenXiangShan/XiangShan/pull/4742), skip for now.
* Currently, there is a situation where xtopei is updated, and then a CSR reads `xtopi` instruction. Since the CSR reads `xtopi` instruction is skipped, `old_xtopei` in NEMU is not updated. Then a CSR reads `xtopei` instruction, causing an error in XiangShan and NEMU diff.
=> fix(csr, perf): skip CSR read xtopei

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala, src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala, src/main/scala/xiangshan/mem/vector/VSegmentUnit.scala
We believe that vectors do not support access to mmio space, so regardless of the circumstances, an af exception should be generated rather than a misalign exception.
=> fix(VLSU): vector ld/st does not generate misalign exception when mmio

src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala
If vector misaligned store causes misalignBufferNack, it is necessary to enter mergebuffer to IQ replay.
Scalar misaligned store does not require continued pipelining, it will allow IQ to perform replay at S1.
=> fix(StoreUnit): vec misalignBufferNack need to mergebuffer

src/main/scala/xiangshan/cache/mmu/MMUBundle.scala, src/main/scala/xiangshan/cache/mmu/MMUConst.scala, src/main/scala/xiangshan/cache/mmu/PageTableCache.scala, src/main/scala/xiangshan/cache/mmu/TLBStorage.scala
In the previous design, both the L1 TLB and L2 TLB did not consider the global bit when checking for hits—they always matched both ASID and VMID. The correct matching logic should be:
1. noS2: Match ASID (or global)
2. onlyStage1: Match ASID (or global) and VMID (always need match)
3. onlyStage2: Match VMID (always need match; global bit in G-stage PTEs must be ignored by hardware)
4. allStage: Match ASID (or global) and VMID (always need match); only L1 TLB stores allStage entries
The implementation logic of sfence and hfence has also been confirmed:
1. sfence (non-virt): Match ASID (conditional based on parameters)
2. sfence (virt): Match ASID (conditional) and VMID (always need match)
3. hfence.vvma: Match ASID (conditional) and VMID (always need match)
4. hfence.gvma: Match VMID …
=> fix(MMU): global entries should always hit even asid switch

src/main/scala/xiangshan/backend/fu/NewCSR/MachineLevel.scala, src/main/scala/xiangshan/backend/fu/NewCSR/VirtualSupervisorLevel.scala
* When the vstart of a vector memory access instruction is not 0, the xstatus.VS field is set to dirty.
=> fix(csr): set xstatus.VS dirty when a vector memory access instr has exception

src/main/scala/xiangshan/Bundle.scala, src/main/scala/xiangshan/backend/fu/wrapper/CSR.scala, src/main/scala/xiangshan/cache/mmu/BitmapCheck.scala, src/main/scala/xiangshan/cache/mmu/L2TLB.scala, src/main/scala/xiangshan/cache/mmu/L2TLBMissQueue.scala, src/main/scala/xiangshan/cache/mmu/L2TlbPrefetch.scala, src/main/scala/xiangshan/cache/mmu/PageTableCache.scala, src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala, src/main/scala/xiangshan/cache/mmu/Repeater.scala, src/main/scala/xiangshan/cache/mmu/TLB.scala, src/main/scala/xiangshan/mem/MemBlock.scala
In the previous LLPTW design, there was only one PMP check interface. When the `hptw_need_addr_check` signal was asserted, it would override `need_addr_check`. However, when handling both virtualized and non-virtualized scenarios simultaneously, both signals could be true at the same time. This could prevent the `need_addr_check` request from receiving a PMP response, eventually leading to a deadlock.
Additionally, this commit flushes all inflight MMU requests when the virt value changes, to ensure correct functionality when the MMU is handling both virtualized and non-virtualized requests concurrently.
=> fix(LLPTW): fix bug in handling both virtualized & non-virtualized cases

src/main/resources/config/Default.yml, src/main/scala/top/XSNoCTop.scala
1. synchronize CHI syscoack for cross clock domain protection
2. remove WFI clock gating related logic when disable this function
=> fix(XSNoCTop): synchronize CHI syscoack for cross clock domain protection

src/main/scala/xiangshan/mem/lsqueue/LoadMisalignBuffer.scala, src/main/scala/xiangshan/mem/lsqueue/StoreMisalignBuffer.scala
Since our misaligned wakeup is generated by three beats in place in the load unit, once the misaligned wakeup request enters the load unit, it cannot be flushed.
Therefore, it is possible that this instruction has been redirected, but a response has been sent back from the load unit, causing the misalign buffer to accept a response that it should not accept.
fix:
For simplicity, we make a judgement in the misalign buffer and do not accept responses from non-current instructions.
=> fix(LSU): fix misalignbuffer response acceptance process

src/main/scala/xiangshan/frontend/Frontend.scala, src/main/scala/xiangshan/mem/MemBlock.scala
`ram_ctl` signals are considered static signals since power-on and never change. If we have `RegNext` in our design, it requires two extra cycles for SRAM to get `ram_ctl` from outside correctly, which may cause unexpected behavior.
=> fix(ramctl): remove RegNext in Frontend and MemBlock

src/main/scala/xiangshan/backend/fu/NewCSR/CommitIDModule.scala
When implemented in vivado2020.2, an empty module will trigger the error DRC INBB-3, which can be solved by adding a wire to the module. The software will optimize this module without increasing the resource occupation
=> fix(fpga): fix fpga compile

src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
Bugs descriptions:
* Here is the instructions sequence:
* Ld0 PA1
* St0 PA2
* Ld1 PA2
* Ld0 need replay by `tlb miss`, Ld1 need St0's data, but it's not ready, hence, Ld1 need replay by `forward fail`
* Ld0 ready to replay, Ld1 ready to replay, but LoadQueueReplay always choose Ld1 (Ld0 and Ld1 in the same bank)
* Ld0 will not committed, St0 will also not committed, finally Ld1 will not committed.
How to fix:
* `stDataReadyVec`: it will not set if it's misalign store
* `dataReadyPtrExt`: it will not move if it's misalign store data ready, until the oldest misalign store committed, `dataReadyPtrExt` plus 1.
=> fix(StoreQueue): fix misalign forward fail stall

src/main/scala/xiangshan/cache/mmu/L2TLB.scala, src/main/scala/xiangshan/cache/mmu/MMUBundle.scala
In the previous code, as long as PTE.n was set to 1, we treated the page size as 64 KB. However, according to the specification, a page should only be considered 64 KB in size when the lower 4 bits of the PPN equal `'b1000`; otherwise, it should still be treated as a 4KB page.
=> fix(MMU): fix the condition for identifying napot pages

src/main/scala/xiangshan/mem/MemBlock.scala, src/main/scala/xiangshan/mem/lsqueue/StoreMisalignBuffer.scala, src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala, src/main/scala/xiangshan/mem/vector/VSplit.scala, src/main/scala/xiangshan/mem/vector/VecBundle.scala
When `younger` misaligned store enters `StoreMisalignedBuffer`, the `older` misaligned vector store will stop to split, which lead to stuck.
=> fix(Vsplit): fix Vec Store split stuck when misaligned

src/main/scala/xiangshan/mem/MemBlock.scala
When loadUnit need to write back a vector request at the same time, misalignBuffer will handshake success, but not real writeback, which lead to the loss of vector misalign request.
=> fix(MisalignBuffer): fix vector misalign request writeback ready

Makefile
* use `--split-verilog` only for systemverilog target
* allow using `FIRTOOL` to specify the firtool binary
=> fix(Makefile): check CHISEL_TARGET/FIRTOOL variables

src/main/scala/xiangshan/Bundle.scala, src/main/scala/xiangshan/backend/fu/NewCSR/CSRBundles.scala, src/main/scala/xiangshan/backend/fu/NewCSR/CSRCustom.scala, src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala, src/main/scala/xiangshan/frontend/Bundles.scala, src/main/scala/xiangshan/frontend/bpu/Abstracts.scala, src/main/scala/xiangshan/frontend/bpu/Bundles.scala, src/main/scala/xiangshan/frontend/bpu/DummyBpu.scala, src/main/scala/xiangshan/frontend/bpu/FallThroughPredictor.scala, src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtb.scala, src/main/scala/xiangshan/frontend/bpu/abtb/Bundles.scala, src/main/scala/xiangshan/frontend/bpu/mbtb/Bundles.scala, src/main/scala/xiangshan/frontend/bpu/mbtb/MainBtb.scala, src/main/scala/xiangshan/frontend/bpu/old/Bpu.scala, src/main/scala/xiangshan/frontend/bpu/old/Ftb.scala, src/main/scala/xiangshan/frontend/bpu/old/MicroFtb.scala, src/main/scala/xiangshan/frontend/bpu/old/Ras.scala, src/main/scala/xiangshan/frontend/bpu/old/Tage.scala, src/main/scala/xiangshan/frontend/bpu/phr/Bundles.scala, src/main/scala/xiangshan/frontend/bpu/phr/Phr.scala, src/main/scala/xiangshan/frontend/bpu/ubtb/Bundles.scala, src/main/scala/xiangshan/frontend/bpu/ubtb/MicroBtb.scala, src/main/scala/xiangshan/frontend/ftq/Bundles.scala, src/main/scala/xiangshan/frontend/ftq/Ftq.scala
Please use rebase and merge, do NOT squash this PR!
Stage part 3 of new Bpu, including:
- timing & x-state fixes
- renewed ports with backend (CsrCtrl & Redirect & Train)
Rebased & squashed from [feat-v3-bpu](https://github.com/OpenXiangShan/XiangShan/tree/feat-v3-bpu) branch, original commit history:
d1150de9faca063936f39efab47af4e0d9189aa9 refactor(Bpu): re-write BpuRedirect and BpuTrain port
546ff6f1e0ebf0eff264603c3a1cece1cbdaac82 fix(abtb): fix s0_fire condition to solve x-state issue **(dropped as already cherry-picked to dev-new-frontend)**
69b1ef4f55fb98265e99721efa2bc5c4d4195ac6 feat(Bpu,Csr): rewrite Sbpctl
01142a1cea6a111791e2898966f77490b218813c timing(fallThroughPredictor): move calculate logic to s1
=> feat(Bpu): v3 bpu part3

src/main/scala/xiangshan/cache/mmu/BitmapCheck.scala, src/main/scala/xiangshan/cache/mmu/L2TLB.scala, src/main/scala/xiangshan/cache/mmu/MMUConst.scala, src/main/scala/xiangshan/cache/mmu/PageTableCache.scala, src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala
* add bitmap wakeup the page table cache check hit state;
* modify the calculation of Bitmap permission data address, all of which are accurate to 4K pages, and only return ITLB/DTLB page tables with 4K granularity when permission check is enabled.
* fixed the issue that two requests in Bitmap check were merged and missed the update permission;
* modify the permission query results of Super Page that are no longer cached in PageTableCache;
* fixed the issue of l0Pets splicing format of PageTableCache output;
* fixed the issue that bitmap_checkfailed registers in PTW and HPTW were not reset;
* fixed the issue that bitmapCacheEntry was not initialized;
* fixed the issue of Napot entry jmp_bitmap_check process;
* In BitmapCheck use parameters to selsct cf bits;
=> fix(Bitmap): fix some bugs related to memory isolation

src/main/scala/xiangshan/frontend/IFU.scala, src/main/scala/xiangshan/frontend/icache/ICacheMissUnit.scala, src/main/scala/xiangshan/frontend/icache/InstrUncache.scala
`MemBackTypeMM`: requesting region backed by main memory (`!pmp.mmio`) (don't care pbmt)
`MemPageTypeNC`: requesting `pbmt=nc` region (don't care backtype)
We need to tell L2 Cache about this via Tilelink to make it work.
This PR:
- ICache: Always work on main memory (`!pmp.mmio && pbmt=pmp`)
- `MemBackTypeMM` is always true
- `MemPageTypeNC` is always false (keep default value)
- Ifu/InstrUncache: Might be working on main memory, but pbmt=nc/io. Or on real mmio region
- `MemBackTypeMM = !f3_pmp_mmio`
- `MemPageTypeNC = f3_itlb_pbmt === Pbmt.nc`
=> fix(ICache,Ifu): set memBackTypeMM and memPageTypeNC correctly

src/main/scala/xiangshan/mem/vector/VSegmentUnit.scala
fullva needs to ensure a complete 64-bit width so that the high-bit check in the TLB is correct.
=> fix(VSegmentUnit): adjust the fullva bit width of the tlb req

src/main/scala/xiangshan/cache/mmu/TLB.scala
In the previous design, vaddr was sign-extended to PAddrBits to prevent cases where the physical address width exceeds the virtual address width. However, in the SV48x4 mode, the actual width of vaddr is 50 bits, which ended up being truncated to 48 bits.
In the onlyStage2 case, the generated guest physical address (gpaddr) should match vaddr. But due to the truncation, gpaddr was also limited to 48 bits, and the upper 2 bits were lost (set to zero).
To fix this bug, and to better support future extensions—vaddr is now extended to the maximum physical address width (PAddrBitsMax) as defined by the RISC-V specification.
=> fix(TLB): vaddr should be extended to PAddrBitsMax

src/main/scala/xiangshan/backend/issue/FuBusyTableWrite.scala
Some instances of this module may have io.out not connected. Under normal circumstances, Chisel would not generate these modules, but due to dontTouch here, these modules without io connections are still generated. We do not yet understand the specific reason for this.
However, such Verilog cannot be synthesized on some FPGA platforms, so in order to ensure the uniformity of RTL, we need to remove this code.
=> fix(BusyTable): remove dontTouch to make Verilog cleaner

src/main/scala/xiangshan/backend/Backend.scala, src/main/scala/xiangshan/backend/datapath/NewPipelineConnect.scala, src/main/scala/xiangshan/mem/MemBlock.scala, src/main/scala/xiangshan/mem/lsqueue/LSQWrapper.scala, src/main/scala/xiangshan/mem/lsqueue/StoreMisalignBuffer.scala, src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala, src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala, src/main/scala/xiangshan/mem/vector/VMergeBuffer.scala, src/main/scala/xiangshan/mem/vector/VSplit.scala, src/main/scala/xiangshan/mem/vector/VecBundle.scala
This PR has significant changes. Please consider whether it needs to be merged into V2.  
Two main changes have been made: 
1. Cross-page and vector misaligned memory accesses need to wait until this flow reaches the head of the StoreQueue(scalar cross-page) or until the uop containing this flow reaches the head of the StoreQueue(vector).
2. Modified the IQ issue logic, adjusted the TimeOut duration, and added logic to select the oldest sent based on sqidx/lqidx.
=> fix(misalign): fixed a hang issue caused by vector misalign

src/main/scala/xiangshan/frontend/IFU.scala
The nc (non-cacheable) attribute instructions go through the MMIO channel. Unlike standard MMIO instructions, nc instructions can be executed speculatively. For MMIO instructions, there's no need to check whether the IBuffer is full when enqueuing. However, nc instructions must check for IBuffer fullness.
This PR primarily fixes the issue where nc instructions were incorrectly allowed to enqueue into the IBuffer even when it was full.
=> fix(ifu): fix IBuffer enqueue check for nc instructions.

src/main/scala/xiangshan/Parameters.scala, src/main/scala/xiangshan/frontend/Bundles.scala, src/main/scala/xiangshan/frontend/IBuffer.scala, src/main/scala/xiangshan/frontend/ftq/Ftq.scala, src/main/scala/xiangshan/frontend/ftq/IfuRedirectReceiver.scala, src/main/scala/xiangshan/frontend/ifu/Bundles.scala, src/main/scala/xiangshan/frontend/ifu/FrontendTrigger.scala, src/main/scala/xiangshan/frontend/ifu/Helpers.scala, src/main/scala/xiangshan/frontend/ifu/Ifu.scala, src/main/scala/xiangshan/frontend/ifu/Parameters.scala, src/main/scala/xiangshan/frontend/ifu/PreDecode.scala, src/main/scala/xiangshan/frontend/ifu/PreDecodeBoundary.scala, src/main/scala/xiangshan/frontend/ifu/PredChecker.scala
Supersede https://github.com/OpenXiangShan/XiangShan/pull/4885
Refactor IFU for two-fetch support and IBuffer write bank partitioning：
- Partially removed "first"/"second" naming in two-fetch logic. Some are retained where interface behavior differs significantly to avoid confusion.
- Removed destination address check from preChecker. Based on prior discussions, such checks offer limited benefit and may introduce selective IBuffer flush behavior in two-fetch mode.
- Optimized preChecker timing logic, especially conditions like:  pd.isJal && instrValid(i) && !isPredTaken(i) && !ignore(i). This improves timing of the IBuffer enqEnable signal.
- Initial support for two-fetch added in IFU; still under refinement.
-  Align IFU output data to IBuffer write ports.
- Support IBuffer write …
=> feat(ifu,ibuffer): new ifu for kunminghu-v3 part2

.scalafmt.conf, src/main/scala/utils/EnumUInt.scala
The original design allows 0 for enums like `ExceptionVec`, we use 0 for `None` and one-hot values for each exception, but in this case, `Vec[Bool]` may be preferred.
When using `EnumUInt` for fsm states, etc., we found that allowing 0 is confusing, and may generate redundant logic. Thanks @TheKiteRunner24.
Therefore, in this PR we disallow 0 as one-hot value by default, and developers are prompt to use `Vec[Bool]` or explicitly use `allowZeroForOneHot`.
Also:
- enable scalafmt for `EnumUInt`
- fix a typo
=> fix(EnumUInt): disallow 0 as one-hot value by default

src/main/scala/top/Configs.scala, src/main/scala/xiangshan/L2Top.scala, src/main/scala/xiangshan/Parameters.scala, src/main/scala/xiangshan/XSCore.scala, src/main/scala/xiangshan/XSDts.scala, src/main/scala/xiangshan/XSTile.scala, src/main/scala/xiangshan/cache/wpu/WPU.scala, src/main/scala/xiangshan/frontend/FrontendParameters.scala, src/main/scala/xiangshan/frontend/icache/Bundles.scala, src/main/scala/xiangshan/frontend/icache/Helpers.scala, src/main/scala/xiangshan/frontend/icache/ICache.scala, src/main/scala/xiangshan/frontend/icache/ICacheCtrlUnit.scala, src/main/scala/xiangshan/frontend/icache/ICacheDataArray.scala, src/main/scala/xiangshan/frontend/icache/ICacheImp.scala, src/main/scala/xiangshan/frontend/icache/ICacheMainPipe.scala, src/main/scala/xiangshan/frontend/icache/ICacheMetaArray.scala, src/main/scala/xiangshan/frontend/icache/ICacheMissUnit.scala, src/main/scala/xiangshan/frontend/icache/ICacheMshr.scala, src/main/scala/xiangshan/frontend/icache/ICachePrefetchPipe.scala, src/main/scala/xiangshan/frontend/icache/ICacheReplacer.scala, src/main/scala/xiangshan/frontend/icache/ICacheWayLookup.scala, src/main/scala/xiangshan/frontend/icache/Parameters.scala
- move icacheParameters into coreParams.frontendParameters
- remove unused params
- `nTLBEntries` is already replaced by `itlbParameters.NWays`
- `partWayNum` is actually fixed to `4`, we cannot change it
- `ICacheDataBanks` is actually `blockBytes * 8 / rowBits`
- `replacement` is never used
- drop `ICache` prefix
=> refactor(ICache): use new frontend parameter system

src/main/scala/xiangshan/backend/decode/DecodeUnit.scala, src/main/scala/xiangshan/backend/rename/BusyTable.scala
The ROB compression ratio improved from 1.38 to 1.43 in 0.3 coverage checkpoints.
=> fix(robCompress): enable compression for isLastInFtqEntry insts

src/main/scala/xiangshan/frontend/icache/ICache.scala, src/main/scala/xiangshan/frontend/icache/ICacheImp.scala, src/main/scala/xiangshan/frontend/icache/ICacheMshr.scala, src/main/scala/xiangshan/frontend/icache/Parameters.scala, src/main/scala/xiangshan/frontend/ifu/Ifu.scala, src/main/scala/xiangshan/frontend/instruncache/Bundles.scala, src/main/scala/xiangshan/frontend/instruncache/InstrUncache.scala, src/main/scala/xiangshan/frontend/instruncache/InstrUncacheEntry.scala
- ICache,Ifu,InstrUncache: pick #4898
- ICache: declare MemBackTypeMMField()
- ICache: drop unused PrefetchField()
- ICache: set AliasField correctly
=> fix(ICache,Ifu,InstrUncache): set tilelink user fields correctly

src/main/scala/xiangshan/frontend/IFU.scala
Revert "feat(IFU,Svpbmt): allow speculatve fetch in pbmt.NC (idempotent) spaces (#3944)"
This reverts commit 7d889d887f665295eec9cdb987e037e008f875a6.
=> fix(IFU,Svpbmt): disallow speculatve fetch in pbmt.NC (idempotent) spaces

.github/CODEOWNERS, Makefile, README.md, readme.zh-cn.md, scripts/Makefile.pdb, scripts/pdb-run.py, scripts/xspdb/__init__.py, scripts/xspdb/requirements.txt, scripts/xspdb/xscmd/__init__.py, scripts/xspdb/xscmd/cmd_difftest.py, scripts/xspdb/xscmd/cmd_dut.py, scripts/xspdb/xscmd/cmd_elf.py, scripts/xspdb/xscmd/cmd_files.py, scripts/xspdb/xscmd/cmd_flash.py, scripts/xspdb/xscmd/cmd_info.py, scripts/xspdb/xscmd/cmd_trap.py, scripts/xspdb/xscmd/cmd_wave.py, scripts/xspdb/xscmd/util.py, scripts/xspdb/xspdb.py
XSPdb is a specialized Python pdb-based debugging tool for RISC-V IP cores, customized for Xiangshan's difftest interface. It provides GDB-like interactive debugging capabilities, integrating: Terminal command-line interface, RTL-level waveform toggling, Automated script replay, System snapshot save/restore, Register initialization configuration
* **New Tool (`XSPdb`)**: The core Python scripts for XSPdb have been added under `scripts/xspdb/`. This tool provides an interactive debugging console with standard pdb commands (e.g., breakpoints, step, continue, register inspection).
* **Build System Integration**: A new Makefile, `pdb.mk`, has been created to define the build targets and logic required for XSPdb.
* **Makefile Modification**: The root Makefile has been updated to include …
=> feat(pdb): Add XSPdb, a GDB-like interactive debugger for XiangShan

src/main/scala/xiangshan/frontend/bpu/Abstracts.scala, src/main/scala/xiangshan/frontend/bpu/Bpu.scala, src/main/scala/xiangshan/frontend/bpu/FallThroughPredictor.scala, src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtb.scala, src/main/scala/xiangshan/frontend/bpu/ittage/Ittage.scala, src/main/scala/xiangshan/frontend/bpu/mbtb/MainBtb.scala, src/main/scala/xiangshan/frontend/bpu/ras/Ras.scala, src/main/scala/xiangshan/frontend/bpu/tage/Tage.scala, src/main/scala/xiangshan/frontend/bpu/ubtb/MicroBtb.scala
Fix #4962 simv failure.
#4962 seems to have other problem, so instead merging this to it, I'd suggest merging this to kunminghu-v3 first and rebase #4962 later.
The root cause of that failure is we send read requests to mbtb/tage before their sram ready. #4946/kunminghu-v3 can pass CI because we don't have Bpu.io.train before #4962, chisel can opt-out train-related code, including the failure assertion.
From SRAMTemplate:
```scala
private val singleHold = if(singlePort) io.w.req.valid else false.B
private val resetHold = if(shouldReset) resetState else false.B
io.r.req.ready := !resetHold && !singleHold && !conflictStallRead
```
We cannot connect `io.r.req.ready` directly to `s0_fire`, that forms a combinational loop in tage. So we use a resetDone register to block requests until Sram …
=> fix(Bpu): wait Sram reset to avoid x-state

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
See [fix(LoadUnit): reaccess the data even if it is a fast replay by Maxpicca-Li · Pull Request #4965 · OpenXiangShan/XiangShan](https://github.com/OpenXiangShan/XiangShan/pull/4965) for bug details.
=> fix(LoadUnit): reaccess the data even if it is a fast replay

src/main/scala/xiangshan/Bundle.scala, src/main/scala/xiangshan/Parameters.scala, src/main/scala/xiangshan/backend/BackendParams.scala, src/main/scala/xiangshan/backend/Bundles.scala, src/main/scala/xiangshan/backend/CtrlBlock.scala, src/main/scala/xiangshan/backend/datapath/BypassNetwork.scala, src/main/scala/xiangshan/backend/fu/FuncUnit.scala, src/main/scala/xiangshan/backend/fu/Jump.scala, src/main/scala/xiangshan/backend/fu/wrapper/BranchUnit.scala, src/main/scala/xiangshan/frontend/Bundles.scala, src/main/scala/xiangshan/frontend/IBuffer.scala, src/main/scala/xiangshan/frontend/ftq/IfuRedirectReceiver.scala, src/main/scala/xiangshan/frontend/ifu/Bundles.scala, src/main/scala/xiangshan/frontend/ifu/Helpers.scala, src/main/scala/xiangshan/frontend/ifu/Ifu.scala, src/main/scala/xiangshan/frontend/ifu/PreDecodeBoundary.scala, src/main/scala/xiangshan/frontend/ifu/PredChecker.scala
- feat(ifu): Switch cross-predict-block instructions from read to wait for concatenation.
- feat(backend): read pc support new ftqOffset from frontend.
- feat(ibuffer): instrOffset to backend now points to instruction end instead of start.
This PR does not handle the case where an MMIO instruction crosses a page boundary. When a single MMIO instruction spans across pages, it may generate a prediction block that contains no valid instructions. Due to the blocked speculative execution policy, this can lead to a deadlock. Since the MMIO fetch strategy will undergo significant changes, we will not add temporary workaround code here. The issue is expected to be fixed together with the MMIO strategy update in a subsequent PR.
=> feat(ifu,ibuffer,backend): adjust instrEndOffset calculation and cross-predict-block handling

src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala
- The Bug occurs when L2TLB handle allStage and noS2xlate request in same time
=> fix(Bitmap): add first_s2xlate_fault init when LLPTW handle jmp_bitmap_check request

src/main/scala/xiangshan/frontend/bpu/ittage/Ittage.scala
This PR fixes 2 assertion failures in Ittage:
1. `t1_meta` is a RegEnable without init, causing x-prop to `updateTotalHits`
https://github.com/OpenXiangShan/XiangShan/blob/75646f33f43e6682163370f217e497a19238d8b5/src/main/scala/xiangshan/frontend/bpu/ittage/Ittage.scala#L131-L134
https://github.com/OpenXiangShan/XiangShan/blob/75646f33f43e6682163370f217e497a19238d8b5/src/main/scala/xiangshan/frontend/bpu/ittage/Ittage.scala#L315-L318
https://github.com/OpenXiangShan/XiangShan/blob/75646f33f43e6682163370f217e497a19238d8b5/src/main/scala/xiangshan/frontend/bpu/ittage/RegionWays.scala#L70-L80
2. resolve train may send target=0 to Bpu
So Ittage will predict target=0 with the same pc
=> fix(Ittage): fix CI assertion failure

Makefile, src/main/scala/top/ArgParser.scala, src/main/scala/xiangshan/Parameters.scala, src/test/scala/xiangshan/frontend/FrontTrigger.scala
To prevent non-synthesizable (?) hierarchy XMR.
=> feat(build): add `DISABLE_XMR` to use `bore` instead of `tapAndRead`

src/main/scala/top/Configs.scala, src/main/scala/xiangshan/frontend/FrontendParameters.scala, src/main/scala/xiangshan/frontend/ifu/PreDecodeBoundary.scala, src/main/scala/xiangshan/frontend/ifu/PredChecker.scala
Also:
- Fix unportable code (use of magic number) in PreDecodeBoundary & PredChecker
For MinimalConfig, we still do 32B fetch, it has `IBufferSize = 24`, but we need `IBufferSize >= FetchBlockSize / 2 + IBufferWriteBanks` to make it work. Since we don't care about performance to much with MinimalConfig, I'd rather decreasing FetchBlockSize instead of increasing IBufferSize.
~~Test ci now, should rebase after #4999, also wait for V3 parameter system in Ifu & IBuffer for cleaner parameters:~~
=> feat(Frontend): increase FetchBlockSize to 64B

src/main/scala/xiangshan/frontend/Bundles.scala, src/main/scala/xiangshan/frontend/ftq/Ftq.scala
`backendException` is a Reg and `backendRedirect` is a RegNext, we have:
1. cycle 0: `backendRedirect.valid && (backendRedirect.bits.backendIPF || backendRedirect.bits.backendIPF || backendRedirect.bits.backendIPF)`
2. cycle 1: `backendException.hasException`, but `!backendRedirect.valid`
So `backendExceptionPtr` is not written unless we have a old backendException
=> fix(Ftq): add ExceptionType.fromBackend & fix write condition in Ftq

src/main/scala/xiangshan/frontend/bpu/Abstracts.scala, src/main/scala/xiangshan/frontend/bpu/Bpu.scala, src/main/scala/xiangshan/frontend/bpu/FallThroughPredictor.scala, src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtb.scala, src/main/scala/xiangshan/frontend/bpu/abtb/Parameters.scala, src/main/scala/xiangshan/frontend/bpu/ittage/Parameters.scala, src/main/scala/xiangshan/frontend/bpu/mbtb/Parameters.scala, src/main/scala/xiangshan/frontend/bpu/ras/Parameters.scala, src/main/scala/xiangshan/frontend/bpu/sc/Parameters.scala, src/main/scala/xiangshan/frontend/bpu/tage/Parameters.scala, src/main/scala/xiangshan/frontend/bpu/ubtb/Parameters.scala
- Add a `EnableFastTrain` parameter to `BasePredictor`
- ubtb can switch between fast train and resolve train
- abtb can only be fast-trained currently, we don't have continuous predict block on resolve, so we don't have `previousPc` used to index SRAM
- S3 predictors cannot be fast-trained, as fast training data is generated by them
- Currently we don't have S3 predictors available, so:
- ubtb has `EnableFastTrain = false` by default
- abtb is disabled completely
- We'll change these in a future PR
=> feat(Bpu): fast train for s1 predictor

.github/workflows/emu.yml
Hopefully this will fix CI failure due to Upload Artifact (on GitHub hosted runner, with only 16G mem) OOM:
Local analysis by jvisualvm shows we need 8.8G heap mem at peak (JVM_XMX=16G with default gc strategy), so maybe we can reduce JVM_MAX from 16G to 10G to trigger gc more frequently, and use less mem.
And, we can clean up unused pre-installed tool to reclaim more space for swap (refer to https://github.com/actions/runner-images/issues/709#issuecomment-612569242), though we're utilizing `/mnt` now and it seems the disk space is already enough. Then we can increase swapfile size.
Also: fix typo
=> misc(ci): increase swap & decrease JVM_XMX to avoid oom

src/main/scala/xiangshan/frontend/icache/Bundles.scala, src/main/scala/xiangshan/frontend/icache/ICacheImp.scala, src/main/scala/xiangshan/frontend/icache/ICacheMainPipe.scala, src/main/scala/xiangshan/frontend/icache/ICachePrefetchPipe.scala, src/main/scala/xiangshan/frontend/icache/ICacheWayLookup.scala
In v3 Ftq, we have `redirect` to Bpu and `redirectNext` to prefetch, therefore bp1=pf0. In this case, when an s1 prediction is overridden by s3, it can reach at most pf2/if1 (i.e. in prefetchPipe `s2` stage reg, wayLookup `entries(writePtr - 1)`, or mainPipe `s1` stage reg). In old design, we only flush pf1, that could be wrong.
Though, we don't have to flush prefetchPipe s2, anyway it's prefetch and has no impact on control flow. (If we don't flush it, it can be seen as some sort of wrong-path prefetch).
So, in this PR we implement wayLookup & mainPipe s1 flush from Bpu s3 override.
NOTE: To reduce implementation cost, wayLookup assumes that we can flush at most 1 entry at tail, this could be wrong if we have Bpu s4/5/even more flush in the future. See comments there.
=> fix(ICache): bpu s3 flush waylookup & mainPipe s1
