src/main/scala/xiangshan/Bundle.scala

Redirect in ExuInput is used to flush the function unit itself.
Redirect in ExuOutput is used to flush other function units.
Just ROB, bru(can exec jal/jalr/csr instrs) and alu(can exec
branch instrs) can generate redirect.

Bundle/ExuIO: add redirect to ExuInput and ExuOutput

---

src/main/scala/xiangshan/backend/rename/FreeList.scala

由于rename机制现在还存在问题，为了能够运行dummy第一条指令，暂时把物理寄存器0号移出freelist。
这个改动只能保证第一条指令能够被正常提交，但仍然存在问题，比如0号寄存器之后会被回收。
这个commit之后，指令可以正确提交了

freelist: init freelist without preg0

---

src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/utils/LogUtils.scala

使用implict module会污染生成的fir中的模块名

Log: use implict module name instead implict module

---

src/main/scala/xiangshan/frontend/FakeIFU.scala
src/main/scala/xiangshan/frontend/Ibuffer.scala

Ibuffer:Fixed instr error after flush

---

src/main/scala/xiangshan/frontend/Ibuffer.scala

给Ibuffer调试信息添加了valid和ready位，且当io.out.ready不为true时会重复输出缓存中前6条32位指令，当缓存为空时会输出全0

Ibuffer: Change XSLog information

---

Makefile

* Previously there is a cpp file called xxx__ALLcls.cpp, which includes
nearly all other cpp files. Such a big cpp file will be compiled. And
it can not leverage parallel jobs with Makefile.
* To enbale parallel build, we should pass VM_PARALLEL_BUILDS=1 to the
Makefile to generate emu.

Makefile: support parallel build with emu

---

build.sbt
build.sc

* This will also bump firrtl to 1.3.2. It seems that the performance of
firrtl compile time is greatly improved. On 9700k, it is improved from
218104.5 ms to 135609.5 ms.

bump chisel to 3.3.2

---

Makefile
src/main/scala/system/SoC.scala
src/test/csrc/emu.h

1. disable l2 cache and prefetcher to increase emulation speed
2. support running emu on remote machine (fix remote image directory)

disable l2cache/l2prefetcher, support remote run-emu

---

.metals/metals.lock.db
src/main/scala/xiangshan/frontend/Ibuffer.scala

优化了IBuffer生成verilog代码太多的问题，现在生成的Verilog文件总行数661369行，其中IBuffer占93890行
删除了.metal目录，该目录是由vscode scala metal插件生成，插件开启时该目录不可被删除，可能会导致git的使用出现问题

IBuffer: Make verilog optimize, cputest passed

---

src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/backend/Backend.scala
src/main/scala/xiangshan/backend/decode/DecodeBuffer.scala
src/main/scala/xiangshan/backend/rename/Rename.scala

By blocking inst at rename (not ibuffer), ipc of microbench test can improve form 0.618 to 0.629

Optimize pipeline

---

src/main/scala/utils/LogUtils.scala
src/test/scala/top/XSSim.scala

* this helps to recude about 40k lines of code, and improve the host
time spent from 89s to 93s for running microbench with test input on
9900k

utils,LogUtils: reduce the number of GTimer()

---

debug/cputest.sh
src/main/scala/xiangshan/backend/brq/Brq.scala
src/main/scala/xiangshan/backend/roq/Roq.scala
src/main/scala/xstransforms/ShowPrintTransform.scala
src/test/scala/top/XSSim.scala

1.Brq: use mem instead vec, reduce verilog code from 6.7w lines to 2.1w lines
2.Roq: rewrite roq, reduce verilog code from 7w+ lines to 5w+ lines
3.ShowPrintfTransform: a custom transform to help us disable printf in every module
4.debug/cputest.sh

Optimize brq and roq; Add a firrtl transform

---

src/main/scala/xiangshan/backend/roq/Roq.scala

For nested redirect (redirect.valid when ROB is walking), if ROB is in extrawalk state, walkPtrExt should not be changed.

roq: dont update walkPtrExt when brqRedirect.valid in extrawalk

---

src/test/csrc/emu.cpp

We need to asynchronous reset the system when reset is true.
In verilator model, it's done by always resetting the external devices when reset is true.
After the reset signal is released, we call init once for external devices to make sure they are correctly reset.

emu: asynchronous reset ram

---

src/test/csrc/ram.cpp
src/test/vsrc/ram.v

Previously, the RAM is synchronous.
However, due to verilator issues, the bug is hidden by Buffer that includes FFs.
The buffer works as follows (simplified):
```
always @(posedge clk)
data_out <= data_form_ram_helper;
```
data_from_ram_helper is given by (synchronous read):
```
always @(posedge clk)
ram_helper(raddr, data_from_ram_helper);
```
At every positive edge, data_out should be assigned with data_from_ram_helper_old,
and data_from_ram_helper should then be evaluated to the new value during the next clock cycle.
However, verilator evaluates data_from_ram_helper first and then assigns it to data_out,
that is, data_out is incorrectly assigned by data_from_ram_helper.
For example, verilator gives the following sequence:
```
raddr    data_from_ram_helper     data_out
0               X …
```

ram: use asynchronous ram and change dpi-c function prototype

---

Makefile
src/test/csrc/emu.cpp

make emu 的时候使用ENABLESNAPSHOT=1来打开snapshot，hit good trap的时候不会保存snapshot

snapshot: add enable macro to be configable

---

src/test/csrc/emu.cpp
src/test/csrc/emu.h
src/test/csrc/main.cpp

Now able to use `-I NUM` or `--max-instr NUM` to set instructions limit when running cpu
modify Emulator::execute function argument list from (uint64_t n) to (uint64_t max_cycle, uint64_t max_instr)

Add --max-instr option for emu

---

Makefile
src/test/csrc/emu.cpp

This pull request replaces $fatal with $finish in the verilog file to avoid verilator abort on assertions.
By replacing $fatal with $finish, the simulation framework takes control of the simulation when assertion failed.

replace $fatal with $finish to avoid verilator abort

---

src/main/scala/system/SoC.scala
src/main/scala/xiangshan/XSCore.scala

This pull request moves L2 cache out of XSCore. L2 cache should be in SoC system-level.

SoC: move l2cache to SoC

---

src/main/scala/xiangshan/backend/brq/Brq.scala

This pull request optimizes Brq's timing. 
* add redirectPtr to keep track of the writeback branch instruction
* set isMisPred when sending redirect instead of exu writing back

brq: optimize timing

---

src/main/scala/utils/DataModuleTemplate.scala
src/main/scala/xiangshan/backend/roq/Roq.scala
src/main/scala/xiangshan/package.scala

This pull request wraps data, deqPtr, enqPtr in Roq into separate modules. This helps physical design optimizations.

Roq: wrap data, deqPtr, enqPtr into separate modules

---

src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/mem/lsqueue/LSQWrapper.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueue.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

Fp load uses different wb port from int load for 2 reasons:
* Fp load needs recode, which is quite slow. We need one complete cycle
for recoding.
* Fp load data has nothing to do with int load data. There is no reason
to mix them together.
An extra recode stage (load_s3) is added for fp load, while int load will
still be writebackd at load_s2.

LoadUnit, LoadQueue: add independent fp load wb port

---

src/main/scala/system/SoC.scala

Make L3 cache see the address without fixed bankBits.
Example address convert log (microbench)
```
[INFO ][time= 2049] TOP.XSSimSoC.soc.c: before bank 0 A in addr 0080000000 -> out addr 0020000000
[INFO ][time= 2052] TOP.XSSimSoC.soc.c_4: after bank 0 A in addr 0020000000 -> out addr 0080000000
[INFO ][time= 2238] TOP.XSSimSoC.soc.c: before bank 0 A in addr 0080004100 -> out addr 0020001040
[INFO ][time= 2239] TOP.XSSimSoC.soc.c: before bank 0 A in addr 0080005900 -> out addr 0020001640
[INFO ][time= 2241] TOP.XSSimSoC.soc.c_4: after bank 0 A in addr 0020001040 -> out addr 0080004100
[INFO ][time= 2244] TOP.XSSimSoC.soc.c_4: after bank 0 A in addr 0020001640 -> out addr 0080005900
[INFO ][time= 2466] TOP.XSSimSoC.soc.c: before bank 0 A in addr 0080004c00 -> out addr 0020001300
[INFO …
```

L3,bank: modify address to avoid dead setBits

---

src/main/scala/xiangshan/cache/icache.scala

In case that the s3 miss request is flushed but it is replay again in
s3, resulting in the counter increasing twice or more.

icache: change icache miss perf register condition.

---

src/main/scala/xiangshan/mem/lsqueue/LoadQueue.scala

This reverts commit 2e0406ca0691ebda089d4b26e1012594c7544e7f.
* It causes CoreMark IPC drop 0.1 for unknown reasons
* As it may harm timing as well, we remove it from master for now

Revert "LoadQueue: select load refilled this cycle for wb"

---

src/main/scala/xiangshan/cache/icache.scala

this commit has two motivations:
1. fix the bug of not sending valid instruction when ipf && !icahce_hit
2. save the delay of adding a mux of huge width before sending instr to predecode

icache: when ipf we modify pd resp instead of pd input

---

src/main/scala/xiangshan/cache/icache.scala

Previously, we only give the first instrcution to backend when the
packet causes a page fault. It will be stuck if not because waymask is 0
because no hit but hit includes ipf. So we seperates them.

icache: fix ipf bug

---

src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/mem/lsqueue/LSQWrapper.scala
src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
src/main/scala/xiangshan/mem/sbuffer/NewSbuffer.scala

When sbuffer checks if it is empty, it needs to check if sq is also empty
so there is no pending store. Errors will emerge rarely if we do not
check sq.

sbuffer: add sq empty check

---

src/main/scala/system/SoC.scala
src/main/scala/utils/DataDontCareNode.scala

This effectly reduces the number of bus data wires from 256 * 3 to 256 * 2.
Use DataDontCareNode to add DontCare to the tilelink nodes you are
interested in.

Use DontCare to remove L2 inner A channel's data field.

---

src/main/scala/system/SoC.scala
src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/cache/icache.scala
src/main/scala/xiangshan/cache/icacheMissQueue.scala
src/main/scala/xiangshan/frontend/Frontend.scala
src/main/scala/xiangshan/frontend/IFU.scala

icache:  use 16 * (64 * 144) SRAM
icacheMissQueue: fix flush when state is s_write_back bug
IFU: if1_can_go use if3_flush
SoC/XSCore/Frontend:  move instruction uncache to Frontend.

Icache uncache

---

src/main/scala/utils/Replacement.scala
src/main/scala/xiangshan/cache/L1plusCache.scala
src/test/scala/cache/ReplaceTest.scala

We use s1_addr address to keep the index for reading valid array when pipeline is blocking.

Fix l1plus double hit problem and random replace bug

---

src/main/scala/xiangshan/frontend/IFU.scala
src/main/scala/xiangshan/frontend/uBTB.scala

We pass redirect ghist directly to a mux, whose output is connected
to bpu.s1_hist, so that the delay of three cascaded 64-bit-wide 2-1
mux could be saved

ifu: opt timing of redirect ghist

---

src/main/scala/utils/Replacement.scala
src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/cache/ICache.scala
src/main/scala/xiangshan/cache/L1plusCache.scala

1. ICache, L1plus Cache now support multi-access for plur state.
2. Delete state change in way method, instead use multi-access logic.

Fix replacement policy and change replacement policies for L1I, L1+

---

src/main/scala/xiangshan/backend/roq/Roq.scala

Previously, we use !flushPipe to reduce serveral or gates.
However, when an instruction has instruction page fault or access fault,
the instruction may be decoded as any instructions, which possibly generates flushPipe.
Thus, previously an instruction with exceptions may trigger a flushPipe instead of exceptions.
Now we use exceptionVec.asUInt.orR to see whether it has exceptions.

Roq: use exceptionVec.asUInt.orR to check whether there're exceptions

---

src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/backend/CtrlBlock.scala
src/main/scala/xiangshan/backend/decode/DecodeUnit.scala
src/main/scala/xiangshan/backend/dispatch/Dispatch1.scala
src/main/scala/xiangshan/backend/fu/CSR.scala
src/main/scala/xiangshan/backend/fu/util/CSRConst.scala
src/main/scala/xiangshan/backend/rename/Rename.scala
src/main/scala/xiangshan/backend/roq/Roq.scala

In this commit, we add support for a simpler version of move elimination.
The original instruction sequences are:
move r1, r0
add r2, r1, r3
The optimized sequnces are:
move pr1, pr0
add pr2, pr0, pr3 # instead of add pr2, pr1, pr3
In this way, add can be issued once r0 is ready and move seems to be eliminated.

Add support for a simple version of move elimination

---

.github/workflows/emu.yml

Previously we use numactl to specify both nodes and cpus for emu.
However, when other processes are using the same cpu, verilated emu
suffers from huge performance degradation. To avoid these scenarios,
we only specify the numa node to achieve a more stable performance.

ci-runner: only specify a numa node for performance stability

---

src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/backend/issue/ReservationStation.scala
src/main/scala/xiangshan/cache/ICache.scala
src/main/scala/xiangshan/cache/TLB.scala
src/main/scala/xiangshan/mem/pipeline/AtomicsUnit.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala

just record the tlb result(access and miss) of first issue by adding
signal isFirstIssue (isFirstIssue = cntCountQueue(i) === 0.U)

RS & DTLB: fix bug of dtlb's hit perf counter

---

src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/backend/ftq/Ftq.scala
src/main/scala/xiangshan/frontend/BPU.scala
src/main/scala/xiangshan/frontend/Btb.scala
src/main/scala/xiangshan/frontend/IFU.scala
src/main/scala/xiangshan/frontend/uBTB.scala

* add perf counters for btb and ubtb
* update btb only on not hit or jalr mispredicts to reduce write stalls

btb: use single port sram to meet timing constraints

---

src/main/scala/device/AXI4SlaveModule.scala
src/main/scala/device/TLTimer.scala
src/main/scala/system/SoC.scala
src/main/scala/utils/DataDontCareNode.scala
src/main/scala/utils/DebugIdentityNode.scala
src/main/scala/utils/PerfCounterUtils.scala
src/main/scala/utils/Replacement.scala
src/main/scala/utils/TLDump.scala
src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/cache/DCacheWrapper.scala
src/main/scala/xiangshan/cache/ICacheMissQueue.scala
src/main/scala/xiangshan/cache/InstrUncache.scala
src/main/scala/xiangshan/cache/L1plusCache.scala
src/main/scala/xiangshan/cache/PTW.scala
src/main/scala/xiangshan/cache/Uncache.scala
src/main/scala/xiangshan/cache/prefetch/L2Prefetcher.scala
src/main/scala/xiangshan/frontend/Frontend.scala
src/test/scala/cache/L1DTest/L1DTest.scala
src/test/scala/cache/L1plusCacheTest.scala
src/test/scala/cache/L2CacheNonInclusiveGetTest.scala
src/test/scala/cache/L2CacheTest.scala
src/test/scala/cache/TLCTest/TLCTest.scala
src/test/scala/cache/TLCTest/TLMasterMMIO.scala
src/test/scala/cache/TLCTest/TLSlaveMMIO.scala
src/test/scala/cache/TLCTest/TLULMMIO.scala
src/test/scala/cache/UnalignedGetTest.scala

Because we use '%m' to print instance name, trait 'HasXSLog' and implicit val 'moduleName' should be removed.

LogUtils: remove trait 'HasXSLog'

---

src/main/scala/xiangshan/cache/ICache.scala

SyncReadMem generates the verilog behavior model whose output rdata is always
mem(RegNext(raddr)). Accidentally, ICache will not change meta and data
SRAMs' raddr if the second pipeline stage is stalled (and ren is false).
Thus, the SRAMs seem to have the holdRead property.
Obviously, it will cause errors on real SRAMs. We set holdRead to true to fix the bug.

ICache: set holdRead to true for meta and data SRAMs

---

Makefile
src/main/scala/xiangshan/cache/ICache.scala
src/main/scala/xiangshan/cache/L1plusCache.scala

Previously we don't use the --infer-rw and --repl-seq-mem flags for simulation verilog.
However, the SyncReadMem fails to generate random read data when ren is not set.
In this commit, SyncReadMem is changed to blackboxes and generated by the vlsi_mem_gen script.
RANDOMIZE_GARBAGE_ASSIGN flag is defined to enable randomization.
Merge this PR after #738, #736.

Makefile: enable SRAM randomization for verilator simulation

---

Makefile
build.sc

Bump chisel to v3.4.3 and re-add `-X verilog` parameter for chisel runs.
Our transform seems to have conflicts when `-X verilog` is not set.
This PR should fix the bug that 9527 is not replaced by %m.

build.sc: bump chisel to v3.4.3

---

src/main/scala/xiangshan/cache/PTW.scala

Previously we RegNext sfence for ITLB and DTLB, but we ignored PTW.
It will cause errors when both sfence.valid and req.fire() are set.

PTW: use RegNext(io.sfence) for sfence-related logic

---

src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/backend/FloatBlock.scala
src/main/scala/xiangshan/backend/IntegerBlock.scala
src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/backend/dispatch/Dispatch.scala

In this commit, we add performance counters for dispatch and issue stages
to track the number of instructions dispatched and issued. Active regfile
read ports are counted as ready instruction source registers.

Add dispatch and issue performance counters

---

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

MMIO should never hit in DCache. However, DCache does not guarantee the miss
is strictly according to the vaddr, paddr provided by the pipeline, when the
load is killed. That is, DCache may response valid = false and miss = false
when the MMIO instruction is accessed and then killed.

LoadUnit: block writeback when the instruction is an MMIO access

---

Makefile.emu

Pipe causes the return value of make command ignored. Pipe is disabled for
cpp compilation output until we find an elegant solution to exit on errors.

Makefile.emu: temporarily disable pipe for EMU_COMPILE

---

Makefile.emu
src/main/scala/system/SoC.scala
src/main/scala/top/Top.scala
src/main/scala/utils/TLIgnoreNode.scala
src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/cache/DCacheWrapper.scala
src/main/scala/xiangshan/cache/L1plusCache.scala
src/main/scala/xiangshan/cache/PTW.scala
src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
src/test/csrc/common/ram.cpp
src/test/csrc/common/ram.h
src/test/csrc/difftest/difftest.cpp
src/test/csrc/difftest/difftest.h
src/test/csrc/difftest/ref.cpp
src/test/csrc/difftest/ref.h
src/test/vsrc/ref.v

In this commit, we add support for using DPI-C calls to replace
DCache, PTW and L1plusCache. L2Cache and L3 Cache are also allowed to
be ignored or bypassed. Configurations are controlled by useFakeDCache,
useFakePTW, useFakeL1plusCache, useFakeL2Cache and useFakeL3Cache.
However, some configurations may not work correctly.

cache: support fake dcache, ptw, l1pluscache, l2cache and l3cache

---

src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/backend/decode/DecodeUnit.scala
src/main/scala/xiangshan/backend/dispatch/Dispatch1.scala
src/main/scala/xiangshan/backend/dispatch/Dispatch2Fp.scala
src/main/scala/xiangshan/backend/dispatch/Dispatch2Int.scala
src/main/scala/xiangshan/backend/dispatch/Dispatch2Ls.scala
src/main/scala/xiangshan/backend/fu/Fence.scala
src/main/scala/xiangshan/backend/issue/ReservationStation.scala
src/main/scala/xiangshan/backend/rename/Rename.scala

This commit uses Vec for lsrc, psrc, srcState and srcType in MicroOp bundle.
This makes uop easier to access.

bundle,uop: use Vec for lsrc, psrc, srcState and srcType

---

src/main/scala/xiangshan/backend/dispatch/DispatchQueue.scala

This commit fixes the bug when redirect.valid and the last valid instruction is in the last slot.
Previously the tailPtr becomes size.U when there're no instructions before headPtr. It works fine
when DispatchQueueSize is power2.

DispatchQueue: wrap around tailPtr index when redirect

---

src/main/scala/system/SoC.scala
src/main/scala/top/ArgParser.scala
src/main/scala/top/Config.scala
src/main/scala/top/Configs.scala
src/main/scala/top/Top.scala
src/main/scala/xiangshan/Parameters.scala
src/test/scala/top/SimTop.scala

MinimalConfig limited queues' size, disabled TAGE to limit generated
verilog size
Usage: change `config = DefaultConfig` to `config = MinimalConfig`
in Top.scala / SimTop.scala

Config: add MinimalConfig

---

src/main/scala/device/AXI4IntrGenerator.scala
src/test/scala/top/SimMMIO.scala
src/test/scala/top/SimTop.scala

This commit adds a new AXI4 device to generate external interrupts.
Previously none of the simulated external devices trigger interrupts.
To test external interrupts, we add this device.

device: add AXI4IntrGenerator to generate external interrupts

---

src/test/csrc/difftest/difftest.cpp
src/test/csrc/difftest/difftest.h
src/test/csrc/difftest/goldenmem.cpp
src/test/csrc/verilator/emu.cpp
src/test/csrc/verilator/emu.h
src/test/csrc/verilator/main.cpp

Refactor is still required to resolve the conflict when --max-instr=NUM and --no-diff are enabled simultaneously

difftest: support --no-diff arg to emulate without difftest by nemu

---

src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/backend/CtrlBlock.scala
src/main/scala/xiangshan/backend/FloatBlock.scala
src/main/scala/xiangshan/backend/IntegerBlock.scala
src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/backend/Scheduler.scala
src/main/scala/xiangshan/backend/dispatch/Dispatch.scala
src/main/scala/xiangshan/backend/dispatch/Dispatch2Fp.scala
src/main/scala/xiangshan/backend/dispatch/Dispatch2Int.scala
src/main/scala/xiangshan/backend/dispatch/Dispatch2Ls.scala
src/main/scala/xiangshan/backend/issue/DataArray.scala
src/main/scala/xiangshan/backend/issue/PayloadArray.scala
src/main/scala/xiangshan/backend/issue/ReservationStation.scala
src/main/scala/xiangshan/backend/issue/SelectPolicy.scala
src/main/scala/xiangshan/backend/issue/StatusArray.scala

This PR adds an non-parameterized scheduler containing all reservation stations. Now IntegerBlock, FloatBlock, MemBlock contain only function units. The Schduler connects dispatch with all function units.
Parameterization to be added later.

backend: wrap all RS into a larger scheduler module

---

src/test/csrc/vcs/main.cpp

#856 splits `difftest_init` and `nemuproxy_init`, which makes vcs not work correctly. This PR fixes it.

test,vcs: fix init order of difftest and nemu

---

src/main/scala/xiangshan/backend/exu/JumpExeUnit.scala
src/main/scala/xiangshan/backend/fu/CSR.scala
src/main/scala/xiangshan/backend/fu/Fence.scala

mstatus.tvm: trap virtual memory
When tvm is set and priv mode is s-mode, access to satp and sfence.vma are disallowed and will raise illegal instr exception.
tvm helps to manage guest os.
See priv isa mannual for more info.

mstatus.tvm: add tvm check for satp access and sfence.vma

---

src/test/csrc/verilator/emu.cpp

When --no-diff option is enable, nemuproxy should not be initialized, to avoid the dependence on NEMU.

test,verilator: --no-diff should not init nemu

---

src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/backend/Scheduler.scala
src/main/scala/xiangshan/backend/issue/ReservationStation.scala
src/main/scala/xiangshan/backend/issue/StatusArray.scala

This commit adds support for multiple enqueue for load and store RS.
Also update the parameters in XSCore to avoid explicitly setting wakeup ports.

scheduler: allow multiple-dequeue RS for load and store

---

src/main/scala/xiangshan/backend/issue/ReservationStation.scala
src/main/scala/xiangshan/backend/issue/SelectPolicy.scala
src/main/scala/xiangshan/backend/issue/StatusArray.scala

This commit adds an age matrix to reservation station to find
the oldest instruction. This enables the RS to schedule the oldest
instruction first.

backend, rs: add an age matrix to find the oldest instruction

---

.github/workflows/emu.yml

This commit changes how performance data file is named. Previously
we use GITHUB_SHA or pull_request.head.sha. However, we cannot easily
get the sha or they do not work for master branch.

github,ci: use action id for perf data filename

---

src/main/scala/xiangshan/XSCore.scala

This commit changes how to organize reservation stations in the
second ExuBlock. Now the second ExuBlock accepts MUL, MUL, STD, STD.
The int regfile in this ExuBlock becomes 6R8W.

backend: change the second regfile to 6R8W

---

src/main/scala/xiangshan/backend/issue/BypassNetwork.scala
src/main/scala/xiangshan/backend/issue/ReservationStation.scala

This commit adds another bypass network implementation to optimize timing of the first stage of function units.
In BypassNetworkLeft, we bypass data at the same cycle that function units write data back. This increases the length of the critical path of the last stage of function units but reduces the length of the critical path of the first stage of function units. Some function units that require a shorter stage zero, like LOAD, may use BypassNetworkLeft.
In this commit, we set all bypass networks to the left style, but we will make it configurable depending on different function units in the future.

rs,bypass: add left and right bypass strategy

---

src/main/scala/xiangshan/backend/ExuBlock.scala
src/main/scala/xiangshan/backend/exu/Exu.scala

This commit optimizes ExuBlock timing by connecting writeback when
possible.
The timing priorities are RegNext(rs.fastUopOut) > fu.writeback >
arbiter.out(--> io.rfWriteback --> rs.writeback). The higher priority,
the better timing.
(1) When function units have exclusive writeback ports, their
wakeup ports for reservation stations can be connected directly from
function units' writeback ports. Special case: when the function unit
has fastUopOut, valid and uop should be RegNext.
(2) If the reservation station has fastUopOut for all instructions
in this exu, we should replace io.fuWriteback with RegNext(fastUopOut).
In this case, the corresponding execution units must have exclusive
writeback ports, unless it's impossible that rs can ensure the
instruction is able to write the regfile.
(3) …

backend,exu: connect writeback when possible

---

src/main/scala/xiangshan/backend/ExuBlock.scala
src/main/scala/xiangshan/backend/exu/Exu.scala
src/main/scala/xiangshan/backend/exu/FmacExeUnit.scala
src/main/scala/xiangshan/backend/exu/WbArbiter.scala
src/main/scala/xiangshan/backend/fu/FunctionUnit.scala
src/main/scala/xiangshan/package.scala

This commit adds fastUopOut support for pipelined function units via
implementing fastUopOut in trait HasPipelineReg.
The following function units now support fastUopOut:
- MUL
- FMA
- F2I
- F2F

backend, fu: support fastUopOut for pipelined fu

---

src/main/scala/xiangshan/backend/exu/Exu.scala
src/main/scala/xiangshan/backend/exu/FmiscExeUnit.scala
src/main/scala/xiangshan/backend/fu/FunctionUnit.scala
src/main/scala/xiangshan/backend/fu/InputBuffer.scala
src/main/scala/xiangshan/package.scala

This commit adds an 8-entry buffer for fdivSqrt function unit input.
Set hasInputBuffer to true to enable input buffers for other function
units.

backend,fu: add InputBuffer for fdivSqrt

---

src/main/scala/device/AXI4DummySD.scala
src/main/scala/utils/BitUtils.scala
src/main/scala/xiangshan/backend/fu/CSR.scala

This commit adds assertion in MaskData to check the width of mask
and data. When the width of mask is smaller than the width of data,
(~mask & data) and (mask & data) will always clear the upper bits
of the data. This usually causes unexpected behavior.
This commit adds explicit width declarations where MaskData is used.

utils,MaskData: assert wmask is wider than data

---

src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/backend/decode/DecodeUnit.scala
src/main/scala/xiangshan/backend/rename/Rename.scala
src/main/scala/xiangshan/backend/rename/freelist/MEFreeList.scala
src/main/scala/xiangshan/backend/roq/Roq.scala

**new feature**: instructions like `mv foo,x0` or `li foo,0` can be eliminated now.
**bug fix**: when eliminated move instruction enters roq, if there already exists valid bit in `exceptionVec`, then it shouldn't be labeled `writebacked` immediately.
Next: optimize verilog code length & timing

backend, rename: support elimination of move instruction whose lsrc is 0 + bug fix

---

src/main/scala/xiangshan/backend/issue/DataArray.scala
src/main/scala/xiangshan/backend/issue/PayloadArray.scala
src/main/scala/xiangshan/backend/issue/ReservationStation.scala
src/main/scala/xiangshan/backend/issue/SelectPolicy.scala

This commit changes how uop and data are read in reservation stations.
It helps the issue timing.
Previously, we access payload array and data array after we decide the
instructions that we want to issue. This method makes issue selection
and array access serialized and brings critial path.
In this commit, we add one more read port to payload array and data
array. This extra read port is for the oldest instruction. We decide
whether to issue the oldest instruction and read uop/data
simultaneously. This change reduces the critical path to each selection
logic + read + Mux (previously it's selection + arbitration + read).
Variable oldestOverride indicates whether we choose the oldest ready
instruction instead of the normal selection. An oldestFirst option is
added to RSParams to …

backend, rs: parallelize selection and data read

---

src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/backend/issue/ReservationStation.scala
src/main/scala/xiangshan/backend/issue/StatusArray.scala
src/main/scala/xiangshan/package.scala

This commit simplifies status logic in reservations stations. Module
StatusArray is mostly rewritten.
The following optimizations are applied:
* Wakeup now has higher priority than enqueue. This reduces the length
of the critical path of ALU back-to-back wakeup.
* Don't compare fpWen/rfWen if the reservation station does not have
float/int operands.
* Ignore status.valid or redirect for srcState update. For data capture,
these are necessary and not changed.
* Remove blocked and scheduled conditions in issue logic when the
reseravtion station does not have loadWait bit and feedback.

rs,status: simplify logic to optimize timing

---

src/main/scala/xiangshan/backend/decode/FusionDecoder.scala
src/main/scala/xiangshan/backend/fu/Alu.scala
src/main/scala/xiangshan/package.scala

This commit adds 3-bit shift fused instructions. When the program
tries to add 8-byte index, these may be used.
List of fused instructions added in this commit:
* szewl3: `slli r1, r0, 32` + `srli r1, r0, 29`
* sr29add: `srli r1, r0, 29` + `add r1, r1, r2`

backend: add 3-bit shift fused instructions

---

src/main/scala/xiangshan/backend/issue/DataArray.scala
src/main/scala/xiangshan/backend/issue/PayloadArray.scala
src/main/scala/xiangshan/backend/issue/ReservationStation.scala
src/main/scala/xiangshan/backend/issue/SelectPolicy.scala
src/main/scala/xiangshan/backend/issue/StatusArray.scala

This commit moves issue select logic in reservation stations to stage 0
from stage 1. It helps timing of stage 1, which load-to-load requires.
Now, reservation stations have the following stages:
* S0: enqueue and wakeup, select. Selection results are RegNext-ed.
* S1: data/uop read and data bypass. Bypassed results are RegNext-ed.
* S2: issue instructions to function units.

backend,rs: move select logic to stage 0

---

src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/backend/CtrlBlock.scala
src/main/scala/xiangshan/backend/ExuBlock.scala
src/main/scala/xiangshan/backend/decode/DecodeUnit.scala
src/main/scala/xiangshan/backend/exu/Exu.scala
src/main/scala/xiangshan/backend/fu/Fence.scala
src/main/scala/xiangshan/backend/fu/FunctionUnit.scala
src/main/scala/xiangshan/backend/roq/Roq.scala
src/main/scala/xiangshan/frontend/Ibuffer.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
src/main/scala/xiangshan/package.scala

This commit cleans up exception vector usages in backend.
Previously the exception vector will go through the pipeline with the
uop. However, instructions with exceptions will enter ROB when they are
dispatched. Thus, actually we don't need the exception vector when an
instruction enters a function unit.
* exceptionVec, flushPipe, replayInst are reset when an instruction
enters function units.
* For execution units that don't have exceptions, we reset their output
exception vectors to avoid ROB to record them.
* Move replayInst to CtrlSignals.

backend: clean up exception vector usages

---

scripts/xiangshan.py

This PR replace coremark, microbench, and all perfromence test workloads by corresponding rv64gcb workloads.

ci: replace rv64gc workloads by rv64gcb workloads

---

src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/backend/CtrlBlock.scala
src/main/scala/xiangshan/backend/issue/ReservationStation.scala
src/main/scala/xiangshan/backend/rename/Rename.scala
src/main/scala/xiangshan/backend/roq/Roq.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueue.scala
src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
src/main/scala/xiangshan/package.scala

This commit adds timer counters for some important pipeline stages,
including rename, dispatch, dispatch2, select, issue, execute, commit.
We add performance counters for different types of instructions to see
the latency in different pipeline stages.

core: add timer counters for important stages

---

src/main/scala/utils/BitUtils.scala
src/main/scala/xiangshan/backend/ExuBlock.scala
src/main/scala/xiangshan/backend/Scheduler.scala
src/main/scala/xiangshan/backend/exu/Exu.scala
src/main/scala/xiangshan/backend/issue/ReservationStation.scala
src/main/scala/xiangshan/backend/issue/SelectPolicy.scala

This commit adds load balance strategy in issue selection logic for
reservation stations.
Previously we have a load balance option in ExuBlock, but it cannot work
if the function units have feedbacks to RS. In this commit it is
removed.
This commit adds a victim index option for oldestFirst. For LOAD, the
first issue port has better performance and thus we set the victim index
to 0. For other function units, we use the last issue port.

backend,rs: load balance for issue selection

---

src/main/scala/xiangshan/backend/fu/fpu/FMA.scala
src/main/scala/xiangshan/mem/MemUtils.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala

This commit adds performance counters for function units that have
feedback to reservation stations, including FMA, Load and Store.
We add performance counters to show how many instructions are issued for
multiple times.

backend: add performance counters for first issue

---

.github/workflows/emu.yml
scripts/xiangshan.py
src/main/scala/xiangshan/backend/decode/DecodeUnit.scala
src/main/scala/xiangshan/backend/decode/FusionDecoder.scala
src/main/scala/xiangshan/backend/decode/Instructions.scala
src/main/scala/xiangshan/backend/fu/Alu.scala
src/main/scala/xiangshan/backend/fu/Bmu.scala
src/main/scala/xiangshan/package.scala

This commit optimizes ALUOpType to 7 bits. Alu timing will be checked
later.
We also apply some misc changes including:
* Move REVB, PACK, PACKH, PACKW to ALU
* Add fused logicZexth, addwZext, addwSexth
* Add instruction fusion test cases to CI

backend: optimize aluOpType to 7 bits

---

.github/workflows/check_pc.py
.github/workflows/emu.yml
src/main/scala/xiangshan/backend/issue/ReservationStation.scala

This commit adds storage for PC in JUMP reservation station. Jalr needs
four operands now, including rs1, pc, jalr_target and imm. Since Jump
currently stores two operands and imm, we have to allocate extra space
to store the one more extra operand for jalr.
It should be optimized later (possibly by reading jalr_target when
issuing the instruction).
This commit also adds regression check for PC usages. PC should not
enter decode stage.

rs: add pcMem to store pc for jalr instructions

---

src/main/scala/xiangshan/backend/issue/ReservationStation.scala

This commit fixes a bug that causes pc to be wrong values when a jump is
blocked for issue and a new jump instruction enters reservation station.
When the jump for issue is blocked, we should latch its pc value because
the entry has been deallocated from rs (and pc no longer exists in the
pc mem).

rs: latch jump pc when deq is blocked

---

src/main/scala/top/Top.scala
src/test/scala/top/SimTop.scala

Current dcache may use same source id for different TL transactions (will not cause functional errors but not conform to spec), so we need to disable TLMonitor until we fix dcache.

Temporarily disable TLMonitor

---

src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/backend/fu/PMA.scala
src/main/scala/xiangshan/backend/fu/PMP.scala
src/main/scala/xiangshan/cache/mmu/MMUBundle.scala
src/main/scala/xiangshan/cache/mmu/MMUConst.scala
src/main/scala/xiangshan/cache/mmu/TLB.scala
src/main/scala/xiangshan/cache/mmu/TLBStorage.scala

timing optimization:
1. when nWays is 1, output data directly and doesn't care if hit or not
2. add parameter to control if put ParallelPriorityMux part into next cycle, but default false
3. put genPPN part into first cycle, may need registers

tlb: timing optimization in 'genPPN', 'pmp check' and 'data out when nWays is 1'

---

src/main/scala/xiangshan/frontend/IFU.scala

This bug happens when a branch prediction results in a fetch to MMIO space, and the backend flush could not flush the MMIO （It waits for commit）, thus results in blocking.

IFU: fix MMIO flush condition bug

---

src/main/scala/xiangshan/cache/mmu/MMUBundle.scala
src/main/scala/xiangshan/cache/mmu/Repeater.scala
src/main/scala/xiangshan/cache/mmu/TLB.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

three ways:
1. superhit seems to faster than normalhit, though normal'way is 1(sram, so sad)
2. RegNext DTLB to PTWFilter's req, perform ptwresp filter and lastReq filter here, do other filters at next stage
3. fastUop needs dtlb's hit, including superhit and normalhit. But normalhit is too slow. Add fast_miss that dontcare normalhit for fastUop. This may influence performance.

mmu: timing optimization for TLB's mux, PTWFilter and LoadUnit's fastUop

---

src/main/scala/xiangshan/backend/rob/Rob.scala

This commit adds an interrupt_safe flag that tracks whether an
instruction is safe for interrupts.
For example, any MMIO instruction is not safe because it changes
the external devices before write-back.

rob: add an interrupt safe flag

---

src/main/scala/xiangshan/backend/exu/WbArbiter.scala
src/main/scala/xiangshan/backend/rob/Rob.scala

This commit changes the splitN algorithm for the write-back arbiter.
Previously we split the function units as follows:
(FU0 FU1 FU2) (FU3 FU4 FU5).
However, this strategy tends to group the function units with the same
type into the same arbiter and may cause performance loss.
In this commit, we change the strategy to: (FU0 FU2 FU4) (FU1 FU3 FU5).

arbiter: better balance among function units

---

scripts/xiangshan.py
src/main/scala/xiangshan/backend/fu/CSR.scala
src/main/scala/xiangshan/backend/fu/util/CSRConst.scala

updated to priv 1.12.
but currently only necessary and not difficult updates are updated.
1. mconfigptr is added but hardwired to 0
2. xret will clear mprv if xpp is not M
3. add xBE, but hardwired to 0. (Acctually it is doned before, just change mstatusStruct)
more priv 1.12 updates may be added later (maybe).
test: add simple unit test of (2)

Updated to priv 1.12

---

src/main/scala/xiangshan/backend/fu/SRT16Divider.scala

This bug occurs when rem is 0 and dividend is negative
Caused by a buggy rightshifter

Fix SRT16div bug with 0 remainder

---

scripts/xiangshan.py
src/main/scala/xiangshan/backend/fu/CSR.scala
src/main/scala/xiangshan/backend/fu/util/CSRConst.scala

1. satp.ppn should have length of (PADDTBITS - PAGE_OFFSET_LEN) , higher bits should be masked
2. xstatus.xs is read-only according to spec. 
(2) seems to be more complicated, see:
https://github.com/riscv-software-src/riscv-isa-sim/issues/878

csr: add write mask to satp.ppn & xstatus.xs

---

src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/backend/CtrlBlock.scala
src/main/scala/xiangshan/backend/ExuBlock.scala
src/main/scala/xiangshan/backend/FUBlock.scala
src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/backend/Scheduler.scala
src/main/scala/xiangshan/backend/decode/DecodeUnit.scala
src/main/scala/xiangshan/backend/dispatch/Dispatch.scala
src/main/scala/xiangshan/backend/exu/ExeUnit.scala
src/main/scala/xiangshan/backend/exu/Exu.scala
src/main/scala/xiangshan/backend/exu/WbArbiter.scala
src/main/scala/xiangshan/backend/fu/CSR.scala
src/main/scala/xiangshan/backend/fu/Fence.scala
src/main/scala/xiangshan/backend/fu/FunctionUnit.scala
src/main/scala/xiangshan/backend/issue/ReservationStation.scala
src/main/scala/xiangshan/backend/rob/Rob.scala
src/main/scala/xiangshan/frontend/Frontend.scala
src/main/scala/xiangshan/frontend/Ibuffer.scala
src/main/scala/xiangshan/mem/MemCommon.scala
src/main/scala/xiangshan/mem/lsqueue/LSQWrapper.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueue.scala
src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
src/main/scala/xiangshan/mem/pipeline/AtomicsUnit.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala
src/main/scala/xiangshan/package.scala

This commit adds WritebackSink and WritebackSource parameters for
multiple modules. These traits hide implementation details from
other modules by defining IO-related functions in modules.
By using WritebackSink, ROB is able to choose the writeback sources.
Now fflags and exceptions are connected from exe units to reduce write
ports and optimize timing.
Further optimizations on write-back to RS and better coding style to
be added later.

core: refactor writeback parameters

---

src/main/scala/xiangshan/backend/CtrlBlock.scala
src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/backend/exu/ExeUnit.scala
src/main/scala/xiangshan/cache/mmu/PTW.scala
src/main/scala/xiangshan/cache/mmu/Repeater.scala
src/main/scala/xiangshan/frontend/Frontend.scala
src/main/scala/xiangshan/frontend/NewFtq.scala

This commit adds DelayN(2) to some CSR-related signals, including
control bits to ITLB, DTLB, PTW, etc.
To avoid accessing the ITLB before control bits change, we also need
to delay the flush for two cycles. We assume branch misprediction or
memory violation does not cause csrCtrl to change.

core: delay csrCtrl for two cycles

---

src/main/scala/xiangshan/backend/fu/Jump.scala

According to RISC-V spec, for the JALR instruction, its target address
is obtained by adding the sign-extended 12-bit I-immediate to the
register rs1, then setting the least-significant bit of the result
to zero.

jump: set the LSB of the target to zero

---

src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/backend/decode/DecodeUnit.scala
src/main/scala/xiangshan/backend/fu/CSR.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

* Soft prefetch will only be replayed when TLB miss
* `soft_prefetch_enable` bit is added to smblockctl (CSR)

mem: fix soft prefetch

---

src/main/scala/xiangshan/backend/fu/CSR.scala

This commit changes the condition to update mtval and stval.
According to the RISC-V spec, when a trap is taken into M/S-mode,
mtval/stval is either set to zero or written wrih exception-specific
information to assist software in handling the trap.
Previously in XiangShan, mtval/stval is updated depending on the
current priviledge mode, which is incorrect.
TODO: mtval/stval should be updated with the faulting instruction
on an illegal instruction trap.

csr: update mtval/stval according to the trap mode

---

src/main/scala/xiangshan/backend/dispatch/Dispatch2Rs.scala

This commit optimizes Dispatch2Rs timing by ignoring lsq.canAccept
when sending bits to reservation stations.

dp2: out.bits does not depend on lsq.canAccept

---

src/main/scala/xiangshan/backend/CtrlBlock.scala
src/main/scala/xiangshan/backend/decode/DecodeUnit.scala
src/main/scala/xiangshan/backend/issue/DataArray.scala
src/main/scala/xiangshan/backend/rename/Rename.scala

This commit adds fused load support by bypassing LUI results to load.
For better timing, detection is done at the rename stage. Imm is stored
in psrc(1), psrc(0) and imm.

rename: add fused lui and load

---

src/main/scala/top/Configs.scala
src/main/scala/xiangshan/PMParameters.scala
src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/backend/fu/PMA.scala
src/main/scala/xiangshan/backend/fu/PMP.scala
src/main/scala/xiangshan/cache/mmu/MMUBundle.scala
src/main/scala/xiangshan/cache/mmu/MMUConst.scala
src/main/scala/xiangshan/cache/mmu/TLB.scala
src/main/scala/xiangshan/cache/mmu/TLBStorage.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala

long latency: tlb's sram may be slow to gen ppn, ppn to pmp may be long latency.
Solution: add static pmp check.
Fatal problem: pmp grain is smalled than TLB pages(4KB, 2MB, 1GB)
Solution part 1: increase pmp'grain to 4K, for 4K entries, pre-check pmp and
store the result into tlb storage. For super pages, still dynamic check
that translation and check.

pmp: add static pmp check that stored in tlb entries

---

src/main/scala/xiangshan/backend/CtrlBlock.scala
src/main/scala/xiangshan/backend/exu/ExeUnit.scala
src/main/scala/xiangshan/backend/fu/CSR.scala
src/main/scala/xiangshan/frontend/Frontend.scala
src/main/scala/xiangshan/frontend/NewFtq.scala

This commit optimizes the timing for exception and trapTarget in CSR.
Flush to frontend has been delayed for five cycles. This commit delays
the computation of target for five cycles as well.

csr: optimize exception and trapTarget timing

---

src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/backend/Scheduler.scala
src/main/scala/xiangshan/mem/lsqueue/LSQWrapper.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueue.scala
src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala

This commit adds an LsqEnqCtrl module to add one more clock cycle
between dispatch and load/store queue.
LsqEnqCtrl maintains the lqEnqPtr/sqEnqPtr and lqCounter/sqCounter.
They are used to determine whether load/store queue can accept new
instructions. After that, instructions are sent to load/store queue.
This module decouples queue allocation and real enqueue.
Besides, uop storage in load/store queue are optimized. In dispatch,
only robIdx is required. Other information is naturally conveyed in
the pipeline and can be stored later in load/store queue if needed.
For example, exception vector, trigger, ftqIdx, pdest, etc are
unnecessary before the instruction leaves the load/store pipeline.

lsq: add LsqEnqCtrl to optimize enqueue timing

---

src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/frontend/NewFtq.scala
src/main/scala/xiangshan/frontend/icache/ICacheMainPipe.scala
src/main/scala/xiangshan/frontend/icache/ICacheMissUnit.scala
src/main/scala/xiangshan/frontend/icache/IPrefetch.scala

* This problem happens because prefetchPtr still exits when close IPrefetch
* Fix PMP req port still be occupied even when ICache miss

IPrefetch: fix prefetchPtr stop problem

---

src/main/scala/xiangshan/backend/MemBlock.scala

Exception address is used serveral cycles after flush. We delay it
by more cycles to ensure its flush safety.

atomics: delay exception.valid for more cycles

---

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

If s2_data_invalid and s2_ldld_violation happens together, enter
s2_ldld_violation workflow.
Note:
ld-ld violation or forward failure will let an normal load inst replay
from fetch. If TLB hit and ld-ld violation / forward failure happens,
we write back that inst immediately. Meanwhile, such insts will not be
replayed from rs.

mem: fix ld-ld violation writeback priority

---

src/main/scala/xiangshan/backend/MemBlock.scala

Valid should be set to true after atomic.exception.valid and cleared
after redirect is valid.

atomic: fix exception valid after #1392

---

src/main/scala/utils/CircularQueuePtr.scala

For 0:x and 1:x, 1:x should be after 0:x.

queuePtr: set isAfter when different flags and same value

---

src/main/scala/xiangshan/backend/dispatch/Dispatch.scala
src/main/scala/xiangshan/backend/dispatch/DispatchQueue.scala

This commit adds blocking logic for instructions when they enter
dispatch queues. If previous instructions have exceptions, any
following instructions should be enter dispatch queue.
Consider the following case. If uop(0) has an exception and is a load.
If uop(1) does not have an exception and is a load as well. Then the
allocation logic in dispatch queue will allocate an entry for both
uop(0) and uop(1). However, uop(0) will not set enq.valid and leave
the entry in dispatch queue empty. uop(1) will be allocated in dpq.
In dispatch queue, pointers are updated according to the real number
of instruction enqueue, which is one. While the second is actually
allocated. This causes errors.

dispatch: block enq when previous instructions have exception

---

src/main/scala/xiangshan/frontend/Frontend.scala
src/main/scala/xiangshan/frontend/IFU.scala

* fix bugs when flash image including RVC instructions
*when a mmio fetch an RVI instruction cross 64 bits, IFU must send paddr + 2.U to fetch the higher 16 bits.
But the paddr + 2.U is not checked by TLB or PMP. This may cause some unexpected fetch stuck problems.

IFU: fix fetching RVC instructions from mmio space bug 

---

src/main/scala/xiangshan/backend/fu/CSR.scala

XiangShan has registered an marchid of 25: https://github.com/riscv/riscv-isa-manual/blob/master/marchid.md. This value should be returned from hardcoded CSR `marchid`.
Fixme: should this value in file fu/util/CSRConst.scala instead of fu/CSR.scala?

Fix marchid value for hart CSR configuration

---

src/main/scala/xiangshan/backend/CtrlBlock.scala
src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/backend/fu/CSR.scala
src/main/scala/xiangshan/backend/rob/Rob.scala
src/main/scala/xiangshan/frontend/PreDecode.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

* Reduce trigger hit wires that goes into exceptiongen
* Fix frontend triggers rewriting hit wire
* Retrieved some accidentally dropped changes in branch dm-debug (mainly fixes to debug mode)
* Fix dmode in tdata1
* Fix ebreaks not causing exception in debug mode
* Fix dcsr field bugs
* Fix faulty distributed tEnable
* Fix store triggers not using vaddr
* Fix store trigger rewriting hit vector
* Initialize distributed tdata registers in MemBlock and Frontend to zero
* Fix load trigger select bit in mcontrol
* Fix singlestep bit valid in debug mode
* Mask all interrupts in debug mode

Debug mode: various bug fixes

---

src/main/scala/xiangshan/backend/Scheduler.scala
src/main/scala/xiangshan/backend/rob/Rob.scala
src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala

CSRs are updated later after instructions commit from ROB. Thus, we
need to delay difftest commit for several cycles.

difftest: delay commit and regfile for two cycles

---

src/main/scala/xiangshan/backend/rob/Rob.scala

This commit fixes the block_commit condition when an instruction has
exception but labeled flushPipe. Previously such an instruction will
commit normally.

rob: block commit when exceptions are valid

---

src/main/scala/xiangshan/frontend/FTB.scala

the mulitple-hit problem is yet to be solved (although it may be very rare)

ftb: fix a bug on replacement policy, remove multiple hit assertion

---

src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala
src/main/scala/xiangshan/cache/dcache/Uncache.scala
src/main/scala/xiangshan/cache/dcache/loadpipe/LoadPipe.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

dcache.resp.bits.miss used to depend on tag_error, it causes severe
timing problem. That dependence is now removed.
Now when tag_error, we:
* Set access fault bit in exception vec
* Do not update miss queue. That is to say, if miss, that inst
may not be refilled
* Mark that inst as dataForwarded so it will not wait for refill
* Report error to CSR and BEU
If tag_error come with a miss, writeback that inst from load
queue. Otherwise, writeback it from load pipeline.

mem: opt dcache tag error check timing

---

src/main/scala/xiangshan/frontend/IFU.scala

*    Problem : ITLB request in IFU will not wait for the ITLB miss.
- When ITLB enables virtual address translation, an MMIO request may cause the 
-  uncached instruction fetch device stuck.
*    Solve : wait until ITLB fix its misses and report exceptions.

IFU <bug-fix>: deal with itlb miss for resend

---

src/main/scala/utils/SRAMTemplate.scala
src/main/scala/xiangshan/cache/mmu/TLB.scala

SRAMTemplate:
Chisel(RTL) Module : when write, read will get random data
Replace Physical Module: when write, read will return last cycle's read data(or in other words, keep last cycle's data)
This difference make tlb's bug difficult to appear.
tlb forgot to check if read is valid or not, but check for data's tag part, which is random in Chisel Module.
The random tag makes it never hit with vpn. However in Physical Module, the "last cycle" tag hit with
vpn. The tag domain in tlb doesn't care index part, so the stored part is always the same.
Fix: when refill, just resp a miss/fast_miss

sram-tlb: change SRAMTemplate & when tlb refill, just resp a miss/fast_miss

---

src/main/scala/xiangshan/cache/mmu/MMUBundle.scala
src/main/scala/xiangshan/cache/mmu/PTW.scala
src/main/scala/xiangshan/cache/mmu/PageTableCache.scala

Corner Case that makes l2tlb's performance decrease sharply:
core may have mis-speculative memory access, which may cause tlb-miss and ptw req to l2tlb.
In l2tlb, the reqs may still miss and even have invalid pte that won't be stored in l2tlb.cache.
If the relative ptes are invalid, these reqs will be held by miss queue and wait for page walker performing
page table walk one by one. It's too slow and will raise time out assert in l2tlb.missqueue.
Solution:
store invalid entries(only super entries) into sp. 
Bad news is that sp only has16 entries, so invaid entries will pollute sp as well.
Good news is that the invalid reqs are always in same super page, so only one entries is mostly enough.

l2tlb.cache: store invalid entries(only super entries) into sp to avoid mem access waste

---

src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala

`s1_tag_match_way` is vaild iff `tag_read.valid` and `meta_read.valid` in s0
for the same req

assert: fix dcache mp s1_way_en assertion

---

src/main/scala/xiangshan/backend/rob/Rob.scala

An instruction with exceptions may have arbitrary instr values and
may be decoded into WFI instructions, which cause errors.

rob: don't set hasWFI if there're exceptions

---

src/main/scala/utils/SRAMTemplate.scala

Previously, the waymask input port of FoldedSRAMTemplate is unused, so that all corresponding ways would be written once requested.
This could be a huge performance boost, as this affects all TAGE srams.

sramtemplate: fix waymask in FoldedSRAMTemplate

---

src/main/scala/system/SoC.scala
src/test/scala/top/SimTop.scala

Previously we made a mistake to connect rtc_clock to rtcTick for CLINT.
rtcTick should be on io_clock clock domain and asserted only one
clock cycle in io_clock for every cycle in rtc_clock. We add sampling
registers in this commit to fix this.

soc: fix implementation of rtc_clock

---

src/main/scala/xiangshan/frontend/NewFtq.scala

we should use jmpOffset instead of cfiIndex when assigning last_may_be_rvi_call in case that a call comes afterlast_may_be_rvi_call in case that a call comes after a taken branch
This could possibly improve ras performance

ftq: fix a bug of FtbEntryGen

---

src/main/scala/xiangshan/frontend/ITTAGE.scala

Previous logic checked the value of old_ctr to select between old target and
new target when updating ittage table. However, when we need to alloc a new
entry, the value of old_ctr is X because we do not reset ittage table. So we
would definitely write an X to the target field, which is the output of the
mux, as the selector is X.

ittage: we should write new target when alloc

---

src/main/scala/xiangshan/frontend/IFU.scala
src/main/scala/xiangshan/frontend/NewFtq.scala
src/main/scala/xiangshan/frontend/icache/ICache.scala
src/main/scala/xiangshan/frontend/icache/ICacheMainPipe.scala
src/main/scala/xiangshan/frontend/icache/IPrefetch.scala

* fix mmio_resend_af wrong assignment
* fix wb_half_flush missOffset ( using wb_lastIdx instead of PredictWidth-1 )
* change pipeline ready condition ( this_ready =  this_stage_fire || this_stage_empty )
* delete 500-cycle ready condition ( toICache(*).ready means the SRAM has been reset and ready for read)

<bug-fix>: fix IFU misOffset bug and optimize code

---

src/main/scala/utils/SRAMTemplate.scala

Previously we use ridx to select between several data of folded srams. ridx is simply RegNext of req.bits.setIdx. However, when holdRead is set, setIdx may change the next cycle, while ren become low, in which case rdata should remain unchanged.
Now we use HoldUnless logic to keep the value of ridx when no new read is requested.
This may improve the accuracy of tage and ittage predictors.

FoldedSRAMTemplate: hold ridx when holdRead is set

---

src/main/scala/xiangshan/frontend/icache/ICache.scala

set ECC data to hardwired zero when ECC is disabled

ICache: fix DataArray non-ecc width

---

src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/backend/decode/DecodeUnit.scala
src/main/scala/xiangshan/backend/dispatch/Dispatch.scala

This commit changes the lsrc/psrc of LUI in dispatch instead of
decode to optimize the timing of lsrc in DecodeStage, which is
critical for rename table.
lsrc/ldest should be directly get from instr for the timing. Fused
instructions change lsrc/ldest now, which will be optimized later.

decode: do not set lsrc of LUI for better timing

---

src/main/scala/xiangshan/backend/CtrlBlock.scala
src/main/scala/xiangshan/backend/decode/DecodeStage.scala
src/main/scala/xiangshan/backend/decode/DecodeUnit.scala
src/main/scala/xiangshan/backend/decode/FusionDecoder.scala
src/main/scala/xiangshan/backend/rename/Rename.scala

This commit optimizes the timing of instruction fusion decoder.
Previously we update all control signals after the fusion decoder,
including the lsrc/ldest sent to rename table. However, RAT has a
critical timing.
Thus, in this commit, we break this critical path into (1) raw
lsrc/ldest gen; (2) read RAT; (3) update RAT read data according to
fusionInfo from the fusion decoder. Now the RAT read works parallelly
with the fusion decoder.

decode: parallel fusion decoder and rat read

---

src/main/scala/utils/PerfCounterUtils.scala
src/main/scala/xiangshan/backend/rename/BusyTable.scala

This commit adds some registers for performance counters to optimize
the timing. Pipelines are added.

core,perf: optimize timing for some registers

---

src/main/scala/utils/PipelineConnect.scala
src/main/scala/xiangshan/backend/exu/Exu.scala
src/main/scala/xiangshan/backend/exu/WbArbiter.scala

This commit adds a buffer after the function unit that operate across
the integer block and the floating-point block, such as f2i and i2f.
For example, previously the out.ready of f2i depends on whether
mul/div/csr/jump has a valid instruction out, since f2i has lower
priority than them. This ready back-propagates from the integer function
units to the floating-point function units, and finally to the
floating-point reservation stations (since f2i is fully pipelined).
We add a buffer after the function unit to break this ready
back-propagation. It incurs one more cycle of execution latency, but we
leave it not-fully-optimized for now.
Timing can be further optimized if we separates the int writeback and fp
writeback in function units. In the current version, the ready of f2i
affects the …

core: add buffers for function units across int/fp

---

src/main/scala/utils/BitUtils.scala
src/main/scala/xiangshan/backend/rename/freelist/BaseFreeList.scala
src/main/scala/xiangshan/backend/rename/freelist/MEFreeList.scala
src/main/scala/xiangshan/backend/rename/freelist/StdFreeList.scala

This commit optimizes the timing of freelist by changing the updating
function of headPtr and tailPtr.
We maintains an one-hot representation of headPtr and further uses it to
read the free registers from the list, which should be better than the
previous implementation where headPtr is used to indexed into the queue.
The update of tailPtr and the freelist is delayed by one cycle to
optimize the timing. Because freelist allocates new registers in the
next cycle iff there are more than RenameWidth free registers in this
cycle. The freed registers in this cycle will never be used in the next
cycle. Thus, we can delay the updating of queue data to the next cycle.
We also move the update of tailPtr to the next cycle, since PopCount
takes a long timing and we move the last adder to the next …

freelist: optimize timing of read and writing

---

src/main/scala/xiangshan/cache/mmu/TLBStorage.scala

Background:
dtlb has 128 entries stored in sram. 128 sets, 1 ways.
advantage: large volume & 1 ways means no tag match logic at data select path
disadvantage: 128 sets means long latency at valid select, which is a Vec-Register.
Optimization: divide valid select into two-cycles

tlb: divide v-select into two cycle for timing optimization

---

src/main/scala/xiangshan/cache/mmu/PageTableCache.scala

now the l2tlb page cache are divided into:
1. stageReq: input && read sram valid && will block when sram write
2. stageDelay: get sram data and delay one cycle
3. stageCheck: check hit and ecc result
4. stageResp: output

l2tlb: delay one cycle when read from sram

---

src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/cache/mmu/Repeater.scala
src/main/scala/xiangshan/frontend/Frontend.scala

These  commits are from branch `nanhu-0621`. Some bugs are fixed but forgot to cherry-pick to master.
1. fix l2tlb dead-lock bug
l2tlb won't merge requests at same addr. It will be blocked when having too many requests. 
PtwFilter has a bug that will send too many requests. Add a counter to avoid that.
2. fix sfence sync at mmu
different modules in mmu may get sfence at different latency, which will lost requests or some requests have no receiver.
Sync the sfence latency manually to avoid the bug.

l2tlb: add counter to ptw-filter to avoid l2tlb deadlock & sync sfence to mmu

---

src/main/scala/utils/PipelineConnect.scala
src/main/scala/xiangshan/backend/Scheduler.scala
src/main/scala/xiangshan/backend/dispatch/Dispatch2Rs.scala
src/main/scala/xiangshan/backend/issue/ReservationStation.scala
src/main/scala/xiangshan/backend/issue/StatusArray.scala
src/main/scala/xiangshan/backend/rob/Rob.scala

Load/store Dispatch2 has a bad timing because it requires the fuType
to disguish the out ports. This brings timing issues because the
instruction has to read busyTable after the port arbitration.
This commit adds a pipeline in dp2Ls, which may cause performance
degradation. Instructions are dispatched according to out, and at
the next cycle it will leave dp2.

dp2: add a pipeline for load/store

---

src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/backend/exu/Exu.scala
src/main/scala/xiangshan/backend/exu/WbArbiter.scala
src/main/scala/xiangshan/backend/fu/FunctionUnit.scala
src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala
src/main/scala/xiangshan/cache/dcache/Uncache.scala
src/main/scala/xiangshan/cache/dcache/data/BankedDataArray.scala
src/main/scala/xiangshan/cache/dcache/loadpipe/LoadPipe.scala
src/main/scala/xiangshan/cache/dcache/mainpipe/AtomicsReplayUnit.scala
src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala
src/main/scala/xiangshan/mem/lsqueue/LSQWrapper.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueue.scala
src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
src/main/scala/xiangshan/mem/pipeline/AtomicsUnit.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
src/main/scala/xiangshan/package.scala

This commit re-pipelines ECC check logic in data cache and exception generate logic for better timing. 
Now ecc error is checked 1 cycle after reading result from data sram. An extra cycle is added for load
writeback to ROB.

dcache: repipeline ecc check logic for timing

---

src/main/scala/xiangshan/frontend/BPU.scala
src/main/scala/xiangshan/frontend/FTB.scala
src/main/scala/xiangshan/frontend/NewFtq.scala

* add one cycle delay to write status registers, and add corresponding bypass logic for it
* add ifuPtrPlus1 register to cut some critical path
* add one cycle delay updating all predictors except ftb, and add one cycle stall for ftb miss update read to break sram-to-sram critical path

timing optimizations for bpu and ftq

---

src/main/scala/utils/CircularQueuePtr.scala
src/main/scala/xiangshan/backend/dispatch/DispatchQueue.scala
src/main/scala/xiangshan/backend/rename/freelist/BaseFreeList.scala

This commit changes the data modules in Dispatch Queue. We use one-hot
indices to read and write the data array.

dpq: optimize read and write timing of data module

---

src/main/scala/xiangshan/backend/decode/DecodeUnit.scala

This commit fixes the bug that the lsrc(0) of trap instructions is
overrided with $a0, which causes timing issues as well.

decode: lsrc should not be overrided for XSTrap

---

src/main/scala/xiangshan/cache/dcache/loadpipe/LoadPipe.scala

It should fix the broken dcache load plru update logic which introduce
X in simulation

dcache: do not update plru when dtlb miss

---

src/main/scala/xiangshan/backend/CtrlBlock.scala
src/main/scala/xiangshan/backend/decode/DecodeStage.scala
src/main/scala/xiangshan/backend/decode/FusionDecoder.scala
src/main/scala/xiangshan/backend/rename/Rename.scala

This commit moves the fusion decoder to both decode and rename stage.
In the decode stage, fusion decoder determines whether the instruction
pairs can be fused. Valid bits of decode are not affected by fusion
decoder. This should fix the timing issues of rename.valid.
In the rename stage, some fields are updated according the result of
fusion decoder. This will bring a minor timing path to both valid and
other fields in uop in the rename stage. However, since freelist and
rat have worse timing. This should not cause timing issues.

decode: move fusion decoder result Mux to rename

---

src/main/scala/utils/BitUtils.scala
src/main/scala/xiangshan/backend/CtrlBlock.scala
src/main/scala/xiangshan/backend/ExuBlock.scala
src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/backend/dispatch/DispatchQueue.scala
src/main/scala/xiangshan/backend/exu/WbArbiter.scala
src/main/scala/xiangshan/backend/rob/Rob.scala

This commit adds separated redirect registers in ExuBlock and MemBlock.
They have one cycle latency compared to redirect in CtrlBlock. This will
help reduce the fanout of redirect registers.

core: optimize redirect timing

---

src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/backend/CtrlBlock.scala
src/main/scala/xiangshan/backend/Scheduler.scala
src/main/scala/xiangshan/backend/dispatch/DispatchQueue.scala

This commit makes copies of dispatch2 in CtrlBlock to avoid long
cross-module timing loop paths. Should be good for timing.

ctrl: optimize the timing of dispatch2 stage

---

src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/backend/decode/DecodeUnit.scala
src/main/scala/xiangshan/backend/rename/Rename.scala

This commit moves the decoder of software prefetch instructions to
the rename stage.
Previously the decoding of software prefetch instructions affects
the imm gen and causes a long critical path.

decode: move the soft-prefetch decoder to rename

---

src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala
src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala

Now we use tag_write_intend to generate ready signal for load issue
It should remove the critical path from dcacheReq.ready to rs

dcache,ldu: simplify load issue ready logic

---

src/main/scala/xiangshan/mem/lsqueue/LoadQueue.scala

Addr match result is slow to generate, we RegNext() it
ldld_violation_mask is now generated in load_s2, as well as
(ldld) have_violation check result

lq: opt ldld_violation_mask gen timing

---

src/main/scala/top/Configs.scala
src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/cache/mmu/MMUBundle.scala
src/main/scala/xiangshan/cache/mmu/TLBStorage.scala

Old Edition:
2 ld tlb but with same entries. 2 st tlb but wih the same entries.
The 'duplicate' is used for timing optimization that each tlb can
be placed close to mem access pipeline unit.
Problem:
The duplicate tlb takes more Power/Area.
New Edition:
Only 1 ld tlb and 1 st tlb now.
If the area is not ok, may merge ld and st together.
Fix: fix some syntax bugs when changing parameters

dtlb: merge duplicated tlb together: one ld-tlb and one st-tlb.

---

src/main/scala/xiangshan/cache/dcache/mainpipe/MissQueue.scala

replace_pipe_req is causing timing problem as vaddr in it is used to
generate mainpipe block signal. Unfortunately, vaddr from
replace_pipe_req is selected form all miss queue entries
(16 by default), which caused timing problem
refill_pipe_req will not be scheduled until dcache main pipe s3 reports
that replace_pipe_req has been finished. Thus it is legal to add a
pipe reg for replace_pipe_req
Now ALL mainpipe req candidates come from pipe reg. At the entry of
main pipe, 1 req is selected from 4 main pipe reqs, and its vaddr is
used to calcuate set block condition

dcache: use arbiter_with_pipereg for replace_pipe_req

---

.github/workflows/emu.yml

* This commit temporarily cancels the CI of vcs. It should be enabled after our eda servers are rearranged

ci: disable vcs ci temporarily

---

src/main/scala/xiangshan/backend/rob/Rob.scala

This commit fixes the wrong update values of commitInstr in ROB.
Previously we add a RegNext to trueCommitCnt in #1644. However,
we don't add RegNext to the ifCommit condition. This makes the
commitInstr larger than the normal value and IPC looks better.
This commit fixes this bug and the IPC numbers should be correct now.

rob: fix commitInstr performance counters

---

src/main/scala/xiangshan/backend/fu/CSR.scala
src/main/scala/xiangshan/mem/mdp/StoreSet.scala

This commit changes the allocation policy in Store Set memory dependence
predictor.
Previously we allocate an entry for the load and store instructions
every time when a memory violation is triggered. However, it's not
robust enough and causes many load instructions to be blocked for
issuing.
The current allocation policy only allocates the same entry for the load
and store instructions after both of them have triggered memory
violations before. That is to say, only when a load/store instruction
pair triggers memory violation twice, we do allocate the same entry to
them. This change may cause more memory violation redirections than
before, but it also reduces the number of blocked load instructions.

storeset: don't allocate upon the first violation

---

src/main/scala/xiangshan/backend/issue/SelectPolicy.scala

rs,select: optimize oldest compare timing

---

src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala

It will save time for store_req generation in dcache Mainpipe, which is
at the beginning of a critical path

sbuffer: gen blockDcacheWrite 1 cycle earlier

---

src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/frontend/Ibuffer.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

uop.ctrl.replayInst in lq should be replayed when load_s2 update lq
i.e. load_s2.io.out.valid
This commit fixes bug introduced by #1685

ldu: update lq correctly when replay_from_fetch

---

src/main/scala/xiangshan/cache/dcache/mainpipe/WritebackQueue.scala

This commit and an extra cycle for miss queue store data and mask write.
For now, there are 18 missqueue entries. Each entry has a 512 bit
data reg and a 64 bit mask reg. If we update writeback queue data in 1
cycle, the fanout will be at least 18x(512+64) = 10368.
Now writeback queue req meta update is unchanged, however, data and mask
update will happen 1 cycle after req fire or release update fire (T0).
In T0, data and meta will be written to a buffer in missqueue.
In T1, s_data_merge or s_data_override in each missqueue entry will
be used as data and mask wen.

dcache: delay wbq data update for 1 cycle

---

src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/cache/CacheInstruction.scala
src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala
src/main/scala/xiangshan/cache/dcache/data/BankedDataArray.scala
src/main/scala/xiangshan/cache/dcache/loadpipe/LoadPipe.scala
src/main/scala/xiangshan/cache/dcache/mainpipe/MissQueue.scala
src/main/scala/xiangshan/cache/dcache/mainpipe/RefillPipe.scala
src/main/scala/xiangshan/cache/dcache/meta/TagArray.scala
src/main/scala/xiangshan/cache/mmu/TLBStorage.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

* pipelineReg and pipelineReg_valid in miss queue
* translated_cache_req_opCode and io_cache_req_valid_reg in cacheOpDecoder
* r_way_en_reg in bankedDataArray
* s2_bank_oh_reg in loadPipe which wires to loadUnit

dcache: duplicate registers for better fanout

---

src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala
src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala

We used to clean mask in sbuffer in 1 cycle when do sbuffer enq,
which introduced 64*16 fanout.
To reduce fanout, now mask in sbuffer is cleaned when dcache hit resp
comes. Clean mask for a line in sbuffer takes 2 cycles.
Meanwhile, dcache reqIdWidth is also reduced from 64 to
log2Up(nEntries) max log2Up(StoreBufferSize).
This commit will not cause perf change.

sbuffer: opt mask clean fanout

---

src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala
src/main/scala/xiangshan/cache/dcache/mainpipe/WritebackQueue.scala

It will remove fanout from mem_release.valid releated logic

dcache: only update wbq addr when allocate

---

src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala

Fix bug when LR with a new address comes into s3 and the old address is invalidated in the same cycle. In this situation, lrsc_count should be set for a start fresh.

MainPipe: fix bug in lrsc_count

---

src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/backend/issue/ReservationStation.scala
src/main/scala/xiangshan/cache/dcache/loadpipe/LoadPipe.scala
src/main/scala/xiangshan/cache/mmu/MMUBundle.scala
src/main/scala/xiangshan/cache/mmu/TLB.scala
src/main/scala/xiangshan/frontend/IFU.scala
src/main/scala/xiangshan/frontend/icache/ICacheMainPipe.scala
src/main/scala/xiangshan/frontend/icache/IPrefetch.scala
src/main/scala/xiangshan/mem/pipeline/AtomicsUnit.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala

This commit optimizes the timing of load-load forwarding by making
it speculatively issue requests to TLB/dcache.
When load_s0 does not have a valid instruction and load_s3 writes
a valid instruction back, we speculatively bypass the writeback
data to load_s0 and assume there will be a pointer chasing instruction
following it. A pointer chasing instruction has a base address that
comes from a previous instruction with a small offset. To avoid timing
issues, now only when the offset does not change the cache set index,
we reduce its latency by speculatively issuing it.

rs,mem: optimize load-load forwarding timing

---

src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/mem/MemCommon.scala
src/main/scala/xiangshan/mem/lsqueue/LSQWrapper.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueue.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

rdataVec (i.e. sram read result merge forward result) is still
generated in load_s2. It will be write to load queue in load_s2

ldu: select data in load_s3

---

src/main/scala/utils/PipelineConnect.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

Load_S1 requires vaddr not only for lsq.forward and sbuffer.forward.
It also sends vaddr to S2, which sends lsq.loadIn when exceptions
and cache misses. We need to update the vaddr for S1 to avoid the wrong
vaddr when exceptions.

load: update s1_vaddr when load-load forwarding

---

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

`forwardData` for load queue does not need data from dcache sram.
In this way, we remove load queue data wdata fanin from all dcache
data srams

ldu: remove dcache sram data from forwardData

---

src/main/scala/xiangshan/backend/issue/ReservationStation.scala

This commit fixes a bug when FMA partially issues but is flushed
just after it is issues. In this case, new instruction will enter
the RS and writes the data array. However, previously midResult
from FMA is written into the data array two cycles after issue.
This may cause the wrong data to be written into the data array.

rs: don't update midResult when flushed

---

src/main/scala/utils/RegMap.scala
src/main/scala/xiangshan/backend/fu/CSR.scala

To reduce fanout of in.valid and address, delay write by one clock
cycle.
Should be careful whether this brings bugs.

csr: delay reg write by one clock cycle

---

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

When write back missed load, io.ldout.bits.uop.ctrl.replayInst should not be overwriteen by load pipeline replay check result `s3_need_replay_from_fetch`

ldu: fix replay from fetch signal for missed load

---

src/main/scala/xiangshan/mem/lsqueue/LoadQueue.scala

* when a load instruction missed in dcache and then refilled by dcache, waiting to be written back, if the block is released by dcache, it also needs to be marked as released

lq: fix load load violation check logic

---

src/main/scala/xiangshan/mem/pipeline/AtomicsUnit.scala

* send tlb req and sbuffer flush req at the same time
* remove s_cache_resp_latch state
* change `data_valid` logic: do not send dcache req until `data_valid` is true

AtomicsUnit: refactor FSM in AtomicsUnit

---

src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/backend/exu/WbArbiter.scala
src/main/scala/xiangshan/mem/MemCommon.scala
src/main/scala/xiangshan/mem/lsqueue/LSQWrapper.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueue.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

sync timing modification of pr #1680
lq: update data field iff load_s2 valid
Now we update data field (fwd data, uop) in load queue when load_s2 is valid. It will help to on lq wen fanout problem.
State flags will be treated differently. They are still updated accurately according to loadIn.valid

sync timing modification of pr #1680

---

scripts/xiangshan.py

Usage:
When make emu, please use EMU_TRACE=1, EMU_TRACE=vcd or EMU_TRACE=VCD 
to dump waveform of vcd format, and use EMU_TRACE=fst or EMU_TRACE=FST 
to dump waveform of fst format.
When use xiangshan.py, please add --trace to dump waveform of vcd format, 
and add --trace-fst to dump waveform of fst format.

Add FST waveform support

---

src/main/scala/device/RocketDebugWrapper.scala
src/main/scala/utils/BitUtils.scala
src/main/scala/utils/IntBuffer.scala
src/main/scala/utils/Trigger.scala
src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/XSTile.scala
src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/backend/dispatch/Dispatch.scala
src/main/scala/xiangshan/backend/fu/CSR.scala
src/main/scala/xiangshan/backend/fu/util/CSRConst.scala
src/main/scala/xiangshan/backend/fu/util/DebugCSR.scala
src/main/scala/xiangshan/backend/fu/util/Trigger.scala
src/main/scala/xiangshan/backend/rob/Rob.scala
src/main/scala/xiangshan/frontend/Frontend.scala
src/main/scala/xiangshan/frontend/IFU.scala
src/main/scala/xiangshan/frontend/PreDecode.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueue.scala
src/main/scala/xiangshan/mem/pipeline/AtomicsUnit.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
src/test/scala/top/SimTop.scala

* Details
+ Set 10 general triggers, instead of 10 special triggers as before(4 fetch, 3 load and 3 store)
+ Remove trigger chain suppprt temporarily
+ Update fetch trigger will lead to pipe flush
* Attentions
+ Trigger update signal will assert 2 cycles after assertion csr.in.valid, since CSR write results has 1 cycle delay.
* Tests
+ Pass riscv-tests breakpoint, diff with NEMU
* Todo:
+ Support 2 triggers chain by enable chain check when setting trigger
+ Relocate load trigger, since it widens entry of LoadQueue
+ Remove useless comments and dead code

Trigger: Refactor

---

.github/workflows/check_verilog.py
src/main/scala/device/RocketDebugWrapper.scala
src/main/scala/top/Top.scala
src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/XSTile.scala
src/main/scala/xiangshan/backend/fu/CSR.scala
src/main/scala/xiangshan/backend/fu/PMA.scala
src/main/scala/xiangshan/backend/fu/PMP.scala
src/main/scala/xiangshan/backend/fu/SRT16Divider.scala
src/main/scala/xiangshan/backend/fu/fpu/FMA.scala
src/main/scala/xiangshan/backend/issue/ReservationStation.scala
src/main/scala/xiangshan/backend/issue/StatusArray.scala
src/main/scala/xiangshan/backend/rename/freelist/MEFreeList.scala
src/main/scala/xiangshan/backend/rename/freelist/RefCounter.scala
src/main/scala/xiangshan/backend/rob/Rob.scala
src/main/scala/xiangshan/cache/dcache/meta/AsynchronousMetaArray.scala
src/main/scala/xiangshan/frontend/BPU.scala
src/main/scala/xiangshan/frontend/SC.scala
src/main/scala/xiangshan/frontend/Tage.scala
src/test/scala/top/SimTop.scala

This commit changes the reset of all modules to asynchronous style, including changes on the initialization values of some registers. For async registers, they must have constant reset values.

Switch to asynchronous reset for all modules

---

src/main/scala/xiangshan/cache/mmu/L2TLB.scala
src/main/scala/xiangshan/cache/mmu/TLB.scala

When L2TLB resp is valid, we will check: ppn, perm and level.
When L1TLB resp is valid, we will check: ppn.
I consider that it is not necessary to do pmp_check or permission_check in difftest when TLB response so L1TLB resp will not be checked when access fault or page fault occurs.
Please also merge https://github.com/OpenXiangShan/difftest/pull/99 to master.

MMU: Add L1TLB and L2TLB Resp difftest

---

src/main/scala/xiangshan/cache/mmu/L2TLB.scala
src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala

This commit fixes wrong assert when page cache refill. Refill is not actually valid when pte is access fault.

L2TLB: fix page cache assert when pte_ppn access fault

---

src/main/scala/xiangshan/Parameters.scala

Here is a bug caused by EnableUncacheWriteOutstanding: The case is extintr in Nexus-AM.
Three steps of the test:
clear intrGen's intr: Stop pass interrupt. A mmio write.
clear plic claim: complete intr. A mmio write.
read plic claim to check: claim should be 0. A mmio read.
The corner case:
intrGen's mmio write is to slow. The instruction after it executes
and plic claim's mmio's write & read execute before it. On the side of core with plic, the claim is cleared. But on the other side of intrGen with plic, the source of interrupt is still enabled and triggers interrupt. So the "read plic claim to check" get a valid claim and fails.

param: set EnableUncacheWriteOutstanding to false

---

debug/local_ci.py

Usage:
1. run ci test `python3 scripts/local_ci.py --xs-path $(pwd) --run`
2. print ci test name `python3 scripts/local_ci.py --xs-path $(pwd) --show-test`
3. print ci test command into splited sh files. Run the sh manualy. `python3 scripts/local_ci.py --xs-path $(pwd)`
More Params:
--sh-path: default is xs-path/ci-sh.
Other Params:
--pick-test MC: only run 'EMU - MC'
--numa: use numa ctrl, require eypc
--head-sha: magic word, default is today's date
--nemu-home/--am-home: don't know if it is used

debug: add local-ci.py to run github/emy.yml's ci tests at local server

---

.github/workflows/emu.yml
.github/workflows/nightly.yml

This commit should solve deprecation warnings in workflows.
See: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/ and https://github.com/actions/checkout#whats-new.

ci: use checkout@v3 instead of v2

---

.github/workflows/emu.yml
.github/workflows/nightly.yml
scripts/xiangshan.py
src/main/resources/constantin.txt
src/main/scala/xiangshan/DbEntry.scala
src/main/scala/xiangshan/backend/rob/Rob.scala
src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala
src/main/scala/xiangshan/cache/dcache/data/BankedDataArray.scala
src/main/scala/xiangshan/cache/dcache/loadpipe/LoadPipe.scala
src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala
src/main/scala/xiangshan/cache/dcache/mainpipe/MissQueue.scala
src/main/scala/xiangshan/cache/mmu/L2TLB.scala
src/main/scala/xiangshan/frontend/IFU.scala
src/main/scala/xiangshan/frontend/NewFtq.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueue.scala
src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
src/main/scala/xiangshan/package.scala

- add `LoadMissTable` to record different load miss state
> 0: first issue and hit
> 1: first miss and get miss entry
> 2: second miss and get miss entry
- add constant control of all databases
- fix some bug and rationalize the code of `constantIn`

LoadMissTable: add it and use constant control

---

src/main/scala/xiangshan/cache/mmu/L2TLB.scala
src/main/scala/xiangshan/cache/mmu/MMUBundle.scala
src/main/scala/xiangshan/cache/mmu/Repeater.scala
src/main/scala/xiangshan/cache/mmu/TLBStorage.scala

This commit is a repair for the decline of  cactusADM.
Submodule difftest will also be updated because l2 tlb check will only report warning when it fails. ( Errors will be reported until regs are wrong)

TLB: Direct-asso tlb will not use sector

---

.github/workflows/emu.yml
.github/workflows/nightly.yml

This reverts commit 33d13d4bd28246aab7d8ac58563d172047923ed2.
It may solve recent problems of invalid url in the checkout phase of CI.

Revert "ci: use checkout@v3 instead of v2 (#1942)"

---

Makefile
src/main/scala/top/ArgParser.scala
src/main/scala/top/Top.scala
src/main/scala/xiangshan/Parameters.scala
src/test/scala/top/SimTop.scala

fix bug:
- utility: if the `constantin.txt` does not exists, it defaults to 0.
- when making emu, use `WITH_CONSTANTIN=0` to close the constant control. In this situation, all ChiselDB switches controlled with constants recorded by Constantin will default to their initial valur. 
> Note that: `WITH_CONSTANT` defaults to 1.

Fix constant

---

src/main/scala/xiangshan/backend/rob/Rab.scala

This bug will be triggered when the ptr shift step is greater than the ptr size

Rab: fix a bug

---

src/main/scala/xiangshan/mem/lsqueue/LoadQueue.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueueReplay.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

- LoadQueueReplay: Worst case, all oldest instructions are allocated to the same bank. And the number of instructions is greater than the number of stages in load unit.
- remove bank conflict block
- Increase priority for data replay classes

LQ: fix select oldest inst and remove bank conflict block

---

src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala

CancelCount to EngPtr violates the timing requirement
Adding one cycle by regnext for better timing.

SQ: RegNext cancelcount for better timing

---

src/main/scala/xiangshan/frontend/PreDecode.scala

jumpTargets was unintentionally casted to 64bit and compare with a zero-extended 39bit signal.

Predecode: fix unintended width cast

---

src/main/scala/xiangshan/frontend/NewFtq.scala

In the old implementation, cfiindex_vec may be changed after the debug cfi capture its value which causes debug cfi check to fail on certain cases where cfiindex's valid is cleared right before the check.

FTQ: fix debug cfi check condition

---

src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala

This is a historical legacy issue where the minimum granularity for writing into the sbuffer used to be 8 bytes. Therefore, when two write requests to the sbuffer were located within the same 8 bytes, the second request (io.in(1)) had to be blocked. Now, with the minimum granularity for writing into the sbuffer being 1 byte, there is no need to block the second request in this situation.

Sbuffer: fix input logic

---

Makefile
src/main/scala/top/ArgParser.scala

1. Compile Option: make emu WITH_CHISELDB=1， to enable chiseldb
if compile emu without WITH_CHISELDB=1, only basic_db(TLLog now) is enabled.
3. Run Option:  ./build/emu --dump-db to dump all the database tables (if data from constantin is true)
4. Run Option:  ./build/emu --dump-select-db to dump selected the database tables (if data from constantin is true)
Param --dump-select-db "PTW TL" will the tables of which name covers one of the key("PTW" and "TL") of --dump-select-db.
TLDR:
1. when chiseldb is not needed, 
1.1 just ignore WITH_CHISELDB=1, --dump-db will only dump tllog.
1.2 compiled with WITH_CHISELDB=1, all the db codes will be compiled. If not use --dump-db, no db will be dumped.
2. when chiseldb is needed, all the db codes will be compiled. 
Use --dump-select-db "key1 key2 …

mk: support --dump-select-db to select chiseldb's table to dump

---

src/main/scala/top/Configs.scala

For better performance under L2 Evict@Refill feature
L3 clientDir will keep meta of all L2 blocks, and used to have the same ways as L2
Previously L2 Release first then Acquire, therefore L3 clientDir is invalidated first and then allocated, 
so it will hardly exceed capacity
Now L2 will Acquire first then Release, which means L3 clientDir is required to allocate when all valid,
so it is often that L3 clientDir will have set-capacity-conflict
An additonal-2-way is sufficient for fully utilizing the performance advantages of Evict@Refill, 
as our experiment shows little difference between +2 ways and +8 ways

Increase L3-clientDir ways

---

src/main/scala/xiangshan/frontend/RAS.scala

With an uninitialized RAS top, the internal state of L2 Cache may be changed with random addr request.

RAS: fix uninitialized top and write bypass entry

---

src/main/scala/xiangshan/backend/rename/Rename.scala

A move instruction can commit so fast that instr page fault or access fault cannot prevent it in time.
In order to fix this, we disable ME in rename stage when an instruction comes with exception.

rename: fix unhandled instr page fault caused by move elimination

---

src/main/scala/xiangshan/frontend/icache/ICache.scala

For timing evaluation purpose, should cause some performance drop.

ICache: shrink to 64K

---

src/main/scala/xiangshan/frontend/ITTAGE.scala

Remove redundant pred logic that selects base prediction when ITTAGE result hits but is not confident.

ITTAGE: use ITTAGE result even when not confident

---

src/main/scala/xiangshan/frontend/NewFtq.scala

This PR fixes redirection target error when:
1. FTB falseHit
2. Predecode stage detects falseHit but coincidently sets pd.isRet while the pd(ftqOffset) is not a RVC instruction.

ftq: fix predecode redirect use RAS condition

---

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

An load inst will fast replay check at s2, if dcache miss occur, data is forwarded from the bus at the same time. The data will be forwarded at s3, but **_s2_hint_fast_rep_** still high level. Hence, load will fast replay even though the data is ready. And the load also writeback s3.
Bug fix:
Update **_s2_hint_fast_rep_** at s3

LDU: fix load writeback twice

---

src/main/scala/xiangshan/backend/exu/ExeUnit.scala

Currently the definitions are instantiated every time when FUBlock is called. Though it addresses the dedup issue for multiple ExeUnits in one FUBlock, it still causes non-dedup modules across various FUBlocks and multiple CPU cores.

exu: fix the definition/instance in multicore

---

src/main/scala/xiangshan/backend/Scheduler.scala
src/main/scala/xiangshan/backend/issue/ReservationStation.scala

Fastdata drops writeback_valid, bypass invalid data to alu, and finally visit ITLB. This result in IPC difference in differenct seed.
After this Commit, there is no Randomness with/without DRAMsim3, tested by SPEC_0.3coverage, 2000000 instruction.
However, Randomness is detected before Iprefetch disabled (#2277) . I will test again after Iprefetch fixed bug and re-enabled

Reservation: Append writeback_valid to fastdata for bypass valid

---

src/main/scala/system/SoC.scala
src/main/scala/top/BusPerfMonitor.scala

The top-level memory port requires the ReqSourceKey user bits.
This would avoid adding an extra key through the BusPerfMonitor and also benefit SoC level optimizations, such as system caches.

SoC: require the ReqSourceKey user bits at top

---

src/main/scala/xiangshan/frontend/icache/ICacheMissUnit.scala

The previous scheme was as follows: After MSHR receiving data from L2, it was first written back to the ICache SRAM, and then the IFU was responded to. 
Now, both writing back to the ICache SRAM and responding to the IFU are done simultaneously.

icache: reduce 1 cycle in mshr

---

src/main/scala/xiangshan/Parameters.scala

Speculative entry number should be 32 rather than 64
Redundant MUX of RAS has proven to be essential for ITTAGE result to work so no fixup for that

RAS: reduce entry to improve timing

---

src/main/scala/xiangshan/frontend/icache/ICache.scala
src/main/scala/xiangshan/frontend/icache/ICacheBankedArray.scala
src/main/scala/xiangshan/frontend/icache/IPrefetch.scala

PrefetchMeta needs multiple read ports because of previous redundant structure. But now it only needs one read port. Both area and timing will be better.

fdip: use a simple sram to replace the prefetch meta with bank

---

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

load will fast wakeup at s2 and data must be writebacked at s3, but store-load nuke query will be occur at s3. This may cause the load to not be properly writebacked, causing other instructions to get wrong source data..
Bugs fix:
remove s3 store-load nuke query logic
PS:  May reduce performance

LDU: remove s3 nuke check logic

---

src/main/scala/xiangshan/frontend/FTB.scala
src/main/scala/xiangshan/frontend/FrontendBundle.scala
src/main/scala/xiangshan/frontend/NewFtq.scala
src/main/scala/xiangshan/frontend/SC.scala

`sc` is used for perf only (i.e. `TAGEMissBubble` counter and `SCMissBubble` counter), so it is better to be stored in Redirect SRAM instead of FTB

top-down: move sc from FTB to redirect SRAM

---

src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/backend/fu/util/CSRConst.scala
src/main/scala/xiangshan/frontend/icache/ICache.scala
src/main/scala/xiangshan/frontend/icache/ICacheMainPipe.scala

ICache ECC control CSR overlapped with CacheInstruction such that ICache ECC check could not be enabled.
This commit fixed the overlapping issue and added ICache ECC error generation mechanism.

ICache: fix ICache ECC function

---

src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala
src/main/scala/xiangshan/mem/prefetch/SMSPrefetcher.scala

The wrong fixed index was used to get alias in `SMSPrefetcher`, and there is no API to get alias in `DCacheWrapper`. The PR is to solve these.

sms: fix alias bug

---

src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/frontend/newRAS.scala

RAS counter size should be ctrsize rather than log2(ctrsize). If CI finished without major performance change, I will decrease ctrsize to log2(current ctrsize) to save space

RAS: fix counter size

---

src/main/scala/xiangshan/frontend/NewFtq.scala
src/main/scala/xiangshan/frontend/SC.scala

Avoid increasing SRAM area with unnecessary signal

top-down: remove 'sc_disagree' from redirect SRAM for FPGAPlatform

---

src/main/scala/xiangshan/mem/lsqueue/UncacheBuffer.scala

Bugs description:
mmio load writeback data by _ld_raw_data_, _ld_raw_data_ is not synchronized when data is written back.
Bugs fix:
use _RegEnable_ to synchronize
@good-circle orz

UncacheBuffer: fix mmio data writeback logic

---

src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/backend/Bundles.scala
src/main/scala/xiangshan/backend/decode/DecodeUnitComp.scala
src/main/scala/xiangshan/backend/decode/UopInfoGen.scala
src/main/scala/xiangshan/backend/fu/FuConfig.scala
src/main/scala/xiangshan/backend/fu/FuType.scala
src/main/scala/xiangshan/backend/fu/fpu/IntToVec.scala
src/main/scala/xiangshan/backend/fu/vector/Bundles.scala
src/main/scala/xiangshan/backend/rename/BusyTable.scala
src/main/scala/xiangshan/package.scala

* Depend on the vector instruction whether can be unblocked/blocked on pipeline, use different three issuequeue
* Use i2vector module for opivv and opmvv instructions

rv64v: reduce the number of vector issue queue

---

src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/backend/CtrlBlock.scala
src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/mem/lsqueue/LoadQueueRAW.scala
src/main/scala/xiangshan/mem/lsqueue/UncacheBuffer.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

Bugs description:
When a **read-after-read** violation occur, **ROB** incorrect flushing can lead to livelock.
Bugs fix:
Use **flushPipe** instead of **replayInst** to control flushing

LDU: fix rar flush logic

---

src/main/scala/xiangshan/backend/fu/PMA.scala

The LR instruction should report a load access fault, while the SC and AMO instructions will only report a store access fault. The confusion between isAtom and isAmo in PMA resulted in the LR instruction being judged as AMO and no load access fault being reported.

PMA: lr should raise load access fault

---

src/main/scala/xiangshan/L2Top.scala
src/main/scala/xiangshan/XSTile.scala
src/main/scala/xiangshan/backend/MemBlock.scala

Now **Triple buffer in PTW - L2** (two in MemBlock, one in L2Top below xbar)
can reduce violation to less than 30ps

Move one buffer in L1I - L2 path from L2Top to MemBlock

---

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

Bugs descriptions:
when RAR nuke occur but dcache miss, load will be writebacked.
Bugs fix:
when dcache miss, set RAR nuke low

LDU: fix ldu ldld nuke generate logic

---

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

Bugs descriptions:
when the load triggers a load-load violation, the load will incorrectly writeback.
Bugs fix:
fix load replay causes update logic

LDU: fix ld-ld nuke rollback logic

---

src/main/scala/xiangshan/mem/lsqueue/LSQWrapper.scala

When an uncache load and _enableOutstanding_ is true (default false), the uncache fsm will transition to an incorrect state.
Bug fix:
remove _enableOutstanding_ from the condition

LSQ: fix uncache req logic

---

src/main/scala/xiangshan/mem/lsqueue/LoadQueueRAR.scala

Bugs description:
LoadQueueRAR requires 2 cycles to store paddr，when a probe request comes in the previous cycle，_released_ will not be updated in correctly.
Bugs fix:
Add a bypass register, store paddr temporary.

LQ: Fixed the bug that the load did not detect RAR violation

---

src/main/scala/xiangshan/backend/rename/Rename.scala
src/main/scala/xiangshan/backend/rob/Rab.scala

* When creating snapshot at the middle of split uops, RAT record the state before this snapshot, but ROB record the enqPtr containing some states of last cycle.

Backend: disallow snapshot when there are tail uops at the same cycle

---

scripts/vlsi_mem_gen

In vlsi_mem_gen, which does transformation from Chisel generated array in MFC mode, use `&` operator instead of for-loop when mask granularity is 1.

scripts: use & when bitmask granularity is 1

---

src/main/scala/xiangshan/frontend/Tage.scala

This removes simulation compile-time warning about index width mismatch.

bpu: fix tage table usage ctr

---

src/main/scala/xiangshan/frontend/icache/ICache.scala
src/main/scala/xiangshan/frontend/icache/ICacheBankedArray.scala

CacheOp is deprecated, but this fix is required to make the compiler happy.
The related PR is the change in SRAMTemplate OpenXiangShan/Utility#50 
https://github.com/OpenXiangShan/Utility/pull/50/files#diff-a473eaad7802dde422ddef37a671d197b04af03e62f0c9c37a79d4c2daf24637R63-R64

ICache: fix cacheop waymask width

---

src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala
src/main/scala/xiangshan/cache/dcache/mainpipe/MissQueue.scala

Imporve gate coverage for DCache MissQueue and MainPipe.
For control signals: `RegNext` -> `GatedValidRegNext`
For datapath: `RegNext` -> `RegEnable`

Gate coverage optimization: MissQueue & MainPipe

---

src/main/scala/xiangshan/backend/decode/DecodeUnitComp.scala

This reverts commit 00960c78943d85961c3def97cd7c0a6cbe9f002d.

Revert "Decode: move vld index table lookup to decodeunit stage"

---

src/main/scala/xiangshan/backend/datapath/DataPath.scala
src/main/scala/xiangshan/backend/issue/IssueQueue.scala

* fix resp signal for vector load/store
* hold the canIssueVec when vector load/store instruction is not the oldest uop

issueQueue: fix vld cannot clear the validReg siganl after issued

---

Makefile
src/main/scala/top/Configs.scala

To run vcs simulation, you need to:
1. change `AlwaysBasicDB` in `Parameters.scala` to `false`
2. `make simv WITH_CONSTANTIN=0 WITH_CHISELDB=0 CONSIDER_FSDB=1 MFC=1`
3. `./build/simv +workload=<workload> +diff=<ref-so>`

build: fix vcs simulation workflow

---

src/main/scala/xiangshan/backend/fu/CSR.scala
src/main/scala/xiangshan/backend/fu/PMP.scala

pmpaddr CSRs could be uninitialized, but for difftesting with NEMU, we opt to initialize them. However, pmp and pma CSRs are not checked in difftest, which should be fixed in feature.
This PR is a part of migrating the Linux-hello test in CI from riscv-pk to OpenSBI.

CSR: initialize pmpaddr with 0 for difftest

---

src/main/scala/xiangshan/backend/fu/CSR.scala
src/main/scala/xiangshan/backend/fu/util/CSRConst.scala

The CSRs menvcfg and senvcfg are required by ISA and openSBI. To run openSBI, we merely include them without any functionality. The functionality around these should be added in the feature.
This PR is a part of migrating the Linux-hello test in CI from riscv-pk to OpenSBI.

CSR: add menvcfg and senvcfg CSR without function

---

src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/backend/fu/CSR.scala
src/main/scala/xiangshan/backend/fu/util/CSRConst.scala

* `ebreak` instruction will raise breakpoint exception when hart not in debug mode.
* Use the signals renamed with "has*" to specify the traps(exceptions/interrupts) are to be handled which were transported from ROB, while the signals renamed with "raise*" are being transported to ROB.
This commit is cherry-pick from nanhu and new-backend.
This PR is a part of migrating the Linux-hello test in CI from riscv-pk to OpenSBI.

CSR: Correct the behavior of `ebreak` when hart not in debug mode

---

.github/workflows/emu.yml
scripts/xiangshan.py

We have discoverd that the older version of riscv-pk crashes on harts that support H-ext due to issues with checking mideleg. Although this issue was fixed back in 2021 (commit 4ae5a88), considering that riscv-pk has been replaced by opensbi, we deciede to gradually transition our testing workloads to utilize opensbi instead.
Using MFC for "EMU - MC" test may decrease the total ci time.
This PR might be the last part of migrating the Linux-hello test in CI from riscv-pk to OpenSBI.

CI: switch to opensbi for linux-hello & switch to mfc for MC

---

src/main/scala/xiangshan/frontend/icache/IPrefetch.scala

If not initialized, it will result in an X state and propagate forward.

ICache: initializing p1_vaddr and p2_vaddr in prefetch pipeline.

---

src/main/scala/device/AXI4UART.scala

At present, there will be no input from uart. Thus, the "Rx FIFO Valid Data bit" of stat reg should be 0 rather than 1. Also, hardware side cannot get any valid indication from software side, this bit could only be 1 or 0 staticly. 
This solves the stuck issuse of xvisor boot-up.
This is just a temporary solution. uart module for emu should be refactored.

device(uartlite): fix wrong stat register

---

src/main/scala/top/Configs.scala
src/main/scala/xiangshan/L2Top.scala
src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/XSTile.scala
src/main/scala/xiangshan/backend/Backend.scala
src/main/scala/xiangshan/backend/CtrlBlock.scala
src/main/scala/xiangshan/backend/ExuBlock.scala
src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/backend/Scheduler.scala
src/main/scala/xiangshan/backend/dispatch/Dispatch.scala
src/main/scala/xiangshan/backend/exu/WbArbiter.scala
src/main/scala/xiangshan/backend/fu/CSR.scala
src/main/scala/xiangshan/backend/rob/Rob.scala
src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala
src/main/scala/xiangshan/cache/dcache/mainpipe/MissQueue.scala
src/main/scala/xiangshan/cache/mmu/MMUBundle.scala
src/main/scala/xiangshan/frontend/Frontend.scala
src/main/scala/xiangshan/frontend/icache/ICache.scala
src/main/scala/xiangshan/frontend/icache/ICacheMainPipe.scala
src/main/scala/xiangshan/frontend/icache/IPrefetch.scala
src/main/scala/xiangshan/mem/lsqueue/LSQWrapper.scala
src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
src/main/scala/xiangshan/mem/pipeline/AtomicsUnit.scala
src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala

Currently, many different lengths of HartId in Xiangshan, making it hard to configure it to scale more than 16 cores since we have set 4bits somewhere. This commit corrects MaxHartIdBits in config and uses MaxHartIDBits where it needs to get this solved.
Note: Huancun and CoupledL2 also need to be fixed. Already merged PR at:
- https://github.com/OpenXiangShan/HuanCun/pull/173
- https://github.com/OpenXiangShan/CoupledL2/pull/102

Configs: correct MaxHartIdBits

---

src/main/scala/system/SoC.scala

`clint.module.io.rtcTick` is assigned twice in `SoCMiscImp`, it should be driven using `rtc_clock` (in #1565), remove the extra fix frequency assignment.

soc: remove extra assignment to rtcTick

---

src/main/scala/xiangshan/mem/prefetch/L1PrefetchComponent.scala

Bug description：
`source_1_older` is not controlled by valid signals so it may become x state, causing all prefetched training signals to become the x state.
Bug Fix:
`source_1_older` is valid only when both prefetch train sources are valid. Thanks to two Gods @good-circle @Tang-Haojin.

fix X problem in l1 prefetch

---

src/main/scala/xiangshan/mem/prefetch/L1PrefetchComponent.scala

Since it is not controlled by the valid signal, source_1_older may become the x state, causing all prefetched training signals to become the x state.

L1Prefetch: fix x problem in l1 prefetch (#2862)

---

src/main/scala/xiangshan/backend/dispatch/Dispatch.scala

This helps to avoid X-state of `io.recv`

Dispatch: consider input valid for `thisIsBlocked`

---

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

When an exception occurs, as s3_out is true, backend will still consider the data valid at this time (which is actually in X state) valid and bypass it. Although in real chips, this situation will be handled after 2 cycles of exception processing (flushing the pipeline and redirecting), when using vcs simulation, the simulation cannot continue due to the problem of X-state propagation. Therefore, when an exception occurs in load_s3, the output data will be forcibly set to 0.

LSU, Loadunit: Set all data to 0 when exception

---

src/main/scala/xiangshan/backend/dispatch/Dispatch.scala

This helps to avoid X-state of `io.recv`

Dispatch: consider input valid for `thisIsBlocked` (#2869)

---

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

When an exception occurs, as s3_out is true, backend will still consider the data valid at this time (which is actually in X state) valid and bypass it. Although in real chips, this situation will be handled after 2 cycles of exception processing (flushing the pipeline and redirecting), when using vcs simulation, the simulation cannot continue due to the problem of X-state propagation. Therefore, when an exception occurs in load_s3, the output data will be forcibly set to 0.

LSU, Loadunit: Set all data to 0 when exception (#2888)

---

src/main/scala/xiangshan/backend/exu/ExeUnit.scala
src/main/scala/xiangshan/backend/fu/FuConfig.scala
src/main/scala/xiangshan/backend/fu/FuncUnit.scala
src/main/scala/xiangshan/backend/fu/wrapper/VIAluFix.scala

Add parameterized delay for fixtiming:
Funcunit : add fixtiming pipereg
exuunit : delay latdiff cycles
Fuconfig : latfixitming delay N cycles to fixtiming
latency - latfixitming is the cycles to be delayed after the result generated
if latfixtiming !=0 latfixtiming is the pre-latency of funcunit
don't support uncertainlatency; fence, csr; branch, mul, std (Funcunit)
vialufix outeew use new pipereg

Exu,FuncUnit,Vialufix: Add parameterized delay for fixtiming

---

src/main/scala/xiangshan/backend/fu/FuConfig.scala
src/main/scala/xiangshan/mem/pipeline/AtomicsUnit.scala
src/main/scala/xiangshan/mem/pipeline/HybridUnit.scala

After new backend was merged into master, the guest page fault was delete from fuConfig. That results in the wrong guest page fault exception vaddr in CSR module. This commit adds gpf back to fuConfig

LSU, RVH: fix the bug about the exception vaddr of guest page fault 

---

Makefile
src/main/scala/top/Generator.scala

This can make users to modify target format without recompiling scala.

build: specify output format in Makefile

---

src/main/scala/xiangshan/backend/fu/FuConfig.scala

H extension exceptions were deleted when new backend was merged

FuConfig, RVH: add H ext exceptions

---

src/main/scala/xiangshan/backend/MemBlock.scala

When the fpgaplatform option is enabled ,We should synchronize the reset and release of frontend and backend to avoid the following errors caused by a multi-core boot on
`Assertion failedat L2TLB.scala:296 assertl!flush latch(i) ll waiting resp(i)) // when sfence latch wait for mem resp, waiting resp should be true`

resetGen: fix memblock reset on fpgaplatform

---

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

Consider the ready signal of mmio.
After 3 cycles of s0 mmio fire, s3_mmio.valid can be set as true.

LoadUnit: fix mmio fake valid in ldu

---

src/main/scala/xiangshan/backend/Backend.scala
src/main/scala/xiangshan/backend/Bundles.scala
src/main/scala/xiangshan/backend/decode/DecodeUnit.scala
src/main/scala/xiangshan/backend/decode/FPDecoder.scala
src/main/scala/xiangshan/backend/exu/ExeUnit.scala
src/main/scala/xiangshan/backend/exu/ExeUnitParams.scala
src/main/scala/xiangshan/backend/exu/ExuBlock.scala
src/main/scala/xiangshan/backend/fu/FuConfig.scala
src/main/scala/xiangshan/backend/fu/FuncUnit.scala
src/main/scala/xiangshan/backend/fu/Vsetu.scala
src/main/scala/xiangshan/backend/fu/wrapper/VSet.scala
src/main/scala/xiangshan/backend/issue/Entries.scala
src/main/scala/xiangshan/backend/issue/EntryBundles.scala
src/main/scala/xiangshan/backend/issue/IssueBlockParams.scala
src/main/scala/xiangshan/backend/issue/IssueQueue.scala
src/main/scala/xiangshan/backend/issue/SchdBlockParams.scala
src/main/scala/xiangshan/backend/issue/Scheduler.scala

1. when the instruction depend on old vd, we cannot set the srctype to imm
2. when vl = 0, we cannot set the srctype to imm because the vd keep the old value
3. when vl = vlmax, we can set srctype to imm when vta is not se

rv64v: add ignore oldvd judgement in issue queue

---

src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala
src/main/scala/xiangshan/cache/dcache/mainpipe/MissQueue.scala

Fix X propagation problem in DCache caused by non-initialized signal in MainPipe.

DCache: Fix X propagation problem

---

.github/workflows/nightly.yml

It takes too long to compile emu using SFC. I propose using MFC instead.

ci: use MFC for nightly regression

---

.github/workflows/check_verilog.py
src/main/scala/xiangshan/backend/fu/CSR.scala
src/main/scala/xiangshan/backend/issue/FuBusyTableWrite.scala
src/main/scala/xiangshan/backend/issue/ImmExtractor.scala

XSTile will duplicated after the new backend is merged. This PR fixed this by preventing the direct use of Map and Set in Chisel and letting them convert to Seq and sorted by some fixed key. And add CI to prevent this from happening again. 
I suggest merging it with **rebase** mode since I have 2 commits, one for bug fixes and one for adding ci, to prevent it from happening again.

Prevent XSTile duplication for new backend

---

src/main/scala/xiangshan/backend/decode/DecodeUnit.scala
src/main/scala/xiangshan/backend/decode/FusionDecoder.scala

This commit sorts out decode by the ratified name of each extension for Zb* and Zk*. And add some comments about RV32 concerns we may need someday.

DecodeUnit: clean up decoder

---

src/main/scala/xiangshan/backend/decode/DecodeUnit.scala
src/main/scala/xiangshan/backend/fu/Alu.scala
src/main/scala/xiangshan/package.scala

This PR added RISC-V Integer Conditional Operations Extension, which is in the RVA23U64 Profile Mandatory Base. And the performance of conditional move instructions in micro-architecture is an interesting point to explore.
Zicond instructions added: czero.eqz, czero.nez
Changes based on spec:
https://github.com/riscvarchive/riscv-zicond/releases/download/v1.0.1/riscv-zicond_1.0.1.pdf

riscv-zicond: Add Zicond Extension

---

src/main/scala/device/AXI4UART.scala

txData is not always on wdata(7,0) when AXI4 DataWidth >= 32 bits, we should adjust it dynamically.

AXI4UART: dynamically adjust txDataPos using beatBytes

---

src/main/scala/xiangshan/frontend/ITTAGE.scala

update.uValid is X when reset, sometimes causing random bits written into ITTAGE useful array.
this commit fixes the useful array write condition and RegEnable reset init.
The figure below is the waveform of the same `emu` on the same workload (microbench) with a different seed.
The X state will not propagate. However, it may already cause problems before it is stabilized by a valid signal from previous stages.
This PR will very likely fix the CI IPC fluctuation.

bpu: fix ittage reset init

---

src/main/scala/utils/LogUtils.scala

Chisel Assertions are checked only when reset is deasserted.
This extra condition is introduced in https://github.com/OpenXiangShan/XiangShan/pull/2023. It seems to be asserted only after reset is deasserted. However, Chisel automatically generates a `~reset` condition for assertions. The simulation seems OK without this extra condition.

LogUtils: remove the unused reset condition

---

src/main/scala/xiangshan/cache/dcache/mainpipe/MissQueue.scala

MissQueue：fix bug: 'isKeyword' update when miss req merge

MissQueue:  fix bug: 'isKeyword' update  when  miss req merge

---

src/main/scala/top/Configs.scala

They should be disabled when the PerfDebug option of XiangShan is disabled.
Now `--disable-perf` will work for L2 and L3 as well.

Configs: fix the enablePerf for L2/L3

---

src/main/scala/top/ArgParser.scala
src/main/scala/top/Configs.scala

This can help users who only build one core but then manually instantiate more than two cores in the SoC.

Config: set minimal hartid width to 6

---

src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala

When the req is sent into LLPTW and its status need to be changed to last_hptw_req, the mem_resp_hit is not valid. It make L2TLB don't store the pte of the req. That is why L2TLB resp a wrong stage 1 pte. So the mem_resp_hit need to be valid when the new req's status is changed into last_hptw_req directly.

LLPTW, RVH: fix the mem_resp_hit when the new req's status is changed to last_hptw_req

---

src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/backend/fu/CSR.scala
src/main/scala/xiangshan/backend/fu/util/CSRConst.scala

Custom-CSR sdsid is a legacy from labeled XiangShan, which is no longer in use. Remove this Custom-CSR.
This patch fixes OpenXiangShan/NEMU#329

CSR: remove useless sdsid custom-CSR

---

Makefile
src/main/scala/top/ArgParser.scala
src/main/scala/top/Top.scala
src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/backend/MemBlock.scala

Separate FPGAplatform from resetgen. Configure restgen as an optional option. RESETGEN is disabled by default on Paladin.
It should be noted that multi-core XIANGSHAN cannot be started after enabling RESETGEN, which may still be bug

args: modify the optional configuration of the run command

---

Makefile

also use echo -e to print "\n"
Related PR https://github.com/OpenXiangShan/difftest/pull/375
mix purpose PR because the modification is minor.

misc: use time -v in time log

---

src/main/scala/xiangshan/backend/datapath/WbArbiter.scala
src/main/scala/xiangshan/backend/exu/ExeUnit.scala
src/main/scala/xiangshan/frontend/icache/ICacheMainPipe.scala

Tile Dedup is essential to reduce the size of Verilog for RTL Simulation. However, some bugs and redundant information prevent tile dedup from being possible when generating multicore XiangShan. This PR gets this fixed.
The detailed message is in the commit. To save the commit messages, I recommend using the rebase method to merge this PR.

Some fixes on Tile Dedup for EMU

---

src/main/scala/top/Top.scala

Previously, difftest bundles can only be generated when building `sim-verilog` target. The difftest can not be used when simulating design that use the output of `make verilog` target.
This patch enable generating of difftest bundles for `make verilog` target, it can further be used to enable difftest support in simulation.

difftest: Support generating difftest bundles for `make verilog` target

---

src/main/scala/xiangshan/cache/dcache/loadpipe/LoadPipe.scala
src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala

- Remove useless data_read when DCache miss in LoadPipe
- Fix req priority in DCache MainPipe

DCache: Remove useless data_read when miss in LoadPipe

---

src/main/scala/xiangshan/backend/issue/Dispatch2Iq.scala

The pattern matching may not success because the sequence of a `Set` is not determined.

Dispatch2Iq: fix store not using store's special select policy

---

src/main/scala/xiangshan/cache/mmu/MMUBundle.scala

When accessfault happens and PTW don‘t get resp from mem before this exception，PTW will resp ppn which is x status. It makes   L1TLB resp x status paddr. Then a assert in IcacheMainPipe will be triggered. This assert is following:
`assert(PopCount(s1_tag_match_vec(0)) <= 1.U && (PopCount(s1_tag_match_vec(1)) <= 1.U || !s1_double_line),
"Multiple hit in main pipe, port0:is=%d,ptag=0x%x,vidx=0x%x,vaddr=0x%x port1:is=%d,ptag=0x%x,vidx=0x%x,vaddr=0x%x ",
PopCount(s1_tag_match_vec(0)) > 1.U,s1_req_ptags(0), get_idx(s1_req_vaddr(0)), s1_req_vaddr(0),
PopCount(s1_tag_match_vec(1)) > 1.U && s1_double_line, s1_req_ptags(1), get_idx(s1_req_vaddr(1)), s1_req_vaddr(1))`

PTW: fix the bug that ppn is x status when accessfault happens

---

src/main/scala/xiangshan/L2Top.scala
src/main/scala/xiangshan/XSTile.scala

* backbone: refactor CoupledL2 top-level framework
TL2TLCoupledL2 and TL2CHICoupledL2 used to flatten all the logics in each top-level module, which makes two versions of CoupledL2 repeat lots of the logics. In fact, these two versions share most of the logics in the top level except for outer interface (one for TileLink and one for CHI).
This commit extracts the common parts between TileLink and CHI and modularizes into CoupledL2, so that TL2TLCoupledL2 and TL2CHICoupledL2 only need to implement the differences with each other.
* MMIOBridge: fix address range for MMIO address space

coupledL2, L2Top, XSTile: refactor CoupledL2 top-level framework

---

src/main/scala/xiangshan/Bundle.scala

`L1CacheErrorInfo.report_to_beu` is valid iff `L1CacheErrorInfo.valid === true.B`, therefore `beu_errors.[id]cache.valid` should be `valid && report_to_beu`.

L1Cache: L1CacheError must be valid to report to beu

---

src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala

In the previous design, for scalar store commands, commits were made based on the `scommit` passed in by rob. That is, after rob commits n store commands in one cycle, it sets scommit to n, and the storequeue needs to commit n entries based on the value of scommit.
Due to the special nature of vector instructions, a vector store instruction may correspond to a maximum of 128 items, and it is not possible to use `scommit` commits, which are similar to scalar commits.
In this modification, both vector and scalar directives are compared against `robidx`, and the storequeue entry is committed when the `uop` stored in `uop` is equal to or older than the `pendingptr` passed in by rob. This has some improvement on timing.
Also, additional processing is currently required for vector instructions. …

StoreQueue: Commit storequeue entry by judging robidx

---

src/main/scala/xiangshan/backend/fu/fpu/IntFPToVec.scala
src/main/scala/xiangshan/package.scala

FPU: fix f2v boxing error 
set result as NAN when higher bit are not all zeros

FPU: fix f2v boxing error when higher bits are not all zeros

---

src/main/scala/top/Configs.scala

EnableBPD is not used by BPU anymore. Remove it in Config.
This PR adds the override config of BPU to MinimalConfig.
This configuration aims to provide very different parameters from DefaultConfig. Thus allowing verification of more parameters.
The overall size of BPU is also reduced, which slightly reduces the compile time (around 20s on 7950X).

config: use smaller BPU in MinimalConfig

---

Makefile
build.sc

Chisel 6.4.0 has released https://github.com/chipsalliance/chisel/releases/tag/v6.4.0
Also bump scala because I encounter a scala compiler bug in JDK 21.
https://github.com/scala/bug/issues/12783
This is fixed in 2.13.11+

deps: bump chisel and scala

---

src/main/scala/xiangshan/backend/Backend.scala
src/main/scala/xiangshan/backend/decode/DecodeUnitComp.scala

* fix uop split bug for vsetvl when rd and rs1 are 0, the first uop use wrong source register
* fix vtype writeback logic, add mux to choose vtype from intExu or vfExu

vtype: fix bug when vsetvl instruction's rd and rs1 are x0

---

src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala

L2TLB flush was controlled by vsatp or hgatp or satp or sfence, but the flush of LLPTW and PTW was controlled by satp and sfence. That makes some bugs

PTW, LLPTW: change the flush signal to be same to the flush in L2TLB

---

src/main/scala/xiangshan/backend/decode/DecodeUnitComp.scala
src/main/scala/xiangshan/backend/fu/FuConfig.scala
src/main/scala/xiangshan/backend/fu/wrapper/VFALU.scala

fix vfredsum/max/min:
When the vector vfredusum/max/min consists entirely of inactive elements and vs1[0] is NaN, the result should be vs1[0]
When both elements of vfredusum are inactive, the temporary result changes from positive zero to negative zero.
nes vcompress to fit v0/vl split:
The vcompress calculation combines the ones_sum result with vs1 using a temporary register to reduce one read operation. Additionally, other uops, except ones_sum, reduce the basemask calculation and the right shift basemask operation.
fix vpermtest to fit new vcompress

VPU: new vcompress to fit v0&vl split; fix vfredsum/min/max

---

src/main/scala/xiangshan/cache/mmu/L2TLB.scala

When LLPTW looks for the last level of the page table (a 4KB page table), it must be a leaf node. The condition that the x w r bits of the page table cannot all be 0 needs to be satisfied. When this condition is not met, the LLPTW needs to report pf to the L1 TLB. (Although in practice the L1 TLB does a permission check as well, which does not result in an error from the MMU's overall perspective)

MMU: LLPTW should report PF when pte is not leaf

---

.github/filters.yaml
.github/workflows/emu.yml

For a long time, modifying files which do not affect CPU core still have to run and pass all CI processes, which could waste a lot of time. This patch introduces dorny/paths-filter@v3 to skip some commits which only modifies edge files such as issue templates, codeowners and readme.

MISC: skip CI for commits that do not modify core sources.

---

src/main/scala/xiangshan/backend/issue/Dispatch2Iq.scala
src/main/scala/xiangshan/backend/issue/IssueBlockParams.scala
src/main/scala/xiangshan/backend/issue/IssueQueue.scala

- generate busytable read ports based on the actual number of read operands required
- check the type of read operands when generating the WB waking up ports
- only wen signals for data types that load IQ will write back can be sent out

Timing optimization for MemScheduler

---

src/main/scala/xiangshan/backend/exu/ExeUnit.scala
src/main/scala/xiangshan/backend/fu/vector/VecPipedFuncUnit.scala
src/main/scala/xiangshan/backend/fu/wrapper/VFALU.scala

fix vfreduction bug:
Unordered reduction only generates fflags in the first round of uops, with the fflags outputs of other rounds set to 0; 
ordered reduction has only the lowest 5 bits of vfalu_0 valid in each uop, while all others are set to 0

VPU: fix vfreduction bug; remove redundant logic for scalar compute

---

src/main/scala/xiangshan/mem/lsqueue/VirtualLoadQueue.scala

usSecondInv is not useful in the current design, and removing this part of the code would speed up Palladium's compilation considerably (there are still some compilation speed issues to be resolved)

VirtualLoadQueue: remove useless logic

---

src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala

If there is an inactive element in a vector access instruction, it will not be sent to the sta pipeline, so the data in the corresponding entry in the StoreQueue is invalid, and we use `vecValid` to differentiate between valid and invalid data in table entries.
For StoreQueue entries, `vecValid` depends on `hasException`, `vecDataValid` (whether the data in the table entry is valid or not), and `isVec` (whether it is a table entry for a vector instruction or not). `vecDataValid` is initialized to false, and will be set to true when sta writes back to the entry and the entry is a vector instruction.
Only vector instructions have invalid data in table entries, because we can't determine how many table entries are needed for a vector access uop at dispatch time.

StoreQueue: fix X  when write StoreBuffer

---

src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala
src/main/scala/xiangshan/cache/dcache/mainpipe/MissQueue.scala

Error signal for L2 refill request is generated when mem_grant but sent to MainPipe in mainpipe_req with l2_hint, which is not correct. 
Move error signal to refill_info now.

DCache: Move L2 refill error signal to refill_info

---

src/main/scala/xiangshan/frontend/icache/ICache.scala
src/main/scala/xiangshan/frontend/icache/ICacheMainPipe.scala
src/main/scala/xiangshan/frontend/icache/ICacheMissUnit.scala

Flush mainPipe, invalidate missSlot, and cancle request to MSHR when receive `fence.i` to prevent fake-valid data from sending to IFU.
This was fixed in kunminghu (#2632), but not in master.
Note that the miss handling state machine is re-designed in master. Instead of marking `missStateQueue` as `m_invalid`, we set `missSlot.valid = false.B` to do invalidate reserved data.

ICache: fence.i should flush mainPipe

---

src/main/scala/xiangshan/cache/mmu/PageTableCache.scala

sfence_vma: When sfence_vma rs1 === x0 and rs2 =/= x0, PageCache incorrectly flush the global mappings in level3. In non-virtmode, sfence_vma fence noS2xlate pte in PageCache.
hfence_gvma: When hfence_gvma rs2=/=x0,  hfence_gvma will specify a single virtual machine identifier (VMID). In PageCache, the case that rs1 =/= x0 is wrong: when rs1 ===x0,  rs2 === x0 specifies a VMID and  rs2=/= x0 don't specifies a VMID.

PageTableCache, RVH: fix the error fence when sfence_vma or hfence_gvma is executed

---

src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/cache/CacheInstruction.scala
src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala
src/main/scala/xiangshan/cache/dcache/data/AbstractDataArray.scala
src/main/scala/xiangshan/cache/dcache/data/BankedDataArray.scala
src/main/scala/xiangshan/cache/dcache/data/DuplicatedDataArray.scala
src/main/scala/xiangshan/cache/dcache/loadpipe/LoadPipe.scala
src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala
src/main/scala/xiangshan/cache/dcache/meta/LegacyMetaArray.scala
src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala
src/main/scala/xiangshan/frontend/Frontend.scala
src/main/scala/xiangshan/frontend/icache/ICache.scala
src/main/scala/xiangshan/frontend/icache/ICacheMainPipe.scala

change the valid in the Bundle to the valid out of Bundle used `ValidIO`.

L1CacheErrorInfo: code refactor for correct and convenient clockgate

---

.github/workflows/emu.yml
scripts/xiangshan.py

This PR adds PGO when building emu for CI. The workload used for training is coremark-2-iteration. To avoid CPU bugs causing PGO workload fails, this PR uses `--no-diff` for PGO.
Preliminary Result is shown below:
Item | [Run 7059(s)](https://github.com/OpenXiangShan/XiangShan/actions/runs/9519739280) | [Run 7051(s)](https://github.com/OpenXiangShan/XiangShan/actions/runs/9516292340) | Speed Up %
-- | -- | -- | --
Set up job | 2 | 2 |  
Run actions/checkout@v2 | 41 | 40 |  
set env | 31 | 31 |  
clean up | 31 | 32 |  
Build EMU | 5193 | 3568 | -31.29
Basic Test - cputest | 179 | 255 | 42.46
Basic Test - riscv-tests | 413 | 649 | 57.14
Basic Test - misc-tests | 1052 | 1916 | 82.13
Basic Test - nodiff-tests | 38 | 42 | 10.53
Simple Test - microbench | 141 | 188 | 33.33
Simple Test - …

CI: enable PGO when building emu for CI

---

src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala

HPTW can translate three levels page. This bug is about non-leaf pte that pte level >= 2. When HPTW gets a level 2 pte and the pte is valid but RWX are zero, it does't raise pagefault. That's wrong.

HPTW, RVH: fix the bug that non-leaf and level >= 2 pte doesn't raise pagefault.

---

.github/workflows/nightly.yml

Enable PGO for nightly regression to reduce the running time.

ci: use PGO for nightly regression

---

src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala

However, databuffer.io.enq.bits.vecValid will be false so this store will not actually write into sbuffer.

StoreQueue: sq entries with exception can deq without allvalid

---

src/main/scala/xiangshan/package.scala

This commit change `fuOpType` of `hlvxhu` and `hlvxwu` to avoid conflicts with `vleff`. Besides, we also change `isHlv` and `isHlvx`.

package: change hypervior load's fuOpType

---

src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala

1. ppn_af will check ppn_high because the paddrbits is 36. But when s2xlate is enabled, stage 1 ppn is 41 bits because stage 2 is sv39x4. ppn_af should not check ppn_high when s2xlate is enabled. 
2. when accessfault happens in stage 1 translation, PTW should resp rather than entering the last stage 2 translation.

PTW, RVH: fix the bug that the last second stage translation continues after the first stage translation raises af

---

src/main/scala/xiangshan/backend/fu/wrapper/VFALU.scala

fix vfredunction fflags:
Vfunordered:
first group uops, only fflags from vfalu_0 are valid;
fflag from last uop is valid
Vfordered:
for each uops, only fflags from vfalu_0 are valid

VFALU: fix vfredunction fflags

---

src/main/scala/xiangshan/backend/decode/DecodeUnitComp.scala
src/main/scala/xiangshan/backend/decode/UopInfoGen.scala
src/main/scala/xiangshan/backend/decode/VecDecoder.scala
src/main/scala/xiangshan/package.scala

when ldest is zero, rfWen is setted to false in decode unit. DecodeUnitComp may override it

rv64v: fix rfWen signal when writing x0 for vector instructions

---

src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala

When access fault exception is reported on s2 of StoreUnit, the exception address will be written into exception buffer of StoreQueue. If the store is flushed on s2, the exception buffer must not be updated otherwise mtval csr might be of false value.

StoreUnit: fix bug when `lsq_replenish` of s2 fails to redirect

---

src/main/scala/xiangshan/cache/mmu/MMUBundle.scala
src/main/scala/xiangshan/cache/mmu/MMUConst.scala
src/main/scala/xiangshan/cache/mmu/PageTableCache.scala
src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala

The first stage is sv39 and the second stage is sv39x4. Before Xiangshan realizes H extension, the paddr is 36 bits, so ppnlen is 24 bits. After Xiangshan realizes H extension, the ppnlen of stage 1 should be 29 bits because the paddr of stage 1 is gpaddr for host and gpaddr is 41 bits. I add the gvpnlen to replace the ppnlen of stage 1 in L2TLB.

L2TLB, RVH: change ppnlen from 24 to 29 for the first stage translation in two stage translation

---

src/main/scala/xiangshan/frontend/icache/IPrefetch.scala

Fixes MC-Linux CI fail: https://github.com/OpenXiangShan/XiangShan/actions/runs/9709320741/job/26802800197.
In IPrefetch:
1. s0 send read request to MetaArray
2. s1:
- receive response from MetaArray (therefore `s1_SRAM_valid === true.B`)
- and receive update request from MSHR(`fromMSHR.valid && !fromMSHR.bits.corrupt === true.B`)
- and `s1_fire === true.B`
3. waymasks directly from SRAM(which might be outdated) enters s2 stage, and update request from MSHR is actually discarded.
If it is a miss(`waymask === 0.U`), IPrefetch will send miss request to MSHR. In this case, multiple refills of the same cache block may occur, which in turn causes a bug with multiple hits in the MetaArray.
As a fix, we should use information from MSHR to update `s1_SRAM_waymasks` too.
Local MC-Linux test passed …

IPrefetch: MSHR should update IPrefetch s1 waymask

---

src/main/scala/xiangshan/backend/fu/CSR.scala

We found that openSBI would assume that `htimedelta` CSR should be emulated if `time` CSR is emulated, which causes failure in the virtual machine time interrupts.
According to [an issue](https://github.com/riscv/riscv-isa-manual/issues/481) in riscv/riscv-isa-manual, `htimedelta` CSR is tide with `time` CSR. Implementations should either implement both CSRs or skip both. As XiangShan currently does not have `time` CSR, the `htimedelta` CSR should be removed.

RVH, CSR: remove htimedelta for openSBI

---

src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/backend/issue/Dispatch2Iq.scala
src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala
src/main/scala/xiangshan/cache/mmu/MMUBundle.scala
src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
src/main/scala/xiangshan/mem/vector/VSegmentUnit.scala
src/main/scala/xiangshan/mem/vector/VecBundle.scala

Fix the timing problem in dispatch2iq caused by wrong bit width calculation is fixed, as described in (401631ccb66daaf5b5a7b1f67ae5402e26be95b7), and unified parameters in (eebd01f8b876d1529595ebded6cdc45d611be759).
Fix an issue where 'segmentUnit' was not connected to 'sbufferVecDifftestInfo' port, as described in (96c35ec3dbed9762cbced86c79ce0bdc550bcb56).
Figured out that we could use an already implemented API to check the 'timeout'. as described in (468eda665c20b26570967bdfb1611edebcd021f2).

rv64v: fix 'segmentUnit' was not connected to 'sbufferDifftestInfo' port and fix timing problem caused by bit width in 'Dispatch2iq'.

---

src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/backend/Bundles.scala
src/main/scala/xiangshan/backend/decode/DecodeStage.scala
src/main/scala/xiangshan/backend/decode/FusionDecoder.scala
src/main/scala/xiangshan/backend/rename/Rename.scala
src/main/scala/xiangshan/backend/rename/RenameTable.scala
src/main/scala/xiangshan/backend/rob/RobBundles.scala

Different rename table has different numbers of entries, leading to differences in the width of read/write ports. In the code we see the widths of all read/write ports were set to 6, which works well but is not parameterized. Now these widths are modified to be controlled by parameters.

Rename table: fix width of rename table ports

---

src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala

gpaddr uses io.in.bits.ppn and io.in.bits.req_info_vpn. They are easy to change. If they become x signal, hpaddr also become x signal. That will make L2TLB stop.

LLPTW, RVH: fix the calculation of gpaddr that makes hgpaddr become x  signal

---

src/main/scala/xiangshan/frontend/IFU.scala
src/main/scala/xiangshan/frontend/icache/ICacheMainPipe.scala
src/main/scala/xiangshan/frontend/icache/IPrefetch.scala
src/main/scala/xiangshan/frontend/icache/WayLookup.scala

Currently, `gpaddr` is used only when guest page fault occurs, so it should be possible to not store every `gpaddr` in WayLookup (as well as in GPAMem).
Considering that every guest page fault should issue a redirect, and thus flush WayLookup/MainPipe/IPrefetch, we should be able to store only the first guest page fault and its `gpaddr` in WayLookup.
By doing this, we can save `2×nWayLookupSize - 1 = 63` registers that are used to store `gpaddr`.
This PR also includes some style changes for WayLookup to satisfy linter.

Frontend: cut waylookup gpaddr

---

src/main/scala/xiangshan/cache/mmu/MMUBundle.scala
src/main/scala/xiangshan/cache/mmu/PageTableCache.scala

In the previous design, even if an access fault occurs on a page table, the page cache is hit and information about the access fault is lost because the page cache truncates the ppn bit width. We have fixed this problem in this PR by determining whether af occurs when a page table refill occurs, and if it does, making it a forced miss.

PageCache: should not hit access fault ptes

---

src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala

The onlyStage1 req is same as the noS2xlate req in LLPTW. So to_mem_out is also applied to the onlyStage1 req.

LLPTW, RVH: fix wrong state transition when onlyStage1 in LLPTW

---

src/main/scala/xiangshan/backend/decode/DecodeUnit.scala

DecodeUnit: fix ignoreOldVd, some vector load instructions use eew instead of sew to check tail

DecodeUnit: fix ignoreOldVd of some vector load instructions

---

src/main/scala/xiangshan/cache/mmu/TLB.scala

- vmEnable is used only when the req is not hyperinst and not in virtmode
- refill doesn't need vmEnable. dtlbRepeater will resp to tlb a ptw_resp if tlb has sent request to it. The ptw_resp tlb maybe refill. But this refill has nothing to do with vmEnable

TLB, RVH: fix the bug about vmEnable

---

src/main/scala/xiangshan/mem/lsqueue/LoadQueue.scala
src/main/scala/xiangshan/mem/vector/VMergeBuffer.scala
src/main/scala/xiangshan/mem/vector/VecCommon.scala

fix the bug of vector unit-stride exception address calculation, as in (b43913a1a16065076728931e4945132851945197).
fix connection between vector exception and 'exceptionBuffer' in 'LoadQueue'. as in (2d1c7300228274e845948a94433933cf667bab11).
At present, the vector access exception processing still needs to wait for the modification of the back-end. We will test after the back-end is completed, and may also adapt the storage access side.

VLSU: fix bugs related to vector access exceptions

---

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala

This commit is to ensure robustness when vector instructions are used to access MMIO regions by mistake. Currently, we do not support vector instruction access to MMIO regions, and in order to handle the situation when a vector instruction incorrectly accesses an MMIO region, an accessfault exception is triggered when the MMIO region is accessed using a vector instruction.

LSU: trigger accessfault for vector mmio access request

---

src/main/scala/xiangshan/frontend/IFU.scala

also reset `mmio_resend_(a|p|gp)f` registers when mmio instr is commited or flush happens
Ref: discussion here https://github.com/OpenXiangShan/XiangShan/pull/3104#discussion_r1653865072 and https://github.com/OpenXiangShan/XiangShan/pull/3104#pullrequestreview-2146994731

IFU: pass mmio gpf to ibuffer & gpaddr to gpaMem

---

src/main/scala/xiangshan/frontend/BPU.scala
src/main/scala/xiangshan/frontend/FTB.scala

In dhrystone, most high bits of PC is gated.

bpu: use (27, 12, 12) segmented PC in BPU

---

src/main/scala/xiangshan/backend/CtrlBlock.scala
src/main/scala/xiangshan/backend/datapath/PcTargetMem.scala
src/main/scala/xiangshan/frontend/Frontend.scala
src/main/scala/xiangshan/frontend/NewFtq.scala

* Hold newest predict target everytime it is updated by frontend.
* Don't use out-of-date predict value even if FtqIdx match.

Backend,Frontend: pass flag of FtqPtr to TargetMem to avoid read out-of-date predict target

---

src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala
src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala
src/main/scala/xiangshan/cache/dcache/mainpipe/MissQueue.scala
src/main/scala/xiangshan/cache/dcache/mainpipe/WritebackQueue.scala

Bug: 
- When two req with different addr x and y enter MissQueue together, req y is real miss req, while req x is **AcquireBlock BtoT**. Req y receive the resp from L2 first and complete the refill operation by replacing the data block with addr x (decided by plru algorithm). MainPipe will release the data block with addr in writeback queue through req **Release BtoN** to L2. Addr x receive GrantData with permission toT at last.
- From the view of L2, the req sequence of addr x is: Acquire BtoT -> GrantData toT -> Release BtoN, which is abnormal.
Fix: When a valid req reaches wbq, check if there is any valid mshr with same block_addr. If a mshr is found, block current wbq_req.

DCache: Block the writeback req when the addr matching a valid req in mshr

---

src/main/scala/xiangshan/frontend/newRAS.scala

Modify the update strategy of the BOS pointer, because the TOSW+1 item in the speculation stack is not committed during commit push.

RAS: Fixed the bottom update issue of the speculative stack

---

src/main/scala/xiangshan/frontend/IFU.scala

f3_ready is assigned twice under the identical condition:
- https://github.com/OpenXiangShan/XiangShan/blob/182b7ece8ba898233f30d6cd83bbed50825943de/src/main/scala/xiangshan/frontend/IFU.scala\#L471
- https://github.com/OpenXiangShan/XiangShan/blob/182b7ece8ba898233f30d6cd83bbed50825943de/src/main/scala/xiangshan/frontend/IFU.scala\#L585
and the former one:
```scala
f3_ready := f3_fire || !f3_valid
//       := (io.toIbuffer.ready && f3_valid && (!f3_req_is_mmio || f3_mmio_can_go) && !f3_flush) || !f3_valid
```
might not ideal since the previous mmio request may be not commited (i.e. `mmio_state === m_waitCommit`)
therefore, remove the former assignment

IFU: remove duplicate assignment for f3_ready

---

src/main/scala/xiangshan/backend/Backend.scala
src/main/scala/xiangshan/backend/datapath/DataPath.scala
src/main/scala/xiangshan/backend/issue/Scheduler.scala
src/main/scala/xiangshan/backend/rename/BusyTable.scala

* only non-load wakeup sources exu should send og0cancel
* og0cancel only works on the wakeup of 0 latency instructions

DataPath, BusyTable: remove unnecessary cancel signals

---

src/main/scala/xiangshan/frontend/icache/ICacheMainPipe.scala
src/main/scala/xiangshan/frontend/icache/IPrefetch.scala

Fixes bug mentioned: https://github.com/OpenXiangShan/XiangShan/pull/3139#discussion_r1679178024
Analysis:
1. (expected) In a doubleline request, port0 AND port1 finds guest page fault(`io_itlb_x_resp_bits_excp_0_gpf_instr`), it is stored in `itlbExcpGPF` register, enters WayLookup and is bypassed to ICacheMainPipe (WayLookup is `empty` and `io_write` fires with `io_read` fire). Finally it goes to backend
2. (expected) Backend send a redirect request and flushes IPrefetch/WayLookup/ICacheMainPipe
3. (WRONG) After flush, this is a singleline request, so port1 does not send request to itlb(`io_itlb_1_req_valid`) and thus not updated, `io_itlb_x_resp_bits_excp_0_gpf_instr` remains `true.B`
4. (WRONG) This false-positive gpf enters WayLookup and is bypassed to ICacheMainPipe
5. (expected) …

IPrefetch: do not pass exception(1) to WayLookup if !s1_doubleline

---

src/main/scala/xiangshan/cache/mmu/L2TLB.scala
src/main/scala/xiangshan/cache/mmu/PageTableCache.scala
src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala

When gaf or gpf happens in the first stage2 translation in LLPTW, L2TLB will resp. But LLPTW doesn't save the stage1 pte because LLPTW performs the first stage2 translation. So this pr saves the stage1 pte coresponding to the first stage2 translation.

L2TLB, RVH: fix the bug that L2TLB resp wrong stage1 pte when gpf/gaf happens in LLPTW

---

src/main/scala/xiangshan/backend/Backend.scala
src/main/scala/xiangshan/backend/datapath/DataPath.scala
src/main/scala/xiangshan/backend/issue/Entries.scala
src/main/scala/xiangshan/backend/issue/EntryBundles.scala
src/main/scala/xiangshan/backend/issue/IssueQueue.scala
src/main/scala/xiangshan/backend/issue/Scheduler.scala
src/main/scala/xiangshan/backend/rename/BusyTable.scala

* use Vec[Bool] instead of UInt for og0Cancel
* only wakeup source Exus containing 0-latency function unit should send og0Cancel

Backend: optimize og0 cancel signals

---

src/main/scala/xiangshan/frontend/icache/IPrefetch.scala

Explained: (**NOT** has exception **AND NOT** hit) === miss === needs fetch
Performance change is expected, as prefetch is actually doing more work.

IPrefetch: fix s2_miss(1) typo

---

src/main/scala/xiangshan/frontend/ITTAGE.scala

Previously, useful bit was stored in registers. In order to save space, useful bit is now integrated into ITTageEntry for unified storage. 
To achieve partial writing, bitMask is used.
Additionally, moving to SRAM avoids bug in the Folded1WDDataModuleTemplate module that was originally compiled.

bpu: ittage us migration to sram & merge two banks to one bank

---

src/main/scala/xiangshan/frontend/icache/ICacheMissUnit.scala

Each time `io.victim.vSetIdx.valid === true.B`, replacer will choose the LRU way as victim and access it to MRU position.
See: https://github.com/OpenXiangShan/XiangShan/blob/e3704ae5040ad97955501e3ec494c059d94f3826/src/main/scala/xiangshan/frontend/icache/ICache.scala#L438-L445
When `acquireArb.io.out.valid === true.B && acquireArb.io.out.ready === false.B`, replacer will be mistakenly updated, thus violates PLRU policy.
We want to update replacer only once per acquire request, so `io.victim.vSetIdx.valid := acquireArb.io.out.fire`.

MissUnit: update replacer only when acuqire fire

---

src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala
src/main/scala/xiangshan/cache/dcache/mainpipe/MissQueue.scala

- Fix refill_info valid signal in MissQueue. `refill_info.valid` is set only when the req in mshr is valid and the req in MainPipe stage s2 is refill req with `s2_req.miss`.
- Enable `error_flag_write.valid` for every refill req in Mainpipe to fix the problem that the error_flag never being updated.

DCache: Fix valid signal of refill_info and error_flag_write

---

src/main/scala/xiangshan/backend/decode/VecExceptionGen.scala

reduction instructions' emul is 1, not depend on lmul

rv64v: exception check for vector widening reduction instructions

---

src/main/scala/system/SoC.scala

CLINT for simulation echoes response in the same cycle as the request. However, AXI4Xbar is unable to handle synchronous response because AXI4Xbar must track id flow.

SoC: add buffer between AXI4Xbar and CLINT

---

.github/workflows/emu.yml
scripts/xiangshan.py

This patch add xvisor_wboxtest to ci, which tests the nested mmu system. riscv-hyp-tests are still on the way.

ci: add basic ci for Hypervisor extension

---

src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala

* Due to support Sscofpmf extension, the local counter overflow interrupt LCOFI(13) is RW
* While NEMU cannot get the value of the counter, so it temporarily skips *ip CSRs

NewCSR: skip *ip difftest

---

src/main/scala/xiangshan/package.scala

I noticed that ALUOpType still defines the beq/bne/blt/bge/bltu/bgeu/ operations, that have been moved to BRUOpType, when experimenting with adding custom instructions to XiangShan.
To make sure that this doesn't break anything I tracked the changes that lead to having the instructions under ALUOpType and BRUOpType:
* [originally the branch ops were implemented in the ALU](https://github.com/OpenXiangShan/XiangShan/commit/675acc6894dd86f75adfa0d6a7c1182a0e48de99#diff-2ac16079a402bdc9ac9074de2e0255c01d8ca901bd07e56c80f87e0cb8477db1)
* [later they were moved to the BRU](https://github.com/OpenXiangShan/XiangShan/commit/3b739f49c5a26805be859c7231717ecc38aade30#diff-2ac16079a402bdc9ac9074de2e0255c01d8ca901bd07e56c80f87e0cb8477db1R370)
* [however the ALUOpType was accidentally still used, …

Remove unused ALUOpType branch ops from package.scalar

---

Makefile
src/main/scala/xiangshan/L2Top.scala
src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/XSTile.scala
src/main/scala/xiangshan/backend/MemBlock.scala

This pull request includes important new features about CoupledL2 as follows:
1. [SRAM: implement real MCP2](https://github.com/OpenXiangShan/CoupledL2/pull/200)
2. [**Support for CHILog**](https://github.com/OpenXiangShan/CoupledL2/pull/207)
3. [**Support for configurable CHI issue E.b interface**](https://github.com/OpenXiangShan/CoupledL2/pull/209)
For bug fixes on CoupledL2:
1. [BOP: add pmp check to avoid illegal prefetch](https://github.com/OpenXiangShan/CoupledL2/pull/205)
2. [TL2TLCoupledL2, SinkB: do not accept Probe when same-addr waiting for ReleaseAck](https://github.com/OpenXiangShan/CoupledL2/pull/208)
3. [TL2CHICoupledL2, MSHR: fix bug when SnpRespFwded nestedwb the same MSHR](https://github.com/OpenXiangShan/CoupledL2/pull/211)
In addition, this pr bumps the latest version …

CoupledL2: support for MCP2 SRAM, CHILog and CHI Issue E.b

---

src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala
src/main/scala/xiangshan/cache/dcache/mainpipe/MainPipe.scala
src/main/scala/xiangshan/cache/dcache/mainpipe/MissQueue.scala
src/main/scala/xiangshan/cache/dcache/mainpipe/WritebackQueue.scala

**Bug:** According to the Tilelink Specification, Chapter 9.2, "A master should not issue a Release if there is a pending Grant on the block." However, in dcache, this situation can occur when refill_req selects an evicted block whose address matches a valid MSHR.
**Solution:** Replay the refill_req if the address selected by the replacement policy matches a valid MSHR, and do not generate a current release request to L2.

DCache: Replay refill_req when the evict_addr matching a valid mshr

---

src/main/scala/xiangshan/frontend/NewFtq.scala

An FTQ entry should be committed when last instruction is committed instead of all are committed, as backend may not commit every single instruction.
This PR also addresses the performance bugs noted in PR #3303, as it involves a complete rewrite. The description of PR #3303 is as follows.
PR #3086 fixes the bug where multiple load replays will fill the whole FTQ by committing the FTQ entries created by load replays. However, these committed entries will generate FTB entries that negatively impact the BP accuracy under certain conditions.
To mitigate this, FTQ entries containing only one single flushed instruction will no longer generate FTB entries. The commPtr and robcommPtr will sill advance in case of running FTQ entries.

FTQ: FTQ entry commit condition and move pointer condition

---

src/main/scala/xiangshan/frontend/newRAS.scala

Overflow handling is not perfect, and a single overflow-related modification may cause negative effects. Restore the original overflow judgment logic.

RAS: Restore the speculative stack overflow judgment code

---

src/main/scala/xiangshan/L2Top.scala
src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/XSTile.scala
src/main/scala/xiangshan/backend/Backend.scala
src/main/scala/xiangshan/backend/MemBlock.scala

Modules in XSTile are reset in the order of L2, MemBlock, Backend and Frontend.

L2Top, MemBlock, Backend: reconstruct reset tree

---

src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala

When the resp is allstage and level == 0, PTW find pte and then gpf happens in the last s2xlate before resp to l1tlb. We can't give fake pte to stage1 because the pte that mem resp is valid in PTW.

PTW, RVH: fix the error S1 resp when gpf happened and s1_level == 0

---

src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala
src/main/scala/xiangshan/backend/fu/NewCSR/TrapHandleModule.scala

* The injected interrupts for HS mode can set some bits in mIRVec and hsIRVec.
* `mIRVec` holds the highest priority interrupt numbered from 1 to 63. Only interrupt 1-13 can trap in M mode. And interrupt 14-63 must trap in HS mode or VS mode, since bits in mideleg(63,14) are read-only 0.
* `hsIRVec` holds the mip parts(by mIRVec & mideleg) and mvip parts(by mIRVec & ~mideleg & mvien) interrupts.
* `vsIRVec` holds the sip|hip parts(by hsIRVec & hideleg) and hvip parts(by hsIRVec & ~hideleg & hvien) interrupts.

CSR: fix custom IRQ injection mechanism

---

src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala

When the first s2xlate happens gpf, the pte is invalid, which makes the pf and af of stage1 is x-states.

PTW, RVH: fix the x state of stage1 pf/af when the first s2xlate happens gpf in PTW

---

src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala

We cannot set vecValid when mask is all 0.

StoreQueue: do not submit inactive vector store to sbuffer

---

src/main/scala/xiangshan/frontend/FrontendBundle.scala
src/main/scala/xiangshan/frontend/IBuffer.scala
src/main/scala/xiangshan/frontend/IFU.scala
src/main/scala/xiangshan/frontend/icache/ICacheMainPipe.scala
src/main/scala/xiangshan/frontend/icache/IPrefetch.scala
src/main/scala/xiangshan/frontend/icache/WayLookup.scala

Combine `excp_pf`/`_gpf`/`_af` into `exception` to:
1. Reduce code redundancy and improve readability and maintainability
e.g. `!itlb_excp_af && !itlb_excp_pf && !itlb_excp_gpf && !pmp_excp_af && !pmp_excp_mmio`
-> `exception === ExcedptionType.none && !mmio`
2. Select exceptions as they are generated (e.g. from iTLB/PMP, or data/meta array ECC check) on a priority basis (e.g. iTLB over PMP), ensuring that there is at most one exception in the pipeline (and on the ports of iCache -> IFU)
3. Save a little bit of pipeline/WayLookup registers (i.e. 3 bit `excp_pf`/`_gpf`/`_af` -> 2bit `exception`)

Frontend: refactor exceptions to labels

---

scripts/xiangshan.py

Because of bugs, riscv-hyp-tests was not added to ci. Now XiangShan master could pass it, so this patch added it back.

ci: enable riscv-hyp-tests

---

src/main/scala/xiangshan/frontend/FrontendBundle.scala
src/main/scala/xiangshan/frontend/icache/ICache.scala
src/main/scala/xiangshan/frontend/icache/ICacheMainPipe.scala
src/main/scala/xiangshan/frontend/icache/IPrefetch.scala

In current design, meta/data array corruption does not raise any exception (whether or not `io.csr_parity_enable === true.B`), which may pose two problems:
1. When meta corrupt, `ptag` comparison result may be invalid, and thus cache hit may be treated as a cache miss, thereby sending (pre)fetch request to L2 cache incorrectly;
2. When meta/data/l2 corrupt, instruction data sent to the backend may be invalid. Although the errors are sent to beu, which sends an interrupt via plic, the timing of the interrupt is not as controllable as an exception. It is therefore reasonable to mark invalid data as access fault to keep it from execution.
This PR:
1. Raise af if meta/data array ECC fail (when `io.csr_parity_enable === true.B`), the priority of this af is lower than iTLB & PMP exceptions
2. …

ICache: raise af if meta/data array ECC fail

---

src/main/scala/xiangshan/backend/Bundles.scala
src/main/scala/xiangshan/backend/decode/DecodeUnit.scala
src/main/scala/xiangshan/backend/fu/FuType.scala
src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala
src/main/scala/xiangshan/backend/fu/NewCSR/Unprivileged.scala
src/main/scala/xiangshan/backend/fu/wrapper/CSR.scala

* When 0 <= inst.rm <= 4, execute inst as usual.
* When inst.rm = 5/6, execute inst will raise EX_II.
* When inst.rm = 7, rm = frm.data. if frm.data > 4 will raise EX_II.
* rm = frm.data for vf* inst.
* Meanwhile, flush pipe when wen frm/fcsr CSR
*       1. frm rdata is Reserved and wdata is normal
*       2. frm rdata is normal and wdata is Reserved
* inst rely on Spike.

Decode: execute inst will raise EX_II when rm is reserved value

---

src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/backend/decode/DecodeUnit.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

1. Support RVA23 SoftPrefetch instructions, include prefetch.i , prefetch.w and prefetch.r.
2. In DecodeUnit, add decode of SoftPrefetch.
3. prefetch.i , prefetch.w and prefetch.r will be dispatch into load-pipe, and then prefetch.w and prefetch.r execute like a load.
4. preftch.i just calculate address in loadUnit, then transfer address to Frontend.(TODO)
5. All SoftPrefetch instructions return “ldout” signals to Backend in stage3 wether hit or miss.

LDU, Decode: add support for software prefetch (Zicbop)

---

src/main/scala/top/Configs.scala

Add a new Class FpgaDefaultConfig for FPGAs Bitstream generation. The L3 Cache clock was turned off, and the L3 Cache size was reduced form 16M to 3M. Set DebugOptions AlwaysBasicDiff and AlwaysBasicDB to false.

Config: Add FpgaDefaultConfig for FPGAs Bitstream generation

---

src/main/scala/xiangshan/frontend/IFU.scala

See https://github.com/OpenXiangShan/XiangShan/pull/3354#discussion_r1718219297
Cross-page access faults are not marked (in the past 2-3 years), so this PR fixed that too.
Also, `crossPageIPFFix` (actually `crossPageExceptionFix`, used to calculate precise exception address in CSR) should be set for both pf/gpf/af (and mmio_resend pf/gpf/af).

IFU: fix cross-page exception

---

src/main/scala/xiangshan/backend/CtrlBlock.scala
src/main/scala/xiangshan/backend/dispatch/Dispatch.scala
src/main/scala/xiangshan/backend/rename/Rename.scala

* `SingleStepStatus` should not be cleared by redirect before hart enter debugMode.
* singleStep should block rob compress in `rename`.

DebugModule: Fix bug of singleStep.

---

src/main/scala/xiangshan/XSCore.scala
src/main/scala/xiangshan/backend/Backend.scala
src/main/scala/xiangshan/backend/MemBlock.scala

* All Top-to-Backend bundles are in class TopToBackendBundle.
* Including hartId, externalInterrupt, msiInfo, clintTime
* All Backend-to-Top bundles are in class BackendToTopBundle.
* Only cpuHalted included
* Use := instead of <> for non-Bidirectional bundles in XSCore.

XSCore,Backend,MemBlock: let Top-to-Backend bundles bypass MemBlock

---

src/main/scala/xiangshan/backend/fu/NewCSR/CSRPermitModule.scala

According AIA spec, when vsiselect has the number of an inaccessible register, attempts from VS-mode to access sireg
(really vsireg) raise a virtual instruction exception. 
But 0x070-0x0ff are external interrupts (IMSIC only), or inaccessible. And we has implemented IMSIC.

sireg: fix the condition of rwSireg_EX_VI.

---

src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/backend/Bundles.scala
src/main/scala/xiangshan/backend/CtrlBlock.scala
src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/backend/decode/DecodeUnit.scala
src/main/scala/xiangshan/backend/dispatch/Dispatch.scala
src/main/scala/xiangshan/backend/fu/CSR.scala
src/main/scala/xiangshan/backend/fu/NewCSR/CSREvents/TrapEntryDEvent.scala
src/main/scala/xiangshan/backend/fu/NewCSR/Debug.scala
src/main/scala/xiangshan/backend/fu/NewCSR/DebugLevel.scala
src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala
src/main/scala/xiangshan/backend/fu/NewCSR/TrapHandleModule.scala
src/main/scala/xiangshan/backend/fu/wrapper/CSR.scala
src/main/scala/xiangshan/backend/rename/CompressUnit.scala
src/main/scala/xiangshan/backend/rename/Rename.scala
src/main/scala/xiangshan/backend/rob/ExceptionGen.scala
src/main/scala/xiangshan/backend/rob/Rob.scala
src/main/scala/xiangshan/backend/rob/RobBundles.scala
src/main/scala/xiangshan/frontend/FrontendBundle.scala
src/main/scala/xiangshan/frontend/IBuffer.scala
src/main/scala/xiangshan/frontend/PreDecode.scala
src/main/scala/xiangshan/mem/pipeline/AtomicsUnit.scala
src/main/scala/xiangshan/mem/pipeline/HybridUnit.scala
src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala
src/main/scala/xiangshan/package.scala

* use `triggerAction` to replace `triggerHitVec` & `TriggerCanfireVec`, that is useful for trace in the future.
* use triggerAction = 15.U to express that action is None.
* put breakpoint exception generated by trigger into ExceptionVec[BP] derectly.
* update exceptionVec in `decode` for bp exception from frontend trigger.
* trigger don't genetate exception in debugMode.
* trigger don't generate exception when tcontrol.mte is false in Mmode.

Trigger: refactor trigger information in pipeline.

---

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

Potential Bug Description:
* If an unaligned `hlv` or `hlvx` is executed, the unaligned exception will be caught and processed by the hardware. When loadMisalignBuffer sends a split request to ldu, the `hlv` and `hlvx` identifiers need to be given, otherwise tlb cannot recognize it.

ldu: fix potential bug when exec unaligned hlv or hlvx

---

src/main/scala/top/Configs.scala
src/main/scala/xiangshan/Bundle.scala
src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/backend/datapath/DataConfig.scala
src/main/scala/xiangshan/backend/fu/wrapper/CSR.scala
src/main/scala/xiangshan/cache/mmu/L2TLB.scala
src/main/scala/xiangshan/cache/mmu/MMUBundle.scala
src/main/scala/xiangshan/cache/mmu/MMUConst.scala
src/main/scala/xiangshan/cache/mmu/PageTableCache.scala
src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala
src/main/scala/xiangshan/cache/mmu/Repeater.scala
src/main/scala/xiangshan/cache/mmu/TLB.scala
src/main/scala/xiangshan/cache/mmu/TLBStorage.scala

1. add the check of the high bits of gpaddr
2. fix the bug that fake pte make wrong pf 
3. add the check of U A D bit of non-leaf pte 
4. fix the perm resp of Page Cache
5. fix the wrong stage1 level when PTW has gpf from HPTW
6. fix the refill of af page in Page Cache, which shouldn't be refilled
7. fix the bug that ptw send wrong llptw req when gpf happens
8. fix the flush_latch bug that making LLPTW resps wrong ppn
9.  fix the bug that l1hit but ptw get gpf in the first s2xlate, PTW resps wrong stage1
Rebase these change on master which be merged sv48 and sv48x4

MMU, RVH: add the check of gpaddr high bits and fix some bugs

---

src/main/scala/xiangshan/Parameters.scala
src/main/scala/xiangshan/backend/Bundles.scala
src/main/scala/xiangshan/backend/rename/Rename.scala
src/main/scala/xiangshan/backend/rob/Rob.scala
src/main/scala/xiangshan/backend/rob/RobBundles.scala
src/main/scala/xiangshan/backend/trace/Interface.scala

In this PR, the main goal is to fix the bug encountered during ROB commit. However, resolving this issue requires information about `iretire` and `ilastsize`, which need be collected by the trace. Therefore, I have also included the trace interface in this PR.
The specific changes are as follows:
* When rob commit, update the ftqIdx and ftqOffset to correctly notify the frontend which instructions have been committed.
* In each robentry, the ftqIdx and ftqOffset belong to the first instruction that was compressed, that is Necessary when exceptions happen.
* Add trace Interface in hart.
* Add trace parameter in parameter.scala.
* Collect trace infomation in backend pipeline.

Rob: fix bug of rob commit.

---

src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala

Traps don’t take place in Debug Mode. Instead, they end execution of the program buffer and the hart remains in Debug Mode. Because they do not trap to M-mode, they do not update registers such as , `mepc`, `mcause`, `mtval`, `mtval2`, and `mtinst`. The same is true for the equivalent privileged registers that are updated when trapping to other modes.

DebugModule: fix bug, trap don't take place in dmode.

---

src/main/scala/xiangshan/L2Top.scala
src/main/scala/xiangshan/backend/MemBlock.scala
src/main/scala/xiangshan/cache/mmu/L2TLB.scala
src/main/scala/xiangshan/cache/mmu/MMUBundle.scala
src/main/scala/xiangshan/cache/mmu/MMUConst.scala
src/main/scala/xiangshan/cache/mmu/PageTableCache.scala
src/main/scala/xiangshan/cache/mmu/TLB.scala
src/main/scala/xiangshan/cache/mmu/TLBStorage.scala
src/main/scala/xiangshan/frontend/FrontendBundle.scala
src/main/scala/xiangshan/frontend/IFU.scala
src/main/scala/xiangshan/frontend/icache/ICacheMainPipe.scala
src/main/scala/xiangshan/frontend/icache/IPrefetch.scala
src/main/scala/xiangshan/frontend/icache/WayLookup.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala

Only the `pbmt` attribute is added and treated as MMIO when `pbmt` is NC or IO.

svpbmt: add simplified support

---

src/main/scala/xiangshan/backend/fu/PMA.scala
src/main/scala/xiangshan/cache/mmu/MMUBundle.scala

*PMA: Extend the default memory space from 0x1000000000L to 0x1000000000000L
*MMU: only trigger accessfault when ppn above PADDRBITS(48)-OFFSETBITS(12) is not zero

PMA, MMU: Fix bug of PA48

---

src/main/scala/xiangshan/cache/mmu/PageTableWalker.scala

1. init a、d、ppn of fake pte
2. modify the logic of isPf and isAf

PTW, RVH: init the A、D、PPN of fake pte to avoid wrong pf and wrong gpaddr in L1TLB

---

src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala

When a store is killed at s1 in StoreUnit because of MMIO check or pipeline flush, the store should not be reported to exception buffer no matter whether there is af exception at s2 or not.

StoreUnit: DONT report af to exceptionBuffer when store is killed

---

src/main/scala/xiangshan/backend/fu/NewCSR/NewCSR.scala

* Only Debug Mode can write the tdata selected when tdata1.dmode is true.B.

Trigger: check tdata1.dmode before write `tdata`

---

src/main/scala/xiangshan/frontend/ITTAGE.scala

previous impl use confidence ctr value as alt differs, which is wrong since nanhu.

bpu: fix-ittage-altdiffers

---

src/main/scala/system/SoC.scala
src/main/scala/top/XSNoCTop.scala
src/main/scala/xiangshan/XSTileWrap.scala

This commit adds a switch for CHI asynchronous bridge and CLINT asynchronous bridge, which is parameterized by `SoCParameters`.

SoC, XSNoCTop, XSTileWrap: add switch for the async bridges

---

src/main/scala/xiangshan/mem/lsqueue/StoreQueue.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala
src/main/scala/xiangshan/mem/pipeline/StoreUnit.scala

In the current design, do not let vector instructions do hardware misaligned.

fix(Zicclsm): Vectors should not support misaligned access by Hardware

---

src/main/scala/xiangshan/frontend/icache/ICache.scala
src/main/scala/xiangshan/frontend/icache/ICacheBundle.scala
src/main/scala/xiangshan/frontend/icache/ICacheMainPipe.scala
src/main/scala/xiangshan/frontend/icache/IPrefetch.scala
src/main/scala/xiangshan/frontend/icache/WayLookup.scala

Currently, metaArray ECC check is valid 2 cycles after request:
https://github.com/OpenXiangShan/XiangShan/blob/49162c9ab67070931573c1d4a372e2c858a72716/src/main/scala/xiangshan/frontend/icache/ICache.scala#L262
However, prefetchPipe s1 handshakes with both WayLookup and prefetchPipe s2 assuming that all signals of the metaArray.io.readResp are valid 1 cycle after the request, resulting in the error.
Simply removing this RegEnable may lead to problems with long timing paths (metaArray (sram) -> ECC check (xor reduction) -> prefetchPipe s1 (wire) -> wayLookup (bypass, wire) -> mainPipe s0 (wire) -> mainPipe s1 (reg)), so no.
This PR may result in case-specific errors not being checked out, which in turn results in additional fetch requests being sent to the L2 cache, but does not causes …

ICache: fix metaArray ECC check

---

src/main/scala/xiangshan/mem/pipeline/HybridUnit.scala
src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

The old version involved manually handling multiple load sources and processing signals like `valid`, `ready`, and `select` one by one. Each time a new source was added, multiple lines of dependent code had to be written. In the new version, `Vec` are used for unified handling, so adding a new source only requires adding the corresponding `idx` and the necessary dependent code.

refactor(LDU, HYU): optimized for low coupling

---

src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala
src/main/scala/xiangshan/cache/dcache/loadpipe/LoadPipe.scala
src/main/scala/xiangshan/mem/prefetch/L1PrefetchInterface.scala
src/main/scala/xiangshan/mem/prefetch/PrefetcherMonitor.scala

Previous design:
When a demand load hits a Cache block fetched by the prefetcher, the `PrefetchSource` of this block will be cleared,
causing it to be mistakenly believed that it was not fetched by the prefetcher initially when it is subsequently replaced from the cache, resulting in not increasing the `good_prefetch` counter
Fix:
Now add a new cache block status(L1_HW_PREFETCH_CLEAR): indicating that this block was originally fetched by the prefetcher

fix(L1PF): fix good_prefetch Counting logic

---

src/main/scala/xiangshan/cache/mmu/TLB.scala

When ptw resp is onlyS2, the gvpn of gpaddr is from the tag of stage2 pte in ptw resp.

fix(L1TLB): fix the wrong refill of gpaddr when ptw resp is onlyS2

---

src/main/scala/xiangshan/mem/pipeline/LoadUnit.scala

In load_s1 stage, a forward request is sent to storequeue to check whether there is any data forward, and also whether a violation occurs when mdp turns on.
In storequeue forward check, both vaddr and paddr need to be checked, so it needs TLB hit (!miss), and when TLB misses, the forward.valid is false. When forward.valid is false, the forward checking information returned by storequeue in load_s2 stage (for example, addrInvalid, dataInvalid, etc.) is uncertain. Only when forward.valid signal of load_s1 is true, can we judge the load replay condition based on the forward information returned from storequeue in load_s2.
Therefore, we add the RegNext(io.lsq.forward.valid) condition to the generation of s2_mem_amb and s2_fwd_fail signals, which are only meaningful when …

fix(LoadUnit): forward resp is only valid when req valid
